//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class AquaticTridentModel extends ModelBase {
   public ModelRenderer staf;
   public ModelRenderer staf2;
   public ModelRenderer shape;
   public ModelRenderer shape_1;
   public ModelRenderer shape_2;
   public ModelRenderer shape_3;
   public ModelRenderer shape_4;
   public ModelRenderer shape_5;
   public ModelRenderer decor;
   public ModelRenderer decor_1;
   public ModelRenderer shell;
   public ModelRenderer shell_1;
   public ModelRenderer shell_2;
   public ModelRenderer shell_3;
   public ModelRenderer thorns;
   public ModelRenderer thorns_1;
   public ModelRenderer shella;
   public ModelRenderer shella_1;
   public ModelRenderer bigshell;
   public ModelRenderer bigshell_1;

   public AquaticTridentModel() {
      this.textureWidth = 26;
      this.textureHeight = 32;
      this.staf = new ModelRenderer(this, 14, 3);
      this.staf.setRotationPoint(0.0F, -2.0F, 4.7F);
      this.staf.addBox(-1.0F, 0.0F, -1.0F, 2, 25, 2, 0.0F);
      this.bigshell_1 = new ModelRenderer(this, 6, 20);
      this.bigshell_1.setRotationPoint(-2.7F, -3.2F, 5.5F);
      this.bigshell_1.addBox(0.0F, 0.0F, 0.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.bigshell_1, -0.91053826F, 0.13665928F, -0.5009095F);
      this.bigshell = new ModelRenderer(this, 6, 24);
      this.bigshell.setRotationPoint(-0.2F, -1.8F, 4.5F);
      this.bigshell.addBox(0.0F, 0.0F, 0.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.bigshell, 0.4098033F, 0.95609134F, -0.22759093F);
      this.decor_1 = new ModelRenderer(this, 0, 14);
      this.decor_1.setRotationPoint(0.0F, 17.8F, 4.7F);
      this.decor_1.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.shape_4 = new ModelRenderer(this, 6, 0);
      this.shape_4.setRotationPoint(0.0F, -3.0F, 4.7F);
      this.shape_4.addBox(2.7F, -9.0F, -0.5F, 1, 4, 1, 0.0F);
      this.shape_2 = new ModelRenderer(this, 0, 0);
      this.shape_2.setRotationPoint(0.0F, -3.0F, 4.7F);
      this.shape_2.addBox(-0.5F, -7.0F, -1.0F, 1, 7, 2, 0.0F);
      this.shell_3 = new ModelRenderer(this, 6, 7);
      this.shell_3.setRotationPoint(2.6F, -5.2F, 4.7F);
      this.shell_3.addBox(-1.3F, 0.0F, -0.9F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shell_3, -0.13665928F, -1.821251F, 0.0F);
      this.thorns_1 = new ModelRenderer(this, 8, 14);
      this.thorns_1.setRotationPoint(0.0F, 1.3F, 4.5F);
      this.thorns_1.addBox(-2.4F, 0.0F, -0.4F, 2, 3, 1, 0.0F);
      this.setRotateAngle(this.thorns_1, -0.13665928F, 2.5953045F, 0.0F);
      this.shape_1 = new ModelRenderer(this, 0, 0);
      this.shape_1.setRotationPoint(0.0F, -7.0F, 4.7F);
      this.shape_1.addBox(3.0F, 0.0F, -1.0F, 1, 6, 2, 0.0F);
      this.staf2 = new ModelRenderer(this, 0, 28);
      this.staf2.setRotationPoint(0.0F, -3.0F, 4.7F);
      this.staf2.addBox(-3.0F, 0.0F, -1.0F, 6, 2, 2, 0.0F);
      this.shape_5 = new ModelRenderer(this, 6, 0);
      this.shape_5.setRotationPoint(0.0F, -3.0F, 4.7F);
      this.shape_5.addBox(-3.7F, -9.0F, -0.5F, 1, 4, 1, 0.0F);
      this.shella_1 = new ModelRenderer(this, 10, 0);
      this.shella_1.setRotationPoint(0.0F, -7.2F, 4.1F);
      this.shella_1.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shella_1, -0.3642502F, 0.5009095F, -0.22759093F);
      this.shella = new ModelRenderer(this, 10, 0);
      this.shella.setRotationPoint(-3.4F, -3.2F, 5.0F);
      this.shella.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shella, -0.22759093F, -0.8196066F, 0.0F);
      this.shell_1 = new ModelRenderer(this, 6, 7);
      this.shell_1.setRotationPoint(0.0F, 11.8F, 4.7F);
      this.shell_1.addBox(-1.0F, 0.0F, -1.6F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shell_1, 0.22759093F, -1.3203416F, 0.0F);
      this.shape = new ModelRenderer(this, 0, 0);
      this.shape.setRotationPoint(0.0F, -7.0F, 4.7F);
      this.shape.addBox(-4.0F, 0.0F, -1.0F, 1, 6, 2, 0.0F);
      this.shape_3 = new ModelRenderer(this, 6, 0);
      this.shape_3.setRotationPoint(0.0F, -3.0F, 4.7F);
      this.shape_3.addBox(-0.5F, -11.0F, -0.5F, 1, 4, 1, 0.0F);
      this.shell_2 = new ModelRenderer(this, 6, 5);
      this.shell_2.setRotationPoint(0.0F, 8.8F, 4.7F);
      this.shell_2.addBox(-1.0F, 0.0F, -0.9F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shell_2, -0.13665928F, (float) Math.PI, 0.0F);
      this.decor = new ModelRenderer(this, 0, 9);
      this.decor.setRotationPoint(0.0F, -1.5F, 4.7F);
      this.decor.addBox(-3.0F, 0.0F, -0.5F, 6, 4, 1, 0.0F);
      this.thorns = new ModelRenderer(this, 8, 14);
      this.thorns.setRotationPoint(0.0F, 10.8F, 4.7F);
      this.thorns.addBox(-2.4F, 0.0F, -0.4F, 2, 3, 1, 0.0F);
      this.setRotateAngle(this.thorns, 0.0F, -0.5009095F, -0.13665928F);
      this.shell = new ModelRenderer(this, 6, 5);
      this.shell.setRotationPoint(0.0F, 14.8F, 4.7F);
      this.shell.addBox(-1.0F, 0.0F, -1.6F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shell, 0.22759093F, 0.27314404F, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf.offsetX, this.staf.offsetY, this.staf.offsetZ);
      GlStateManager.translate(this.staf.rotationPointX * f5, this.staf.rotationPointY * f5, this.staf.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.9, 0.7);
      GlStateManager.translate(-this.staf.offsetX, -this.staf.offsetY, -this.staf.offsetZ);
      GlStateManager.translate(-this.staf.rotationPointX * f5, -this.staf.rotationPointY * f5, -this.staf.rotationPointZ * f5);
      this.staf.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.bigshell_1.offsetX, this.bigshell_1.offsetY, this.bigshell_1.offsetZ);
      GlStateManager.translate(this.bigshell_1.rotationPointX * f5, this.bigshell_1.rotationPointY * f5, this.bigshell_1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.bigshell_1.offsetX, -this.bigshell_1.offsetY, -this.bigshell_1.offsetZ);
      GlStateManager.translate(-this.bigshell_1.rotationPointX * f5, -this.bigshell_1.rotationPointY * f5, -this.bigshell_1.rotationPointZ * f5);
      this.bigshell_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.bigshell.offsetX, this.bigshell.offsetY, this.bigshell.offsetZ);
      GlStateManager.translate(this.bigshell.rotationPointX * f5, this.bigshell.rotationPointY * f5, this.bigshell.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.bigshell.offsetX, -this.bigshell.offsetY, -this.bigshell.offsetZ);
      GlStateManager.translate(-this.bigshell.rotationPointX * f5, -this.bigshell.rotationPointY * f5, -this.bigshell.rotationPointZ * f5);
      this.bigshell.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.decor_1.offsetX, this.decor_1.offsetY, this.decor_1.offsetZ);
      GlStateManager.translate(this.decor_1.rotationPointX * f5, this.decor_1.rotationPointY * f5, this.decor_1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.decor_1.offsetX, -this.decor_1.offsetY, -this.decor_1.offsetZ);
      GlStateManager.translate(-this.decor_1.rotationPointX * f5, -this.decor_1.rotationPointY * f5, -this.decor_1.rotationPointZ * f5);
      this.decor_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_4.offsetX, this.shape_4.offsetY, this.shape_4.offsetZ);
      GlStateManager.translate(this.shape_4.rotationPointX * f5, this.shape_4.rotationPointY * f5, this.shape_4.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape_4.offsetX, -this.shape_4.offsetY, -this.shape_4.offsetZ);
      GlStateManager.translate(-this.shape_4.rotationPointX * f5, -this.shape_4.rotationPointY * f5, -this.shape_4.rotationPointZ * f5);
      this.shape_4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_2.offsetX, this.shape_2.offsetY, this.shape_2.offsetZ);
      GlStateManager.translate(this.shape_2.rotationPointX * f5, this.shape_2.rotationPointY * f5, this.shape_2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape_2.offsetX, -this.shape_2.offsetY, -this.shape_2.offsetZ);
      GlStateManager.translate(-this.shape_2.rotationPointX * f5, -this.shape_2.rotationPointY * f5, -this.shape_2.rotationPointZ * f5);
      this.shape_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shell_3.offsetX, this.shell_3.offsetY, this.shell_3.offsetZ);
      GlStateManager.translate(this.shell_3.rotationPointX * f5, this.shell_3.rotationPointY * f5, this.shell_3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shell_3.offsetX, -this.shell_3.offsetY, -this.shell_3.offsetZ);
      GlStateManager.translate(-this.shell_3.rotationPointX * f5, -this.shell_3.rotationPointY * f5, -this.shell_3.rotationPointZ * f5);
      this.shell_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.thorns_1.offsetX, this.thorns_1.offsetY, this.thorns_1.offsetZ);
      GlStateManager.translate(this.thorns_1.rotationPointX * f5, this.thorns_1.rotationPointY * f5, this.thorns_1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.7);
      GlStateManager.translate(-this.thorns_1.offsetX, -this.thorns_1.offsetY, -this.thorns_1.offsetZ);
      GlStateManager.translate(-this.thorns_1.rotationPointX * f5, -this.thorns_1.rotationPointY * f5, -this.thorns_1.rotationPointZ * f5);
      this.thorns_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_1.offsetX, this.shape_1.offsetY, this.shape_1.offsetZ);
      GlStateManager.translate(this.shape_1.rotationPointX * f5, this.shape_1.rotationPointY * f5, this.shape_1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape_1.offsetX, -this.shape_1.offsetY, -this.shape_1.offsetZ);
      GlStateManager.translate(-this.shape_1.rotationPointX * f5, -this.shape_1.rotationPointY * f5, -this.shape_1.rotationPointZ * f5);
      this.shape_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf2.offsetX, this.staf2.offsetY, this.staf2.offsetZ);
      GlStateManager.translate(this.staf2.rotationPointX * f5, this.staf2.rotationPointY * f5, this.staf2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.staf2.offsetX, -this.staf2.offsetY, -this.staf2.offsetZ);
      GlStateManager.translate(-this.staf2.rotationPointX * f5, -this.staf2.rotationPointY * f5, -this.staf2.rotationPointZ * f5);
      this.staf2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_5.offsetX, this.shape_5.offsetY, this.shape_5.offsetZ);
      GlStateManager.translate(this.shape_5.rotationPointX * f5, this.shape_5.rotationPointY * f5, this.shape_5.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape_5.offsetX, -this.shape_5.offsetY, -this.shape_5.offsetZ);
      GlStateManager.translate(-this.shape_5.rotationPointX * f5, -this.shape_5.rotationPointY * f5, -this.shape_5.rotationPointZ * f5);
      this.shape_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shella_1.offsetX, this.shella_1.offsetY, this.shella_1.offsetZ);
      GlStateManager.translate(this.shella_1.rotationPointX * f5, this.shella_1.rotationPointY * f5, this.shella_1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shella_1.offsetX, -this.shella_1.offsetY, -this.shella_1.offsetZ);
      GlStateManager.translate(-this.shella_1.rotationPointX * f5, -this.shella_1.rotationPointY * f5, -this.shella_1.rotationPointZ * f5);
      this.shella_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shella.offsetX, this.shella.offsetY, this.shella.offsetZ);
      GlStateManager.translate(this.shella.rotationPointX * f5, this.shella.rotationPointY * f5, this.shella.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shella.offsetX, -this.shella.offsetY, -this.shella.offsetZ);
      GlStateManager.translate(-this.shella.rotationPointX * f5, -this.shella.rotationPointY * f5, -this.shella.rotationPointZ * f5);
      this.shella.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shell_1.offsetX, this.shell_1.offsetY, this.shell_1.offsetZ);
      GlStateManager.translate(this.shell_1.rotationPointX * f5, this.shell_1.rotationPointY * f5, this.shell_1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shell_1.offsetX, -this.shell_1.offsetY, -this.shell_1.offsetZ);
      GlStateManager.translate(-this.shell_1.rotationPointX * f5, -this.shell_1.rotationPointY * f5, -this.shell_1.rotationPointZ * f5);
      this.shell_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape.offsetX, this.shape.offsetY, this.shape.offsetZ);
      GlStateManager.translate(this.shape.rotationPointX * f5, this.shape.rotationPointY * f5, this.shape.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape.offsetX, -this.shape.offsetY, -this.shape.offsetZ);
      GlStateManager.translate(-this.shape.rotationPointX * f5, -this.shape.rotationPointY * f5, -this.shape.rotationPointZ * f5);
      this.shape.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_3.offsetX, this.shape_3.offsetY, this.shape_3.offsetZ);
      GlStateManager.translate(this.shape_3.rotationPointX * f5, this.shape_3.rotationPointY * f5, this.shape_3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape_3.offsetX, -this.shape_3.offsetY, -this.shape_3.offsetZ);
      GlStateManager.translate(-this.shape_3.rotationPointX * f5, -this.shape_3.rotationPointY * f5, -this.shape_3.rotationPointZ * f5);
      this.shape_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shell_2.offsetX, this.shell_2.offsetY, this.shell_2.offsetZ);
      GlStateManager.translate(this.shell_2.rotationPointX * f5, this.shell_2.rotationPointY * f5, this.shell_2.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shell_2.offsetX, -this.shell_2.offsetY, -this.shell_2.offsetZ);
      GlStateManager.translate(-this.shell_2.rotationPointX * f5, -this.shell_2.rotationPointY * f5, -this.shell_2.rotationPointZ * f5);
      this.shell_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.decor.offsetX, this.decor.offsetY, this.decor.offsetZ);
      GlStateManager.translate(this.decor.rotationPointX * f5, this.decor.rotationPointY * f5, this.decor.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.9, 1.53);
      GlStateManager.translate(-this.decor.offsetX, -this.decor.offsetY, -this.decor.offsetZ);
      GlStateManager.translate(-this.decor.rotationPointX * f5, -this.decor.rotationPointY * f5, -this.decor.rotationPointZ * f5);
      this.decor.render(f5);
      GlStateManager.popMatrix();
      this.thorns.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shell.offsetX, this.shell.offsetY, this.shell.offsetZ);
      GlStateManager.translate(this.shell.rotationPointX * f5, this.shell.rotationPointY * f5, this.shell.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shell.offsetX, -this.shell.offsetY, -this.shell.offsetZ);
      GlStateManager.translate(-this.shell.rotationPointX * f5, -this.shell.rotationPointY * f5, -this.shell.rotationPointZ * f5);
      this.shell.render(f5);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
