//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.ColorConverters;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class BilebiterModel extends ModelBase {
   public ModelRenderer shape1;
   public ModelRenderer shape1_1;
   public ModelRenderer shape1_2;
   public ModelRenderer shape1_3;
   public ModelRenderer shape1_4;
   public ModelRenderer shape1_5;
   public ModelRenderer shape1_6;
   public ModelRenderer shape1_7;
   public ModelRenderer shape1_8;
   public ModelRenderer shape1_9;
   public ModelRenderer shape1_10;
   public ModelRenderer sphere1;
   public ModelRenderer sphere2;
   public ModelRenderer shape1_11;
   public ModelRenderer shape1_12;
   public ModelRenderer shape1_13;
   public ModelRenderer shape1_14;
   public ModelRenderer shape1_15;
   public ModelRenderer wing1;
   public ModelRenderer wing2;
   public ModelRenderer wing7;
   public ModelRenderer wing4;
   public ModelRenderer wing5;
   public ModelRenderer wing6;
   public ModelRenderer wing3;
   public ModelRenderer wing8;
   public ModelRenderer scope1;
   public ModelRenderer scope2;
   public ModelRenderer priklad1;
   public ModelRenderer priklad2;
   public ModelRenderer hhhhsphere1;
   public ModelRenderer hhhhsphere2;
   public ModelRenderer hhhhsphere3;
   public ModelRenderer hhhhsphere4;
   public ModelRenderer hhhhsphere5;
   public ModelRenderer aaaasphere1;
   public ModelRenderer aaaasphere2;
   public ModelRenderer aaaasphere3;
   public ModelRenderer aaaasphere4;
   public ModelRenderer aaaasphere5;
   public ModelRenderer bbbbsphere1;
   public ModelRenderer bbbbsphere2;
   public ModelRenderer bbbbsphere3;
   public ModelRenderer bbbbsphere4;
   public ModelRenderer bbbbsphere5;
   public ModelRenderer ammosphere;

   public BilebiterModel() {
      this.textureWidth = 32;
      this.textureHeight = 32;
      this.shape1 = new ModelRenderer(this, 28, 19);
      this.shape1.setRotationPoint(0.0F, 1.0F, 4.0F);
      this.shape1.addBox(-0.5F, 0.0F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape1, 0.3642502F, 0.0F, 0.0F);
      this.shape1_7 = new ModelRenderer(this, 18, 19);
      this.shape1_7.setRotationPoint(0.0F, -2.2F, 15.1F);
      this.shape1_7.addBox(-1.0F, -1.0F, -0.7F, 2, 2, 5, 0.0F);
      this.setRotateAngle(this.shape1_7, -0.18203785F, 0.0F, 0.0F);
      this.priklad2 = new ModelRenderer(this, 11, 6);
      this.priklad2.setRotationPoint(0.0F, -1.6F, 7.2F);
      this.priklad2.addBox(-0.5F, -1.0F, 0.5F, 1, 3, 4, 0.0F);
      this.shape1_9 = new ModelRenderer(this, 5, 26);
      this.shape1_9.setRotationPoint(0.0F, 1.0F, -2.0F);
      this.shape1_9.addBox(-1.5F, -2.6F, -2.2F, 3, 3, 2, 0.0F);
      this.setRotateAngle(this.shape1_9, -0.13665928F, 0.0F, 0.0F);
      this.bbbbsphere4 = new ModelRenderer(this, 4, 0);
      this.bbbbsphere4.setRotationPoint(0.0F, -0.9F, 1.7F);
      this.bbbbsphere4.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.bbbbsphere4, 0.22759093F, -0.22759093F, (float) (Math.PI / 4));
      this.scope2 = new ModelRenderer(this, 0, 4);
      this.scope2.setRotationPoint(4.1F, -0.6F, -2.0F);
      this.scope2.addBox(0.5F, -0.5F, -2.0F, 1, 1, 5, 0.0F);
      this.hhhhsphere3 = new ModelRenderer(this, 8, 0);
      this.hhhhsphere3.setRotationPoint(1.7F, 0.55F, 1.3F);
      this.hhhhsphere3.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.hhhhsphere3, 0.63739425F, 0.5009095F, 0.0F);
      this.hhhhsphere1 = new ModelRenderer(this, 4, 0);
      this.hhhhsphere1.setRotationPoint(1.7F, 0.7F, -1.1F);
      this.hhhhsphere1.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.hhhhsphere1, 0.63739425F, 0.5009095F, 0.0F);
      this.aaaasphere3 = new ModelRenderer(this, 0, 0);
      this.aaaasphere3.setRotationPoint(-1.8F, 0.55F, 1.3F);
      this.aaaasphere3.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.aaaasphere3, 0.63739425F, -0.5009095F, 0.0F);
      this.bbbbsphere3 = new ModelRenderer(this, 0, 0);
      this.bbbbsphere3.setRotationPoint(0.0F, -0.9F, 0.5F);
      this.bbbbsphere3.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.bbbbsphere3, 0.091106184F, -0.091106184F, (float) (Math.PI / 4));
      this.priklad1 = new ModelRenderer(this, 9, 4);
      this.priklad1.setRotationPoint(0.0F, -2.2F, 10.0F);
      this.priklad1.addBox(-0.5F, -1.0F, 0.5F, 1, 4, 6, 0.0F);
      this.setRotateAngle(this.priklad1, -0.18203785F, 0.0F, 0.0F);
      this.shape1_15 = new ModelRenderer(this, 18, 10);
      this.shape1_15.setRotationPoint(0.0F, 2.0F, -1.0F);
      this.shape1_15.addBox(-1.0F, 0.0F, -2.8F, 2, 2, 5, 0.0F);
      this.setRotateAngle(this.shape1_15, 0.091106184F, 0.0F, 0.0F);
      this.aaaasphere1 = new ModelRenderer(this, 4, 0);
      this.aaaasphere1.setRotationPoint(-1.7F, 0.7F, -1.1F);
      this.aaaasphere1.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.aaaasphere1, 0.63739425F, -0.5009095F, 0.0F);
      this.hhhhsphere2 = new ModelRenderer(this, 10, 0);
      this.hhhhsphere2.setRotationPoint(1.7F, 0.74F, 0.0F);
      this.hhhhsphere2.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.hhhhsphere2, 0.63739425F, 0.5009095F, 0.0F);
      this.shape1_13 = new ModelRenderer(this, 19, 20);
      this.shape1_13.setRotationPoint(1.0F, -0.7F, -7.2F);
      this.shape1_13.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape1_13, -0.13665928F, 0.0F, 0.0F);
      this.shape1_5 = new ModelRenderer(this, 18, 19);
      this.shape1_5.setRotationPoint(0.0F, -2.8F, 11.1F);
      this.shape1_5.addBox(-1.0F, -1.0F, -0.7F, 2, 2, 5, 0.0F);
      this.shape1_12 = new ModelRenderer(this, 19, 20);
      this.shape1_12.setRotationPoint(-1.0F, -0.7F, -7.2F);
      this.shape1_12.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape1_12, -0.13665928F, 0.0F, 0.0F);
      this.aaaasphere2 = new ModelRenderer(this, 12, 0);
      this.aaaasphere2.setRotationPoint(-1.8F, 0.74F, 0.0F);
      this.aaaasphere2.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.aaaasphere2, 0.63739425F, -0.5009095F, 0.0F);
      this.bbbbsphere1 = new ModelRenderer(this, 8, 0);
      this.bbbbsphere1.setRotationPoint(0.0F, -1.0F, -2.0F);
      this.bbbbsphere1.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.bbbbsphere1, -0.13665928F, 0.13665928F, (float) (Math.PI / 4));
      this.wing2 = new ModelRenderer(this, 16, 17);
      this.wing2.setRotationPoint(6.75F, 0.0F, -2.9F);
      this.wing2.addBox(-0.1F, -0.5F, -0.3F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing2, 0.0F, -0.13665928F, 0.0F);
      this.bbbbsphere5 = new ModelRenderer(this, 0, 0);
      this.bbbbsphere5.setRotationPoint(0.0F, -0.9F, 2.95F);
      this.bbbbsphere5.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.bbbbsphere5, 0.31869712F, -0.31869712F, (float) (Math.PI / 4));
      this.wing7 = new ModelRenderer(this, 16, 17);
      this.wing7.setRotationPoint(-1.5F, 1.3F, -1.7F);
      this.wing7.addBox(-0.2F, -0.5F, -0.5F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing7, 0.0F, 0.22759093F, 2.8228955F);
      this.wing8 = new ModelRenderer(this, 16, 17);
      this.wing8.setRotationPoint(-6.75F, 3.0F, -2.9F);
      this.wing8.addBox(-0.65F, -0.2F, -0.22F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing8, 0.0F, -0.13665928F, 2.9140017F);
      this.wing4 = new ModelRenderer(this, 16, 17);
      this.wing4.setRotationPoint(6.75F, 3.0F, -2.9F);
      this.wing4.addBox(-0.65F, -0.8F, -0.22F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing4, 0.0F, -0.13665928F, 0.22759093F);
      this.scope1 = new ModelRenderer(this, 0, 4);
      this.scope1.setRotationPoint(3.6F, -0.6F, -2.0F);
      this.scope1.addBox(-0.5F, -0.5F, -2.0F, 1, 1, 5, 0.0F);
      this.aaaasphere5 = new ModelRenderer(this, 4, 0);
      this.aaaasphere5.setRotationPoint(-1.4F, -0.15F, 4.0F);
      this.aaaasphere5.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.aaaasphere5, 0.63739425F, -0.5009095F, 0.0F);
      this.shape1_2 = new ModelRenderer(this, 0, 22);
      this.shape1_2.setRotationPoint(0.0F, 1.0F, 0.0F);
      this.shape1_2.addBox(-2.0F, -2.4F, -3.0F, 4, 4, 6, 0.0F);
      this.setRotateAngle(this.shape1_2, -0.045553092F, 0.0F, 0.0F);
      this.wing5 = new ModelRenderer(this, 16, 17);
      this.wing5.setRotationPoint(-1.5F, 0.0F, -1.7F);
      this.wing5.addBox(-0.1F, -0.5F, -0.5F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing5, 0.0F, 0.22759093F, (float) Math.PI);
      this.shape1_4 = new ModelRenderer(this, 18, 19);
      this.shape1_4.setRotationPoint(0.0F, -2.0F, 8.4F);
      this.shape1_4.addBox(-1.0F, -1.0F, -0.5F, 2, 2, 5, 0.0F);
      this.setRotateAngle(this.shape1_4, 0.31869712F, 0.0F, 0.0F);
      this.aaaasphere4 = new ModelRenderer(this, 10, 0);
      this.aaaasphere4.setRotationPoint(-1.6F, 0.25F, 2.7F);
      this.aaaasphere4.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.aaaasphere4, 0.63739425F, -0.5009095F, 0.0F);
      this.shape1_14 = new ModelRenderer(this, 18, 5);
      this.shape1_14.setRotationPoint(0.0F, 1.08F, -2.4F);
      this.shape1_14.addBox(-1.5F, -1.42F, -4.7F, 3, 1, 4, 0.0F);
      this.setRotateAngle(this.shape1_14, 0.5462881F, 0.0F, 0.0F);
      this.shape1_1 = new ModelRenderer(this, 0, 14);
      this.shape1_1.setRotationPoint(0.0F, 1.0F, 4.0F);
      this.shape1_1.addBox(-1.5F, -2.6F, -2.2F, 3, 3, 5, 0.0F);
      this.setRotateAngle(this.shape1_1, 0.22759093F, 0.0F, 0.0F);
      this.shape1_8 = new ModelRenderer(this, 0, 12);
      this.shape1_8.setRotationPoint(0.0F, 0.4F, -7.7F);
      this.shape1_8.addBox(-0.5F, -0.5F, -0.5F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shape1_8, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape1_11 = new ModelRenderer(this, 20, 0);
      this.shape1_11.setRotationPoint(0.0F, -0.5F, -4.2F);
      this.shape1_11.addBox(-1.5F, -1.0F, -4.2F, 3, 1, 3, 0.0F);
      this.setRotateAngle(this.shape1_11, 0.13665928F, 0.0F, 0.0F);
      this.sphere2 = new ModelRenderer(this, 20, 26);
      this.sphere2.setRotationPoint(-1.2F, -0.8F, -4.8F);
      this.sphere2.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.sphere2, 0.63739425F, 0.0F, 0.0F);
      this.hhhhsphere5 = new ModelRenderer(this, 4, 0);
      this.hhhhsphere5.setRotationPoint(1.4F, -0.15F, 4.0F);
      this.hhhhsphere5.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.hhhhsphere5, 0.63739425F, 0.5009095F, 0.0F);
      this.hhhhsphere4 = new ModelRenderer(this, 0, 0);
      this.hhhhsphere4.setRotationPoint(1.6F, 0.25F, 2.7F);
      this.hhhhsphere4.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.hhhhsphere4, 0.63739425F, 0.5009095F, 0.0F);
      this.ammosphere = new ModelRenderer(this, 7, 5);
      this.ammosphere.setRotationPoint(0.0F, -2.4F, 16.41F);
      this.ammosphere.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.ammosphere, 0.63739425F, -0.5462881F, 0.63739425F);
      this.wing1 = new ModelRenderer(this, 16, 17);
      this.wing1.setRotationPoint(1.5F, 0.0F, -1.7F);
      this.wing1.addBox(-0.1F, -0.5F, -0.5F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing1, 0.0F, 0.22759093F, 0.0F);
      this.wing3 = new ModelRenderer(this, 16, 17);
      this.wing3.setRotationPoint(1.5F, 1.3F, -1.7F);
      this.wing3.addBox(-0.2F, -0.5F, -0.5F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing3, 0.0F, 0.22759093F, 0.31869712F);
      this.bbbbsphere2 = new ModelRenderer(this, 6, 0);
      this.bbbbsphere2.setRotationPoint(0.0F, -1.0F, -0.65F);
      this.bbbbsphere2.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.bbbbsphere2, -0.045553092F, 0.045553092F, (float) (Math.PI / 4));
      this.shape1_3 = new ModelRenderer(this, 18, 19);
      this.shape1_3.setRotationPoint(0.0F, -0.2F, 5.0F);
      this.shape1_3.addBox(-1.0F, -1.0F, 0.5F, 2, 2, 5, 0.0F);
      this.setRotateAngle(this.shape1_3, 0.5009095F, 0.0F, 0.0F);
      this.shape1_6 = new ModelRenderer(this, 18, 19);
      this.shape1_6.setRotationPoint(0.0F, -2.7F, 13.4F);
      this.shape1_6.addBox(-1.0F, -1.0F, -0.7F, 2, 2, 5, 0.0F);
      this.setRotateAngle(this.shape1_6, -0.27314404F, 0.0F, 0.0F);
      this.shape1_10 = new ModelRenderer(this, 20, 0);
      this.shape1_10.setRotationPoint(0.0F, -0.5F, -4.2F);
      this.shape1_10.addBox(-1.5F, -1.2F, -1.2F, 3, 2, 3, 0.0F);
      this.setRotateAngle(this.shape1_10, 0.13665928F, 0.0F, 0.0F);
      this.sphere1 = new ModelRenderer(this, 20, 26);
      this.sphere1.setRotationPoint(1.2F, -0.8F, -4.8F);
      this.sphere1.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.sphere1, 0.63739425F, 0.0F, 0.0F);
      this.wing6 = new ModelRenderer(this, 16, 17);
      this.wing6.setRotationPoint(-6.85F, 0.0F, -2.9F);
      this.wing6.addBox(-0.1F, -0.5F, -0.3F, 7, 1, 1, 0.0F);
      this.setRotateAngle(this.wing6, 0.0F, -0.13665928F, (float) Math.PI);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.shape1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_7.offsetX, this.shape1_7.offsetY, this.shape1_7.offsetZ);
      GlStateManager.translate(this.shape1_7.rotationPointX * f5, this.shape1_7.rotationPointY * f5, this.shape1_7.rotationPointZ * f5);
      GlStateManager.scale(0.3, 0.3, 0.3);
      GlStateManager.translate(-this.shape1_7.offsetX, -this.shape1_7.offsetY, -this.shape1_7.offsetZ);
      GlStateManager.translate(-this.shape1_7.rotationPointX * f5, -this.shape1_7.rotationPointY * f5, -this.shape1_7.rotationPointZ * f5);
      this.shape1_7.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.priklad2.offsetX, this.priklad2.offsetY, this.priklad2.offsetZ);
      GlStateManager.translate(this.priklad2.rotationPointX * f5, this.priklad2.rotationPointY * f5, this.priklad2.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.7, 0.7);
      GlStateManager.translate(-this.priklad2.offsetX, -this.priklad2.offsetY, -this.priklad2.offsetZ);
      GlStateManager.translate(-this.priklad2.rotationPointX * f5, -this.priklad2.rotationPointY * f5, -this.priklad2.rotationPointZ * f5);
      this.priklad2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_9.offsetX, this.shape1_9.offsetY, this.shape1_9.offsetZ);
      GlStateManager.translate(this.shape1_9.rotationPointX * f5, this.shape1_9.rotationPointY * f5, this.shape1_9.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shape1_9.offsetX, -this.shape1_9.offsetY, -this.shape1_9.offsetZ);
      GlStateManager.translate(-this.shape1_9.rotationPointX * f5, -this.shape1_9.rotationPointY * f5, -this.shape1_9.rotationPointZ * f5);
      this.shape1_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.scope2.offsetX, this.scope2.offsetY, this.scope2.offsetZ);
      GlStateManager.translate(this.scope2.rotationPointX * f5, this.scope2.rotationPointY * f5, this.scope2.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.6);
      GlStateManager.translate(-this.scope2.offsetX, -this.scope2.offsetY, -this.scope2.offsetZ);
      GlStateManager.translate(-this.scope2.rotationPointX * f5, -this.scope2.rotationPointY * f5, -this.scope2.rotationPointZ * f5);
      this.scope2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.priklad1.offsetX, this.priklad1.offsetY, this.priklad1.offsetZ);
      GlStateManager.translate(this.priklad1.rotationPointX * f5, this.priklad1.rotationPointY * f5, this.priklad1.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.7, 0.7);
      GlStateManager.translate(-this.priklad1.offsetX, -this.priklad1.offsetY, -this.priklad1.offsetZ);
      GlStateManager.translate(-this.priklad1.rotationPointX * f5, -this.priklad1.rotationPointY * f5, -this.priklad1.rotationPointZ * f5);
      this.priklad1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_15.offsetX, this.shape1_15.offsetY, this.shape1_15.offsetZ);
      GlStateManager.translate(this.shape1_15.rotationPointX * f5, this.shape1_15.rotationPointY * f5, this.shape1_15.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shape1_15.offsetX, -this.shape1_15.offsetY, -this.shape1_15.offsetZ);
      GlStateManager.translate(-this.shape1_15.rotationPointX * f5, -this.shape1_15.rotationPointY * f5, -this.shape1_15.rotationPointZ * f5);
      this.shape1_15.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_13.offsetX, this.shape1_13.offsetY, this.shape1_13.offsetZ);
      GlStateManager.translate(this.shape1_13.rotationPointX * f5, this.shape1_13.rotationPointY * f5, this.shape1_13.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.shape1_13.offsetX, -this.shape1_13.offsetY, -this.shape1_13.offsetZ);
      GlStateManager.translate(-this.shape1_13.rotationPointX * f5, -this.shape1_13.rotationPointY * f5, -this.shape1_13.rotationPointZ * f5);
      this.shape1_13.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_5.offsetX, this.shape1_5.offsetY, this.shape1_5.offsetZ);
      GlStateManager.translate(this.shape1_5.rotationPointX * f5, this.shape1_5.rotationPointY * f5, this.shape1_5.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.shape1_5.offsetX, -this.shape1_5.offsetY, -this.shape1_5.offsetZ);
      GlStateManager.translate(-this.shape1_5.rotationPointX * f5, -this.shape1_5.rotationPointY * f5, -this.shape1_5.rotationPointZ * f5);
      this.shape1_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_12.offsetX, this.shape1_12.offsetY, this.shape1_12.offsetZ);
      GlStateManager.translate(this.shape1_12.rotationPointX * f5, this.shape1_12.rotationPointY * f5, this.shape1_12.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.shape1_12.offsetX, -this.shape1_12.offsetY, -this.shape1_12.offsetZ);
      GlStateManager.translate(-this.shape1_12.rotationPointX * f5, -this.shape1_12.rotationPointY * f5, -this.shape1_12.rotationPointZ * f5);
      this.shape1_12.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing2.offsetX, this.wing2.offsetY, this.wing2.offsetZ);
      GlStateManager.translate(this.wing2.rotationPointX * f5, this.wing2.rotationPointY * f5, this.wing2.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.65, 0.65);
      GlStateManager.translate(-this.wing2.offsetX, -this.wing2.offsetY, -this.wing2.offsetZ);
      GlStateManager.translate(-this.wing2.rotationPointX * f5, -this.wing2.rotationPointY * f5, -this.wing2.rotationPointZ * f5);
      this.wing2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing7.offsetX, this.wing7.offsetY, this.wing7.offsetZ);
      GlStateManager.translate(this.wing7.rotationPointX * f5, this.wing7.rotationPointY * f5, this.wing7.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.7, 0.7);
      GlStateManager.translate(-this.wing7.offsetX, -this.wing7.offsetY, -this.wing7.offsetZ);
      GlStateManager.translate(-this.wing7.rotationPointX * f5, -this.wing7.rotationPointY * f5, -this.wing7.rotationPointZ * f5);
      this.wing7.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing8.offsetX, this.wing8.offsetY, this.wing8.offsetZ);
      GlStateManager.translate(this.wing8.rotationPointX * f5, this.wing8.rotationPointY * f5, this.wing8.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.65, 0.65);
      GlStateManager.translate(-this.wing8.offsetX, -this.wing8.offsetY, -this.wing8.offsetZ);
      GlStateManager.translate(-this.wing8.rotationPointX * f5, -this.wing8.rotationPointY * f5, -this.wing8.rotationPointZ * f5);
      this.wing8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing4.offsetX, this.wing4.offsetY, this.wing4.offsetZ);
      GlStateManager.translate(this.wing4.rotationPointX * f5, this.wing4.rotationPointY * f5, this.wing4.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.65, 0.65);
      GlStateManager.translate(-this.wing4.offsetX, -this.wing4.offsetY, -this.wing4.offsetZ);
      GlStateManager.translate(-this.wing4.rotationPointX * f5, -this.wing4.rotationPointY * f5, -this.wing4.rotationPointZ * f5);
      this.wing4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.scope1.offsetX, this.scope1.offsetY, this.scope1.offsetZ);
      GlStateManager.translate(this.scope1.rotationPointX * f5, this.scope1.rotationPointY * f5, this.scope1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.scope1.offsetX, -this.scope1.offsetY, -this.scope1.offsetZ);
      GlStateManager.translate(-this.scope1.rotationPointX * f5, -this.scope1.rotationPointY * f5, -this.scope1.rotationPointZ * f5);
      this.scope1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_2.offsetX, this.shape1_2.offsetY, this.shape1_2.offsetZ);
      GlStateManager.translate(this.shape1_2.rotationPointX * f5, this.shape1_2.rotationPointY * f5, this.shape1_2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape1_2.offsetX, -this.shape1_2.offsetY, -this.shape1_2.offsetZ);
      GlStateManager.translate(-this.shape1_2.rotationPointX * f5, -this.shape1_2.rotationPointY * f5, -this.shape1_2.rotationPointZ * f5);
      this.shape1_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing5.offsetX, this.wing5.offsetY, this.wing5.offsetZ);
      GlStateManager.translate(this.wing5.rotationPointX * f5, this.wing5.rotationPointY * f5, this.wing5.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.7, 0.7);
      GlStateManager.translate(-this.wing5.offsetX, -this.wing5.offsetY, -this.wing5.offsetZ);
      GlStateManager.translate(-this.wing5.rotationPointX * f5, -this.wing5.rotationPointY * f5, -this.wing5.rotationPointZ * f5);
      this.wing5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_4.offsetX, this.shape1_4.offsetY, this.shape1_4.offsetZ);
      GlStateManager.translate(this.shape1_4.rotationPointX * f5, this.shape1_4.rotationPointY * f5, this.shape1_4.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.6);
      GlStateManager.translate(-this.shape1_4.offsetX, -this.shape1_4.offsetY, -this.shape1_4.offsetZ);
      GlStateManager.translate(-this.shape1_4.rotationPointX * f5, -this.shape1_4.rotationPointY * f5, -this.shape1_4.rotationPointZ * f5);
      this.shape1_4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_14.offsetX, this.shape1_14.offsetY, this.shape1_14.offsetZ);
      GlStateManager.translate(this.shape1_14.rotationPointX * f5, this.shape1_14.rotationPointY * f5, this.shape1_14.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.8, 0.8);
      GlStateManager.translate(-this.shape1_14.offsetX, -this.shape1_14.offsetY, -this.shape1_14.offsetZ);
      GlStateManager.translate(-this.shape1_14.rotationPointX * f5, -this.shape1_14.rotationPointY * f5, -this.shape1_14.rotationPointZ * f5);
      this.shape1_14.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_1.offsetX, this.shape1_1.offsetY, this.shape1_1.offsetZ);
      GlStateManager.translate(this.shape1_1.rotationPointX * f5, this.shape1_1.rotationPointY * f5, this.shape1_1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape1_1.offsetX, -this.shape1_1.offsetY, -this.shape1_1.offsetZ);
      GlStateManager.translate(-this.shape1_1.rotationPointX * f5, -this.shape1_1.rotationPointY * f5, -this.shape1_1.rotationPointZ * f5);
      this.shape1_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_8.offsetX, this.shape1_8.offsetY, this.shape1_8.offsetZ);
      GlStateManager.translate(this.shape1_8.rotationPointX * f5, this.shape1_8.rotationPointY * f5, this.shape1_8.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape1_8.offsetX, -this.shape1_8.offsetY, -this.shape1_8.offsetZ);
      GlStateManager.translate(-this.shape1_8.rotationPointX * f5, -this.shape1_8.rotationPointY * f5, -this.shape1_8.rotationPointZ * f5);
      this.shape1_8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_11.offsetX, this.shape1_11.offsetY, this.shape1_11.offsetZ);
      GlStateManager.translate(this.shape1_11.rotationPointX * f5, this.shape1_11.rotationPointY * f5, this.shape1_11.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.8, 0.8);
      GlStateManager.translate(-this.shape1_11.offsetX, -this.shape1_11.offsetY, -this.shape1_11.offsetZ);
      GlStateManager.translate(-this.shape1_11.rotationPointX * f5, -this.shape1_11.rotationPointY * f5, -this.shape1_11.rotationPointZ * f5);
      this.shape1_11.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.sphere2.offsetX, this.sphere2.offsetY, this.sphere2.offsetZ);
      GlStateManager.translate(this.sphere2.rotationPointX * f5, this.sphere2.rotationPointY * f5, this.sphere2.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.6);
      GlStateManager.translate(-this.sphere2.offsetX, -this.sphere2.offsetY, -this.sphere2.offsetZ);
      GlStateManager.translate(-this.sphere2.rotationPointX * f5, -this.sphere2.rotationPointY * f5, -this.sphere2.rotationPointZ * f5);
      this.sphere2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.ammosphere.offsetX, this.ammosphere.offsetY, this.ammosphere.offsetZ);
      GlStateManager.translate(this.ammosphere.rotationPointX * f5, this.ammosphere.rotationPointY * f5, this.ammosphere.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.ammosphere.offsetX, -this.ammosphere.offsetY, -this.ammosphere.offsetZ);
      GlStateManager.translate(-this.ammosphere.rotationPointX * f5, -this.ammosphere.rotationPointY * f5, -this.ammosphere.rotationPointZ * f5);
      this.ammosphere.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing1.offsetX, this.wing1.offsetY, this.wing1.offsetZ);
      GlStateManager.translate(this.wing1.rotationPointX * f5, this.wing1.rotationPointY * f5, this.wing1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.7, 0.7);
      GlStateManager.translate(-this.wing1.offsetX, -this.wing1.offsetY, -this.wing1.offsetZ);
      GlStateManager.translate(-this.wing1.rotationPointX * f5, -this.wing1.rotationPointY * f5, -this.wing1.rotationPointZ * f5);
      this.wing1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing3.offsetX, this.wing3.offsetY, this.wing3.offsetZ);
      GlStateManager.translate(this.wing3.rotationPointX * f5, this.wing3.rotationPointY * f5, this.wing3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.7, 0.7);
      GlStateManager.translate(-this.wing3.offsetX, -this.wing3.offsetY, -this.wing3.offsetZ);
      GlStateManager.translate(-this.wing3.rotationPointX * f5, -this.wing3.rotationPointY * f5, -this.wing3.rotationPointZ * f5);
      this.wing3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_3.offsetX, this.shape1_3.offsetY, this.shape1_3.offsetZ);
      GlStateManager.translate(this.shape1_3.rotationPointX * f5, this.shape1_3.rotationPointY * f5, this.shape1_3.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shape1_3.offsetX, -this.shape1_3.offsetY, -this.shape1_3.offsetZ);
      GlStateManager.translate(-this.shape1_3.rotationPointX * f5, -this.shape1_3.rotationPointY * f5, -this.shape1_3.rotationPointZ * f5);
      this.shape1_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_6.offsetX, this.shape1_6.offsetY, this.shape1_6.offsetZ);
      GlStateManager.translate(this.shape1_6.rotationPointX * f5, this.shape1_6.rotationPointY * f5, this.shape1_6.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.4, 0.4);
      GlStateManager.translate(-this.shape1_6.offsetX, -this.shape1_6.offsetY, -this.shape1_6.offsetZ);
      GlStateManager.translate(-this.shape1_6.rotationPointX * f5, -this.shape1_6.rotationPointY * f5, -this.shape1_6.rotationPointZ * f5);
      this.shape1_6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_10.offsetX, this.shape1_10.offsetY, this.shape1_10.offsetZ);
      GlStateManager.translate(this.shape1_10.rotationPointX * f5, this.shape1_10.rotationPointY * f5, this.shape1_10.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape1_10.offsetX, -this.shape1_10.offsetY, -this.shape1_10.offsetZ);
      GlStateManager.translate(-this.shape1_10.rotationPointX * f5, -this.shape1_10.rotationPointY * f5, -this.shape1_10.rotationPointZ * f5);
      this.shape1_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.sphere1.offsetX, this.sphere1.offsetY, this.sphere1.offsetZ);
      GlStateManager.translate(this.sphere1.rotationPointX * f5, this.sphere1.rotationPointY * f5, this.sphere1.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.6);
      GlStateManager.translate(-this.sphere1.offsetX, -this.sphere1.offsetY, -this.sphere1.offsetZ);
      GlStateManager.translate(-this.sphere1.rotationPointX * f5, -this.sphere1.rotationPointY * f5, -this.sphere1.rotationPointZ * f5);
      this.sphere1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.wing6.offsetX, this.wing6.offsetY, this.wing6.offsetZ);
      GlStateManager.translate(this.wing6.rotationPointX * f5, this.wing6.rotationPointY * f5, this.wing6.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.65, 0.65);
      GlStateManager.translate(-this.wing6.offsetX, -this.wing6.offsetY, -this.wing6.offsetZ);
      GlStateManager.translate(-this.wing6.rotationPointX * f5, -this.wing6.rotationPointY * f5, -this.wing6.rotationPointZ * f5);
      this.wing6.render(f5);
      GlStateManager.popMatrix();
      int for1PRIM = 20;
      int maxPRIM = 100;
      if (f4 == 1.0F) {
         for1PRIM = 15;
         int var17 = 75;
      }

      if (f4 > 1.0F) {
         for1PRIM = 10;
         int var18 = 50;
      }

      int for1shootS = 40;
      int maxchargeS = 200;
      if (f4 == 1.0F) {
         for1shootS = 35;
         int var19 = 175;
      }

      if (f4 > 1.0F) {
         for1shootS = 30;
         int var20 = 150;
      }

      GlStateManager.pushMatrix();
      GlStateManager.translate(this.bbbbsphere1.offsetX, this.bbbbsphere1.offsetY, this.bbbbsphere1.offsetZ);
      GlStateManager.translate(this.bbbbsphere1.rotationPointX * f5, this.bbbbsphere1.rotationPointY * f5, this.bbbbsphere1.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.bbbbsphere1.offsetX, -this.bbbbsphere1.offsetY, -this.bbbbsphere1.offsetZ);
      GlStateManager.translate(-this.bbbbsphere1.rotationPointX * f5, -this.bbbbsphere1.rotationPointY * f5, -this.bbbbsphere1.rotationPointZ * f5);
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(
         OpenGlHelper.lightmapTexUnit,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3) * 11.0F + 20.0F,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3) * 11.0F + 20.0F
      );
      this.bbbbsphere1.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.bbbbsphere2.offsetX, this.bbbbsphere2.offsetY, this.bbbbsphere2.offsetZ);
      GlStateManager.translate(this.bbbbsphere2.rotationPointX * f5, this.bbbbsphere2.rotationPointY * f5, this.bbbbsphere2.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.4, 0.4);
      GlStateManager.translate(-this.bbbbsphere2.offsetX, -this.bbbbsphere2.offsetY, -this.bbbbsphere2.offsetZ);
      GlStateManager.translate(-this.bbbbsphere2.rotationPointX * f5, -this.bbbbsphere2.rotationPointY * f5, -this.bbbbsphere2.rotationPointZ * f5);
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(
         OpenGlHelper.lightmapTexUnit,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM) * 11.0F + 20.0F,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM) * 11.0F + 20.0F
      );
      this.bbbbsphere2.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.bbbbsphere3.offsetX, this.bbbbsphere3.offsetY, this.bbbbsphere3.offsetZ);
      GlStateManager.translate(this.bbbbsphere3.rotationPointX * f5, this.bbbbsphere3.rotationPointY * f5, this.bbbbsphere3.rotationPointZ * f5);
      GlStateManager.scale(0.35, 0.35, 0.35);
      GlStateManager.translate(-this.bbbbsphere3.offsetX, -this.bbbbsphere3.offsetY, -this.bbbbsphere3.offsetZ);
      GlStateManager.translate(-this.bbbbsphere3.rotationPointX * f5, -this.bbbbsphere3.rotationPointY * f5, -this.bbbbsphere3.rotationPointZ * f5);
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(
         OpenGlHelper.lightmapTexUnit,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM * 2) * 11.0F + 20.0F,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM * 2) * 11.0F + 20.0F
      );
      this.bbbbsphere3.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.bbbbsphere4.offsetX, this.bbbbsphere4.offsetY, this.bbbbsphere4.offsetZ);
      GlStateManager.translate(this.bbbbsphere4.rotationPointX * f5, this.bbbbsphere4.rotationPointY * f5, this.bbbbsphere4.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.4, 0.4);
      GlStateManager.translate(-this.bbbbsphere4.offsetX, -this.bbbbsphere4.offsetY, -this.bbbbsphere4.offsetZ);
      GlStateManager.translate(-this.bbbbsphere4.rotationPointX * f5, -this.bbbbsphere4.rotationPointY * f5, -this.bbbbsphere4.rotationPointZ * f5);
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(
         OpenGlHelper.lightmapTexUnit,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM * 3) * 11.0F + 20.0F,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM * 3) * 11.0F + 20.0F
      );
      this.bbbbsphere4.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.bbbbsphere5.offsetX, this.bbbbsphere5.offsetY, this.bbbbsphere5.offsetZ);
      GlStateManager.translate(this.bbbbsphere5.rotationPointX * f5, this.bbbbsphere5.rotationPointY * f5, this.bbbbsphere5.rotationPointZ * f5);
      GlStateManager.scale(0.45, 0.45, 0.45);
      GlStateManager.translate(-this.bbbbsphere5.offsetX, -this.bbbbsphere5.offsetY, -this.bbbbsphere5.offsetZ);
      GlStateManager.translate(-this.bbbbsphere5.rotationPointX * f5, -this.bbbbsphere5.rotationPointY * f5, -this.bbbbsphere5.rotationPointZ * f5);
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(
         OpenGlHelper.lightmapTexUnit,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM * 4) * 11.0F + 20.0F,
         ColorConverters.InBorder(0.0F, (float)for1PRIM, f3 - for1PRIM * 4) * 11.0F + 20.0F
      );
      this.bbbbsphere5.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
      float ha1 = ColorConverters.InBorder(0.0F, (float)for1shootS, f2) * 5.5F + 20.0F;
      float ha2 = ColorConverters.InBorder(0.0F, (float)for1shootS, f2 - for1shootS) * 5.5F + 20.0F;
      float ha3 = ColorConverters.InBorder(0.0F, (float)for1shootS, f2 - for1shootS * 2) * 5.5F + 20.0F;
      float ha4 = ColorConverters.InBorder(0.0F, (float)for1shootS, f2 - for1shootS * 3) * 5.5F + 20.0F;
      float ha5 = ColorConverters.InBorder(0.0F, (float)for1shootS, f2 - for1shootS * 4) * 5.5F + 20.0F;
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      GlStateManager.translate(this.hhhhsphere5.offsetX, this.hhhhsphere5.offsetY, this.hhhhsphere5.offsetZ);
      GlStateManager.translate(this.hhhhsphere5.rotationPointX * f5, this.hhhhsphere5.rotationPointY * f5, this.hhhhsphere5.rotationPointZ * f5);
      GlStateManager.scale(0.35, 0.35, 0.35);
      GlStateManager.translate(-this.hhhhsphere5.offsetX, -this.hhhhsphere5.offsetY, -this.hhhhsphere5.offsetZ);
      GlStateManager.translate(-this.hhhhsphere5.rotationPointX * f5, -this.hhhhsphere5.rotationPointY * f5, -this.hhhhsphere5.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha5, ha5);
      this.hhhhsphere5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.hhhhsphere4.offsetX, this.hhhhsphere4.offsetY, this.hhhhsphere4.offsetZ);
      GlStateManager.translate(this.hhhhsphere4.rotationPointX * f5, this.hhhhsphere4.rotationPointY * f5, this.hhhhsphere4.rotationPointZ * f5);
      GlStateManager.scale(0.45, 0.45, 0.45);
      GlStateManager.translate(-this.hhhhsphere4.offsetX, -this.hhhhsphere4.offsetY, -this.hhhhsphere4.offsetZ);
      GlStateManager.translate(-this.hhhhsphere4.rotationPointX * f5, -this.hhhhsphere4.rotationPointY * f5, -this.hhhhsphere4.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha4, ha4);
      this.hhhhsphere4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.hhhhsphere3.offsetX, this.hhhhsphere3.offsetY, this.hhhhsphere3.offsetZ);
      GlStateManager.translate(this.hhhhsphere3.rotationPointX * f5, this.hhhhsphere3.rotationPointY * f5, this.hhhhsphere3.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.hhhhsphere3.offsetX, -this.hhhhsphere3.offsetY, -this.hhhhsphere3.offsetZ);
      GlStateManager.translate(-this.hhhhsphere3.rotationPointX * f5, -this.hhhhsphere3.rotationPointY * f5, -this.hhhhsphere3.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha3, ha3);
      this.hhhhsphere3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.hhhhsphere2.offsetX, this.hhhhsphere2.offsetY, this.hhhhsphere2.offsetZ);
      GlStateManager.translate(this.hhhhsphere2.rotationPointX * f5, this.hhhhsphere2.rotationPointY * f5, this.hhhhsphere2.rotationPointZ * f5);
      GlStateManager.scale(0.45, 0.45, 0.45);
      GlStateManager.translate(-this.hhhhsphere2.offsetX, -this.hhhhsphere2.offsetY, -this.hhhhsphere2.offsetZ);
      GlStateManager.translate(-this.hhhhsphere2.rotationPointX * f5, -this.hhhhsphere2.rotationPointY * f5, -this.hhhhsphere2.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha2, ha2);
      this.hhhhsphere2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.hhhhsphere1.offsetX, this.hhhhsphere1.offsetY, this.hhhhsphere1.offsetZ);
      GlStateManager.translate(this.hhhhsphere1.rotationPointX * f5, this.hhhhsphere1.rotationPointY * f5, this.hhhhsphere1.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.4, 0.4);
      GlStateManager.translate(-this.hhhhsphere1.offsetX, -this.hhhhsphere1.offsetY, -this.hhhhsphere1.offsetZ);
      GlStateManager.translate(-this.hhhhsphere1.rotationPointX * f5, -this.hhhhsphere1.rotationPointY * f5, -this.hhhhsphere1.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha1, ha1);
      this.hhhhsphere1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.aaaasphere1.offsetX, this.aaaasphere1.offsetY, this.aaaasphere1.offsetZ);
      GlStateManager.translate(this.aaaasphere1.rotationPointX * f5, this.aaaasphere1.rotationPointY * f5, this.aaaasphere1.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.4, 0.4);
      GlStateManager.translate(-this.aaaasphere1.offsetX, -this.aaaasphere1.offsetY, -this.aaaasphere1.offsetZ);
      GlStateManager.translate(-this.aaaasphere1.rotationPointX * f5, -this.aaaasphere1.rotationPointY * f5, -this.aaaasphere1.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha1, ha1);
      this.aaaasphere1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.aaaasphere2.offsetX, this.aaaasphere2.offsetY, this.aaaasphere2.offsetZ);
      GlStateManager.translate(this.aaaasphere2.rotationPointX * f5, this.aaaasphere2.rotationPointY * f5, this.aaaasphere2.rotationPointZ * f5);
      GlStateManager.scale(0.45, 0.45, 0.45);
      GlStateManager.translate(-this.aaaasphere2.offsetX, -this.aaaasphere2.offsetY, -this.aaaasphere2.offsetZ);
      GlStateManager.translate(-this.aaaasphere2.rotationPointX * f5, -this.aaaasphere2.rotationPointY * f5, -this.aaaasphere2.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha2, ha2);
      this.aaaasphere2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.aaaasphere3.offsetX, this.aaaasphere3.offsetY, this.aaaasphere3.offsetZ);
      GlStateManager.translate(this.aaaasphere3.rotationPointX * f5, this.aaaasphere3.rotationPointY * f5, this.aaaasphere3.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.aaaasphere3.offsetX, -this.aaaasphere3.offsetY, -this.aaaasphere3.offsetZ);
      GlStateManager.translate(-this.aaaasphere3.rotationPointX * f5, -this.aaaasphere3.rotationPointY * f5, -this.aaaasphere3.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha3, ha3);
      this.aaaasphere3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.aaaasphere4.offsetX, this.aaaasphere4.offsetY, this.aaaasphere4.offsetZ);
      GlStateManager.translate(this.aaaasphere4.rotationPointX * f5, this.aaaasphere4.rotationPointY * f5, this.aaaasphere4.rotationPointZ * f5);
      GlStateManager.scale(0.45, 0.45, 0.45);
      GlStateManager.translate(-this.aaaasphere4.offsetX, -this.aaaasphere4.offsetY, -this.aaaasphere4.offsetZ);
      GlStateManager.translate(-this.aaaasphere4.rotationPointX * f5, -this.aaaasphere4.rotationPointY * f5, -this.aaaasphere4.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha4, ha4);
      this.aaaasphere4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.aaaasphere5.offsetX, this.aaaasphere5.offsetY, this.aaaasphere5.offsetZ);
      GlStateManager.translate(this.aaaasphere5.rotationPointX * f5, this.aaaasphere5.rotationPointY * f5, this.aaaasphere5.rotationPointZ * f5);
      GlStateManager.scale(0.35, 0.35, 0.35);
      GlStateManager.translate(-this.aaaasphere5.offsetX, -this.aaaasphere5.offsetY, -this.aaaasphere5.offsetZ);
      GlStateManager.translate(-this.aaaasphere5.rotationPointX * f5, -this.aaaasphere5.rotationPointY * f5, -this.aaaasphere5.rotationPointZ * f5);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, ha5, ha5);
      this.aaaasphere5.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
