//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class BubbleFishModel extends ModelBase {
   public ModelRenderer shapess1;
   public ModelRenderer shapess1_1;
   public ModelRenderer shapess1_2;
   public ModelRenderer shape;
   public ModelRenderer shape_1;
   public ModelRenderer shape_2;
   public ModelRenderer shape_3;
   public ModelRenderer shape_4;
   public ModelRenderer shape_5;
   public ModelRenderer shape_6;
   public ModelRenderer shape_7;
   public ModelRenderer shape_8;
   public ModelRenderer shape_9;
   public ModelRenderer shape_10;
   public ModelRenderer shapeaa1;
   public ModelRenderer shapebb;
   public ModelRenderer shapeaa1_1;
   public ModelRenderer shapebb_1;
   public ModelRenderer shape_11;

   public BubbleFishModel() {
      this.textureWidth = 22;
      this.textureHeight = 32;
      this.shape_10 = new ModelRenderer(this, 12, 23);
      this.shape_10.setRotationPoint(0.0F, 1.7F, -2.7F);
      this.shape_10.addBox(-1.5F, 0.0F, 0.0F, 0, 3, 5, 0.0F);
      this.setRotateAngle(this.shape_10, 0.0F, 0.0F, 0.13665928F);
      this.shape_3 = new ModelRenderer(this, 10, 18);
      this.shape_3.setRotationPoint(0.0F, -1.45F, 9.0F);
      this.shape_3.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.shape_3, -0.045553092F, 0.0F, 0.0F);
      this.shape_2 = new ModelRenderer(this, 0, 18);
      this.shape_2.setRotationPoint(0.0F, -1.45F, 6.0F);
      this.shape_2.addBox(-1.5F, 0.0F, 0.0F, 3, 3, 4, 0.0F);
      this.setRotateAngle(this.shape_2, 0.091106184F, 0.0F, 0.0F);
      this.shape_6 = new ModelRenderer(this, 12, 0);
      this.shape_6.setRotationPoint(0.0F, 0.0F, -6.2F);
      this.shape_6.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.shape_6, 0.091106184F, 0.0F, 0.0F);
      this.shapess1_1 = new ModelRenderer(this, 18, 4);
      this.shapess1_1.setRotationPoint(0.0F, 1.5F, 4.3F);
      this.shapess1_1.addBox(-0.5F, -0.5F, 0.0F, 1, 8, 1, 0.0F);
      this.setRotateAngle(this.shapess1_1, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape_1 = new ModelRenderer(this, 0, 12);
      this.shape_1.setRotationPoint(0.0F, -1.2F, 3.3F);
      this.shape_1.addBox(-1.5F, 0.0F, 0.0F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.shape_1, 0.18203785F, 0.0F, 0.0F);
      this.shape = new ModelRenderer(this, 0, 0);
      this.shape.setRotationPoint(0.0F, -1.3F, -2.7F);
      this.shape.addBox(-1.5F, 0.0F, 0.0F, 3, 3, 6, 0.0F);
      this.shapeaa1 = new ModelRenderer(this, 0, 18);
      this.shapeaa1.setRotationPoint(2.0F, 0.3F, -3.2F);
      this.shapeaa1.addBox(-0.5F, -0.5F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shapeaa1, -0.22759093F, 0.0F, -1.4114478F);
      this.shape_4 = new ModelRenderer(this, 0, 25);
      this.shape_4.setRotationPoint(0.0F, -1.1F, -4.7F);
      this.shape_4.addBox(-1.5F, 0.0F, 0.0F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.shape_4, 0.13665928F, 0.0F, 0.0F);
      this.shape_7 = new ModelRenderer(this, 0, 0);
      this.shape_7.setRotationPoint(0.0F, 0.0F, -10.9F);
      this.shape_7.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shapeaa1_1 = new ModelRenderer(this, 0, 18);
      this.shapeaa1_1.setRotationPoint(-2.0F, 0.3F, -3.2F);
      this.shapeaa1_1.addBox(-0.5F, -0.5F, -1.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shapeaa1_1, 0.22759093F, (float) Math.PI, 1.4114478F);
      this.shape_8 = new ModelRenderer(this, 0, 1);
      this.shape_8.setRotationPoint(0.0F, -4.3F, -2.7F);
      this.shape_8.addBox(0.0F, 0.0F, 0.0F, 0, 3, 8, 0.0F);
      this.shapebb_1 = new ModelRenderer(this, 12, 14);
      this.shapebb_1.setRotationPoint(-4.5F, 0.0F, -4.1F);
      this.shapebb_1.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.shapebb_1, 0.091106184F, 0.0F, 0.0F);
      this.shape_11 = new ModelRenderer(this, 12, 23);
      this.shape_11.setRotationPoint(0.0F, 1.7F, -2.7F);
      this.shape_11.addBox(1.5F, 0.0F, 0.0F, 0, 3, 5, 0.0F);
      this.setRotateAngle(this.shape_11, 0.0F, 0.0F, -0.13665928F);
      this.shape_9 = new ModelRenderer(this, 14, 22);
      this.shape_9.setRotationPoint(0.0F, -2.3F, 9.3F);
      this.shape_9.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 3, 0.0F);
      this.setRotateAngle(this.shape_9, -0.045553092F, 0.0F, 0.0F);
      this.shapebb = new ModelRenderer(this, 12, 14);
      this.shapebb.setRotationPoint(4.5F, 0.0F, -4.1F);
      this.shapebb.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.shapebb, 0.091106184F, 0.0F, 0.0F);
      this.shapess1_2 = new ModelRenderer(this, 18, 4);
      this.shapess1_2.setRotationPoint(0.0F, 1.5F, 5.7F);
      this.shapess1_2.addBox(-0.5F, -0.5F, -1.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shapess1_2, 1.9123572F, 0.0F, 0.0F);
      this.shape_5 = new ModelRenderer(this, 12, 9);
      this.shape_5.setRotationPoint(0.0F, 0.4F, -5.8F);
      this.shape_5.addBox(-0.5F, 0.0F, -4.0F, 1, 1, 4, 0.0F);
      this.shapess1 = new ModelRenderer(this, 18, 4);
      this.shapess1.setRotationPoint(0.0F, 2.0F, 4.5F);
      this.shapess1.addBox(-0.5F, -0.5F, 0.0F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shapess1, 0.27314404F, 0.0F, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_10.offsetX, this.shape_10.offsetY, this.shape_10.offsetZ);
      GlStateManager.translate(this.shape_10.rotationPointX * f5, this.shape_10.rotationPointY * f5, this.shape_10.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.shape_10.offsetX, -this.shape_10.offsetY, -this.shape_10.offsetZ);
      GlStateManager.translate(-this.shape_10.rotationPointX * f5, -this.shape_10.rotationPointY * f5, -this.shape_10.rotationPointZ * f5);
      this.shape_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_3.offsetX, this.shape_3.offsetY, this.shape_3.offsetZ);
      GlStateManager.translate(this.shape_3.rotationPointX * f5, this.shape_3.rotationPointY * f5, this.shape_3.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape_3.offsetX, -this.shape_3.offsetY, -this.shape_3.offsetZ);
      GlStateManager.translate(-this.shape_3.rotationPointX * f5, -this.shape_3.rotationPointY * f5, -this.shape_3.rotationPointZ * f5);
      this.shape_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_2.offsetX, this.shape_2.offsetY, this.shape_2.offsetZ);
      GlStateManager.translate(this.shape_2.rotationPointX * f5, this.shape_2.rotationPointY * f5, this.shape_2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape_2.offsetX, -this.shape_2.offsetY, -this.shape_2.offsetZ);
      GlStateManager.translate(-this.shape_2.rotationPointX * f5, -this.shape_2.rotationPointY * f5, -this.shape_2.rotationPointZ * f5);
      this.shape_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_6.offsetX, this.shape_6.offsetY, this.shape_6.offsetZ);
      GlStateManager.translate(this.shape_6.rotationPointX * f5, this.shape_6.rotationPointY * f5, this.shape_6.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape_6.offsetX, -this.shape_6.offsetY, -this.shape_6.offsetZ);
      GlStateManager.translate(-this.shape_6.rotationPointX * f5, -this.shape_6.rotationPointY * f5, -this.shape_6.rotationPointZ * f5);
      this.shape_6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1_1.offsetX, this.shapess1_1.offsetY, this.shapess1_1.offsetZ);
      GlStateManager.translate(this.shapess1_1.rotationPointX * f5, this.shapess1_1.rotationPointY * f5, this.shapess1_1.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.0, 1.2);
      GlStateManager.translate(-this.shapess1_1.offsetX, -this.shapess1_1.offsetY, -this.shapess1_1.offsetZ);
      GlStateManager.translate(-this.shapess1_1.rotationPointX * f5, -this.shapess1_1.rotationPointY * f5, -this.shapess1_1.rotationPointZ * f5);
      this.shapess1_1.render(f5);
      GlStateManager.popMatrix();
      this.shape_1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape.offsetX, this.shape.offsetY, this.shape.offsetZ);
      GlStateManager.translate(this.shape.rotationPointX * f5, this.shape.rotationPointY * f5, this.shape.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.1, 1.1);
      GlStateManager.translate(-this.shape.offsetX, -this.shape.offsetY, -this.shape.offsetZ);
      GlStateManager.translate(-this.shape.rotationPointX * f5, -this.shape.rotationPointY * f5, -this.shape.rotationPointZ * f5);
      this.shape.render(f5);
      GlStateManager.popMatrix();
      this.shapeaa1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_4.offsetX, this.shape_4.offsetY, this.shape_4.offsetZ);
      GlStateManager.translate(this.shape_4.rotationPointX * f5, this.shape_4.rotationPointY * f5, this.shape_4.rotationPointZ * f5);
      GlStateManager.scale(1.3, 1.1, 1.1);
      GlStateManager.translate(-this.shape_4.offsetX, -this.shape_4.offsetY, -this.shape_4.offsetZ);
      GlStateManager.translate(-this.shape_4.rotationPointX * f5, -this.shape_4.rotationPointY * f5, -this.shape_4.rotationPointZ * f5);
      this.shape_4.render(f5);
      GlStateManager.popMatrix();
      this.shape_7.render(f5);
      this.shapeaa1_1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_8.offsetX, this.shape_8.offsetY, this.shape_8.offsetZ);
      GlStateManager.translate(this.shape_8.rotationPointX * f5, this.shape_8.rotationPointY * f5, this.shape_8.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.1, 1.1);
      GlStateManager.translate(-this.shape_8.offsetX, -this.shape_8.offsetY, -this.shape_8.offsetZ);
      GlStateManager.translate(-this.shape_8.rotationPointX * f5, -this.shape_8.rotationPointY * f5, -this.shape_8.rotationPointZ * f5);
      this.shape_8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapebb_1.offsetX, this.shapebb_1.offsetY, this.shapebb_1.offsetZ);
      GlStateManager.translate(this.shapebb_1.rotationPointX * f5, this.shapebb_1.rotationPointY * f5, this.shapebb_1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shapebb_1.offsetX, -this.shapebb_1.offsetY, -this.shapebb_1.offsetZ);
      GlStateManager.translate(-this.shapebb_1.rotationPointX * f5, -this.shapebb_1.rotationPointY * f5, -this.shapebb_1.rotationPointZ * f5);
      this.shapebb_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_11.offsetX, this.shape_11.offsetY, this.shape_11.offsetZ);
      GlStateManager.translate(this.shape_11.rotationPointX * f5, this.shape_11.rotationPointY * f5, this.shape_11.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.shape_11.offsetX, -this.shape_11.offsetY, -this.shape_11.offsetZ);
      GlStateManager.translate(-this.shape_11.rotationPointX * f5, -this.shape_11.rotationPointY * f5, -this.shape_11.rotationPointZ * f5);
      this.shape_11.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_9.offsetX, this.shape_9.offsetY, this.shape_9.offsetZ);
      GlStateManager.translate(this.shape_9.rotationPointX * f5, this.shape_9.rotationPointY * f5, this.shape_9.rotationPointZ * f5);
      GlStateManager.scale(0.5, 1.1, 1.1);
      GlStateManager.translate(-this.shape_9.offsetX, -this.shape_9.offsetY, -this.shape_9.offsetZ);
      GlStateManager.translate(-this.shape_9.rotationPointX * f5, -this.shape_9.rotationPointY * f5, -this.shape_9.rotationPointZ * f5);
      this.shape_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapebb.offsetX, this.shapebb.offsetY, this.shapebb.offsetZ);
      GlStateManager.translate(this.shapebb.rotationPointX * f5, this.shapebb.rotationPointY * f5, this.shapebb.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shapebb.offsetX, -this.shapebb.offsetY, -this.shapebb.offsetZ);
      GlStateManager.translate(-this.shapebb.rotationPointX * f5, -this.shapebb.rotationPointY * f5, -this.shapebb.rotationPointZ * f5);
      this.shapebb.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1_2.offsetX, this.shapess1_2.offsetY, this.shapess1_2.offsetZ);
      GlStateManager.translate(this.shapess1_2.rotationPointX * f5, this.shapess1_2.rotationPointY * f5, this.shapess1_2.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.0, 1.2);
      GlStateManager.translate(-this.shapess1_2.offsetX, -this.shapess1_2.offsetY, -this.shapess1_2.offsetZ);
      GlStateManager.translate(-this.shapess1_2.rotationPointX * f5, -this.shapess1_2.rotationPointY * f5, -this.shapess1_2.rotationPointZ * f5);
      this.shapess1_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_5.offsetX, this.shape_5.offsetY, this.shape_5.offsetZ);
      GlStateManager.translate(this.shape_5.rotationPointX * f5, this.shape_5.rotationPointY * f5, this.shape_5.rotationPointZ * f5);
      GlStateManager.scale(1.3, 1.1, 1.1);
      GlStateManager.translate(-this.shape_5.offsetX, -this.shape_5.offsetY, -this.shape_5.offsetZ);
      GlStateManager.translate(-this.shape_5.rotationPointX * f5, -this.shape_5.rotationPointY * f5, -this.shape_5.rotationPointZ * f5);
      this.shape_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1.offsetX, this.shapess1.offsetY, this.shapess1.offsetZ);
      GlStateManager.translate(this.shapess1.rotationPointX * f5, this.shapess1.rotationPointY * f5, this.shapess1.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.0, 1.2);
      GlStateManager.translate(-this.shapess1.offsetX, -this.shapess1.offsetY, -this.shapess1.offsetZ);
      GlStateManager.translate(-this.shapess1.rotationPointX * f5, -this.shapess1.rotationPointY * f5, -this.shapess1.rotationPointZ * f5);
      this.shapess1.render(f5);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
