package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.GetMOP;
import com.Vivern.Arpg.renders.ModelRendererGlow;
import com.Vivern.Arpg.renders.ModelRendererLimited;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class CinderBowModel extends ModelBase {
   public ModelRenderer shapeMAIN;
   public ModelRenderer shapeUP1;
   public ModelRenderer shapeDOWN1;
   public ModelRenderer shapeMAINglow;
   public ModelRenderer shapeUP1glow;
   public ModelRenderer shapeDOWN1glow;
   public ModelRenderer shapeUP2;
   public ModelRenderer shapeUP3;
   public ModelRenderer ropeUP;
   public ModelRenderer shapeDOWN2;
   public ModelRenderer shapeDOWN3;
   public ModelRenderer ropeDOWN;
   public ModelRenderer shapeUP2glow;
   public ModelRenderer shapeUP3glow;
   public ModelRenderer shapeDOWN2glow;
   public ModelRenderer shapeDOWN3glow;

   public CinderBowModel() {
      this.textureWidth = 32;
      this.textureHeight = 16;
      this.shapeDOWN2 = new ModelRenderer(this, 12, 0);
      this.shapeDOWN2.setRotationPoint(0.0F, -5.6F, 0.0F);
      this.shapeDOWN2.addBox(-1.0F, -5.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.shapeDOWN2, -0.18203785F, 0.0F, 0.0F);
      this.ropeUP = new ModelRendererGlow(this, 0, -1, 230, false);
      this.ropeUP.setRotationPoint(0.0F, -3.5F, 0.2F);
      this.ropeUP.addBox(0.0F, 0.0F, -0.5F, 0, 16, 1, 0.0F);
      this.setRotateAngle(this.ropeUP, 0.5462881F, 0.0F, 0.0F);
      this.shapeDOWN3glow = new ModelRenderer(this, 28, 12);
      this.shapeDOWN3glow.setRotationPoint(0.0F, -4.6F, 0.0F);
      this.shapeDOWN3glow.addBox(-0.5F, -2.0F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shapeDOWN3glow, -0.18203785F, 0.0F, 0.0F);
      this.shapeMAIN = new ModelRenderer(this, 2, 0);
      this.shapeMAIN.setRotationPoint(0.0F, 3.5F, 5.0F);
      this.shapeMAIN.addBox(-1.5F, -3.0F, -1.5F, 3, 6, 2, 0.0F);
      this.shapeMAINglow = new ModelRenderer(this, 2, 8);
      this.shapeMAINglow.setRotationPoint(0.0F, 3.5F, 5.0F);
      this.shapeMAINglow.addBox(-1.5F, -3.0F, -1.5F, 3, 6, 2, 0.0F);
      this.shapeUP3glow = new ModelRenderer(this, 28, 12);
      this.shapeUP3glow.setRotationPoint(0.0F, -4.6F, 0.0F);
      this.shapeUP3glow.addBox(-0.5F, -2.0F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shapeUP3glow, -0.18203785F, 0.0F, 0.0F);
      this.shapeDOWN3 = new ModelRenderer(this, 24, 11);
      this.shapeDOWN3.setRotationPoint(0.0F, -4.6F, 0.0F);
      this.shapeDOWN3.addBox(-0.5F, -4.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shapeDOWN3, -0.18203785F, 0.0F, 0.0F);
      this.shapeDOWN1 = new ModelRenderer(this, 12, 7);
      this.shapeDOWN1.setRotationPoint(0.0F, 6.0F, 5.0F);
      this.shapeDOWN1.addBox(-1.5F, -6.0F, -1.5F, 3, 6, 3, 0.05F);
      this.setRotateAngle(this.shapeDOWN1, -0.18203785F, 0.0F, (float) Math.PI);
      this.shapeUP3 = new ModelRenderer(this, 24, 11);
      this.shapeUP3.setRotationPoint(0.0F, -4.6F, 0.0F);
      this.shapeUP3.addBox(-0.5F, -4.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shapeUP3, -0.18203785F, 0.0F, 0.0F);
      this.ropeDOWN = new ModelRendererGlow(this, 0, -1, 230, false);
      this.ropeDOWN.setRotationPoint(0.0F, -3.5F, 0.2F);
      this.ropeDOWN.addBox(0.0F, 0.0F, -0.5F, 0, 16, 1, 0.0F);
      this.setRotateAngle(this.ropeDOWN, 0.5462881F, 0.0F, 0.0F);
      this.shapeUP2glow = new ModelRendererLimited(this, 24, 5, true, true, false, false, true, true);
      this.shapeUP2glow.setRotationPoint(0.0F, -5.6F, 0.0F);
      this.shapeUP2glow.addBox(-1.0F, -3.0F, -1.0F, 2, 3, 2, 0.0F);
      this.setRotateAngle(this.shapeUP2glow, -0.18203785F, 0.0F, 0.0F);
      this.shapeDOWN2glow = new ModelRendererLimited(this, 24, 5, true, true, false, false, true, true);
      this.shapeDOWN2glow.setRotationPoint(0.0F, -5.6F, 0.0F);
      this.shapeDOWN2glow.addBox(-1.0F, -3.0F, -1.0F, 2, 3, 2, 0.0F);
      this.setRotateAngle(this.shapeDOWN2glow, -0.18203785F, 0.0F, 0.0F);
      this.shapeUP2 = new ModelRenderer(this, 12, 0);
      this.shapeUP2.setRotationPoint(0.0F, -5.6F, 0.0F);
      this.shapeUP2.addBox(-1.0F, -5.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.shapeUP2, -0.18203785F, 0.0F, 0.0F);
      this.shapeUP1glow = new ModelRenderer(this, 20, 0);
      this.shapeUP1glow.setRotationPoint(0.0F, 1.0F, 5.0F);
      this.shapeUP1glow.addBox(-1.5F, -4.0F, -1.5F, 3, 4, 3, 0.05F);
      this.setRotateAngle(this.shapeUP1glow, -0.18203785F, 0.0F, 0.0F);
      this.shapeDOWN1glow = new ModelRenderer(this, 20, 0);
      this.shapeDOWN1glow.setRotationPoint(0.0F, 6.0F, 5.0F);
      this.shapeDOWN1glow.addBox(-1.5F, -4.0F, -1.5F, 3, 4, 3, 0.05F);
      this.setRotateAngle(this.shapeDOWN1glow, -0.18203785F, 0.0F, (float) Math.PI);
      this.shapeUP1 = new ModelRenderer(this, 12, 7);
      this.shapeUP1.setRotationPoint(0.0F, 1.0F, 5.0F);
      this.shapeUP1.addBox(-1.5F, -6.0F, -1.5F, 3, 6, 3, 0.05F);
      this.setRotateAngle(this.shapeUP1, -0.18203785F, 0.0F, 0.0F);
      this.shapeDOWN1.addChild(this.shapeDOWN2);
      this.shapeUP3.addChild(this.ropeUP);
      this.shapeDOWN2glow.addChild(this.shapeDOWN3glow);
      this.shapeUP2glow.addChild(this.shapeUP3glow);
      this.shapeDOWN2.addChild(this.shapeDOWN3);
      this.shapeUP2.addChild(this.shapeUP3);
      this.shapeDOWN3.addChild(this.ropeDOWN);
      this.shapeUP1glow.addChild(this.shapeUP2glow);
      this.shapeDOWN1glow.addChild(this.shapeDOWN2glow);
      this.shapeUP1.addChild(this.shapeUP2);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.shapeUP1.rotateAngleX = GetMOP.partial(-0.318697F, -0.18203785F, f);
      this.shapeUP2.rotateAngleX = this.shapeUP1.rotateAngleX;
      this.shapeUP3.rotateAngleX = this.shapeUP1.rotateAngleX;
      this.ropeUP.rotateAngleX = GetMOP.partial(1.43117F, 0.5462881F, f);
      this.ropeDOWN.rotateAngleX = this.ropeUP.rotateAngleX;
      this.shapeDOWN1.rotateAngleX = this.shapeUP1.rotateAngleX;
      this.shapeDOWN2.rotateAngleX = this.shapeUP2.rotateAngleX;
      this.shapeDOWN3.rotateAngleX = this.shapeUP3.rotateAngleX;
      this.shapeUP1glow.rotateAngleX = this.shapeUP1.rotateAngleX;
      this.shapeUP2glow.rotateAngleX = this.shapeUP2.rotateAngleX;
      this.shapeUP3glow.rotateAngleX = this.shapeUP3.rotateAngleX;
      this.shapeDOWN1glow.rotateAngleX = this.shapeUP1.rotateAngleX;
      this.shapeDOWN2glow.rotateAngleX = this.shapeUP2.rotateAngleX;
      this.shapeDOWN3glow.rotateAngleX = this.shapeUP3.rotateAngleX;
      boolean ench = f1 == 1.0F;
      this.shapeMAINglow.isHidden = ench;
      this.shapeUP1glow.isHidden = ench;
      this.shapeUP2glow.isHidden = ench;
      this.shapeUP3glow.isHidden = ench;
      this.shapeDOWN1glow.isHidden = ench;
      this.shapeDOWN2glow.isHidden = ench;
      this.shapeDOWN3glow.isHidden = ench;
      boolean hideNoglow = f1 == 2.0F;
      this.shapeMAIN.isHidden = hideNoglow;
      this.shapeUP1.isHidden = hideNoglow;
      this.shapeUP2.isHidden = hideNoglow;
      this.shapeUP3.isHidden = hideNoglow;
      this.shapeDOWN1.isHidden = hideNoglow;
      this.shapeDOWN2.isHidden = hideNoglow;
      this.shapeDOWN3.isHidden = hideNoglow;
      this.ropeUP.isHidden = hideNoglow;
      this.ropeDOWN.isHidden = hideNoglow;
      GlStateManager.disableCull();
      this.shapeMAIN.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeMAINglow.offsetX, this.shapeMAINglow.offsetY, this.shapeMAINglow.offsetZ);
      GlStateManager.translate(this.shapeMAINglow.rotationPointX * f5, this.shapeMAINglow.rotationPointY * f5, this.shapeMAINglow.rotationPointZ * f5);
      GlStateManager.scale(1.02, 1.02, 1.02);
      GlStateManager.translate(-this.shapeMAINglow.offsetX, -this.shapeMAINglow.offsetY, -this.shapeMAINglow.offsetZ);
      GlStateManager.translate(-this.shapeMAINglow.rotationPointX * f5, -this.shapeMAINglow.rotationPointY * f5, -this.shapeMAINglow.rotationPointZ * f5);
      this.shapeMAINglow.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeDOWN1.offsetX, this.shapeDOWN1.offsetY, this.shapeDOWN1.offsetZ);
      GlStateManager.translate(this.shapeDOWN1.rotationPointX * f5, this.shapeDOWN1.rotationPointY * f5, this.shapeDOWN1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapeDOWN1.offsetX, -this.shapeDOWN1.offsetY, -this.shapeDOWN1.offsetZ);
      GlStateManager.translate(-this.shapeDOWN1.rotationPointX * f5, -this.shapeDOWN1.rotationPointY * f5, -this.shapeDOWN1.rotationPointZ * f5);
      this.shapeDOWN1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeUP1glow.offsetX, this.shapeUP1glow.offsetY, this.shapeUP1glow.offsetZ);
      GlStateManager.translate(this.shapeUP1glow.rotationPointX * f5, this.shapeUP1glow.rotationPointY * f5, this.shapeUP1glow.rotationPointZ * f5);
      GlStateManager.scale(0.81, 0.81, 0.81);
      GlStateManager.translate(-this.shapeUP1glow.offsetX, -this.shapeUP1glow.offsetY, -this.shapeUP1glow.offsetZ);
      GlStateManager.translate(-this.shapeUP1glow.rotationPointX * f5, -this.shapeUP1glow.rotationPointY * f5, -this.shapeUP1glow.rotationPointZ * f5);
      this.shapeUP1glow.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeDOWN1glow.offsetX, this.shapeDOWN1glow.offsetY, this.shapeDOWN1glow.offsetZ);
      GlStateManager.translate(this.shapeDOWN1glow.rotationPointX * f5, this.shapeDOWN1glow.rotationPointY * f5, this.shapeDOWN1glow.rotationPointZ * f5);
      GlStateManager.scale(0.81, 0.81, 0.81);
      GlStateManager.translate(-this.shapeDOWN1glow.offsetX, -this.shapeDOWN1glow.offsetY, -this.shapeDOWN1glow.offsetZ);
      GlStateManager.translate(-this.shapeDOWN1glow.rotationPointX * f5, -this.shapeDOWN1glow.rotationPointY * f5, -this.shapeDOWN1glow.rotationPointZ * f5);
      this.shapeDOWN1glow.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeUP1.offsetX, this.shapeUP1.offsetY, this.shapeUP1.offsetZ);
      GlStateManager.translate(this.shapeUP1.rotationPointX * f5, this.shapeUP1.rotationPointY * f5, this.shapeUP1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapeUP1.offsetX, -this.shapeUP1.offsetY, -this.shapeUP1.offsetZ);
      GlStateManager.translate(-this.shapeUP1.rotationPointX * f5, -this.shapeUP1.rotationPointY * f5, -this.shapeUP1.rotationPointZ * f5);
      this.shapeUP1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.enableCull();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
