//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.AnimationTimer;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class CoralArmorModel extends ModelBiped {
   public ModelRenderer chest;
   public ModelRenderer leftarm;
   public ModelRenderer rightarm;
   public ModelRenderer helm;
   public ModelRenderer leftleg;
   public ModelRenderer rightleg;
   public ModelRenderer leftboot;
   public ModelRenderer rightboot;
   public ModelRenderer hood1;
   public ModelRenderer hood2;
   public ModelRenderer hood3;
   public ModelRenderer hood4;
   public ModelRenderer chestf;
   public ModelRenderer ane;
   public ModelRenderer ane_1;
   public ModelRenderer ane_2;
   public ModelRenderer ane_3;
   public ModelRenderer ane_4;
   public ModelRenderer ane_5;
   public ModelRenderer ane_6;
   public ModelRenderer ane_7;
   public ModelRenderer ane_8;
   public ModelRenderer ane_9;
   public ModelRenderer ane_10;
   public ModelRenderer ane_11;
   public ModelRenderer ane_12;
   public ModelRenderer ane1;
   public ModelRenderer ane2;
   public ModelRenderer ane3;
   public ModelRenderer ane4;
   public ModelRenderer legf;
   public ModelRenderer legf_1;
   public ModelRenderer leftbootf;
   public ModelRenderer rightbootf;

   public CoralArmorModel() {
      this.textureWidth = 64;
      this.textureHeight = 64;
      this.ane3 = new ModelRenderer(this, 52, -6);
      this.ane3.setRotationPoint(0.0F, -8.0F, 2.0F);
      this.ane3.addBox(0.0F, -8.0F, 0.0F, 0, 10, 6, 0.0F);
      this.setRotateAngle(this.ane3, -0.4553564F, -0.045553092F, 0.0F);
      this.rightarm = new ModelRenderer(this, 40, 11);
      this.rightarm.mirror = true;
      this.rightarm.setRotationPoint(-5.0F, 2.0F, 0.0F);
      this.rightarm.addBox(-3.0F, -2.0F, -2.0F, 4, 9, 4, 0.4F);
      this.ane_5 = new ModelRenderer(this, 30, 51);
      this.ane_5.setRotationPoint(-2.0F, -8.0F, 0.0F);
      this.ane_5.addBox(-5.0F, -4.0F, 0.0F, 10, 4, 0, 0.0F);
      this.setRotateAngle(this.ane_5, 0.0F, 0.59184116F, -0.13665928F);
      this.ane_8 = new ModelRenderer(this, 30, 59);
      this.ane_8.mirror = true;
      this.ane_8.setRotationPoint(-2.0F, -8.0F, 0.0F);
      this.ane_8.addBox(-7.0F, -4.0F, 0.0F, 17, 5, 0, 0.0F);
      this.setRotateAngle(this.ane_8, -0.22759093F, 2.5953045F, -0.4098033F);
      this.leftleg = new ModelRenderer(this, 0, 16);
      this.leftleg.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.ane_7 = new ModelRenderer(this, 30, 51);
      this.ane_7.setRotationPoint(-2.0F, -8.0F, 0.0F);
      this.ane_7.addBox(-5.0F, -4.0F, 0.0F, 10, 4, 0, 0.0F);
      this.setRotateAngle(this.ane_7, 0.0F, 1.6845918F, 0.0F);
      this.ane_6 = new ModelRenderer(this, 30, 51);
      this.ane_6.setRotationPoint(-2.0F, -8.0F, 0.0F);
      this.ane_6.addBox(-5.0F, -4.0F, 0.0F, 10, 4, 0, 0.0F);
      this.setRotateAngle(this.ane_6, 0.0F, 1.1838568F, -0.045553092F);
      this.leftbootf = new ModelRenderer(this, 2, 60);
      this.leftbootf.setRotationPoint(1.9F, 10.0F, 1.5F);
      this.leftbootf.addBox(-2.0F, 0.0F, -1.0F, 4, 0, 4, 0.0F);
      this.setRotateAngle(this.leftbootf, -0.7285004F, 0.0F, 0.0F);
      this.ane1 = new ModelRenderer(this, 52, -6);
      this.ane1.setRotationPoint(2.0F, -8.0F, 2.0F);
      this.ane1.addBox(0.0F, -8.0F, 0.0F, 0, 10, 6, 0.0F);
      this.setRotateAngle(this.ane1, -0.18203785F, 0.27314404F, 0.18203785F);
      this.leftarm = new ModelRenderer(this, 40, 11);
      this.leftarm.setRotationPoint(5.0F, 2.0F, 0.0F);
      this.leftarm.addBox(-1.0F, -2.0F, -2.0F, 4, 9, 4, 0.4F);
      this.chestf = new ModelRenderer(this, 20, 49);
      this.chestf.setRotationPoint(0.2F, 0.4F, 2.5F);
      this.chestf.addBox(0.0F, 0.0F, 0.0F, 0, 10, 5, 0.0F);
      this.ane_4 = new ModelRenderer(this, 30, 55);
      this.ane_4.setRotationPoint(-2.0F, -8.0F, 0.0F);
      this.ane_4.addBox(-6.0F, -4.0F, 0.0F, 12, 4, 0, 0.0F);
      this.setRotateAngle(this.ane_4, 0.0F, 0.0F, -0.22759093F);
      this.legf = new ModelRenderer(this, 14, 53);
      this.legf.setRotationPoint(2.2F, 0.4F, 2.5F);
      this.legf.addBox(0.0F, 0.0F, -0.5F, 0, 8, 3, 0.0F);
      this.setRotateAngle(this.legf, 0.0F, 0.4553564F, 0.0F);
      this.ane_10 = new ModelRenderer(this, 24, 0);
      this.ane_10.setRotationPoint(4.0F, -8.0F, 1.0F);
      this.ane_10.addBox(-2.0F, -5.0F, 0.0F, 5, 5, 0, 0.0F);
      this.setRotateAngle(this.ane_10, -0.045553092F, -0.13665928F, 0.31869712F);
      this.ane_11 = new ModelRenderer(this, 24, 0);
      this.ane_11.setRotationPoint(4.0F, -5.0F, -2.0F);
      this.ane_11.addBox(-2.0F, -5.0F, 0.0F, 5, 5, 0, 0.0F);
      this.setRotateAngle(this.ane_11, -0.045553092F, 0.5462881F, 0.31869712F);
      this.chest = new ModelRenderer(this, 16, 16);
      this.chest.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.chest.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.5F);
      this.rightboot = new ModelRenderer(this, 40, 24);
      this.rightboot.mirror = true;
      this.rightboot.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightboot.addBox(-2.0F, 8.0F, -2.0F, 4, 4, 4, 0.4F);
      this.hood2 = new ModelRenderer(this, 18, 32);
      this.hood2.setRotationPoint(5.0F, 11.0F, 0.2F);
      this.hood2.addBox(-4.0F, 0.0F, 0.0F, 7, 14, 0, 0.0F);
      this.setRotateAngle(this.hood2, 0.0F, -1.1383038F, -0.31869712F);
      this.legf_1 = new ModelRenderer(this, 14, 53);
      this.legf_1.setRotationPoint(-2.2F, 0.4F, 2.5F);
      this.legf_1.addBox(0.0F, 0.0F, -0.5F, 0, 8, 3, 0.0F);
      this.setRotateAngle(this.legf_1, 0.0F, -0.4553564F, 0.0F);
      this.ane_3 = new ModelRenderer(this, 0, 0);
      this.ane_3.setRotationPoint(-3.0F, 4.0F, 1.4F);
      this.ane_3.addBox(-3.0F, -5.0F, 0.0F, 4, 5, 0, 0.0F);
      this.setRotateAngle(this.ane_3, 0.0F, -0.13665928F, -0.27314404F);
      this.ane4 = new ModelRenderer(this, 52, -6);
      this.ane4.setRotationPoint(-1.0F, -8.0F, 2.0F);
      this.ane4.addBox(0.0F, -8.0F, 0.0F, 0, 10, 6, 0.0F);
      this.setRotateAngle(this.ane4, -0.59184116F, -0.22759093F, -0.045553092F);
      this.helm = new ModelRenderer(this, 0, 0);
      this.helm.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8, 0.2F);
      this.ane_1 = new ModelRenderer(this, 24, 0);
      this.ane_1.setRotationPoint(3.0F, -1.0F, 1.0F);
      this.ane_1.addBox(-2.0F, -5.0F, 0.0F, 5, 5, 0, 0.0F);
      this.setRotateAngle(this.ane_1, -0.045553092F, 0.7285004F, 0.31869712F);
      this.rightleg = new ModelRenderer(this, 0, 16);
      this.rightleg.mirror = true;
      this.rightleg.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.ane_2 = new ModelRenderer(this, 0, 0);
      this.ane_2.setRotationPoint(3.0F, 4.0F, 0.7F);
      this.ane_2.addBox(-1.0F, -5.0F, 0.0F, 4, 5, 0, 0.0F);
      this.setRotateAngle(this.ane_2, -0.045553092F, 0.22759093F, 0.31869712F);
      this.hood3 = new ModelRenderer(this, 32, 32);
      this.hood3.setRotationPoint(-2.8F, 12.0F, -2.7F);
      this.hood3.addBox(-2.0F, 0.0F, 0.0F, 6, 9, 0, 0.0F);
      this.setRotateAngle(this.hood3, -0.18203785F, 0.045553092F, 0.091106184F);
      this.hood1 = new ModelRenderer(this, 0, 32);
      this.hood1.setRotationPoint(0.5F, 9.0F, -3.3F);
      this.hood1.addBox(-4.3F, 0.0F, 0.0F, 9, 16, 0, 0.0F);
      this.setRotateAngle(this.hood1, -0.18203785F, -0.22759093F, -0.31869712F);
      this.rightbootf = new ModelRenderer(this, 2, 60);
      this.rightbootf.mirror = true;
      this.rightbootf.setRotationPoint(-1.9F, 10.0F, 1.5F);
      this.rightbootf.addBox(-2.0F, 0.0F, -1.0F, 4, 0, 4, 0.0F);
      this.setRotateAngle(this.rightbootf, -0.7285004F, 0.0F, 0.0F);
      this.hood4 = new ModelRenderer(this, 44, 25);
      this.hood4.setRotationPoint(-4.2F, 10.5F, 0.2F);
      this.hood4.addBox(0.0F, 0.0F, -4.0F, 0, 14, 7, 0.0F);
      this.setRotateAngle(this.hood4, 0.27314404F, -0.045553092F, 0.27314404F);
      this.leftboot = new ModelRenderer(this, 40, 24);
      this.leftboot.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftboot.addBox(-2.0F, 8.0F, -2.0F, 4, 4, 4, 0.4F);
      this.ane2 = new ModelRenderer(this, 52, -6);
      this.ane2.setRotationPoint(1.0F, -8.0F, 2.0F);
      this.ane2.addBox(0.0F, -8.0F, 0.0F, 0, 10, 6, 0.0F);
      this.setRotateAngle(this.ane2, -0.3642502F, 0.091106184F, 0.045553092F);
      this.ane_9 = new ModelRenderer(this, 32, 3);
      this.ane_9.setRotationPoint(-2.0F, -8.0F, 0.0F);
      this.ane_9.addBox(-2.5F, -1.6F, -2.5F, 5, 2, 5, 0.0F);
      this.setRotateAngle(this.ane_9, 0.0F, 0.0F, -0.13665928F);
      this.ane_12 = new ModelRenderer(this, 24, 0);
      this.ane_12.setRotationPoint(3.0F, -6.0F, 4.0F);
      this.ane_12.addBox(-2.0F, -5.0F, 0.0F, 5, 5, 0, 0.0F);
      this.setRotateAngle(this.ane_12, -0.045553092F, -0.68294734F, 0.31869712F);
      this.ane = new ModelRenderer(this, 54, 53);
      this.ane.setRotationPoint(3.0F, -2.0F, 1.0F);
      this.ane.addBox(-2.0F, -6.0F, 0.0F, 5, 6, 0, 0.0F);
      this.setRotateAngle(this.ane, -0.045553092F, -0.13665928F, 0.22759093F);
      this.helm.addChild(this.ane3);
      this.helm.addChild(this.ane_5);
      this.helm.addChild(this.ane_8);
      this.helm.addChild(this.ane_7);
      this.helm.addChild(this.ane_6);
      this.leftboot.addChild(this.leftbootf);
      this.helm.addChild(this.ane1);
      this.chest.addChild(this.chestf);
      this.helm.addChild(this.ane_4);
      this.leftleg.addChild(this.legf);
      this.helm.addChild(this.ane_10);
      this.helm.addChild(this.ane_11);
      this.chest.addChild(this.hood2);
      this.rightleg.addChild(this.legf_1);
      this.rightarm.addChild(this.ane_3);
      this.helm.addChild(this.ane4);
      this.leftarm.addChild(this.ane_1);
      this.leftarm.addChild(this.ane_2);
      this.chest.addChild(this.hood3);
      this.chest.addChild(this.hood1);
      this.rightboot.addChild(this.rightbootf);
      this.chest.addChild(this.hood4);
      this.helm.addChild(this.ane2);
      this.helm.addChild(this.ane_9);
      this.helm.addChild(this.ane_12);
      this.leftarm.addChild(this.ane);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      if (entity.isSneaking()) {
         GlStateManager.translate(0.0F, 0.2F, 0.0F);
      }

      float w = MathHelper.sin(AnimationTimer.tick / 70.0F) * 0.06F;
      float al = this.leftleg.rotateAngleX > 0.0F ? this.leftleg.rotateAngleX / 3.0F : this.leftleg.rotateAngleX;
      this.hood1.rotateAngleX = -0.18203785F + al / 2.0F - w;
      this.hood3.rotateAngleX = -0.18203785F + this.rightleg.rotateAngleX;
      this.hood2.rotateAngleY = -1.1383038F + this.leftleg.rotateAngleX / 5.0F + w;
      this.hood4.rotateAngleX = 0.27314404F + this.rightleg.rotateAngleX / 4.0F;
      this.hood4.rotateAngleZ = 0.27314404F + w;
      this.hood1.rotateAngleZ = -0.31869712F + w;
      this.hood3.rotateAngleZ = 0.091106184F - w;
      this.helm.render(f5);
      this.rightarm.render(f5);
      this.leftarm.render(f5);
      this.leftleg.render(f5);
      this.chest.render(f5);
      this.rightboot.render(f5);
      this.rightleg.render(f5);
      this.leftboot.render(f5);
      GlStateManager.popMatrix();
   }

   public void setModelAttributes(ModelBase model) {
      super.setModelAttributes(model);
      if (model instanceof ModelBiped) {
         ModelBiped modelbiped = (ModelBiped)model;
         this.rightarm.rotateAngleX = modelbiped.bipedRightArm.rotateAngleX;
         this.rightarm.rotateAngleY = modelbiped.bipedRightArm.rotateAngleY;
         this.rightarm.rotateAngleZ = modelbiped.bipedRightArm.rotateAngleZ;
         this.leftarm.rotateAngleX = modelbiped.bipedLeftArm.rotateAngleX;
         this.leftarm.rotateAngleY = modelbiped.bipedLeftArm.rotateAngleY;
         this.leftarm.rotateAngleZ = modelbiped.bipedLeftArm.rotateAngleZ;
         this.helm.rotateAngleX = modelbiped.bipedHead.rotateAngleX;
         this.helm.rotateAngleY = modelbiped.bipedHead.rotateAngleY;
         this.helm.rotateAngleZ = modelbiped.bipedHead.rotateAngleZ;
         this.chest.rotateAngleX = modelbiped.bipedBody.rotateAngleX;
         this.chest.rotateAngleY = modelbiped.bipedBody.rotateAngleY;
         this.chest.rotateAngleZ = modelbiped.bipedBody.rotateAngleZ;
         this.rightleg.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightleg.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightleg.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftleg.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftleg.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftleg.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightboot.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightboot.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightboot.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftboot.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftboot.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftboot.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightarm.rotationPointX = modelbiped.bipedRightArm.rotationPointX;
         this.rightarm.rotationPointY = modelbiped.bipedRightArm.rotationPointY;
         this.rightarm.rotationPointZ = modelbiped.bipedRightArm.rotationPointZ;
         this.leftarm.rotationPointX = modelbiped.bipedLeftArm.rotationPointX;
         this.leftarm.rotationPointY = modelbiped.bipedLeftArm.rotationPointY;
         this.leftarm.rotationPointZ = modelbiped.bipedLeftArm.rotationPointZ;
         this.helm.rotationPointX = modelbiped.bipedHead.rotationPointX;
         this.helm.rotationPointY = modelbiped.bipedHead.rotationPointY;
         this.helm.rotationPointZ = modelbiped.bipedHead.rotationPointZ;
         this.chest.rotationPointX = modelbiped.bipedBody.rotationPointX;
         this.chest.rotationPointY = modelbiped.bipedBody.rotationPointY;
         this.chest.rotationPointZ = modelbiped.bipedBody.rotationPointZ;
         this.rightleg.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightleg.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightleg.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftleg.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftleg.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftleg.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
         this.rightboot.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightboot.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightboot.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftboot.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftboot.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftboot.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
      }
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
