//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class CrystalStarModel extends ModelBase {
   public ModelRenderer staf;
   public ModelRenderer cryst;
   public ModelRenderer cryst_1;
   public ModelRenderer cryst_2;
   public ModelRenderer cryst_3;
   public ModelRenderer cryst_4;
   public ModelRenderer cryst_5;
   public ModelRenderer cryst_6;
   public ModelRenderer cryst_7;
   public ModelRenderer cryst_8;
   public ModelRenderer cryst_9;
   public ModelRenderer cryst_10;
   public ModelRenderer cryst_11;
   public ModelRenderer cryst_12;
   public ModelRenderer cryst_13;
   public ModelRenderer cryst_14;
   public ModelRenderer cryst_15;
   public ModelRenderer cryst_16;
   public ModelRenderer cryst_17;
   public ModelRenderer cryst_18;
   public ModelRenderer staf2;

   public CrystalStarModel() {
      this.textureWidth = 8;
      this.textureHeight = 32;
      this.cryst_17 = new ModelRenderer(this, 0, 0);
      this.cryst_17.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_17.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.cryst_17, -1.9123572F, (float) (Math.PI / 3), -0.22759093F);
      this.cryst_18 = new ModelRenderer(this, 0, 0);
      this.cryst_18.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_18.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_18, -1.9123572F, 2.5497515F, -0.68294734F);
      this.cryst_9 = new ModelRenderer(this, 0, 0);
      this.cryst_9.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_9.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_9, -2.7317894F, 2.2310543F, -0.4098033F);
      this.cryst_12 = new ModelRenderer(this, 0, 0);
      this.cryst_12.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_12.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.cryst_12, 2.8684487F, (float) (-Math.PI / 3), -0.22759093F);
      this.cryst_8 = new ModelRenderer(this, 0, 0);
      this.cryst_8.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_8.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_8, -2.048842F, 1.0016445F, -1.1383038F);
      this.cryst_6 = new ModelRenderer(this, 0, 0);
      this.cryst_6.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_6.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_6, -0.3642502F, -2.6862361F, -0.63739425F);
      this.cryst_7 = new ModelRenderer(this, 0, 0);
      this.cryst_7.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_7.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.cryst_7, -1.3203416F, 2.6406832F, -1.1383038F);
      this.cryst_13 = new ModelRenderer(this, 0, 0);
      this.cryst_13.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_13.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.cryst_13, -2.1399481F, 2.8684487F, 1.3658947F);
      this.cryst_14 = new ModelRenderer(this, 0, 0);
      this.cryst_14.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_14.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_14, 0.13665928F, 0.27314404F, -1.2747885F);
      this.cryst_2 = new ModelRenderer(this, 0, 0);
      this.cryst_2.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_2.addBox(-1.0F, 0.0F, -1.0F, 2, 6, 2, 0.0F);
      this.setRotateAngle(this.cryst_2, -0.7740535F, -1.8668041F, -1.2292354F);
      this.cryst_3 = new ModelRenderer(this, 0, 0);
      this.cryst_3.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_3.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_3, -0.7740535F, (float) (Math.PI / 3), 0.31869712F);
      this.cryst_15 = new ModelRenderer(this, 0, 0);
      this.cryst_15.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_15.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_15, 1.821251F, 0.63739425F, -1.1383038F);
      this.cryst = new ModelRenderer(this, 0, 0);
      this.cryst.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.cryst, -2.276433F, 0.3642502F, 0.0F);
      this.cryst_11 = new ModelRenderer(this, 0, 0);
      this.cryst_11.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_11.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_11, -0.91053826F, 0.31869712F, -2.048842F);
      this.cryst_1 = new ModelRenderer(this, 0, 0);
      this.cryst_1.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_1.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_1, -0.7740535F, (float) (-Math.PI / 3), -0.22759093F);
      this.cryst_16 = new ModelRenderer(this, 0, 0);
      this.cryst_16.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_16.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_16, -1.6390387F, 2.2310543F, -0.7740535F);
      this.cryst_5 = new ModelRenderer(this, 0, 0);
      this.cryst_5.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_5.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_5, -2.048842F, -2.6862361F, -1.1383038F);
      this.cryst_10 = new ModelRenderer(this, 0, 0);
      this.cryst_10.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_10.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.cryst_10, (float) (-Math.PI / 3), 0.18203785F, -1.1383038F);
      this.staf = new ModelRenderer(this, 0, 8);
      this.staf.setRotationPoint(0.0F, -3.0F, 5.0F);
      this.staf.addBox(-1.0F, 0.0F, -1.0F, 2, 10, 2, 0.0F);
      this.staf2 = new ModelRenderer(this, 0, 20);
      this.staf2.setRotationPoint(0.0F, 6.0F, 5.0F);
      this.staf2.addBox(-1.0F, 0.0F, -1.0F, 2, 10, 2, 0.0F);
      this.cryst_4 = new ModelRenderer(this, 0, 0);
      this.cryst_4.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.cryst_4.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.cryst_4, -2.5497515F, -0.4553564F, -0.22759093F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf.offsetX, this.staf.offsetY, this.staf.offsetZ);
      GlStateManager.translate(this.staf.rotationPointX * f5, this.staf.rotationPointY * f5, this.staf.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.9, 0.7);
      GlStateManager.translate(-this.staf.offsetX, -this.staf.offsetY, -this.staf.offsetZ);
      GlStateManager.translate(-this.staf.rotationPointX * f5, -this.staf.rotationPointY * f5, -this.staf.rotationPointZ * f5);
      this.staf.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf2.offsetX, this.staf2.offsetY, this.staf2.offsetZ);
      GlStateManager.translate(this.staf2.rotationPointX * f5, this.staf2.rotationPointY * f5, this.staf2.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.staf2.offsetX, -this.staf2.offsetY, -this.staf2.offsetZ);
      GlStateManager.translate(-this.staf2.rotationPointX * f5, -this.staf2.rotationPointY * f5, -this.staf2.rotationPointZ * f5);
      this.staf2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 170.0F, 170.0F);
      GlStateManager.translate(this.cryst_17.offsetX, this.cryst_17.offsetY, this.cryst_17.offsetZ);
      GlStateManager.translate(this.cryst_17.rotationPointX * f5, this.cryst_17.rotationPointY * f5, this.cryst_17.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.5, 0.7);
      GlStateManager.translate(-this.cryst_17.offsetX, -this.cryst_17.offsetY, -this.cryst_17.offsetZ);
      GlStateManager.translate(-this.cryst_17.rotationPointX * f5, -this.cryst_17.rotationPointY * f5, -this.cryst_17.rotationPointZ * f5);
      this.cryst_17.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_18.offsetX, this.cryst_18.offsetY, this.cryst_18.offsetZ);
      GlStateManager.translate(this.cryst_18.rotationPointX * f5, this.cryst_18.rotationPointY * f5, this.cryst_18.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.4, 0.5);
      GlStateManager.translate(-this.cryst_18.offsetX, -this.cryst_18.offsetY, -this.cryst_18.offsetZ);
      GlStateManager.translate(-this.cryst_18.rotationPointX * f5, -this.cryst_18.rotationPointY * f5, -this.cryst_18.rotationPointZ * f5);
      this.cryst_18.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_9.offsetX, this.cryst_9.offsetY, this.cryst_9.offsetZ);
      GlStateManager.translate(this.cryst_9.rotationPointX * f5, this.cryst_9.rotationPointY * f5, this.cryst_9.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.5, 0.8);
      GlStateManager.translate(-this.cryst_9.offsetX, -this.cryst_9.offsetY, -this.cryst_9.offsetZ);
      GlStateManager.translate(-this.cryst_9.rotationPointX * f5, -this.cryst_9.rotationPointY * f5, -this.cryst_9.rotationPointZ * f5);
      this.cryst_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_12.offsetX, this.cryst_12.offsetY, this.cryst_12.offsetZ);
      GlStateManager.translate(this.cryst_12.rotationPointX * f5, this.cryst_12.rotationPointY * f5, this.cryst_12.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.8, 0.5);
      GlStateManager.translate(-this.cryst_12.offsetX, -this.cryst_12.offsetY, -this.cryst_12.offsetZ);
      GlStateManager.translate(-this.cryst_12.rotationPointX * f5, -this.cryst_12.rotationPointY * f5, -this.cryst_12.rotationPointZ * f5);
      this.cryst_12.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_8.offsetX, this.cryst_8.offsetY, this.cryst_8.offsetZ);
      GlStateManager.translate(this.cryst_8.rotationPointX * f5, this.cryst_8.rotationPointY * f5, this.cryst_8.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 1.0);
      GlStateManager.translate(-this.cryst_8.offsetX, -this.cryst_8.offsetY, -this.cryst_8.offsetZ);
      GlStateManager.translate(-this.cryst_8.rotationPointX * f5, -this.cryst_8.rotationPointY * f5, -this.cryst_8.rotationPointZ * f5);
      this.cryst_8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_6.offsetX, this.cryst_6.offsetY, this.cryst_6.offsetZ);
      GlStateManager.translate(this.cryst_6.rotationPointX * f5, this.cryst_6.rotationPointY * f5, this.cryst_6.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 1.0);
      GlStateManager.translate(-this.cryst_6.offsetX, -this.cryst_6.offsetY, -this.cryst_6.offsetZ);
      GlStateManager.translate(-this.cryst_6.rotationPointX * f5, -this.cryst_6.rotationPointY * f5, -this.cryst_6.rotationPointZ * f5);
      this.cryst_6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_7.offsetX, this.cryst_7.offsetY, this.cryst_7.offsetZ);
      GlStateManager.translate(this.cryst_7.rotationPointX * f5, this.cryst_7.rotationPointY * f5, this.cryst_7.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.8, 0.8);
      GlStateManager.translate(-this.cryst_7.offsetX, -this.cryst_7.offsetY, -this.cryst_7.offsetZ);
      GlStateManager.translate(-this.cryst_7.rotationPointX * f5, -this.cryst_7.rotationPointY * f5, -this.cryst_7.rotationPointZ * f5);
      this.cryst_7.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_13.offsetX, this.cryst_13.offsetY, this.cryst_13.offsetZ);
      GlStateManager.translate(this.cryst_13.rotationPointX * f5, this.cryst_13.rotationPointY * f5, this.cryst_13.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.6, 0.9);
      GlStateManager.translate(-this.cryst_13.offsetX, -this.cryst_13.offsetY, -this.cryst_13.offsetZ);
      GlStateManager.translate(-this.cryst_13.rotationPointX * f5, -this.cryst_13.rotationPointY * f5, -this.cryst_13.rotationPointZ * f5);
      this.cryst_13.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_14.offsetX, this.cryst_14.offsetY, this.cryst_14.offsetZ);
      GlStateManager.translate(this.cryst_14.rotationPointX * f5, this.cryst_14.rotationPointY * f5, this.cryst_14.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.6);
      GlStateManager.translate(-this.cryst_14.offsetX, -this.cryst_14.offsetY, -this.cryst_14.offsetZ);
      GlStateManager.translate(-this.cryst_14.rotationPointX * f5, -this.cryst_14.rotationPointY * f5, -this.cryst_14.rotationPointZ * f5);
      this.cryst_14.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_2.offsetX, this.cryst_2.offsetY, this.cryst_2.offsetZ);
      GlStateManager.translate(this.cryst_2.rotationPointX * f5, this.cryst_2.rotationPointY * f5, this.cryst_2.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.8, 0.8);
      GlStateManager.translate(-this.cryst_2.offsetX, -this.cryst_2.offsetY, -this.cryst_2.offsetZ);
      GlStateManager.translate(-this.cryst_2.rotationPointX * f5, -this.cryst_2.rotationPointY * f5, -this.cryst_2.rotationPointZ * f5);
      this.cryst_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_3.offsetX, this.cryst_3.offsetY, this.cryst_3.offsetZ);
      GlStateManager.translate(this.cryst_3.rotationPointX * f5, this.cryst_3.rotationPointY * f5, this.cryst_3.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.3);
      GlStateManager.translate(-this.cryst_3.offsetX, -this.cryst_3.offsetY, -this.cryst_3.offsetZ);
      GlStateManager.translate(-this.cryst_3.rotationPointX * f5, -this.cryst_3.rotationPointY * f5, -this.cryst_3.rotationPointZ * f5);
      this.cryst_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_15.offsetX, this.cryst_15.offsetY, this.cryst_15.offsetZ);
      GlStateManager.translate(this.cryst_15.rotationPointX * f5, this.cryst_15.rotationPointY * f5, this.cryst_15.rotationPointZ * f5);
      GlStateManager.scale(0.5, 1.0, 0.5);
      GlStateManager.translate(-this.cryst_15.offsetX, -this.cryst_15.offsetY, -this.cryst_15.offsetZ);
      GlStateManager.translate(-this.cryst_15.rotationPointX * f5, -this.cryst_15.rotationPointY * f5, -this.cryst_15.rotationPointZ * f5);
      this.cryst_15.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst.offsetX, this.cryst.offsetY, this.cryst.offsetZ);
      GlStateManager.translate(this.cryst.rotationPointX * f5, this.cryst.rotationPointY * f5, this.cryst.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.5, 1.0);
      GlStateManager.translate(-this.cryst.offsetX, -this.cryst.offsetY, -this.cryst.offsetZ);
      GlStateManager.translate(-this.cryst.rotationPointX * f5, -this.cryst.rotationPointY * f5, -this.cryst.rotationPointZ * f5);
      this.cryst.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_11.offsetX, this.cryst_11.offsetY, this.cryst_11.offsetZ);
      GlStateManager.translate(this.cryst_11.rotationPointX * f5, this.cryst_11.rotationPointY * f5, this.cryst_11.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.5, 0.6);
      GlStateManager.translate(-this.cryst_11.offsetX, -this.cryst_11.offsetY, -this.cryst_11.offsetZ);
      GlStateManager.translate(-this.cryst_11.rotationPointX * f5, -this.cryst_11.rotationPointY * f5, -this.cryst_11.rotationPointZ * f5);
      this.cryst_11.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_1.offsetX, this.cryst_1.offsetY, this.cryst_1.offsetZ);
      GlStateManager.translate(this.cryst_1.rotationPointX * f5, this.cryst_1.rotationPointY * f5, this.cryst_1.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.8, 0.8);
      GlStateManager.translate(-this.cryst_1.offsetX, -this.cryst_1.offsetY, -this.cryst_1.offsetZ);
      GlStateManager.translate(-this.cryst_1.rotationPointX * f5, -this.cryst_1.rotationPointY * f5, -this.cryst_1.rotationPointZ * f5);
      this.cryst_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_16.offsetX, this.cryst_16.offsetY, this.cryst_16.offsetZ);
      GlStateManager.translate(this.cryst_16.rotationPointX * f5, this.cryst_16.rotationPointY * f5, this.cryst_16.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.5);
      GlStateManager.translate(-this.cryst_16.offsetX, -this.cryst_16.offsetY, -this.cryst_16.offsetZ);
      GlStateManager.translate(-this.cryst_16.rotationPointX * f5, -this.cryst_16.rotationPointY * f5, -this.cryst_16.rotationPointZ * f5);
      this.cryst_16.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_5.offsetX, this.cryst_5.offsetY, this.cryst_5.offsetZ);
      GlStateManager.translate(this.cryst_5.rotationPointX * f5, this.cryst_5.rotationPointY * f5, this.cryst_5.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.8);
      GlStateManager.translate(-this.cryst_5.offsetX, -this.cryst_5.offsetY, -this.cryst_5.offsetZ);
      GlStateManager.translate(-this.cryst_5.rotationPointX * f5, -this.cryst_5.rotationPointY * f5, -this.cryst_5.rotationPointZ * f5);
      this.cryst_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_10.offsetX, this.cryst_10.offsetY, this.cryst_10.offsetZ);
      GlStateManager.translate(this.cryst_10.rotationPointX * f5, this.cryst_10.rotationPointY * f5, this.cryst_10.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.9);
      GlStateManager.translate(-this.cryst_10.offsetX, -this.cryst_10.offsetY, -this.cryst_10.offsetZ);
      GlStateManager.translate(-this.cryst_10.rotationPointX * f5, -this.cryst_10.rotationPointY * f5, -this.cryst_10.rotationPointZ * f5);
      this.cryst_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.cryst_4.offsetX, this.cryst_4.offsetY, this.cryst_4.offsetZ);
      GlStateManager.translate(this.cryst_4.rotationPointX * f5, this.cryst_4.rotationPointY * f5, this.cryst_4.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.7, 0.8);
      GlStateManager.translate(-this.cryst_4.offsetX, -this.cryst_4.offsetY, -this.cryst_4.offsetZ);
      GlStateManager.translate(-this.cryst_4.rotationPointX * f5, -this.cryst_4.rotationPointY * f5, -this.cryst_4.rotationPointZ * f5);
      this.cryst_4.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
