package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.renders.ModelRendererGlow;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class CrystalMantleModel extends ModelBiped {
   public ModelRenderer chest;
   public ModelRenderer leftarm;
   public ModelRenderer rightarm;
   public ModelRenderer helm;
   public ModelRenderer leftleg;
   public ModelRenderer rightleg;
   public ModelRenderer rightboot;
   public ModelRenderer leftboot;
   public ModelRenderer crystCh1;
   public ModelRenderer crystCh2;
   public ModelRenderer crystal;
   public ModelRenderer leftarmCr;
   public ModelRenderer rightarmCr;
   public ModelRenderer helm1;
   public ModelRenderer helm2;
   public ModelRenderer helm3;
   public ModelRenderer helm4;
   public ModelRenderer helm5;
   public ModelRenderer helm5_1;
   public ModelRenderer helm6;
   public ModelRenderer helm7;
   public ModelRenderer helmglow;
   public ModelRenderer mantleh1;
   public ModelRenderer mantleh2;
   public ModelRenderer mantleh3;
   public ModelRenderer mantleL1;
   public ModelRenderer mantleL2;
   public ModelRenderer mantleL2glow;
   public ModelRenderer bootCr2;
   public ModelRenderer bootCr1;

   public CrystalMantleModel() {
      this.textureWidth = 82;
      this.textureHeight = 64;
      this.leftleg = new ModelRenderer(this, 0, 18);
      this.leftleg.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.helm1 = new ModelRenderer(this, 0, 34);
      this.helm1.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helm1.addBox(-4.0F, -8.5F, -4.2F, 8, 8, 0, 0.0F);
      this.setRotateAngle(this.helm1, 0.091106184F, 0.0F, 0.0F);
      this.helm = new ModelRenderer(this, 0, 0);
      this.helm.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm.addBox(-4.0F, -8.0F, -4.0F, 8, 10, 8, 0.2F);
      this.helm6 = new ModelRenderer(this, 32, 34);
      this.helm6.mirror = true;
      this.helm6.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helm6.addBox(-4.0F, -8.5F, -4.2F, 8, 8, 0, 0.0F);
      this.setRotateAngle(this.helm6, 0.091106184F, (float) (Math.PI * 2.0 / 3.0), 0.0F);
      this.mantleh1 = new ModelRenderer(this, 16, 42);
      this.mantleh1.mirror = true;
      this.mantleh1.setRotationPoint(-4.0F, -8.5F, -4.2F);
      this.mantleh1.addBox(0.0F, 0.0F, 0.0F, 8, 22, 0, 0.0F);
      this.setRotateAngle(this.mantleh1, -0.18203785F, 0.0F, 0.0F);
      this.bootCr1 = new ModelRendererGlow(this, 40, 51, 200, false);
      this.bootCr1.setRotationPoint(0.0F, 12.0F, -2.3F);
      this.bootCr1.addBox(-2.0F, -3.0F, 0.0F, 4, 3, 0, 0.0F);
      this.setRotateAngle(this.bootCr1, 0.3642502F, 0.0F, 0.0F);
      this.helm5 = new ModelRenderer(this, 16, 34);
      this.helm5.mirror = true;
      this.helm5.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helm5.addBox(-4.0F, -8.5F, -4.2F, 8, 8, 0, 0.0F);
      this.setRotateAngle(this.helm5, 0.091106184F, (float) (Math.PI / 3), 0.0F);
      this.rightboot = new ModelRenderer(this, 57, 27);
      this.rightboot.mirror = true;
      this.rightboot.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightboot.addBox(-2.0F, 9.0F, -2.0F, 4, 3, 4, 0.3F);
      this.mantleL1 = new ModelRenderer(this, 56, 0);
      this.mantleL1.setRotationPoint(2.0F, -2.7F, -1.7F);
      this.mantleL1.addBox(-8.0F, 0.0F, -1.0F, 8, 13, 5, 0.0F);
      this.setRotateAngle(this.mantleL1, 0.045553092F, 0.0F, -0.13665928F);
      this.helm2 = new ModelRenderer(this, 16, 34);
      this.helm2.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helm2.addBox(-4.0F, -8.5F, -4.2F, 8, 8, 0, 0.0F);
      this.setRotateAngle(this.helm2, 0.091106184F, (float) (-Math.PI / 3), 0.0F);
      this.leftarm = new ModelRenderer(this, 40, 19);
      this.leftarm.setRotationPoint(5.0F, 2.0F, 0.0F);
      this.leftarm.addBox(-1.0F, -2.0F, -2.0F, 4, 10, 4, 0.4F);
      this.setRotateAngle(this.leftarm, 0.0F, 0.0F, -0.045553092F);
      this.helm4 = new ModelRenderer(this, 56, 18);
      this.helm4.setRotationPoint(0.0F, -8.0F, 0.6F);
      this.helm4.addBox(-5.5F, -7.5F, -5.0F, 11, 7, 0, 0.0F);
      this.setRotateAngle(this.helm4, 0.11920599F, 0.0F, 0.0F);
      this.helm5_1 = new ModelRenderer(this, 32, 34);
      this.helm5_1.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helm5_1.addBox(-4.0F, -8.5F, -4.2F, 8, 8, 0, 0.0F);
      this.setRotateAngle(this.helm5_1, 0.091106184F, (float) (-Math.PI * 2.0 / 3.0), 0.0F);
      this.rightleg = new ModelRenderer(this, 0, 18);
      this.rightleg.mirror = true;
      this.rightleg.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.rightarm = new ModelRenderer(this, 40, 19);
      this.rightarm.mirror = true;
      this.rightarm.setRotationPoint(-5.0F, 2.0F, 0.0F);
      this.rightarm.addBox(-3.0F, -2.0F, -2.0F, 4, 10, 4, 0.4F);
      this.setRotateAngle(this.rightarm, 0.0F, 0.0F, 0.045553092F);
      this.mantleL2glow = new ModelRendererGlow(this, 65, 34, 200, false);
      this.mantleL2glow.setRotationPoint(-2.0F, -2.7F, -2.3F);
      this.mantleL2glow.addBox(0.0F, 0.0F, -0.1F, 8, 13, 0, 0.0F);
      this.setRotateAngle(this.mantleL2glow, -0.13665928F, 0.0F, 0.13665928F);
      this.mantleh2 = new ModelRenderer(this, 16, 42);
      this.mantleh2.setRotationPoint(-4.0F, -8.5F, -4.2F);
      this.mantleh2.addBox(0.0F, 0.0F, 0.0F, 8, 22, 0, 0.0F);
      this.setRotateAngle(this.mantleh2, -0.18203785F, 0.0F, 0.0F);
      this.crystal = new ModelRendererGlow(this, 0, 42, 200, false);
      this.crystal.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.crystal.addBox(-1.0F, 5.0F, -2.6F, 2, 2, 0, 0.0F);
      this.chest = new ModelRenderer(this, 16, 18);
      this.chest.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.chest.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.5F);
      this.mantleL2 = new ModelRenderer(this, 32, 0);
      this.mantleL2.setRotationPoint(-2.0F, -2.7F, -2.3F);
      this.mantleL2.addBox(0.0F, 0.0F, 0.0F, 8, 13, 4, 0.0F);
      this.setRotateAngle(this.mantleL2, -0.13665928F, 0.0F, 0.13665928F);
      this.crystCh2 = new ModelRenderer(this, 48, 46);
      this.crystCh2.mirror = true;
      this.crystCh2.setRotationPoint(-0.8F, 5.0F, -1.5F);
      this.crystCh2.addBox(-2.5F, 0.0F, -1.5F, 4, 14, 4, 0.0F);
      this.setRotateAngle(this.crystCh2, 0.0F, 0.5009095F, 2.1855013F);
      this.leftboot = new ModelRenderer(this, 57, 27);
      this.leftboot.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftboot.addBox(-2.0F, 9.0F, -2.0F, 4, 3, 4, 0.3F);
      this.rightarmCr = new ModelRenderer(this, 52, 35);
      this.rightarmCr.mirror = true;
      this.rightarmCr.setRotationPoint(0.5F, -1.0F, 0.0F);
      this.rightarmCr.addBox(-1.5F, 0.0F, -1.5F, 3, 8, 3, 0.0F);
      this.setRotateAngle(this.rightarmCr, 0.0F, 0.63739425F, 1.7301449F);
      this.helm7 = new ModelRenderer(this, 32, 42);
      this.helm7.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helm7.addBox(-4.0F, -8.5F, -4.2F, 8, 8, 0, 0.0F);
      this.setRotateAngle(this.helm7, 0.091106184F, (float) -Math.PI, 0.0F);
      this.helmglow = new ModelRendererGlow(this, 0, 44, 200, false);
      this.helmglow.setRotationPoint(0.0F, -8.0F, 0.4F);
      this.helmglow.addBox(-0.5F, -7.0F, -5.1F, 1, 1, 0, 0.0F);
      this.setRotateAngle(this.helmglow, 0.13665928F, 0.0F, 0.0F);
      this.bootCr2 = new ModelRendererGlow(this, 40, 54, 200, false);
      this.bootCr2.setRotationPoint(0.0F, 12.0F, -2.3F);
      this.bootCr2.addBox(-2.0F, -3.0F, 0.0F, 4, 3, 0, 0.0F);
      this.setRotateAngle(this.bootCr2, 0.3642502F, 0.0F, 0.0F);
      this.leftarmCr = new ModelRenderer(this, 52, 35);
      this.leftarmCr.setRotationPoint(-0.5F, -1.0F, 0.0F);
      this.leftarmCr.addBox(-1.5F, 0.0F, -1.5F, 3, 8, 3, 0.0F);
      this.setRotateAngle(this.leftarmCr, 0.0F, -0.63739425F, -1.7301449F);
      this.mantleh3 = new ModelRenderer(this, 0, 48);
      this.mantleh3.setRotationPoint(-4.0F, -8.5F, -4.2F);
      this.mantleh3.addBox(0.0F, 0.0F, 0.0F, 8, 16, 0, 0.0F);
      this.setRotateAngle(this.mantleh3, -0.18203785F, 0.0F, 0.0F);
      this.crystCh1 = new ModelRenderer(this, 48, 46);
      this.crystCh1.setRotationPoint(0.8F, 5.0F, -1.5F);
      this.crystCh1.addBox(-1.5F, 0.0F, -1.5F, 4, 14, 4, 0.0F);
      this.setRotateAngle(this.crystCh1, 0.0F, -0.5009095F, -2.1855013F);
      this.helm3 = new ModelRenderer(this, 34, 51);
      this.helm3.setRotationPoint(0.0F, -8.0F, 0.4F);
      this.helm3.addBox(-1.5F, -10.5F, -5.0F, 3, 10, 0, 0.0F);
      this.setRotateAngle(this.helm3, 0.13665928F, 0.0F, 0.0F);
      this.helm.addChild(this.helm1);
      this.helm.addChild(this.helm6);
      this.helm5_1.addChild(this.mantleh1);
      this.leftboot.addChild(this.bootCr1);
      this.helm.addChild(this.helm5);
      this.leftleg.addChild(this.mantleL1);
      this.helm.addChild(this.helm2);
      this.helm.addChild(this.helm4);
      this.helm.addChild(this.helm5_1);
      this.rightleg.addChild(this.mantleL2glow);
      this.helm6.addChild(this.mantleh2);
      this.chest.addChild(this.crystal);
      this.rightleg.addChild(this.mantleL2);
      this.chest.addChild(this.crystCh2);
      this.rightarm.addChild(this.rightarmCr);
      this.helm.addChild(this.helm7);
      this.helm.addChild(this.helmglow);
      this.rightboot.addChild(this.bootCr2);
      this.leftarm.addChild(this.leftarmCr);
      this.helm7.addChild(this.mantleh3);
      this.chest.addChild(this.crystCh1);
      this.helm.addChild(this.helm3);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.rightleg.render(f5);
      this.chest.render(f5);
      this.rightarm.render(f5);
      this.leftarm.render(f5);
      this.helm.render(f5);
      this.leftleg.render(f5);
      this.leftboot.render(f5);
      this.rightboot.render(f5);
   }

   public void setModelAttributes(ModelBase model) {
      super.setModelAttributes(model);
      if (model instanceof ModelBiped) {
         ModelBiped modelbiped = (ModelBiped)model;
         this.rightarm.rotateAngleX = modelbiped.bipedRightArm.rotateAngleX;
         this.rightarm.rotateAngleY = modelbiped.bipedRightArm.rotateAngleY;
         this.rightarm.rotateAngleZ = modelbiped.bipedRightArm.rotateAngleZ;
         this.leftarm.rotateAngleX = modelbiped.bipedLeftArm.rotateAngleX;
         this.leftarm.rotateAngleY = modelbiped.bipedLeftArm.rotateAngleY;
         this.leftarm.rotateAngleZ = modelbiped.bipedLeftArm.rotateAngleZ;
         this.helm.rotateAngleX = modelbiped.bipedHead.rotateAngleX;
         this.helm.rotateAngleY = modelbiped.bipedHead.rotateAngleY;
         this.helm.rotateAngleZ = modelbiped.bipedHead.rotateAngleZ;
         this.chest.rotateAngleX = modelbiped.bipedBody.rotateAngleX;
         this.chest.rotateAngleY = modelbiped.bipedBody.rotateAngleY;
         this.chest.rotateAngleZ = modelbiped.bipedBody.rotateAngleZ;
         this.rightleg.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightleg.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightleg.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftleg.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftleg.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftleg.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightboot.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightboot.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightboot.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftboot.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftboot.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftboot.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightarm.rotationPointX = modelbiped.bipedRightArm.rotationPointX;
         this.rightarm.rotationPointY = modelbiped.bipedRightArm.rotationPointY;
         this.rightarm.rotationPointZ = modelbiped.bipedRightArm.rotationPointZ;
         this.leftarm.rotationPointX = modelbiped.bipedLeftArm.rotationPointX;
         this.leftarm.rotationPointY = modelbiped.bipedLeftArm.rotationPointY;
         this.leftarm.rotationPointZ = modelbiped.bipedLeftArm.rotationPointZ;
         this.helm.rotationPointX = modelbiped.bipedHead.rotationPointX;
         this.helm.rotationPointY = modelbiped.bipedHead.rotationPointY;
         this.helm.rotationPointZ = modelbiped.bipedHead.rotationPointZ;
         this.chest.rotationPointX = modelbiped.bipedBody.rotationPointX;
         this.chest.rotationPointY = modelbiped.bipedBody.rotationPointY;
         this.chest.rotationPointZ = modelbiped.bipedBody.rotationPointZ;
         this.rightleg.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightleg.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightleg.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftleg.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftleg.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftleg.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
         this.rightboot.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightboot.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightboot.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftboot.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftboot.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftboot.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
      }
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
