package com.vivern.arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class CursedBladeModel extends ModelBase {
   public ModelRenderer staf;
   public ModelRenderer blade;
   public ModelRenderer shape;
   public ModelRenderer staf_1;
   public ModelRenderer staf_2;
   public ModelRenderer staf_3;
   public ModelRenderer shape_1;
   public ModelRenderer shape_2;
   public ModelRenderer shape_3;
   public ModelRenderer shape_4;
   public ModelRenderer shape_5;
   public ModelRenderer shape_6;
   public ModelRenderer shape_7;
   public ModelRenderer shape_8;
   public ModelRenderer shape_9;
   public ModelRenderer shape_10;
   public ModelRenderer shape_11;
   public ModelRenderer shape_12;
   public ModelRenderer shape_13;
   public ModelRenderer shape_14;
   public ModelRenderer shape_15;
   public ModelRenderer shape_16;
   public ModelRenderer shape_17;
   public ModelRenderer shape_18;
   public ModelRenderer shape_19;
   public ModelRenderer shape_20;
   public ModelRenderer shape_21;
   public ModelRenderer shape_22;
   public ModelRenderer shape_23;
   public ModelRenderer shape_24;
   public ModelRenderer shape_25;
   public ModelRenderer shape_26;
   public ModelRenderer shape_27;
   public ModelRenderer shape_28;
   public ModelRenderer shape_29;
   public ModelRenderer shape_30;
   public ModelRenderer shape_31;
   public ModelRenderer shape_32;
   public ModelRenderer shape_33;

   public CursedBladeModel() {
      this.textureWidth = 18;
      this.textureHeight = 32;
      this.shape_28 = new ModelRenderer(this, 14, 0);
      this.shape_28.setRotationPoint(-0.3F, 3.1F, 5.0F);
      this.shape_28.addBox(-0.5F, -7.0F, -1.8F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_28, 0.7740535F, 0.0F, 0.8651597F);
      this.shape_6 = new ModelRenderer(this, 14, 24);
      this.shape_6.setRotationPoint(0.0F, 9.5F, 0.0F);
      this.shape_6.addBox(-0.5F, 0.0F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_6, -0.27314404F, 0.0F, -0.3642502F);
      this.shape_24 = new ModelRenderer(this, 14, 0);
      this.shape_24.setRotationPoint(-0.3F, -0.9F, 5.0F);
      this.shape_24.addBox(-0.5F, -5.0F, 0.8F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape_24, -0.7740535F, 0.0F, 0.8651597F);
      this.shape_18 = new ModelRenderer(this, 14, 0);
      this.shape_18.setRotationPoint(0.3F, 1.1F, 5.0F);
      this.shape_18.addBox(-0.5F, -6.0F, 0.8F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shape_18, -0.7740535F, 0.0F, -0.8651597F);
      this.shape_9 = new ModelRenderer(this, 14, 0);
      this.shape_9.setRotationPoint(0.3F, -2.9F, 5.0F);
      this.shape_9.addBox(-0.5F, -4.0F, -1.8F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape_9, 0.7740535F, 0.0F, -0.8651597F);
      this.blade = new ModelRenderer(this, 0, 0);
      this.blade.setRotationPoint(0.0F, 6.0F, 5.0F);
      this.blade.addBox(-0.5F, -22.0F, -1.0F, 1, 22, 2, 0.0F);
      this.shape = new ModelRenderer(this, 14, 10);
      this.shape.setRotationPoint(0.0F, 7.5F, 2.0F);
      this.shape.addBox(-0.5F, 0.0F, -0.5F, 1, 10, 1, 0.0F);
      this.setRotateAngle(this.shape, 2.003289F, 0.31869712F, 0.0F);
      this.shape_4 = new ModelRenderer(this, 14, 24);
      this.shape_4.setRotationPoint(0.0F, 9.5F, 0.0F);
      this.shape_4.addBox(-0.5F, 0.0F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_4, 0.27314404F, 0.0F, 0.3642502F);
      this.shape_10 = new ModelRenderer(this, 6, 16);
      this.shape_10.setRotationPoint(-0.2F, -2.9F, 5.0F);
      this.shape_10.addBox(0.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_10, 0.0F, 0.0F, 0.95609134F);
      this.shape_14 = new ModelRenderer(this, 14, 0);
      this.shape_14.setRotationPoint(0.3F, 3.1F, 5.0F);
      this.shape_14.addBox(-0.5F, -7.0F, 0.8F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_14, -0.7740535F, 0.0F, -0.8651597F);
      this.staf_1 = new ModelRenderer(this, 0, 24);
      this.staf_1.setRotationPoint(0.0F, 5.0F, 5.0F);
      this.staf_1.addBox(-1.0F, 0.0F, -1.5F, 2, 2, 3, 0.0F);
      this.setRotateAngle(this.staf_1, 0.0F, 0.68294734F, 0.0F);
      this.shape_12 = new ModelRenderer(this, 14, 0);
      this.shape_12.setRotationPoint(0.3F, -0.9F, 5.0F);
      this.shape_12.addBox(-0.5F, -5.0F, -1.8F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape_12, 0.7740535F, 0.0F, -0.8651597F);
      this.shape_19 = new ModelRenderer(this, 14, 0);
      this.shape_19.setRotationPoint(0.3F, 1.1F, 5.0F);
      this.shape_19.addBox(-0.5F, -6.0F, -1.8F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shape_19, 0.7740535F, 0.0F, -0.8651597F);
      this.shape_26 = new ModelRenderer(this, 6, 18);
      this.shape_26.setRotationPoint(0.2F, -0.9F, 5.0F);
      this.shape_26.addBox(-1.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_26, 0.0F, 0.0F, -0.95609134F);
      this.staf = new ModelRenderer(this, 6, 0);
      this.staf.setRotationPoint(0.0F, 6.0F, 5.0F);
      this.staf.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.shape_1 = new ModelRenderer(this, 14, 10);
      this.shape_1.setRotationPoint(0.0F, 7.5F, 2.0F);
      this.shape_1.addBox(-0.5F, 0.0F, -0.5F, 1, 10, 1, 0.0F);
      this.setRotateAngle(this.shape_1, 2.003289F, -0.31869712F, 0.0F);
      this.shape_2 = new ModelRenderer(this, 14, 10);
      this.shape_2.setRotationPoint(0.0F, 7.5F, 8.0F);
      this.shape_2.addBox(-0.5F, 0.0F, -0.5F, 1, 10, 1, 0.0F);
      this.setRotateAngle(this.shape_2, -2.003289F, 0.31869712F, 0.0F);
      this.shape_17 = new ModelRenderer(this, 6, 17);
      this.shape_17.setRotationPoint(-0.2F, 1.1F, 5.0F);
      this.shape_17.addBox(0.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_17, 0.0F, 0.0F, 0.95609134F);
      this.shape_3 = new ModelRenderer(this, 14, 10);
      this.shape_3.setRotationPoint(0.0F, 7.5F, 8.0F);
      this.shape_3.addBox(-0.5F, 0.0F, -0.5F, 1, 10, 1, 0.0F);
      this.setRotateAngle(this.shape_3, -2.003289F, -0.31869712F, 0.0F);
      this.shape_7 = new ModelRenderer(this, 14, 24);
      this.shape_7.setRotationPoint(0.0F, 9.5F, 0.0F);
      this.shape_7.addBox(-0.5F, 0.0F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_7, -0.27314404F, 0.0F, 0.3642502F);
      this.shape_13 = new ModelRenderer(this, 6, 18);
      this.shape_13.setRotationPoint(-0.2F, -0.9F, 5.0F);
      this.shape_13.addBox(0.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_13, 0.0F, 0.0F, 0.95609134F);
      this.shape_20 = new ModelRenderer(this, 10, 21);
      this.shape_20.setRotationPoint(0.0F, -1.9F, 5.0F);
      this.shape_20.addBox(0.0F, -1.0F, -0.5F, 1, 10, 1, 0.0F);
      this.shape_22 = new ModelRenderer(this, 14, 0);
      this.shape_22.setRotationPoint(-0.3F, -2.9F, 5.0F);
      this.shape_22.addBox(-0.5F, -4.0F, -1.8F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape_22, 0.7740535F, 0.0F, 0.8651597F);
      this.shape_30 = new ModelRenderer(this, 6, 17);
      this.shape_30.setRotationPoint(0.2F, 1.1F, 5.0F);
      this.shape_30.addBox(-1.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_30, 0.0F, 0.0F, -0.95609134F);
      this.staf_3 = new ModelRenderer(this, 6, 12);
      this.staf_3.setRotationPoint(0.0F, 14.0F, 5.0F);
      this.staf_3.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.staf_3, 0.7285004F, 0.91053826F, -1.548107F);
      this.shape_8 = new ModelRenderer(this, 14, 0);
      this.shape_8.setRotationPoint(0.3F, -2.9F, 5.0F);
      this.shape_8.addBox(-0.5F, -4.0F, 0.8F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape_8, -0.7740535F, 0.0F, -0.8651597F);
      this.shape_16 = new ModelRenderer(this, 6, 16);
      this.shape_16.setRotationPoint(-0.2F, 3.1F, 5.0F);
      this.shape_16.addBox(0.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_16, 0.0F, 0.0F, 0.95609134F);
      this.shape_11 = new ModelRenderer(this, 14, 0);
      this.shape_11.setRotationPoint(0.3F, -0.9F, 5.0F);
      this.shape_11.addBox(-0.5F, -5.0F, 0.8F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape_11, -0.7740535F, 0.0F, -0.8651597F);
      this.shape_15 = new ModelRenderer(this, 14, 0);
      this.shape_15.setRotationPoint(0.3F, 3.1F, 5.0F);
      this.shape_15.addBox(-0.5F, -7.0F, -1.8F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_15, 0.7740535F, 0.0F, -0.8651597F);
      this.shape_27 = new ModelRenderer(this, 14, 0);
      this.shape_27.setRotationPoint(-0.3F, 3.1F, 5.0F);
      this.shape_27.addBox(-0.5F, -7.0F, 0.8F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_27, -0.7740535F, 0.0F, 0.8651597F);
      this.shape_21 = new ModelRenderer(this, 14, 0);
      this.shape_21.setRotationPoint(-0.3F, -2.9F, 5.0F);
      this.shape_21.addBox(-0.5F, -4.0F, 0.8F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape_21, -0.7740535F, 0.0F, 0.8651597F);
      this.shape_23 = new ModelRenderer(this, 6, 16);
      this.shape_23.setRotationPoint(0.2F, -2.9F, 5.0F);
      this.shape_23.addBox(-1.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_23, 0.0F, 0.0F, -0.95609134F);
      this.shape_25 = new ModelRenderer(this, 14, 0);
      this.shape_25.setRotationPoint(-0.3F, -0.9F, 5.0F);
      this.shape_25.addBox(-0.5F, -5.0F, -1.8F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape_25, 0.7740535F, 0.0F, 0.8651597F);
      this.shape_5 = new ModelRenderer(this, 14, 24);
      this.shape_5.setRotationPoint(0.0F, 9.5F, 0.0F);
      this.shape_5.addBox(-0.5F, 0.0F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_5, 0.27314404F, 0.0F, -0.3642502F);
      this.shape_29 = new ModelRenderer(this, 6, 16);
      this.shape_29.setRotationPoint(0.2F, 3.1F, 5.0F);
      this.shape_29.addBox(-1.0F, -1.0F, -1.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.shape_29, 0.0F, 0.0F, -0.95609134F);
      this.staf_2 = new ModelRenderer(this, 6, 6);
      this.staf_2.setRotationPoint(0.0F, 10.0F, 5.0F);
      this.staf_2.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.shape_32 = new ModelRenderer(this, 14, 0);
      this.shape_32.setRotationPoint(-0.3F, 1.1F, 5.0F);
      this.shape_32.addBox(-0.5F, -6.0F, -1.8F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shape_32, 0.7740535F, 0.0F, 0.8651597F);
      this.shape_31 = new ModelRenderer(this, 14, 0);
      this.shape_31.setRotationPoint(-0.3F, 1.1F, 5.0F);
      this.shape_31.addBox(-0.5F, -6.0F, 0.8F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shape_31, -0.7740535F, 0.0F, 0.8651597F);
      this.shape_33 = new ModelRenderer(this, 10, 21);
      this.shape_33.setRotationPoint(0.0F, -1.9F, 5.0F);
      this.shape_33.addBox(-1.0F, -1.0F, -0.5F, 1, 10, 1, 0.0F);
      this.shape_2.addChild(this.shape_6);
      this.shape.addChild(this.shape_4);
      this.shape_3.addChild(this.shape_7);
      this.shape_1.addChild(this.shape_5);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_28.offsetX, this.shape_28.offsetY, this.shape_28.offsetZ);
      GlStateManager.translate(this.shape_28.rotationPointX * f5, this.shape_28.rotationPointY * f5, this.shape_28.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_28.offsetX, -this.shape_28.offsetY, -this.shape_28.offsetZ);
      GlStateManager.translate(-this.shape_28.rotationPointX * f5, -this.shape_28.rotationPointY * f5, -this.shape_28.rotationPointZ * f5);
      this.shape_28.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_24.offsetX, this.shape_24.offsetY, this.shape_24.offsetZ);
      GlStateManager.translate(this.shape_24.rotationPointX * f5, this.shape_24.rotationPointY * f5, this.shape_24.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_24.offsetX, -this.shape_24.offsetY, -this.shape_24.offsetZ);
      GlStateManager.translate(-this.shape_24.rotationPointX * f5, -this.shape_24.rotationPointY * f5, -this.shape_24.rotationPointZ * f5);
      this.shape_24.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_18.offsetX, this.shape_18.offsetY, this.shape_18.offsetZ);
      GlStateManager.translate(this.shape_18.rotationPointX * f5, this.shape_18.rotationPointY * f5, this.shape_18.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_18.offsetX, -this.shape_18.offsetY, -this.shape_18.offsetZ);
      GlStateManager.translate(-this.shape_18.rotationPointX * f5, -this.shape_18.rotationPointY * f5, -this.shape_18.rotationPointZ * f5);
      this.shape_18.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_9.offsetX, this.shape_9.offsetY, this.shape_9.offsetZ);
      GlStateManager.translate(this.shape_9.rotationPointX * f5, this.shape_9.rotationPointY * f5, this.shape_9.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_9.offsetX, -this.shape_9.offsetY, -this.shape_9.offsetZ);
      GlStateManager.translate(-this.shape_9.rotationPointX * f5, -this.shape_9.rotationPointY * f5, -this.shape_9.rotationPointZ * f5);
      this.shape_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape.offsetX, this.shape.offsetY, this.shape.offsetZ);
      GlStateManager.translate(this.shape.rotationPointX * f5, this.shape.rotationPointY * f5, this.shape.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.5);
      GlStateManager.translate(-this.shape.offsetX, -this.shape.offsetY, -this.shape.offsetZ);
      GlStateManager.translate(-this.shape.rotationPointX * f5, -this.shape.rotationPointY * f5, -this.shape.rotationPointZ * f5);
      this.shape.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_10.offsetX, this.shape_10.offsetY, this.shape_10.offsetZ);
      GlStateManager.translate(this.shape_10.rotationPointX * f5, this.shape_10.rotationPointY * f5, this.shape_10.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.95, 0.45);
      GlStateManager.translate(-this.shape_10.offsetX, -this.shape_10.offsetY, -this.shape_10.offsetZ);
      GlStateManager.translate(-this.shape_10.rotationPointX * f5, -this.shape_10.rotationPointY * f5, -this.shape_10.rotationPointZ * f5);
      this.shape_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_14.offsetX, this.shape_14.offsetY, this.shape_14.offsetZ);
      GlStateManager.translate(this.shape_14.rotationPointX * f5, this.shape_14.rotationPointY * f5, this.shape_14.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_14.offsetX, -this.shape_14.offsetY, -this.shape_14.offsetZ);
      GlStateManager.translate(-this.shape_14.rotationPointX * f5, -this.shape_14.rotationPointY * f5, -this.shape_14.rotationPointZ * f5);
      this.shape_14.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf_1.offsetX, this.staf_1.offsetY, this.staf_1.offsetZ);
      GlStateManager.translate(this.staf_1.rotationPointX * f5, this.staf_1.rotationPointY * f5, this.staf_1.rotationPointZ * f5);
      GlStateManager.scale(0.85, 0.8, 0.8);
      GlStateManager.translate(-this.staf_1.offsetX, -this.staf_1.offsetY, -this.staf_1.offsetZ);
      GlStateManager.translate(-this.staf_1.rotationPointX * f5, -this.staf_1.rotationPointY * f5, -this.staf_1.rotationPointZ * f5);
      this.staf_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_12.offsetX, this.shape_12.offsetY, this.shape_12.offsetZ);
      GlStateManager.translate(this.shape_12.rotationPointX * f5, this.shape_12.rotationPointY * f5, this.shape_12.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_12.offsetX, -this.shape_12.offsetY, -this.shape_12.offsetZ);
      GlStateManager.translate(-this.shape_12.rotationPointX * f5, -this.shape_12.rotationPointY * f5, -this.shape_12.rotationPointZ * f5);
      this.shape_12.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_19.offsetX, this.shape_19.offsetY, this.shape_19.offsetZ);
      GlStateManager.translate(this.shape_19.rotationPointX * f5, this.shape_19.rotationPointY * f5, this.shape_19.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_19.offsetX, -this.shape_19.offsetY, -this.shape_19.offsetZ);
      GlStateManager.translate(-this.shape_19.rotationPointX * f5, -this.shape_19.rotationPointY * f5, -this.shape_19.rotationPointZ * f5);
      this.shape_19.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_26.offsetX, this.shape_26.offsetY, this.shape_26.offsetZ);
      GlStateManager.translate(this.shape_26.rotationPointX * f5, this.shape_26.rotationPointY * f5, this.shape_26.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.05, 0.5);
      GlStateManager.translate(-this.shape_26.offsetX, -this.shape_26.offsetY, -this.shape_26.offsetZ);
      GlStateManager.translate(-this.shape_26.rotationPointX * f5, -this.shape_26.rotationPointY * f5, -this.shape_26.rotationPointZ * f5);
      this.shape_26.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf.offsetX, this.staf.offsetY, this.staf.offsetZ);
      GlStateManager.translate(this.staf.rotationPointX * f5, this.staf.rotationPointY * f5, this.staf.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.0, 0.6);
      GlStateManager.translate(-this.staf.offsetX, -this.staf.offsetY, -this.staf.offsetZ);
      GlStateManager.translate(-this.staf.rotationPointX * f5, -this.staf.rotationPointY * f5, -this.staf.rotationPointZ * f5);
      this.staf.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_1.offsetX, this.shape_1.offsetY, this.shape_1.offsetZ);
      GlStateManager.translate(this.shape_1.rotationPointX * f5, this.shape_1.rotationPointY * f5, this.shape_1.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.5);
      GlStateManager.translate(-this.shape_1.offsetX, -this.shape_1.offsetY, -this.shape_1.offsetZ);
      GlStateManager.translate(-this.shape_1.rotationPointX * f5, -this.shape_1.rotationPointY * f5, -this.shape_1.rotationPointZ * f5);
      this.shape_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_2.offsetX, this.shape_2.offsetY, this.shape_2.offsetZ);
      GlStateManager.translate(this.shape_2.rotationPointX * f5, this.shape_2.rotationPointY * f5, this.shape_2.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.5);
      GlStateManager.translate(-this.shape_2.offsetX, -this.shape_2.offsetY, -this.shape_2.offsetZ);
      GlStateManager.translate(-this.shape_2.rotationPointX * f5, -this.shape_2.rotationPointY * f5, -this.shape_2.rotationPointZ * f5);
      this.shape_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_17.offsetX, this.shape_17.offsetY, this.shape_17.offsetZ);
      GlStateManager.translate(this.shape_17.rotationPointX * f5, this.shape_17.rotationPointY * f5, this.shape_17.rotationPointZ * f5);
      GlStateManager.scale(0.95, 1.1, 0.6);
      GlStateManager.translate(-this.shape_17.offsetX, -this.shape_17.offsetY, -this.shape_17.offsetZ);
      GlStateManager.translate(-this.shape_17.rotationPointX * f5, -this.shape_17.rotationPointY * f5, -this.shape_17.rotationPointZ * f5);
      this.shape_17.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_3.offsetX, this.shape_3.offsetY, this.shape_3.offsetZ);
      GlStateManager.translate(this.shape_3.rotationPointX * f5, this.shape_3.rotationPointY * f5, this.shape_3.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.5);
      GlStateManager.translate(-this.shape_3.offsetX, -this.shape_3.offsetY, -this.shape_3.offsetZ);
      GlStateManager.translate(-this.shape_3.rotationPointX * f5, -this.shape_3.rotationPointY * f5, -this.shape_3.rotationPointZ * f5);
      this.shape_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_13.offsetX, this.shape_13.offsetY, this.shape_13.offsetZ);
      GlStateManager.translate(this.shape_13.rotationPointX * f5, this.shape_13.rotationPointY * f5, this.shape_13.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.05, 0.5);
      GlStateManager.translate(-this.shape_13.offsetX, -this.shape_13.offsetY, -this.shape_13.offsetZ);
      GlStateManager.translate(-this.shape_13.rotationPointX * f5, -this.shape_13.rotationPointY * f5, -this.shape_13.rotationPointZ * f5);
      this.shape_13.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_20.offsetX, this.shape_20.offsetY, this.shape_20.offsetZ);
      GlStateManager.translate(this.shape_20.rotationPointX * f5, this.shape_20.rotationPointY * f5, this.shape_20.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.8, 0.6);
      GlStateManager.translate(-this.shape_20.offsetX, -this.shape_20.offsetY, -this.shape_20.offsetZ);
      GlStateManager.translate(-this.shape_20.rotationPointX * f5, -this.shape_20.rotationPointY * f5, -this.shape_20.rotationPointZ * f5);
      this.shape_20.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_22.offsetX, this.shape_22.offsetY, this.shape_22.offsetZ);
      GlStateManager.translate(this.shape_22.rotationPointX * f5, this.shape_22.rotationPointY * f5, this.shape_22.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_22.offsetX, -this.shape_22.offsetY, -this.shape_22.offsetZ);
      GlStateManager.translate(-this.shape_22.rotationPointX * f5, -this.shape_22.rotationPointY * f5, -this.shape_22.rotationPointZ * f5);
      this.shape_22.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_30.offsetX, this.shape_30.offsetY, this.shape_30.offsetZ);
      GlStateManager.translate(this.shape_30.rotationPointX * f5, this.shape_30.rotationPointY * f5, this.shape_30.rotationPointZ * f5);
      GlStateManager.scale(0.95, 1.1, 0.6);
      GlStateManager.translate(-this.shape_30.offsetX, -this.shape_30.offsetY, -this.shape_30.offsetZ);
      GlStateManager.translate(-this.shape_30.rotationPointX * f5, -this.shape_30.rotationPointY * f5, -this.shape_30.rotationPointZ * f5);
      this.shape_30.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf_3.offsetX, this.staf_3.offsetY, this.staf_3.offsetZ);
      GlStateManager.translate(this.staf_3.rotationPointX * f5, this.staf_3.rotationPointY * f5, this.staf_3.rotationPointZ * f5);
      GlStateManager.scale(0.85, 0.8, 0.8);
      GlStateManager.translate(-this.staf_3.offsetX, -this.staf_3.offsetY, -this.staf_3.offsetZ);
      GlStateManager.translate(-this.staf_3.rotationPointX * f5, -this.staf_3.rotationPointY * f5, -this.staf_3.rotationPointZ * f5);
      this.staf_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_8.offsetX, this.shape_8.offsetY, this.shape_8.offsetZ);
      GlStateManager.translate(this.shape_8.rotationPointX * f5, this.shape_8.rotationPointY * f5, this.shape_8.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_8.offsetX, -this.shape_8.offsetY, -this.shape_8.offsetZ);
      GlStateManager.translate(-this.shape_8.rotationPointX * f5, -this.shape_8.rotationPointY * f5, -this.shape_8.rotationPointZ * f5);
      this.shape_8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_16.offsetX, this.shape_16.offsetY, this.shape_16.offsetZ);
      GlStateManager.translate(this.shape_16.rotationPointX * f5, this.shape_16.rotationPointY * f5, this.shape_16.rotationPointZ * f5);
      GlStateManager.scale(0.95, 1.2, 0.6);
      GlStateManager.translate(-this.shape_16.offsetX, -this.shape_16.offsetY, -this.shape_16.offsetZ);
      GlStateManager.translate(-this.shape_16.rotationPointX * f5, -this.shape_16.rotationPointY * f5, -this.shape_16.rotationPointZ * f5);
      this.shape_16.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_11.offsetX, this.shape_11.offsetY, this.shape_11.offsetZ);
      GlStateManager.translate(this.shape_11.rotationPointX * f5, this.shape_11.rotationPointY * f5, this.shape_11.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_11.offsetX, -this.shape_11.offsetY, -this.shape_11.offsetZ);
      GlStateManager.translate(-this.shape_11.rotationPointX * f5, -this.shape_11.rotationPointY * f5, -this.shape_11.rotationPointZ * f5);
      this.shape_11.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_15.offsetX, this.shape_15.offsetY, this.shape_15.offsetZ);
      GlStateManager.translate(this.shape_15.rotationPointX * f5, this.shape_15.rotationPointY * f5, this.shape_15.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_15.offsetX, -this.shape_15.offsetY, -this.shape_15.offsetZ);
      GlStateManager.translate(-this.shape_15.rotationPointX * f5, -this.shape_15.rotationPointY * f5, -this.shape_15.rotationPointZ * f5);
      this.shape_15.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_27.offsetX, this.shape_27.offsetY, this.shape_27.offsetZ);
      GlStateManager.translate(this.shape_27.rotationPointX * f5, this.shape_27.rotationPointY * f5, this.shape_27.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_27.offsetX, -this.shape_27.offsetY, -this.shape_27.offsetZ);
      GlStateManager.translate(-this.shape_27.rotationPointX * f5, -this.shape_27.rotationPointY * f5, -this.shape_27.rotationPointZ * f5);
      this.shape_27.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_21.offsetX, this.shape_21.offsetY, this.shape_21.offsetZ);
      GlStateManager.translate(this.shape_21.rotationPointX * f5, this.shape_21.rotationPointY * f5, this.shape_21.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_21.offsetX, -this.shape_21.offsetY, -this.shape_21.offsetZ);
      GlStateManager.translate(-this.shape_21.rotationPointX * f5, -this.shape_21.rotationPointY * f5, -this.shape_21.rotationPointZ * f5);
      this.shape_21.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_23.offsetX, this.shape_23.offsetY, this.shape_23.offsetZ);
      GlStateManager.translate(this.shape_23.rotationPointX * f5, this.shape_23.rotationPointY * f5, this.shape_23.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.95, 0.45);
      GlStateManager.translate(-this.shape_23.offsetX, -this.shape_23.offsetY, -this.shape_23.offsetZ);
      GlStateManager.translate(-this.shape_23.rotationPointX * f5, -this.shape_23.rotationPointY * f5, -this.shape_23.rotationPointZ * f5);
      this.shape_23.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_25.offsetX, this.shape_25.offsetY, this.shape_25.offsetZ);
      GlStateManager.translate(this.shape_25.rotationPointX * f5, this.shape_25.rotationPointY * f5, this.shape_25.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_25.offsetX, -this.shape_25.offsetY, -this.shape_25.offsetZ);
      GlStateManager.translate(-this.shape_25.rotationPointX * f5, -this.shape_25.rotationPointY * f5, -this.shape_25.rotationPointZ * f5);
      this.shape_25.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_29.offsetX, this.shape_29.offsetY, this.shape_29.offsetZ);
      GlStateManager.translate(this.shape_29.rotationPointX * f5, this.shape_29.rotationPointY * f5, this.shape_29.rotationPointZ * f5);
      GlStateManager.scale(0.95, 1.2, 0.6);
      GlStateManager.translate(-this.shape_29.offsetX, -this.shape_29.offsetY, -this.shape_29.offsetZ);
      GlStateManager.translate(-this.shape_29.rotationPointX * f5, -this.shape_29.rotationPointY * f5, -this.shape_29.rotationPointZ * f5);
      this.shape_29.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf_2.offsetX, this.staf_2.offsetY, this.staf_2.offsetZ);
      GlStateManager.translate(this.staf_2.rotationPointX * f5, this.staf_2.rotationPointY * f5, this.staf_2.rotationPointZ * f5);
      GlStateManager.scale(0.5, 1.0, 0.5);
      GlStateManager.translate(-this.staf_2.offsetX, -this.staf_2.offsetY, -this.staf_2.offsetZ);
      GlStateManager.translate(-this.staf_2.rotationPointX * f5, -this.staf_2.rotationPointY * f5, -this.staf_2.rotationPointZ * f5);
      this.staf_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_32.offsetX, this.shape_32.offsetY, this.shape_32.offsetZ);
      GlStateManager.translate(this.shape_32.rotationPointX * f5, this.shape_32.rotationPointY * f5, this.shape_32.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_32.offsetX, -this.shape_32.offsetY, -this.shape_32.offsetZ);
      GlStateManager.translate(-this.shape_32.rotationPointX * f5, -this.shape_32.rotationPointY * f5, -this.shape_32.rotationPointZ * f5);
      this.shape_32.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_31.offsetX, this.shape_31.offsetY, this.shape_31.offsetZ);
      GlStateManager.translate(this.shape_31.rotationPointX * f5, this.shape_31.rotationPointY * f5, this.shape_31.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.4);
      GlStateManager.translate(-this.shape_31.offsetX, -this.shape_31.offsetY, -this.shape_31.offsetZ);
      GlStateManager.translate(-this.shape_31.rotationPointX * f5, -this.shape_31.rotationPointY * f5, -this.shape_31.rotationPointZ * f5);
      this.shape_31.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_33.offsetX, this.shape_33.offsetY, this.shape_33.offsetZ);
      GlStateManager.translate(this.shape_33.rotationPointX * f5, this.shape_33.rotationPointY * f5, this.shape_33.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.8, 0.6);
      GlStateManager.translate(-this.shape_33.offsetX, -this.shape_33.offsetY, -this.shape_33.offsetZ);
      GlStateManager.translate(-this.shape_33.rotationPointX * f5, -this.shape_33.rotationPointY * f5, -this.shape_33.rotationPointZ * f5);
      this.shape_33.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 190.0F, 190.0F);
      GlStateManager.translate(this.blade.offsetX, this.blade.offsetY, this.blade.offsetZ);
      GlStateManager.translate(this.blade.rotationPointX * f5, this.blade.rotationPointY * f5, this.blade.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 0.7);
      GlStateManager.translate(-this.blade.offsetX, -this.blade.offsetY, -this.blade.offsetZ);
      GlStateManager.translate(-this.blade.rotationPointX * f5, -this.blade.rotationPointY * f5, -this.blade.rotationPointZ * f5);
      this.blade.render(f5);
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
