package com.vivern.arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class DrillModel extends ModelBase {
   public ModelRenderer shapess2;
   public ModelRenderer shapess3;
   public ModelRenderer shapess1;
   public ModelRenderer bottom1;
   public ModelRenderer corpus;
   public ModelRenderer cap;
   public ModelRenderer mechanism;
   public ModelRenderer bottom2;
   public ModelRenderer engineFuel;
   public ModelRenderer shaft;
   public ModelRenderer grip2;
   public ModelRenderer engineElectric;
   public ModelRenderer buttonsGlow;
   public ModelRenderer enginef1;
   public ModelRenderer engineftube1;
   public ModelRenderer engineftube2;
   public ModelRenderer engineftube3;
   public ModelRenderer engineftube1a;
   public ModelRenderer engineftube2a;
   public ModelRenderer engineftube3a;
   public ModelRenderer bore;
   public ModelRenderer bore_1;
   public ModelRenderer bore_2;
   public ModelRenderer bore_3;
   public ModelRenderer bore_4;
   public ModelRenderer bore_5;
   public ModelRenderer bore_6;
   public ModelRenderer bore_7;
   public ModelRenderer bore_8;
   public ModelRenderer bore_9;
   public ModelRenderer bore_10;
   public ModelRenderer bore_11;
   public ModelRenderer grip3;
   public ModelRenderer grip1;
   public ModelRenderer enginee;
   public ModelRenderer enginee_1;
   public ModelRenderer enginee_2;
   public ModelRenderer enginee_3;
   public ModelRenderer enginee_4;
   public ModelRenderer enginee_5;

   public DrillModel() {
      this.textureWidth = 64;
      this.textureHeight = 64;
      this.shapess3 = new ModelRenderer(this, 36, 24);
      this.shapess3.setRotationPoint(0.0F, 4.0F, 6.5F);
      this.shapess3.addBox(-1.0F, 0.0F, 0.0F, 2, 4, 2, 0.0F);
      this.shapess1 = new ModelRenderer(this, 48, 24);
      this.shapess1.setRotationPoint(0.0F, 0.5F, 1.0F);
      this.shapess1.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 4, 0.0F);
      this.engineftube2a = new ModelRenderer(this, 12, 25);
      this.engineftube2a.setRotationPoint(-1.0F, 1.0F, -2.5F);
      this.engineftube2a.addBox(0.5F, -3.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.engineftube2a, 0.0F, 0.0F, (float) (-Math.PI / 4));
      this.shaft = new ModelRenderer(this, 0, 8);
      this.shaft.setRotationPoint(0.0F, 4.0F, -7.5F);
      this.shaft.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 2, 0.0F);
      this.engineftube1a = new ModelRenderer(this, 12, 25);
      this.engineftube1a.setRotationPoint(-1.0F, 1.0F, -1.0F);
      this.engineftube1a.addBox(0.5F, -3.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.engineftube1a, 0.0F, 0.0F, (float) (-Math.PI / 4));
      this.bore_10 = new ModelRenderer(this, 3, 0);
      this.bore_10.setRotationPoint(0.0F, 0.0F, -10.0F);
      this.bore_10.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 2, 0.0F);
      this.grip1 = new ModelRenderer(this, 43, 12);
      this.grip1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.grip1.addBox(0.0F, -0.5F, -0.5F, 1, 2, 3, 0.0F);
      this.bore_7 = new ModelRenderer(this, 20, 6);
      this.bore_7.setRotationPoint(0.0F, 0.0F, -5.5F);
      this.bore_7.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 1, 0.0F);
      this.setRotateAngle(this.bore_7, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.engineftube1 = new ModelRenderer(this, 12, 25);
      this.engineftube1.setRotationPoint(1.0F, 1.0F, -1.0F);
      this.engineftube1.addBox(-1.5F, -3.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.engineftube1, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.bore_6 = new ModelRenderer(this, 34, 7);
      this.bore_6.setRotationPoint(0.0F, 0.0F, -3.5F);
      this.bore_6.addBox(-2.5F, -2.5F, 0.0F, 5, 5, 1, 0.0F);
      this.bore = new ModelRenderer(this, 47, 0);
      this.bore.setRotationPoint(0.0F, 0.0F, -2.0F);
      this.bore.addBox(-3.0F, -3.0F, 0.0F, 6, 6, 2, 0.0F);
      this.enginee_5 = new ModelRenderer(this, 0, 18);
      this.enginee_5.setRotationPoint(0.0F, -1.0F, -5.0F);
      this.enginee_5.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_5, 0.0F, 0.0F, (float) (-Math.PI * 3.0 / 4.0));
      this.cap = new ModelRenderer(this, 5, 19);
      this.cap.setRotationPoint(0.0F, 0.0F, -4.0F);
      this.cap.addBox(-1.5F, 0.0F, 0.0F, 3, 1, 5, 0.0F);
      this.buttonsGlow = new ModelRenderer(this, 44, 54);
      this.buttonsGlow.setRotationPoint(0.0F, 1.0F, -2.0F);
      this.buttonsGlow.addBox(2.51F, 0.0F, 0.0F, 0, 5, 5, 0.0F);
      this.bore_3 = new ModelRenderer(this, 11, 0);
      this.bore_3.setRotationPoint(0.0F, 0.0F, -8.0F);
      this.bore_3.addBox(-1.5F, -1.5F, 0.0F, 3, 3, 2, 0.0F);
      this.setRotateAngle(this.bore_3, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.enginee = new ModelRenderer(this, 0, 18);
      this.enginee.setRotationPoint(0.0F, -1.0F, -5.0F);
      this.enginee.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.engineElectric = new ModelRenderer(this, 20, 0);
      this.engineElectric.setRotationPoint(0.0F, 5.0F, -1.5F);
      this.engineElectric.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 0, 0.0F);
      this.engineFuel = new ModelRenderer(this, 20, 0);
      this.engineFuel.setRotationPoint(0.0F, 5.0F, -1.5F);
      this.engineFuel.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 0, 0.0F);
      this.engineftube3 = new ModelRenderer(this, 12, 25);
      this.engineftube3.setRotationPoint(1.0F, 1.0F, -4.02F);
      this.engineftube3.addBox(-1.5F, -3.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.engineftube3, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.enginee_1 = new ModelRenderer(this, 0, 18);
      this.enginee_1.setRotationPoint(0.0F, -1.0F, -5.0F);
      this.enginee_1.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_1, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.bore_11 = new ModelRenderer(this, 0, 0);
      this.bore_11.setRotationPoint(0.0F, 0.0F, -11.0F);
      this.bore_11.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.bore_11, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.enginef1 = new ModelRenderer(this, 25, 8);
      this.enginef1.setRotationPoint(0.0F, 0.0F, -5.48F);
      this.enginef1.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 5, 0.0F);
      this.setRotateAngle(this.enginef1, 0.0F, 0.0F, 0.7285004F);
      this.enginee_2 = new ModelRenderer(this, 0, 18);
      this.enginee_2.setRotationPoint(0.0F, -1.0F, -5.0F);
      this.enginee_2.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_2, 0.0F, 0.0F, (float) (-Math.PI / 4));
      this.grip2 = new ModelRenderer(this, 51, 21);
      this.grip2.setRotationPoint(2.5F, 4.5F, 0.1F);
      this.grip2.addBox(1.0F, 0.0F, 0.0F, 4, 1, 2, 0.0F);
      this.setRotateAngle(this.grip2, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.bore_9 = new ModelRenderer(this, 0, 5);
      this.bore_9.setRotationPoint(0.0F, 0.0F, -9.5F);
      this.bore_9.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 1, 0.0F);
      this.setRotateAngle(this.bore_9, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.bore_1 = new ModelRenderer(this, 33, 0);
      this.bore_1.setRotationPoint(0.0F, 0.0F, -4.0F);
      this.bore_1.addBox(-2.5F, -2.5F, 0.0F, 5, 5, 2, 0.0F);
      this.setRotateAngle(this.bore_1, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.mechanism = new ModelRenderer(this, 0, 25);
      this.mechanism.setRotationPoint(0.0F, 1.0F, -6.0F);
      this.mechanism.addBox(-2.0F, 0.0F, 0.0F, 4, 3, 4, 0.0F);
      this.corpus = new ModelRenderer(this, 16, 22);
      this.corpus.setRotationPoint(0.0F, 1.0F, -2.0F);
      this.corpus.addBox(-2.5F, 0.0F, 0.0F, 5, 5, 5, 0.0F);
      this.bore_2 = new ModelRenderer(this, 21, 0);
      this.bore_2.setRotationPoint(0.0F, 0.0F, -6.0F);
      this.bore_2.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 2, 0.0F);
      this.bore_4 = new ModelRenderer(this, 51, 15);
      this.bore_4.setRotationPoint(0.0F, 0.0F, -0.5F);
      this.bore_4.addBox(-2.5F, -2.5F, 0.0F, 5, 5, 1, 0.0F);
      this.bottom2 = new ModelRenderer(this, 7, 5);
      this.bottom2.setRotationPoint(0.0F, 6.0F, -5.5F);
      this.bottom2.addBox(-1.5F, 0.0F, 0.0F, 3, 1, 7, 0.0F);
      this.bore_8 = new ModelRenderer(this, 6, 5);
      this.bore_8.setRotationPoint(0.0F, 0.0F, -7.5F);
      this.bore_8.addBox(-1.5F, -1.5F, 0.0F, 3, 3, 1, 0.0F);
      this.grip3 = new ModelRenderer(this, 56, 24);
      this.grip3.setRotationPoint(5.0F, 0.0F, 0.0F);
      this.grip3.addBox(0.0F, -0.5F, 0.0F, 1, 2, 2, 0.0F);
      this.bottom1 = new ModelRenderer(this, 36, 22);
      this.bottom1.setRotationPoint(0.0F, 6.0F, -1.5F);
      this.bottom1.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 8, 0.0F);
      this.enginee_3 = new ModelRenderer(this, 0, 18);
      this.enginee_3.setRotationPoint(0.0F, -1.0F, -5.0F);
      this.enginee_3.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_3, 0.0F, 0.0F, (float) (Math.PI * 3.0 / 4.0));
      this.shapess2 = new ModelRenderer(this, 38, 38);
      this.shapess2.setRotationPoint(0.5F, 1.0F, 4.0F);
      this.shapess2.addBox(-1.0F, 0.3F, -1.0F, 1, 5, 2, 0.0F);
      this.setRotateAngle(this.shapess2, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.enginee_4 = new ModelRenderer(this, 0, 18);
      this.enginee_4.setRotationPoint(0.0F, -1.0F, -5.0F);
      this.enginee_4.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_4, 0.0F, 0.0F, (float) Math.PI);
      this.engineftube2 = new ModelRenderer(this, 12, 25);
      this.engineftube2.setRotationPoint(1.0F, 1.0F, -2.5F);
      this.engineftube2.addBox(-1.5F, -3.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.engineftube2, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.engineftube3a = new ModelRenderer(this, 12, 25);
      this.engineftube3a.setRotationPoint(-1.0F, 1.0F, -4.02F);
      this.engineftube3a.addBox(0.5F, -3.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.engineftube3a, 0.0F, 0.0F, (float) (-Math.PI / 4));
      this.bore_5 = new ModelRenderer(this, 48, 8);
      this.bore_5.setRotationPoint(0.0F, 0.0F, -1.5F);
      this.bore_5.addBox(-3.0F, -3.0F, 0.0F, 6, 6, 1, 0.0F);
      this.setRotateAngle(this.bore_5, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.engineFuel.addChild(this.engineftube2a);
      this.engineFuel.addChild(this.engineftube1a);
      this.shaft.addChild(this.bore_10);
      this.grip2.addChild(this.grip1);
      this.shaft.addChild(this.bore_7);
      this.engineFuel.addChild(this.engineftube1);
      this.shaft.addChild(this.bore_6);
      this.shaft.addChild(this.bore);
      this.engineElectric.addChild(this.enginee_5);
      this.shaft.addChild(this.bore_3);
      this.engineElectric.addChild(this.enginee);
      this.engineFuel.addChild(this.engineftube3);
      this.engineElectric.addChild(this.enginee_1);
      this.shaft.addChild(this.bore_11);
      this.engineFuel.addChild(this.enginef1);
      this.engineElectric.addChild(this.enginee_2);
      this.shaft.addChild(this.bore_9);
      this.shaft.addChild(this.bore_1);
      this.shaft.addChild(this.bore_2);
      this.shaft.addChild(this.bore_4);
      this.shaft.addChild(this.bore_8);
      this.grip2.addChild(this.grip3);
      this.engineElectric.addChild(this.enginee_3);
      this.engineElectric.addChild(this.enginee_4);
      this.engineFuel.addChild(this.engineftube2);
      this.engineFuel.addChild(this.engineftube3a);
      this.shaft.addChild(this.bore_5);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.disableCull();
      this.shaft.rotateAngleZ = f * 0.036F;
      this.shapess3.render(f5);
      this.shapess1.render(f5);
      this.shaft.render(f5);
      this.cap.render(f5);
      if (f2 == 1.0F) {
         this.engineElectric.render(f5);
      }

      if (f2 == 2.0F) {
         this.engineFuel.render(f5);
      }

      this.grip2.render(f5);
      this.mechanism.render(f5);
      this.corpus.render(f5);
      this.bottom2.render(f5);
      this.bottom1.render(f5);
      this.shapess2.render(f5);
      if (f1 == 0.0F && f2 == 1.0F) {
         AbstractMobModel.light(240, false);
         this.buttonsGlow.render(f5);
         AbstractMobModel.returnlight();
      }

      GlStateManager.enableCull();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
