package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.AnimationTimer;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.GlStateManager.DestFactor;
import net.minecraft.client.renderer.GlStateManager.SourceFactor;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class EnderSeerModel extends ModelBase {
   public ModelRenderer shape1;
   public ModelRenderer eye1;
   public ModelRenderer eye2;
   public ModelRenderer eye3;
   public ModelRenderer eye4;
   public ModelRenderer eye5;
   public ModelRenderer tent1;
   public ModelRenderer tent2;
   public ModelRenderer tent4;
   public ModelRenderer tent5;
   public ModelRenderer shape2;
   public ModelRenderer shape3;
   public ModelRenderer tent3;
   public ModelRenderer tent6;
   public ModelRenderer shape4;

   public EnderSeerModel() {
      this.textureWidth = 64;
      this.textureHeight = 32;
      this.eye5 = new ModelRenderer(this, 0, 0);
      this.eye5.mirror = true;
      this.eye5.setRotationPoint(-4.7F, 20.6F, -0.2F);
      this.eye5.addBox(-3.0F, -2.0F, -2.0F, 4, 4, 4, 0.0F);
      this.setRotateAngle(this.eye5, 0.0F, -1.0016445F, 0.0F);
      this.shape4 = new ModelRenderer(this, 54, 4);
      this.shape4.setRotationPoint(0.0F, 16.01F, 5.01F);
      this.shape4.addBox(-0.5F, -7.0F, -5.0F, 1, 16, 4, 0.0F);
      this.setRotateAngle(this.shape4, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.tent2 = new ModelRenderer(this, 28, 0);
      this.tent2.setRotationPoint(4.7F, 20.5F, 3.5F);
      this.tent2.addBox(-0.5F, -1.0F, -1.0F, 16, 2, 2, 0.0F);
      this.tent4 = new ModelRenderer(this, 28, 0);
      this.tent4.mirror = true;
      this.tent4.setRotationPoint(-4.7F, 20.5F, -2.5F);
      this.tent4.addBox(-15.5F, -1.0F, -1.0F, 16, 2, 2, 0.0F);
      this.tent1 = new ModelRenderer(this, 28, 0);
      this.tent1.setRotationPoint(4.7F, 20.5F, -2.5F);
      this.tent1.addBox(-0.5F, -1.0F, -1.0F, 16, 2, 2, 0.0F);
      this.shape2 = new ModelRenderer(this, 25, 15);
      this.shape2.setRotationPoint(0.0F, 0.0F, 6.0F);
      this.shape2.addBox(-4.0F, -3.5F, 0.0F, 8, 7, 9, 0.0F);
      this.eye3 = new ModelRenderer(this, 0, 0);
      this.eye3.mirror = true;
      this.eye3.setRotationPoint(-4.7F, 16.6F, 4.0F);
      this.eye3.addBox(-3.0F, -2.0F, -2.0F, 4, 4, 4, 0.0F);
      this.setRotateAngle(this.eye3, 0.0F, -1.548107F, 0.0F);
      this.eye4 = new ModelRenderer(this, 0, 0);
      this.eye4.setRotationPoint(3.8F, 19.7F, 7.0F);
      this.eye4.addBox(-0.5F, -2.0F, -2.0F, 4, 4, 4, 0.0F);
      this.setRotateAngle(this.eye4, 0.0F, 1.1838568F, 0.0F);
      this.tent5 = new ModelRenderer(this, 28, 0);
      this.tent5.mirror = true;
      this.tent5.setRotationPoint(-4.7F, 20.5F, 3.5F);
      this.tent5.addBox(-15.5F, -1.0F, -1.0F, 16, 2, 2, 0.0F);
      this.shape3 = new ModelRenderer(this, 27, 16);
      this.shape3.setRotationPoint(0.0F, 0.0F, 8.0F);
      this.shape3.addBox(-3.0F, -3.0F, 0.0F, 6, 6, 8, 0.0F);
      this.shape1 = new ModelRenderer(this, 22, 13);
      this.shape1.setRotationPoint(0.0F, 18.0F, 0.0F);
      this.shape1.addBox(-5.0F, -4.0F, -4.0F, 10, 8, 11, 0.0F);
      this.eye2 = new ModelRenderer(this, 0, 0);
      this.eye2.setRotationPoint(4.7F, 17.1F, 1.0F);
      this.eye2.addBox(-0.5F, -2.0F, -2.0F, 4, 4, 4, 0.0F);
      this.setRotateAngle(this.eye2, 0.0F, 1.3203416F, 0.0F);
      this.tent3 = new ModelRenderer(this, 28, 4);
      this.tent3.setRotationPoint(3.7F, 2.49F, 6.5F);
      this.tent3.addBox(-0.5F, -1.0F, -1.0F, 9, 2, 2, 0.0F);
      this.tent6 = new ModelRenderer(this, 28, 4);
      this.tent6.mirror = true;
      this.tent6.setRotationPoint(-3.7F, 2.49F, 6.5F);
      this.tent6.addBox(-8.5F, -1.0F, -1.0F, 9, 2, 2, 0.0F);
      this.eye1 = new ModelRenderer(this, 0, 8);
      this.eye1.setRotationPoint(0.0F, 18.0F, -4.0F);
      this.eye1.addBox(-4.0F, -4.0F, -6.0F, 8, 8, 8, 0.0F);
      this.shape1.addChild(this.shape2);
      this.shape2.addChild(this.shape3);
      this.shape2.addChild(this.tent3);
      this.shape2.addChild(this.tent6);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      f5 *= 4.0F;
      GlStateManager.pushMatrix();
      GlStateManager.translate(0.0F, -4.0F, 0.0F);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.eye5.offsetX, this.eye5.offsetY, this.eye5.offsetZ);
      GlStateManager.translate(this.eye5.rotationPointX * f5, this.eye5.rotationPointY * f5, this.eye5.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.eye5.offsetX, -this.eye5.offsetY, -this.eye5.offsetZ);
      GlStateManager.translate(-this.eye5.rotationPointX * f5, -this.eye5.rotationPointY * f5, -this.eye5.rotationPointZ * f5);
      this.eye5.render(f5);
      GlStateManager.popMatrix();
      this.tent2.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.tent4.offsetX, this.tent4.offsetY, this.tent4.offsetZ);
      GlStateManager.translate(this.tent4.rotationPointX * f5, this.tent4.rotationPointY * f5, this.tent4.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 1.0);
      GlStateManager.translate(-this.tent4.offsetX, -this.tent4.offsetY, -this.tent4.offsetZ);
      GlStateManager.translate(-this.tent4.rotationPointX * f5, -this.tent4.rotationPointY * f5, -this.tent4.rotationPointZ * f5);
      this.tent4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.tent1.offsetX, this.tent1.offsetY, this.tent1.offsetZ);
      GlStateManager.translate(this.tent1.rotationPointX * f5, this.tent1.rotationPointY * f5, this.tent1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 1.0);
      GlStateManager.translate(-this.tent1.offsetX, -this.tent1.offsetY, -this.tent1.offsetZ);
      GlStateManager.translate(-this.tent1.rotationPointX * f5, -this.tent1.rotationPointY * f5, -this.tent1.rotationPointZ * f5);
      this.tent1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.eye3.offsetX, this.eye3.offsetY, this.eye3.offsetZ);
      GlStateManager.translate(this.eye3.rotationPointX * f5, this.eye3.rotationPointY * f5, this.eye3.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.1, 1.1);
      GlStateManager.translate(-this.eye3.offsetX, -this.eye3.offsetY, -this.eye3.offsetZ);
      GlStateManager.translate(-this.eye3.rotationPointX * f5, -this.eye3.rotationPointY * f5, -this.eye3.rotationPointZ * f5);
      this.eye3.render(f5);
      GlStateManager.popMatrix();
      this.eye4.render(f5);
      this.tent5.render(f5);
      this.shape1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.eye2.offsetX, this.eye2.offsetY, this.eye2.offsetZ);
      GlStateManager.translate(this.eye2.rotationPointX * f5, this.eye2.rotationPointY * f5, this.eye2.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.eye2.offsetX, -this.eye2.offsetY, -this.eye2.offsetZ);
      GlStateManager.translate(-this.eye2.rotationPointX * f5, -this.eye2.rotationPointY * f5, -this.eye2.rotationPointZ * f5);
      this.eye2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.eye1.offsetX, this.eye1.offsetY, this.eye1.offsetZ);
      GlStateManager.translate(this.eye1.rotationPointX * f5, this.eye1.rotationPointY * f5, this.eye1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.eye1.offsetX, -this.eye1.offsetY, -this.eye1.offsetZ);
      GlStateManager.translate(-this.eye1.rotationPointX * f5, -this.eye1.rotationPointY * f5, -this.eye1.rotationPointZ * f5);
      this.eye1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glEnable(3042);
      GlStateManager.blendFunc(SourceFactor.SRC_ALPHA, DestFactor.ONE_MINUS_SRC_ALPHA);
      GlStateManager.translate(this.shape4.offsetX, this.shape4.offsetY, this.shape4.offsetZ);
      GlStateManager.translate(this.shape4.rotationPointX * f5, this.shape4.rotationPointY * f5, this.shape4.rotationPointZ * f5);
      GlStateManager.scale(4.0, 1.2, 1.0);
      GlStateManager.translate(-this.shape4.offsetX, -this.shape4.offsetY, -this.shape4.offsetZ);
      GlStateManager.translate(-this.shape4.rotationPointX * f5, -this.shape4.rotationPointY * f5, -this.shape4.rotationPointZ * f5);
      this.shape4.render(f5);
      GlStateManager.blendFunc(SourceFactor.SRC_ALPHA, DestFactor.ONE_MINUS_SRC_ALPHA);
      GL11.glDisable(3042);
      GlStateManager.popMatrix();
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }

   public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
      this.eye1.rotateAngleY = netHeadYaw * (float) (Math.PI / 180.0);
      this.eye1.rotateAngleX = headPitch * (float) (Math.PI / 180.0);
      this.eye2.rotateAngleY = netHeadYaw * (float) (Math.PI / 180.0) + 1.3203416F;
      this.eye2.rotateAngleX = headPitch * (float) (Math.PI / 180.0);
      this.eye4.rotateAngleY = netHeadYaw * (float) (Math.PI / 180.0) + 1.1838568F;
      this.eye4.rotateAngleX = headPitch * (float) (Math.PI / 180.0);
      this.eye5.rotateAngleY = netHeadYaw * (float) (Math.PI / 180.0) - 1.0016445F;
      this.eye5.rotateAngleX = headPitch * (float) (Math.PI / 180.0);
      this.eye3.rotateAngleY = netHeadYaw * (float) (Math.PI / 180.0) - 1.548107F;
      this.eye3.rotateAngleX = headPitch * (float) (Math.PI / 180.0);
      float anglee = (float)Math.sin(AnimationTimer.tick / 40.0);
      this.tent1.rotateAngleY = (float)Math.sin((AnimationTimer.tick + 20) / 40.0) / 2.0F;
      this.tent2.rotateAngleY = (float)Math.sin((AnimationTimer.tick + 38) / 40.0) / 2.0F;
      this.tent3.rotateAngleY = (float)Math.sin((AnimationTimer.tick + 61) / 40.0) / 2.0F;
      this.tent4.rotateAngleY = (float)(-Math.sin((AnimationTimer.tick + 22) / 40.0)) / 2.0F;
      this.tent5.rotateAngleY = (float)(-Math.sin((AnimationTimer.tick + 41) / 40.0)) / 2.0F;
      this.tent6.rotateAngleY = (float)(-Math.sin((AnimationTimer.tick + 59) / 40.0)) / 2.0F;
      this.tent1.rotateAngleZ = anglee / 3.0F;
      this.tent2.rotateAngleZ = -anglee / 3.0F;
      this.tent3.rotateAngleZ = anglee / 3.5F;
      this.tent4.rotateAngleZ = anglee / 3.0F;
      this.tent5.rotateAngleZ = -anglee / 3.0F;
      this.tent6.rotateAngleZ = anglee / 3.5F;
      this.shape2.rotateAngleY = anglee / 3.0F;
      this.shape3.rotateAngleY = anglee / 3.0F;
   }
}
