package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class HeadShooterModel extends ModelBase {
   public ModelRenderer shapessh;
   public ModelRenderer shape1;
   public ModelRenderer shape2;
   public ModelRenderer shape3;
   public ModelRenderer shape4;
   public ModelRenderer shape5;
   public ModelRenderer shape6;
   public ModelRenderer shape7;
   public ModelRenderer shape8;
   public ModelRenderer shape9;
   public ModelRenderer shape10;
   public ModelRenderer shape11;
   public ModelRenderer shape12;
   public ModelRenderer shape13;
   public ModelRenderer shape14;
   public ModelRenderer shape15;

   public HeadShooterModel() {
      this.textureWidth = 22;
      this.textureHeight = 32;
      this.shape4 = new ModelRenderer(this, 9, 16);
      this.shape4.setRotationPoint(0.0F, -0.5F, -10.5F);
      this.shape4.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 3, 0.0F);
      this.shape2 = new ModelRenderer(this, 8, 25);
      this.shape2.setRotationPoint(0.0F, -2.0F, -4.5F);
      this.shape2.addBox(-1.0F, -0.5F, 0.0F, 2, 4, 3, 0.0F);
      this.shape14 = new ModelRenderer(this, 7, 20);
      this.shape14.setRotationPoint(0.0F, -3.3F, 0.5F);
      this.shape14.addBox(-0.5F, -0.5F, 0.0F, 1, 2, 2, 0.0F);
      this.shape15 = new ModelRenderer(this, 0, 13);
      this.shape15.setRotationPoint(0.0F, 2.9F, -2.0F);
      this.shape15.addBox(-1.0F, -0.5F, 0.0F, 2, 2, 4, 0.0F);
      this.shape3 = new ModelRenderer(this, 0, 21);
      this.shape3.setRotationPoint(0.0F, -0.5F, -7.5F);
      this.shape3.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 3, 0.0F);
      this.shape11 = new ModelRenderer(this, 16, 9);
      this.shape11.setRotationPoint(0.0F, -0.45F, -0.5F);
      this.shape11.addBox(-1.0F, -0.5F, 0.0F, 2, 5, 1, 0.0F);
      this.setRotateAngle(this.shape11, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape13 = new ModelRenderer(this, 10, 20);
      this.shape13.setRotationPoint(0.0F, -4.0F, -2.0F);
      this.shape13.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 4, 0.0F);
      this.shapessh = new ModelRenderer(this, 0, 0);
      this.shapessh.setRotationPoint(0.0F, 2.0F, 4.8F);
      this.shapessh.addBox(-0.5F, -1.5F, 0.0F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shapessh, 0.27314404F, 0.0F, 0.0F);
      this.shape6 = new ModelRenderer(this, 12, 0);
      this.shape6.setRotationPoint(0.0F, -1.5F, -1.5F);
      this.shape6.addBox(-1.0F, -0.5F, 0.0F, 2, 3, 1, 0.0F);
      this.shape9 = new ModelRenderer(this, 8, 11);
      this.shape9.setRotationPoint(0.0F, -1.5F, 9.5F);
      this.shape9.addBox(-1.0F, -0.5F, 0.0F, 2, 1, 4, 0.0F);
      this.shape12 = new ModelRenderer(this, 0, 7);
      this.shape12.setRotationPoint(0.0F, -4.5F, 2.0F);
      this.shape12.addBox(-1.0F, -0.5F, 0.0F, 2, 2, 4, 0.0F);
      this.shape7 = new ModelRenderer(this, 4, 0);
      this.shape7.setRotationPoint(0.0F, -1.5F, 1.5F);
      this.shape7.addBox(-1.0F, -0.5F, 0.0F, 2, 3, 4, 0.0F);
      this.shape10 = new ModelRenderer(this, 16, 19);
      this.shape10.setRotationPoint(0.0F, -1.5F, 13.5F);
      this.shape10.addBox(-1.0F, -0.5F, 0.0F, 2, 4, 1, 0.0F);
      this.shape8 = new ModelRenderer(this, 8, 7);
      this.shape8.setRotationPoint(0.0F, -1.5F, 7.5F);
      this.shape8.addBox(-1.0F, -0.5F, 0.0F, 2, 2, 2, 0.0F);
      this.shape1 = new ModelRenderer(this, 0, 26);
      this.shape1.setRotationPoint(0.0F, -2.0F, 5.5F);
      this.shape1.addBox(-1.0F, -0.5F, 0.0F, 2, 4, 2, 0.0F);
      this.shape5 = new ModelRenderer(this, 0, 26);
      this.shape5.setRotationPoint(0.0F, -2.0F, -0.5F);
      this.shape5.addBox(-1.0F, -0.5F, 0.0F, 2, 4, 2, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape2.offsetX, this.shape2.offsetY, this.shape2.offsetZ);
      GlStateManager.translate(this.shape2.rotationPointX * f5, this.shape2.rotationPointY * f5, this.shape2.rotationPointZ * f5);
      GlStateManager.scale(1.3, 1.0, 1.0);
      GlStateManager.translate(-this.shape2.offsetX, -this.shape2.offsetY, -this.shape2.offsetZ);
      GlStateManager.translate(-this.shape2.rotationPointX * f5, -this.shape2.rotationPointY * f5, -this.shape2.rotationPointZ * f5);
      this.shape2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape14.offsetX, this.shape14.offsetY, this.shape14.offsetZ);
      GlStateManager.translate(this.shape14.rotationPointX * f5, this.shape14.rotationPointY * f5, this.shape14.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.0, 1.0);
      GlStateManager.translate(-this.shape14.offsetX, -this.shape14.offsetY, -this.shape14.offsetZ);
      GlStateManager.translate(-this.shape14.rotationPointX * f5, -this.shape14.rotationPointY * f5, -this.shape14.rotationPointZ * f5);
      this.shape14.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape15.offsetX, this.shape15.offsetY, this.shape15.offsetZ);
      GlStateManager.translate(this.shape15.rotationPointX * f5, this.shape15.rotationPointY * f5, this.shape15.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.8, 0.9);
      GlStateManager.translate(-this.shape15.offsetX, -this.shape15.offsetY, -this.shape15.offsetZ);
      GlStateManager.translate(-this.shape15.rotationPointX * f5, -this.shape15.rotationPointY * f5, -this.shape15.rotationPointZ * f5);
      this.shape15.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape11.offsetX, this.shape11.offsetY, this.shape11.offsetZ);
      GlStateManager.translate(this.shape11.rotationPointX * f5, this.shape11.rotationPointY * f5, this.shape11.rotationPointZ * f5);
      GlStateManager.scale(1.6, 1.0, 1.0);
      GlStateManager.translate(-this.shape11.offsetX, -this.shape11.offsetY, -this.shape11.offsetZ);
      GlStateManager.translate(-this.shape11.rotationPointX * f5, -this.shape11.rotationPointY * f5, -this.shape11.rotationPointZ * f5);
      this.shape11.render(f5);
      GlStateManager.popMatrix();
      this.shape13.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapessh.offsetX, this.shapessh.offsetY, this.shapessh.offsetZ);
      GlStateManager.translate(this.shapessh.rotationPointX * f5, this.shapessh.rotationPointY * f5, this.shapessh.rotationPointZ * f5);
      GlStateManager.scale(1.0, 1.0, 1.2);
      GlStateManager.translate(-this.shapessh.offsetX, -this.shapessh.offsetY, -this.shapessh.offsetZ);
      GlStateManager.translate(-this.shapessh.rotationPointX * f5, -this.shapessh.rotationPointY * f5, -this.shapessh.rotationPointZ * f5);
      this.shapessh.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape9.offsetX, this.shape9.offsetY, this.shape9.offsetZ);
      GlStateManager.translate(this.shape9.rotationPointX * f5, this.shape9.rotationPointY * f5, this.shape9.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.shape9.offsetX, -this.shape9.offsetY, -this.shape9.offsetZ);
      GlStateManager.translate(-this.shape9.rotationPointX * f5, -this.shape9.rotationPointY * f5, -this.shape9.rotationPointZ * f5);
      this.shape9.render(f5);
      GlStateManager.popMatrix();
      this.shape12.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape10.offsetX, this.shape10.offsetY, this.shape10.offsetZ);
      GlStateManager.translate(this.shape10.rotationPointX * f5, this.shape10.rotationPointY * f5, this.shape10.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.shape10.offsetX, -this.shape10.offsetY, -this.shape10.offsetZ);
      GlStateManager.translate(-this.shape10.rotationPointX * f5, -this.shape10.rotationPointY * f5, -this.shape10.rotationPointZ * f5);
      this.shape10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape8.offsetX, this.shape8.offsetY, this.shape8.offsetZ);
      GlStateManager.translate(this.shape8.rotationPointX * f5, this.shape8.rotationPointY * f5, this.shape8.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.shape8.offsetX, -this.shape8.offsetY, -this.shape8.offsetZ);
      GlStateManager.translate(-this.shape8.rotationPointX * f5, -this.shape8.rotationPointY * f5, -this.shape8.rotationPointZ * f5);
      this.shape8.render(f5);
      GlStateManager.popMatrix();
      this.shape1.render(f5);
      this.shape5.render(f5);
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(
         OpenGlHelper.lightmapTexUnit, Math.min(240.0F, OpenGlHelper.lastBrightnessX + 140.0F), Math.min(240.0F, OpenGlHelper.lastBrightnessY + 140.0F)
      );
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape4.offsetX, this.shape4.offsetY, this.shape4.offsetZ);
      GlStateManager.translate(this.shape4.rotationPointX * f5, this.shape4.rotationPointY * f5, this.shape4.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 1.0);
      GlStateManager.translate(-this.shape4.offsetX, -this.shape4.offsetY, -this.shape4.offsetZ);
      GlStateManager.translate(-this.shape4.rotationPointX * f5, -this.shape4.rotationPointY * f5, -this.shape4.rotationPointZ * f5);
      this.shape4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape6.offsetX, this.shape6.offsetY, this.shape6.offsetZ);
      GlStateManager.translate(this.shape6.rotationPointX * f5, this.shape6.rotationPointY * f5, this.shape6.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.shape6.offsetX, -this.shape6.offsetY, -this.shape6.offsetZ);
      GlStateManager.translate(-this.shape6.rotationPointX * f5, -this.shape6.rotationPointY * f5, -this.shape6.rotationPointZ * f5);
      this.shape6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape3.offsetX, this.shape3.offsetY, this.shape3.offsetZ);
      GlStateManager.translate(this.shape3.rotationPointX * f5, this.shape3.rotationPointY * f5, this.shape3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 1.0);
      GlStateManager.translate(-this.shape3.offsetX, -this.shape3.offsetY, -this.shape3.offsetZ);
      GlStateManager.translate(-this.shape3.rotationPointX * f5, -this.shape3.rotationPointY * f5, -this.shape3.rotationPointZ * f5);
      this.shape3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape7.offsetX, this.shape7.offsetY, this.shape7.offsetZ);
      GlStateManager.translate(this.shape7.rotationPointX * f5, this.shape7.rotationPointY * f5, this.shape7.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.shape7.offsetX, -this.shape7.offsetY, -this.shape7.offsetZ);
      GlStateManager.translate(-this.shape7.rotationPointX * f5, -this.shape7.rotationPointY * f5, -this.shape7.rotationPointZ * f5);
      this.shape7.render(f5);
      GlStateManager.popMatrix();
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
