package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class IcicleMinigunModel extends ModelBase {
   public ModelRenderer shapessh;
   public ModelRenderer shape1;
   public ModelRenderer shapessh_1;
   public ModelRenderer shape1_1;
   public ModelRenderer shape1_2;
   public ModelRenderer shapessh_2;
   public ModelRenderer barr1;
   public ModelRenderer barr;
   public ModelRenderer barr_1;
   public ModelRenderer barr_2;
   public ModelRenderer barr_3;
   public ModelRenderer barr_4;
   public ModelRenderer shape1_3;
   public ModelRenderer shapessh_3;
   public ModelRenderer shape1_4;

   public IcicleMinigunModel() {
      this.textureWidth = 26;
      this.textureHeight = 26;
      this.shapessh_1 = new ModelRenderer(this, 4, 0);
      this.shapessh_1.setRotationPoint(0.0F, 3.0F, 8.4F);
      this.shapessh_1.addBox(-0.5F, 0.0F, -0.5F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shapessh_1, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.barr_1 = new ModelRenderer(this, 6, 20);
      this.barr_1.setRotationPoint(0.0F, 8.5F, -3.0F);
      this.barr_1.addBox(-0.5F, -1.7F, -4.5F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.barr_1, 0.0F, 0.0F, (float) (Math.PI * 2.0 / 3.0));
      this.shape1_1 = new ModelRenderer(this, 12, 9);
      this.shape1_1.setRotationPoint(0.0F, 8.0F, -1.0F);
      this.shape1_1.addBox(-2.0F, -1.5F, -1.5F, 4, 4, 3, 0.0F);
      this.shape1_2 = new ModelRenderer(this, 0, 19);
      this.shape1_2.setRotationPoint(0.0F, 9.5F, 2.5F);
      this.shape1_2.addBox(-2.0F, -1.5F, -1.5F, 4, 4, 1, 0.0F);
      this.shapessh_3 = new ModelRenderer(this, 0, 0);
      this.shapessh_3.setRotationPoint(0.0F, 2.5F, 2.5F);
      this.shapessh_3.addBox(-0.5F, 0.0F, 0.0F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shapessh_3, -0.5009095F, 0.0F, 0.0F);
      this.shapessh = new ModelRenderer(this, 0, 10);
      this.shapessh.setRotationPoint(0.0F, 3.5F, 6.8F);
      this.shapessh.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.barr_3 = new ModelRenderer(this, 6, 20);
      this.barr_3.setRotationPoint(0.0F, 8.5F, -3.0F);
      this.barr_3.addBox(-0.5F, -1.7F, -4.5F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.barr_3, 0.0F, 0.0F, (float) (-Math.PI / 3));
      this.shapessh_2 = new ModelRenderer(this, 18, 16);
      this.shapessh_2.setRotationPoint(0.0F, 8.5F, 0.7F);
      this.shapessh_2.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2, 0.0F);
      this.setRotateAngle(this.shapessh_2, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape1 = new ModelRenderer(this, 0, 10);
      this.shape1.setRotationPoint(0.5F, 9.0F, 2.5F);
      this.shape1.addBox(-2.0F, -1.5F, -2.0F, 3, 2, 6, 0.0F);
      this.shape1_4 = new ModelRenderer(this, 0, 0);
      this.shape1_4.setRotationPoint(0.0F, 8.0F, 2.0F);
      this.shape1_4.addBox(-2.0F, -1.5F, -1.5F, 4, 1, 8, 0.0F);
      this.barr = new ModelRenderer(this, 6, 20);
      this.barr.setRotationPoint(0.0F, 8.5F, -3.0F);
      this.barr.addBox(-0.5F, -1.7F, -4.5F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.barr, 0.0F, 0.0F, (float) (Math.PI / 3));
      this.barr_4 = new ModelRenderer(this, 6, 20);
      this.barr_4.setRotationPoint(0.0F, 8.5F, -3.0F);
      this.barr_4.addBox(-0.5F, -1.7F, -4.5F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.barr_4, 0.0F, 0.0F, (float) (-Math.PI * 2.0 / 3.0));
      this.barr1 = new ModelRenderer(this, 6, 20);
      this.barr1.setRotationPoint(0.0F, 8.5F, -3.0F);
      this.barr1.addBox(-0.5F, -1.7F, -4.5F, 1, 1, 5, 0.0F);
      this.barr_2 = new ModelRenderer(this, 6, 20);
      this.barr_2.setRotationPoint(0.0F, 8.5F, -3.0F);
      this.barr_2.addBox(-0.5F, -1.7F, -4.5F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.barr_2, 0.0F, 0.0F, (float) Math.PI);
      this.shape1_3 = new ModelRenderer(this, 16, 0);
      this.shape1_3.setRotationPoint(0.0F, 9.5F, 7.6F);
      this.shape1_3.addBox(-2.0F, -1.3F, 0.3F, 4, 7, 1, 0.0F);
      this.setRotateAngle(this.shape1_3, 3.0277972F, 0.0F, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      float m = 0.017453F;
      this.setRotateAngle(this.barr, 0.0F, 0.0F, f1 * m + (float) (Math.PI / 3));
      this.setRotateAngle(this.barr1, 0.0F, 0.0F, f1 * m);
      this.setRotateAngle(this.barr_1, 0.0F, 0.0F, f1 * m + (float) (Math.PI * 2.0 / 3.0));
      this.setRotateAngle(this.barr_2, 0.0F, 0.0F, f1 * m + (float) Math.PI);
      this.setRotateAngle(this.barr_3, 0.0F, 0.0F, f1 * m - (float) (Math.PI / 3));
      this.setRotateAngle(this.barr_4, 0.0F, 0.0F, f1 * m - (float) (Math.PI * 2.0 / 3.0));
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapessh_1.offsetX, this.shapessh_1.offsetY, this.shapessh_1.offsetZ);
      GlStateManager.translate(this.shapessh_1.rotationPointX * f5, this.shapessh_1.rotationPointY * f5, this.shapessh_1.rotationPointZ * f5);
      GlStateManager.scale(1.05, 1.05, 1.0);
      GlStateManager.translate(-this.shapessh_1.offsetX, -this.shapessh_1.offsetY, -this.shapessh_1.offsetZ);
      GlStateManager.translate(-this.shapessh_1.rotationPointX * f5, -this.shapessh_1.rotationPointY * f5, -this.shapessh_1.rotationPointZ * f5);
      this.shapessh_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.barr_1.offsetX, this.barr_1.offsetY, this.barr_1.offsetZ);
      GlStateManager.translate(this.barr_1.rotationPointX * f5, this.barr_1.rotationPointY * f5, this.barr_1.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.1, 1.0);
      GlStateManager.translate(-this.barr_1.offsetX, -this.barr_1.offsetY, -this.barr_1.offsetZ);
      GlStateManager.translate(-this.barr_1.rotationPointX * f5, -this.barr_1.rotationPointY * f5, -this.barr_1.rotationPointZ * f5);
      this.barr_1.render(f5);
      GlStateManager.popMatrix();
      this.shape1_2.render(f5);
      this.shapessh_3.render(f5);
      this.shapessh.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.barr_3.offsetX, this.barr_3.offsetY, this.barr_3.offsetZ);
      GlStateManager.translate(this.barr_3.rotationPointX * f5, this.barr_3.rotationPointY * f5, this.barr_3.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.1, 1.0);
      GlStateManager.translate(-this.barr_3.offsetX, -this.barr_3.offsetY, -this.barr_3.offsetZ);
      GlStateManager.translate(-this.barr_3.rotationPointX * f5, -this.barr_3.rotationPointY * f5, -this.barr_3.rotationPointZ * f5);
      this.barr_3.render(f5);
      GlStateManager.popMatrix();
      this.shapessh_2.render(f5);
      this.shape1.render(f5);
      this.shape1_4.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.barr.offsetX, this.barr.offsetY, this.barr.offsetZ);
      GlStateManager.translate(this.barr.rotationPointX * f5, this.barr.rotationPointY * f5, this.barr.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.1, 1.0);
      GlStateManager.translate(-this.barr.offsetX, -this.barr.offsetY, -this.barr.offsetZ);
      GlStateManager.translate(-this.barr.rotationPointX * f5, -this.barr.rotationPointY * f5, -this.barr.rotationPointZ * f5);
      this.barr.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.barr_4.offsetX, this.barr_4.offsetY, this.barr_4.offsetZ);
      GlStateManager.translate(this.barr_4.rotationPointX * f5, this.barr_4.rotationPointY * f5, this.barr_4.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.1, 1.0);
      GlStateManager.translate(-this.barr_4.offsetX, -this.barr_4.offsetY, -this.barr_4.offsetZ);
      GlStateManager.translate(-this.barr_4.rotationPointX * f5, -this.barr_4.rotationPointY * f5, -this.barr_4.rotationPointZ * f5);
      this.barr_4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.barr1.offsetX, this.barr1.offsetY, this.barr1.offsetZ);
      GlStateManager.translate(this.barr1.rotationPointX * f5, this.barr1.rotationPointY * f5, this.barr1.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.1, 1.0);
      GlStateManager.translate(-this.barr1.offsetX, -this.barr1.offsetY, -this.barr1.offsetZ);
      GlStateManager.translate(-this.barr1.rotationPointX * f5, -this.barr1.rotationPointY * f5, -this.barr1.rotationPointZ * f5);
      this.barr1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.barr_2.offsetX, this.barr_2.offsetY, this.barr_2.offsetZ);
      GlStateManager.translate(this.barr_2.rotationPointX * f5, this.barr_2.rotationPointY * f5, this.barr_2.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.1, 1.0);
      GlStateManager.translate(-this.barr_2.offsetX, -this.barr_2.offsetY, -this.barr_2.offsetZ);
      GlStateManager.translate(-this.barr_2.rotationPointX * f5, -this.barr_2.rotationPointY * f5, -this.barr_2.rotationPointZ * f5);
      this.barr_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_3.offsetX, this.shape1_3.offsetY, this.shape1_3.offsetZ);
      GlStateManager.translate(this.shape1_3.rotationPointX * f5, this.shape1_3.rotationPointY * f5, this.shape1_3.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.4, 1.5);
      GlStateManager.translate(-this.shape1_3.offsetX, -this.shape1_3.offsetY, -this.shape1_3.offsetZ);
      GlStateManager.translate(-this.shape1_3.rotationPointX * f5, -this.shape1_3.rotationPointY * f5, -this.shape1_3.rotationPointZ * f5);
      this.shape1_3.render(f5);
      GlStateManager.popMatrix();
      this.shape1_1.render(f5);
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
