package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.AnimationTimer;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class LichArmorModel extends ModelBiped {
   public ModelRenderer helm;
   public ModelRenderer chest;
   public ModelRenderer rightarm;
   public ModelRenderer leftarm;
   public ModelRenderer rightleg;
   public ModelRenderer leftleg;
   public ModelRenderer rightboot;
   public ModelRenderer leftboot;
   public ModelRenderer helm_1;
   public ModelRenderer helm_2;
   public ModelRenderer helmsp1;
   public ModelRenderer helmsp2;
   public ModelRenderer helmsp3;
   public ModelRenderer helmsp4;
   public ModelRenderer helm_3;
   public ModelRenderer helm_4;
   public ModelRenderer helm_5;
   public ModelRenderer helm_6;
   public ModelRenderer helm_7;
   public ModelRenderer helmspa1;
   public ModelRenderer helmspa2;
   public ModelRenderer helmspa3;
   public ModelRenderer helmspa4;
   public ModelRenderer hood1;
   public ModelRenderer hood2;
   public ModelRenderer hood3;
   public ModelRenderer hood4;
   public ModelRenderer hooda1;
   public ModelRenderer hooda2;
   public ModelRenderer hooda3;
   public ModelRenderer hooda4;
   public ModelRenderer rightarmsp;
   public ModelRenderer leftarmsp;

   public LichArmorModel() {
      this.textureWidth = 64;
      this.textureHeight = 64;
      this.hooda2 = new ModelRenderer(this, 36, 32);
      this.hooda2.mirror = true;
      this.hooda2.setRotationPoint(-3.2F, 9.0F, -2.8F);
      this.hooda2.addBox(-2.0F, 0.0F, 0.0F, 5, 9, 0, 0.0F);
      this.setRotateAngle(this.hooda2, -0.18203785F, 0.091106184F, 0.091106184F);
      this.helm = new ModelRenderer(this, 0, 0);
      this.helm.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8, 0.1F);
      this.helmsp3 = new ModelRenderer(this, 18, 50);
      this.helmsp3.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmsp3.addBox(3.5F, -5.5F, 1.0F, 4, 7, 1, 0.0F);
      this.setRotateAngle(this.helmsp3, 0.0F, -0.31869712F, -0.045553092F);
      this.hood4 = new ModelRenderer(this, 20, 24);
      this.hood4.setRotationPoint(3.7F, 9.0F, 2.5F);
      this.hood4.addBox(0.0F, 0.0F, -4.0F, 0, 15, 8, 0.0F);
      this.setRotateAngle(this.hood4, 0.3642502F, -0.91053826F, -0.3642502F);
      this.helmspa4 = new ModelRenderer(this, 52, 44);
      this.helmspa4.mirror = true;
      this.helmspa4.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmspa4.addBox(-9.4F, -5.5F, 0.5F, 5, 8, 1, 0.0F);
      this.setRotateAngle(this.helmspa4, 0.18203785F, 0.8651597F, 0.31869712F);
      this.hooda1 = new ModelRenderer(this, 0, 22);
      this.hooda1.setRotationPoint(-4.7F, 9.0F, 0.0F);
      this.hooda1.addBox(0.0F, 0.0F, -5.0F, 0, 15, 10, 0.0F);
      this.setRotateAngle(this.hooda1, 0.091106184F, 0.0F, 0.18203785F);
      this.rightarm = new ModelRenderer(this, 40, 14);
      this.rightarm.mirror = true;
      this.rightarm.setRotationPoint(-5.0F, 2.0F, 0.0F);
      this.rightarm.addBox(-3.0F, -2.0F, -2.0F, 4, 6, 4, 0.4F);
      this.hood3 = new ModelRenderer(this, 46, 32);
      this.hood3.setRotationPoint(4.0F, 5.0F, -2.7F);
      this.hood3.addBox(-1.6F, 0.0F, 0.0F, 3, 10, 0, 0.0F);
      this.setRotateAngle(this.hood3, -0.22759093F, -0.4553564F, -0.045553092F);
      this.rightleg = new ModelRenderer(this, 0, 16);
      this.rightleg.mirror = true;
      this.rightleg.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.hooda4 = new ModelRenderer(this, 20, 24);
      this.hooda4.setRotationPoint(-3.7F, 9.0F, 2.5F);
      this.hooda4.addBox(0.0F, 0.0F, -4.0F, 0, 15, 8, 0.0F);
      this.setRotateAngle(this.hooda4, 0.3642502F, 0.91053826F, 0.3642502F);
      this.chest = new ModelRenderer(this, 16, 16);
      this.chest.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.chest.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.5F);
      this.helm_3 = new ModelRenderer(this, 24, 0);
      this.helm_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm_3.addBox(-1.0F, -14.0F, -3.0F, 2, 3, 2, 0.0F);
      this.helmsp2 = new ModelRenderer(this, 8, 50);
      this.helmsp2.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmsp2.addBox(3.0F, -4.5F, 0.0F, 4, 6, 1, 0.0F);
      this.setRotateAngle(this.helmsp2, 0.0F, -0.045553092F, 0.091106184F);
      this.leftarmsp = new ModelRenderer(this, 0, 58);
      this.leftarmsp.setRotationPoint(3.0F, -5.0F, 0.0F);
      this.leftarmsp.addBox(0.5F, -3.5F, 0.0F, 4, 5, 1, 0.0F);
      this.setRotateAngle(this.leftarmsp, -0.18203785F, 0.13665928F, 1.0016445F);
      this.helm_1 = new ModelRenderer(this, 24, 53);
      this.helm_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm_1.addBox(-5.0F, -7.0F, -5.0F, 10, 1, 10, 0.0F);
      this.leftarm = new ModelRenderer(this, 40, 14);
      this.leftarm.setRotationPoint(5.0F, 2.0F, 0.0F);
      this.leftarm.addBox(-1.0F, -2.0F, -2.0F, 4, 6, 4, 0.4F);
      this.helmspa1 = new ModelRenderer(this, 0, 50);
      this.helmspa1.mirror = true;
      this.helmspa1.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmspa1.addBox(-6.5F, -4.0F, -1.0F, 3, 5, 1, 0.0F);
      this.setRotateAngle(this.helmspa1, 0.0F, -0.22759093F, -0.22759093F);
      this.hood2 = new ModelRenderer(this, 36, 32);
      this.hood2.setRotationPoint(3.2F, 9.0F, -2.8F);
      this.hood2.addBox(-3.0F, 0.0F, 0.0F, 5, 9, 0, 0.0F);
      this.setRotateAngle(this.hood2, -0.18203785F, -0.091106184F, -0.091106184F);
      this.helm_4 = new ModelRenderer(this, 32, 6);
      this.helm_4.setRotationPoint(0.0F, -12.5F, 0.0F);
      this.helm_4.addBox(-2.0F, -2.0F, -2.5F, 4, 4, 1, 0.0F);
      this.setRotateAngle(this.helm_4, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.helm_5 = new ModelRenderer(this, 0, 0);
      this.helm_5.setRotationPoint(0.0F, -16.0F, -2.0F);
      this.helm_5.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.helm_5, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.helm_7 = new ModelRenderer(this, 32, -10);
      this.helm_7.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm_7.addBox(-6.0F, -5.0F, -5.0F, 0, 6, 10, 0.0F);
      this.setRotateAngle(this.helm_7, 0.0F, 0.0F, 0.18203785F);
      this.hood1 = new ModelRenderer(this, 0, 22);
      this.hood1.setRotationPoint(4.7F, 9.0F, 0.0F);
      this.hood1.addBox(0.0F, 0.0F, -5.0F, 0, 15, 10, 0.0F);
      this.setRotateAngle(this.hood1, 0.091106184F, 0.0F, -0.18203785F);
      this.hooda3 = new ModelRenderer(this, 46, 32);
      this.hooda3.mirror = true;
      this.hooda3.setRotationPoint(-4.0F, 5.0F, -2.7F);
      this.hooda3.addBox(-1.4F, 0.0F, 0.0F, 3, 10, 0, 0.0F);
      this.setRotateAngle(this.hooda3, -0.22759093F, 0.4553564F, 0.045553092F);
      this.rightboot = new ModelRenderer(this, 40, 24);
      this.rightboot.mirror = true;
      this.rightboot.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightboot.addBox(-2.0F, 8.0F, -2.0F, 4, 4, 4, 0.4F);
      this.helmsp1 = new ModelRenderer(this, 0, 50);
      this.helmsp1.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmsp1.addBox(3.5F, -4.0F, -1.0F, 3, 5, 1, 0.0F);
      this.setRotateAngle(this.helmsp1, 0.0F, 0.22759093F, 0.22759093F);
      this.leftboot = new ModelRenderer(this, 40, 24);
      this.leftboot.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftboot.addBox(-2.0F, 8.0F, -2.0F, 4, 4, 4, 0.4F);
      this.leftleg = new ModelRenderer(this, 0, 16);
      this.leftleg.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.helmspa2 = new ModelRenderer(this, 8, 50);
      this.helmspa2.mirror = true;
      this.helmspa2.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmspa2.addBox(-7.0F, -4.5F, 0.0F, 4, 6, 1, 0.0F);
      this.setRotateAngle(this.helmspa2, 0.0F, 0.045553092F, -0.091106184F);
      this.helmspa3 = new ModelRenderer(this, 18, 50);
      this.helmspa3.mirror = true;
      this.helmspa3.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmspa3.addBox(-7.5F, -5.5F, 1.0F, 4, 7, 1, 0.0F);
      this.setRotateAngle(this.helmspa3, 0.0F, 0.31869712F, 0.045553092F);
      this.rightarmsp = new ModelRenderer(this, 0, 58);
      this.rightarmsp.mirror = true;
      this.rightarmsp.setRotationPoint(-3.0F, -5.0F, 0.0F);
      this.rightarmsp.addBox(-4.5F, -3.5F, 0.0F, 4, 5, 1, 0.0F);
      this.setRotateAngle(this.rightarmsp, -0.18203785F, -0.13665928F, -1.0016445F);
      this.helm_6 = new ModelRenderer(this, 32, -10);
      this.helm_6.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm_6.addBox(6.0F, -5.0F, -5.0F, 0, 6, 10, 0.0F);
      this.setRotateAngle(this.helm_6, 0.0F, 0.0F, -0.18203785F);
      this.helm_2 = new ModelRenderer(this, 32, 48);
      this.helm_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm_2.addBox(-4.0F, -11.0F, -4.0F, 8, 3, 2, 0.0F);
      this.helmsp4 = new ModelRenderer(this, 52, 44);
      this.helmsp4.setRotationPoint(0.0F, -8.0F, 0.0F);
      this.helmsp4.addBox(4.4F, -5.5F, 0.5F, 5, 8, 1, 0.0F);
      this.setRotateAngle(this.helmsp4, 0.18203785F, -0.8651597F, -0.31869712F);
      this.chest.addChild(this.hooda2);
      this.helm.addChild(this.helmsp3);
      this.chest.addChild(this.hood4);
      this.helm.addChild(this.helmspa4);
      this.chest.addChild(this.hooda1);
      this.chest.addChild(this.hood3);
      this.chest.addChild(this.hooda4);
      this.helm.addChild(this.helm_3);
      this.helm.addChild(this.helmsp2);
      this.leftarm.addChild(this.leftarmsp);
      this.helm.addChild(this.helm_1);
      this.helm.addChild(this.helmspa1);
      this.chest.addChild(this.hood2);
      this.helm.addChild(this.helm_4);
      this.helm.addChild(this.helm_5);
      this.helm.addChild(this.helm_7);
      this.chest.addChild(this.hood1);
      this.chest.addChild(this.hooda3);
      this.helm.addChild(this.helmsp1);
      this.helm.addChild(this.helmspa2);
      this.helm.addChild(this.helmspa3);
      this.rightarm.addChild(this.rightarmsp);
      this.helm.addChild(this.helm_6);
      this.helm.addChild(this.helm_2);
      this.helm.addChild(this.helmsp4);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      if (entity.isSneaking()) {
         GlStateManager.translate(0.0F, 0.2F, 0.0F);
      }

      float w = MathHelper.sin(AnimationTimer.tick / 70.0F) * 0.07F;
      this.hood3.rotateAngleY = -0.4553564F + w;
      this.hooda3.rotateAngleY = 0.4553564F + w;
      this.hood2.rotateAngleX = -0.18203785F + this.leftleg.rotateAngleX / 2.0F;
      this.hooda2.rotateAngleX = -0.18203785F + this.rightleg.rotateAngleX / 2.0F;
      this.hood4.rotateAngleZ = -0.3642502F + this.leftleg.rotateAngleX / 10.0F;
      this.hood4.rotateAngleY = -0.91053826F + this.leftleg.rotateAngleX / 1.5F + w;
      this.hooda4.rotateAngleZ = 0.3642502F - this.rightleg.rotateAngleX / 10.0F;
      this.hooda4.rotateAngleY = 0.91053826F - this.rightleg.rotateAngleX / 1.5F + w;
      this.hood1.rotateAngleX = 0.091106184F + this.leftleg.rotateAngleX / 4.0F;
      this.hooda1.rotateAngleX = 0.091106184F + this.rightleg.rotateAngleX / 4.0F;
      this.hood1.rotateAngleZ = -0.18203785F + w;
      this.hooda1.rotateAngleZ = 0.18203785F - w;
      this.helm.render(f5);
      this.rightarm.render(f5);
      this.rightleg.render(f5);
      this.chest.render(f5);
      this.leftarm.render(f5);
      this.rightboot.render(f5);
      this.leftboot.render(f5);
      this.leftleg.render(f5);
      GlStateManager.popMatrix();
   }

   public void setModelAttributes(ModelBase model) {
      super.setModelAttributes(model);
      if (model instanceof ModelBiped) {
         ModelBiped modelbiped = (ModelBiped)model;
         this.rightarm.rotateAngleX = modelbiped.bipedRightArm.rotateAngleX;
         this.rightarm.rotateAngleY = modelbiped.bipedRightArm.rotateAngleY;
         this.rightarm.rotateAngleZ = modelbiped.bipedRightArm.rotateAngleZ;
         this.leftarm.rotateAngleX = modelbiped.bipedLeftArm.rotateAngleX;
         this.leftarm.rotateAngleY = modelbiped.bipedLeftArm.rotateAngleY;
         this.leftarm.rotateAngleZ = modelbiped.bipedLeftArm.rotateAngleZ;
         this.helm.rotateAngleX = modelbiped.bipedHead.rotateAngleX;
         this.helm.rotateAngleY = modelbiped.bipedHead.rotateAngleY;
         this.helm.rotateAngleZ = modelbiped.bipedHead.rotateAngleZ;
         this.chest.rotateAngleX = modelbiped.bipedBody.rotateAngleX;
         this.chest.rotateAngleY = modelbiped.bipedBody.rotateAngleY;
         this.chest.rotateAngleZ = modelbiped.bipedBody.rotateAngleZ;
         this.rightleg.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightleg.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightleg.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftleg.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftleg.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftleg.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightboot.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightboot.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightboot.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftboot.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftboot.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftboot.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightarm.rotationPointX = modelbiped.bipedRightArm.rotationPointX;
         this.rightarm.rotationPointY = modelbiped.bipedRightArm.rotationPointY;
         this.rightarm.rotationPointZ = modelbiped.bipedRightArm.rotationPointZ;
         this.leftarm.rotationPointX = modelbiped.bipedLeftArm.rotationPointX;
         this.leftarm.rotationPointY = modelbiped.bipedLeftArm.rotationPointY;
         this.leftarm.rotationPointZ = modelbiped.bipedLeftArm.rotationPointZ;
         this.helm.rotationPointX = modelbiped.bipedHead.rotationPointX;
         this.helm.rotationPointY = modelbiped.bipedHead.rotationPointY;
         this.helm.rotationPointZ = modelbiped.bipedHead.rotationPointZ;
         this.chest.rotationPointX = modelbiped.bipedBody.rotationPointX;
         this.chest.rotationPointY = modelbiped.bipedBody.rotationPointY;
         this.chest.rotationPointZ = modelbiped.bipedBody.rotationPointZ;
         this.rightleg.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightleg.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightleg.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftleg.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftleg.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftleg.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
         this.rightboot.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightboot.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightboot.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftboot.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftboot.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftboot.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
      }
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
