package com.vivern.arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class MiningLaserModel extends ModelBase {
   public ModelRenderer shapess2;
   public ModelRenderer shapess3;
   public ModelRenderer shapess1;
   public ModelRenderer bottom1;
   public ModelRenderer corpus;
   public ModelRenderer cap;
   public ModelRenderer mechanism;
   public ModelRenderer bottom2;
   public ModelRenderer grip2;
   public ModelRenderer engineElectric;
   public ModelRenderer head;
   public ModelRenderer core;
   public ModelRenderer plasmatron;
   public ModelRenderer brasstube;
   public ModelRenderer brasstube_1;
   public ModelRenderer brasstube_2;
   public ModelRenderer corpusGlow;
   public ModelRenderer mechanismGlow;
   public ModelRenderer coreGlow;
   public ModelRenderer plasmatronGlow;
   public ModelRenderer grip3;
   public ModelRenderer grip1;
   public ModelRenderer enginee;
   public ModelRenderer enginee_1;
   public ModelRenderer enginee_2;
   public ModelRenderer enginee_3;
   public ModelRenderer enginee_4;
   public ModelRenderer enginee_5;
   public ModelRenderer headshaft;
   public ModelRenderer headshaft_1;
   public ModelRenderer headshaft_2;
   public ModelRenderer headshaft_3;
   public ModelRenderer headshaftcap;
   public ModelRenderer headshaftcap_1;
   public ModelRenderer headshaftcap_2;
   public ModelRenderer headshaftcap_3;
   public ModelRenderer brasstube_3;
   public ModelRenderer brasstube_4;
   public ModelRenderer brasstube_5;
   public ModelRenderer brasstube_6;
   public ModelRenderer brasstube_7;
   public ModelRenderer brasstube_8;

   public MiningLaserModel() {
      this.textureWidth = 64;
      this.textureHeight = 64;
      this.headshaft_1 = new ModelRenderer(this, 2, 41);
      this.headshaft_1.setRotationPoint(0.0F, 0.0F, 1.5F);
      this.headshaft_1.addBox(-0.5F, -3.5F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.headshaft_1, 0.0F, 0.0F, (float) Math.PI);
      this.headshaftcap_2 = new ModelRenderer(this, 0, 38);
      this.headshaftcap_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.headshaftcap_2.addBox(-1.0F, -4.5F, -1.0F, 2, 1, 2, 0.0F);
      this.brasstube_4 = new ModelRenderer(this, 17, 32);
      this.brasstube_4.mirror = true;
      this.brasstube_4.setRotationPoint(0.01F, 1.0F, 2.0F);
      this.brasstube_4.addBox(-0.5F, -1.0F, 0.0F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.brasstube_4, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.corpus = new ModelRenderer(this, 16, 22);
      this.corpus.setRotationPoint(0.0F, 1.0F, -2.0F);
      this.corpus.addBox(-2.5F, 0.0F, 0.0F, 5, 5, 5, 0.0F);
      this.headshaft = new ModelRenderer(this, 2, 41);
      this.headshaft.setRotationPoint(0.0F, 0.0F, 1.5F);
      this.headshaft.addBox(-0.5F, -3.5F, -0.5F, 1, 2, 1, 0.0F);
      this.brasstube_3 = new ModelRenderer(this, 16, 32);
      this.brasstube_3.setRotationPoint(-0.01F, -0.5F, 2.0F);
      this.brasstube_3.addBox(-0.5F, 0.0F, 0.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.brasstube_3, (float) (-Math.PI / 4), 0.0F, 0.0F);
      this.headshaftcap_3 = new ModelRenderer(this, 0, 38);
      this.headshaftcap_3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.headshaftcap_3.addBox(-1.0F, -4.5F, -1.0F, 2, 1, 2, 0.0F);
      this.headshaft_2 = new ModelRenderer(this, 2, 41);
      this.headshaft_2.setRotationPoint(0.0F, 0.0F, 1.5F);
      this.headshaft_2.addBox(-0.5F, -3.5F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.headshaft_2, 0.0F, 0.0F, (float) (Math.PI / 2));
      this.head = new ModelRenderer(this, 0, 32);
      this.head.setRotationPoint(0.0F, 4.0F, -13.5F);
      this.head.addBox(-1.5F, -1.5F, 0.0F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.head, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.shapess1 = new ModelRenderer(this, 48, 24);
      this.shapess1.setRotationPoint(0.0F, 0.5F, 1.0F);
      this.shapess1.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 4, 0.0F);
      this.grip2 = new ModelRenderer(this, 51, 21);
      this.grip2.setRotationPoint(2.5F, 4.5F, 0.1F);
      this.grip2.addBox(1.0F, 0.0F, 0.0F, 4, 1, 2, 0.0F);
      this.setRotateAngle(this.grip2, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.enginee_3 = new ModelRenderer(this, 0, 18);
      this.enginee_3.setRotationPoint(0.0F, 0.0F, -5.0F);
      this.enginee_3.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_3, 0.0F, 0.0F, (float) (Math.PI * 3.0 / 4.0));
      this.shapess2 = new ModelRenderer(this, 38, 38);
      this.shapess2.setRotationPoint(0.5F, 1.0F, 4.0F);
      this.shapess2.addBox(-1.0F, 0.3F, -1.0F, 1, 5, 2, 0.0F);
      this.setRotateAngle(this.shapess2, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.engineElectric = new ModelRenderer(this, 20, 0);
      this.engineElectric.setRotationPoint(0.0F, 4.0F, -5.0F);
      this.engineElectric.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 0, 0.0F);
      this.setRotateAngle(this.engineElectric, 0.0F, 0.0F, (float) (Math.PI / 2));
      this.brasstube = new ModelRenderer(this, 17, 32);
      this.brasstube.mirror = true;
      this.brasstube.setRotationPoint(0.0F, 4.0F, -9.5F);
      this.brasstube.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 5, 0.0F);
      this.plasmatronGlow = new ModelRenderer(this, 54, 55);
      this.plasmatronGlow.setRotationPoint(0.0F, 4.0F, -15.0F);
      this.plasmatronGlow.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 4, 0.01F);
      this.bottom1 = new ModelRenderer(this, 36, 22);
      this.bottom1.setRotationPoint(0.0F, 6.0F, -1.5F);
      this.bottom1.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 8, 0.0F);
      this.bottom2 = new ModelRenderer(this, 7, 5);
      this.bottom2.setRotationPoint(0.0F, 6.5F, -7.5F);
      this.bottom2.addBox(-1.5F, 0.0F, 0.0F, 3, 1, 7, 0.0F);
      this.enginee_5 = new ModelRenderer(this, 0, 18);
      this.enginee_5.setRotationPoint(0.0F, 0.0F, -5.0F);
      this.enginee_5.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_5, 0.0F, 0.0F, (float) (-Math.PI * 3.0 / 4.0));
      this.headshaft_3 = new ModelRenderer(this, 2, 41);
      this.headshaft_3.setRotationPoint(0.0F, 0.0F, 1.5F);
      this.headshaft_3.addBox(-0.5F, -3.5F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.headshaft_3, 0.0F, 0.0F, (float) (-Math.PI / 2));
      this.corpusGlow = new ModelRenderer(this, 44, 32);
      this.corpusGlow.setRotationPoint(0.0F, 1.0F, -2.0F);
      this.corpusGlow.addBox(-2.5F, 0.0F, 0.0F, 5, 5, 5, 0.01F);
      this.enginee_2 = new ModelRenderer(this, 0, 18);
      this.enginee_2.setRotationPoint(0.0F, 0.0F, -5.0F);
      this.enginee_2.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_2, 0.0F, 0.0F, (float) (-Math.PI / 4));
      this.mechanism = new ModelRenderer(this, 0, 25);
      this.mechanism.setRotationPoint(0.0F, 2.0F, -5.0F);
      this.mechanism.addBox(-2.0F, 0.0F, 0.0F, 4, 3, 4, 0.0F);
      this.brasstube_2 = new ModelRenderer(this, 16, 32);
      this.brasstube_2.setRotationPoint(-2.0F, 6.0F, -13.2F);
      this.brasstube_2.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.brasstube_2, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.brasstube_5 = new ModelRenderer(this, 17, 32);
      this.brasstube_5.mirror = true;
      this.brasstube_5.setRotationPoint(-0.01F, 0.0F, 5.0F);
      this.brasstube_5.addBox(-0.5F, -1.0F, 0.0F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.brasstube_5, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.plasmatron = new ModelRenderer(this, 18, 38);
      this.plasmatron.setRotationPoint(0.0F, 4.0F, -15.0F);
      this.plasmatron.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 4, 0.0F);
      this.enginee_1 = new ModelRenderer(this, 0, 18);
      this.enginee_1.setRotationPoint(0.0F, 0.0F, -5.0F);
      this.enginee_1.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_1, 0.0F, 0.0F, (float) (Math.PI / 4));
      this.coreGlow = new ModelRenderer(this, 52, 49);
      this.coreGlow.setRotationPoint(0.0F, 4.0F, -11.5F);
      this.coreGlow.addBox(-1.5F, -1.5F, 0.0F, 3, 3, 3, 0.01F);
      this.headshaftcap_1 = new ModelRenderer(this, 0, 38);
      this.headshaftcap_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.headshaftcap_1.addBox(-1.0F, -4.5F, -1.0F, 2, 1, 2, 0.0F);
      this.enginee_4 = new ModelRenderer(this, 0, 18);
      this.enginee_4.setRotationPoint(0.0F, 0.0F, -5.0F);
      this.enginee_4.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.setRotateAngle(this.enginee_4, 0.0F, 0.0F, (float) Math.PI);
      this.headshaftcap = new ModelRenderer(this, 0, 38);
      this.headshaftcap.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.headshaftcap.addBox(-1.0F, -4.5F, -1.0F, 2, 1, 2, 0.0F);
      this.cap = new ModelRenderer(this, 5, 19);
      this.cap.setRotationPoint(0.0F, 0.0F, -2.0F);
      this.cap.addBox(-1.5F, 0.0F, 0.0F, 3, 1, 5, 0.0F);
      this.mechanismGlow = new ModelRenderer(this, 48, 42);
      this.mechanismGlow.setRotationPoint(0.0F, 2.0F, -5.0F);
      this.mechanismGlow.addBox(-2.0F, 0.0F, 0.0F, 4, 3, 4, 0.01F);
      this.grip1 = new ModelRenderer(this, 43, 12);
      this.grip1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.grip1.addBox(0.0F, -0.5F, -0.5F, 1, 2, 3, 0.0F);
      this.brasstube_1 = new ModelRenderer(this, 16, 32);
      this.brasstube_1.setRotationPoint(2.0F, 6.0F, -13.2F);
      this.brasstube_1.addBox(-0.5F, -0.5F, 0.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.brasstube_1, 0.0F, 0.0F, (float) (-Math.PI / 4));
      this.brasstube_6 = new ModelRenderer(this, 16, 32);
      this.brasstube_6.setRotationPoint(0.01F, -0.5F, 2.0F);
      this.brasstube_6.addBox(-0.5F, 0.0F, 0.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.brasstube_6, (float) (-Math.PI / 4), 0.0F, 0.0F);
      this.brasstube_7 = new ModelRenderer(this, 17, 32);
      this.brasstube_7.setRotationPoint(-0.01F, 1.0F, 2.0F);
      this.brasstube_7.addBox(-0.5F, -1.0F, 0.0F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.brasstube_7, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.core = new ModelRenderer(this, 29, 32);
      this.core.setRotationPoint(0.0F, 4.0F, -11.5F);
      this.core.addBox(-1.5F, -1.5F, 0.0F, 3, 3, 3, 0.0F);
      this.brasstube_8 = new ModelRenderer(this, 17, 32);
      this.brasstube_8.setRotationPoint(0.01F, 0.0F, 5.0F);
      this.brasstube_8.addBox(-0.5F, -1.0F, 0.0F, 1, 1, 5, 0.0F);
      this.setRotateAngle(this.brasstube_8, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.shapess3 = new ModelRenderer(this, 36, 24);
      this.shapess3.setRotationPoint(0.0F, 4.0F, 6.5F);
      this.shapess3.addBox(-1.0F, 0.0F, 0.0F, 2, 4, 2, 0.0F);
      this.enginee = new ModelRenderer(this, 0, 18);
      this.enginee.setRotationPoint(0.0F, 0.0F, -5.0F);
      this.enginee.addBox(2.0F, -1.0F, 0.0F, 1, 2, 4, 0.0F);
      this.grip3 = new ModelRenderer(this, 56, 24);
      this.grip3.setRotationPoint(5.0F, 0.0F, 0.0F);
      this.grip3.addBox(0.0F, -0.5F, 0.0F, 1, 2, 2, 0.0F);
      this.head.addChild(this.headshaft_1);
      this.headshaft_2.addChild(this.headshaftcap_2);
      this.brasstube_3.addChild(this.brasstube_4);
      this.head.addChild(this.headshaft);
      this.brasstube_1.addChild(this.brasstube_3);
      this.headshaft_3.addChild(this.headshaftcap_3);
      this.head.addChild(this.headshaft_2);
      this.engineElectric.addChild(this.enginee_3);
      this.engineElectric.addChild(this.enginee_5);
      this.head.addChild(this.headshaft_3);
      this.engineElectric.addChild(this.enginee_2);
      this.brasstube_4.addChild(this.brasstube_5);
      this.engineElectric.addChild(this.enginee_1);
      this.headshaft_1.addChild(this.headshaftcap_1);
      this.engineElectric.addChild(this.enginee_4);
      this.headshaft.addChild(this.headshaftcap);
      this.grip2.addChild(this.grip1);
      this.brasstube_2.addChild(this.brasstube_6);
      this.brasstube_6.addChild(this.brasstube_7);
      this.brasstube_7.addChild(this.brasstube_8);
      this.engineElectric.addChild(this.enginee);
      this.grip2.addChild(this.grip3);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.disableCull();
      this.corpus.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.head.offsetX, this.head.offsetY, this.head.offsetZ);
      GlStateManager.translate(this.head.rotationPointX * f5, this.head.rotationPointY * f5, this.head.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 0.5);
      GlStateManager.translate(-this.head.offsetX, -this.head.offsetY, -this.head.offsetZ);
      GlStateManager.translate(-this.head.rotationPointX * f5, -this.head.rotationPointY * f5, -this.head.rotationPointZ * f5);
      this.head.render(f5);
      GlStateManager.popMatrix();
      this.shapess1.render(f5);
      this.grip2.render(f5);
      this.shapess2.render(f5);
      this.engineElectric.render(f5);
      this.brasstube.render(f5);
      this.bottom1.render(f5);
      this.bottom2.render(f5);
      this.mechanism.render(f5);
      this.brasstube_2.render(f5);
      this.plasmatron.render(f5);
      this.cap.render(f5);
      this.brasstube_1.render(f5);
      this.core.render(f5);
      this.shapess3.render(f5);
      AbstractMobModel.light(240, false);
      this.plasmatronGlow.render(f5);
      this.coreGlow.render(f5);
      this.mechanismGlow.render(f5);
      this.corpusGlow.render(f5);
      AbstractMobModel.returnlight();
      GlStateManager.enableCull();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
