package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class PlasmaRifleModel extends ModelBase {
   public ModelRenderer shapess1;
   public ModelRenderer shape1;
   public ModelRenderer shape2;
   public ModelRenderer shape3;
   public ModelRenderer shape4;
   public ModelRenderer shape5;
   public ModelRenderer shape6;
   public ModelRenderer shape7;
   public ModelRenderer shape8;
   public ModelRenderer shape9;

   public PlasmaRifleModel() {
      this.textureWidth = 54;
      this.textureHeight = 32;
      this.shape7 = new ModelRenderer(this, 40, 23);
      this.shape7.setRotationPoint(0.0F, -3.0F, 5.7F);
      this.shape7.addBox(-3.0F, -0.8F, -1.0F, 6, 8, 1, 0.0F);
      this.setRotateAngle(this.shape7, -0.59184116F, 0.0F, 0.0F);
      this.shape9 = new ModelRenderer(this, 32, 4);
      this.shape9.setRotationPoint(0.0F, 1.2F, -4.5F);
      this.shape9.addBox(-2.0F, -1.8F, -1.0F, 4, 9, 5, 0.0F);
      this.setRotateAngle(this.shape9, -0.22759093F, 0.0F, 0.0F);
      this.shape5 = new ModelRenderer(this, 32, 18);
      this.shape5.setRotationPoint(0.0F, -2.8F, 6.7F);
      this.shape5.addBox(-1.5F, -0.9F, -1.0F, 3, 13, 1, 0.0F);
      this.setRotateAngle(this.shape5, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape2 = new ModelRenderer(this, 20, 4);
      this.shape2.mirror = true;
      this.shape2.setRotationPoint(0.0F, -1.7F, 5.5F);
      this.shape2.addBox(-1.8F, -5.5F, 0.0F, 1, 25, 3, 0.0F);
      this.setRotateAngle(this.shape2, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape3 = new ModelRenderer(this, 20, 4);
      this.shape3.setRotationPoint(0.0F, -1.7F, 5.5F);
      this.shape3.addBox(0.8F, -5.5F, 0.0F, 1, 25, 3, 0.0F);
      this.setRotateAngle(this.shape3, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shapess1 = new ModelRenderer(this, 12, 4);
      this.shapess1.setRotationPoint(0.0F, 1.9F, 4.4F);
      this.shapess1.addBox(-1.0F, -0.5F, 0.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.shapess1, 0.5009095F, 0.0F, 0.0F);
      this.shape1 = new ModelRenderer(this, 0, 11);
      this.shape1.setRotationPoint(0.0F, -3.0F, 5.5F);
      this.shape1.addBox(-2.5F, -1.5F, 0.0F, 5, 16, 5, 0.0F);
      this.setRotateAngle(this.shape1, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape4 = new ModelRenderer(this, 28, 11);
      this.shape4.setRotationPoint(0.0F, 0.3F, 5.45F);
      this.shape4.addBox(-0.5F, -1.5F, 0.0F, 1, 20, 1, 0.0F);
      this.setRotateAngle(this.shape4, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape6 = new ModelRenderer(this, 40, 23);
      this.shape6.setRotationPoint(0.0F, -3.0F, 7.9F);
      this.shape6.addBox(-3.0F, -0.8F, -1.0F, 6, 8, 1, 0.0F);
      this.setRotateAngle(this.shape6, -0.59184116F, 0.0F, 0.0F);
      this.shape8 = new ModelRenderer(this, 40, 23);
      this.shape8.setRotationPoint(0.0F, -3.0F, 3.6F);
      this.shape8.addBox(-3.0F, -0.8F, -1.0F, 6, 8, 1, 0.0F);
      this.setRotateAngle(this.shape8, -0.59184116F, 0.0F, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape7.offsetX, this.shape7.offsetY, this.shape7.offsetZ);
      GlStateManager.translate(this.shape7.rotationPointX * f5, this.shape7.rotationPointY * f5, this.shape7.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape7.offsetX, -this.shape7.offsetY, -this.shape7.offsetZ);
      GlStateManager.translate(-this.shape7.rotationPointX * f5, -this.shape7.rotationPointY * f5, -this.shape7.rotationPointZ * f5);
      this.shape7.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape9.offsetX, this.shape9.offsetY, this.shape9.offsetZ);
      GlStateManager.translate(this.shape9.rotationPointX * f5, this.shape9.rotationPointY * f5, this.shape9.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.3, 0.9);
      GlStateManager.translate(-this.shape9.offsetX, -this.shape9.offsetY, -this.shape9.offsetZ);
      GlStateManager.translate(-this.shape9.rotationPointX * f5, -this.shape9.rotationPointY * f5, -this.shape9.rotationPointZ * f5);
      this.shape9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape5.offsetX, this.shape5.offsetY, this.shape5.offsetZ);
      GlStateManager.translate(this.shape5.rotationPointX * f5, this.shape5.rotationPointY * f5, this.shape5.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shape5.offsetX, -this.shape5.offsetY, -this.shape5.offsetZ);
      GlStateManager.translate(-this.shape5.rotationPointX * f5, -this.shape5.rotationPointY * f5, -this.shape5.rotationPointZ * f5);
      this.shape5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1.offsetX, this.shapess1.offsetY, this.shapess1.offsetZ);
      GlStateManager.translate(this.shapess1.rotationPointX * f5, this.shapess1.rotationPointY * f5, this.shapess1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shapess1.offsetX, -this.shapess1.offsetY, -this.shapess1.offsetZ);
      GlStateManager.translate(-this.shapess1.rotationPointX * f5, -this.shapess1.rotationPointY * f5, -this.shapess1.rotationPointZ * f5);
      this.shapess1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1.offsetX, this.shape1.offsetY, this.shape1.offsetZ);
      GlStateManager.translate(this.shape1.rotationPointX * f5, this.shape1.rotationPointY * f5, this.shape1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shape1.offsetX, -this.shape1.offsetY, -this.shape1.offsetZ);
      GlStateManager.translate(-this.shape1.rotationPointX * f5, -this.shape1.rotationPointY * f5, -this.shape1.rotationPointZ * f5);
      this.shape1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape6.offsetX, this.shape6.offsetY, this.shape6.offsetZ);
      GlStateManager.translate(this.shape6.rotationPointX * f5, this.shape6.rotationPointY * f5, this.shape6.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape6.offsetX, -this.shape6.offsetY, -this.shape6.offsetZ);
      GlStateManager.translate(-this.shape6.rotationPointX * f5, -this.shape6.rotationPointY * f5, -this.shape6.rotationPointZ * f5);
      this.shape6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape8.offsetX, this.shape8.offsetY, this.shape8.offsetZ);
      GlStateManager.translate(this.shape8.rotationPointX * f5, this.shape8.rotationPointY * f5, this.shape8.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape8.offsetX, -this.shape8.offsetY, -this.shape8.offsetZ);
      GlStateManager.translate(-this.shape8.rotationPointX * f5, -this.shape8.rotationPointY * f5, -this.shape8.rotationPointZ * f5);
      this.shape8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 150.0F, 150.0F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape2.offsetX, this.shape2.offsetY, this.shape2.offsetZ);
      GlStateManager.translate(this.shape2.rotationPointX * f5, this.shape2.rotationPointY * f5, this.shape2.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shape2.offsetX, -this.shape2.offsetY, -this.shape2.offsetZ);
      GlStateManager.translate(-this.shape2.rotationPointX * f5, -this.shape2.rotationPointY * f5, -this.shape2.rotationPointZ * f5);
      this.shape2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape3.offsetX, this.shape3.offsetY, this.shape3.offsetZ);
      GlStateManager.translate(this.shape3.rotationPointX * f5, this.shape3.rotationPointY * f5, this.shape3.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shape3.offsetX, -this.shape3.offsetY, -this.shape3.offsetZ);
      GlStateManager.translate(-this.shape3.rotationPointX * f5, -this.shape3.rotationPointY * f5, -this.shape3.rotationPointZ * f5);
      this.shape3.render(f5);
      GlStateManager.popMatrix();
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0F, 240.0F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape4.offsetX, this.shape4.offsetY, this.shape4.offsetZ);
      GlStateManager.translate(this.shape4.rotationPointX * f5, this.shape4.rotationPointY * f5, this.shape4.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shape4.offsetX, -this.shape4.offsetY, -this.shape4.offsetZ);
      GlStateManager.translate(-this.shape4.rotationPointX * f5, -this.shape4.rotationPointY * f5, -this.shape4.rotationPointZ * f5);
      this.shape4.render(f5);
      GlStateManager.popMatrix();
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
