package com.vivern.arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class PlasmaPistolModel extends ModelBase {
   public ModelRenderer shapess1;
   public ModelRenderer shape;
   public ModelRenderer shape_1;
   public ModelRenderer shape_2;
   public ModelRenderer shape_3;
   public ModelRenderer shape_4;
   public ModelRenderer shape_5;
   public ModelRenderer shape_6;
   public ModelRenderer shape_7;
   public ModelRenderer shape_8;
   public ModelRenderer shape_9;
   public ModelRenderer shape_10;
   public ModelRenderer shape_11;

   public PlasmaPistolModel() {
      this.textureWidth = 18;
      this.textureHeight = 16;
      this.shape_10 = new ModelRenderer(this, 0, 11);
      this.shape_10.setRotationPoint(0.0F, 6.5F, 4.9F);
      this.shape_10.addBox(-0.5F, -1.0F, -1.0F, 1, 1, 4, 0.0F);
      this.shape = new ModelRenderer(this, 0, 0);
      this.shape.setRotationPoint(0.0F, 0.2F, 5.0F);
      this.shape.addBox(-1.0F, -1.0F, 0.0F, 2, 3, 1, 0.0F);
      this.shape_6 = new ModelRenderer(this, 0, 4);
      this.shape_6.setRotationPoint(0.0F, 0.5F, 0.0F);
      this.shape_6.addBox(-1.0F, -1.0F, -2.0F, 2, 2, 2, 0.0F);
      this.shape_7 = new ModelRenderer(this, 14, 3);
      this.shape_7.setRotationPoint(0.0F, 1.9F, 5.0F);
      this.shape_7.addBox(-0.5F, 0.0F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape_7, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape_3 = new ModelRenderer(this, 12, 13);
      this.shape_3.setRotationPoint(0.0F, 0.4F, 3.0F);
      this.shape_3.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shapess1 = new ModelRenderer(this, 0, 10);
      this.shapess1.setRotationPoint(0.0F, 2.5F, 4.5F);
      this.shapess1.addBox(-0.5F, -0.7F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shapess1, 0.18203785F, 0.0F, 0.0F);
      this.shape_4 = new ModelRenderer(this, 12, 13);
      this.shape_4.setRotationPoint(0.0F, 0.4F, 1.8F);
      this.shape_4.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shape_11 = new ModelRenderer(this, 0, 11);
      this.shape_11.setRotationPoint(0.0F, 7.2F, 3.9F);
      this.shape_11.addBox(-0.5F, -1.0F, -1.0F, 1, 1, 4, 0.0F);
      this.shape_9 = new ModelRenderer(this, 5, 7);
      this.shape_9.setRotationPoint(0.0F, -1.0F, -0.6F);
      this.shape_9.addBox(-0.5F, -1.0F, -1.0F, 1, 1, 3, 0.0F);
      this.shape_1 = new ModelRenderer(this, 10, 3);
      this.shape_1.setRotationPoint(0.0F, 0.4F, 5.0F);
      this.shape_1.addBox(-0.5F, 0.0F, -0.5F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.shape_1, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shape_8 = new ModelRenderer(this, 12, 0);
      this.shape_8.setRotationPoint(0.0F, 0.5F, -2.0F);
      this.shape_8.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 1, 0.0F);
      this.shape_5 = new ModelRenderer(this, 12, 13);
      this.shape_5.setRotationPoint(0.0F, 0.4F, 0.6F);
      this.shape_5.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shape_2 = new ModelRenderer(this, 6, 0);
      this.shape_2.setRotationPoint(0.0F, 0.5F, 6.0F);
      this.shape_2.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 1, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_10.offsetX, this.shape_10.offsetY, this.shape_10.offsetZ);
      GlStateManager.translate(this.shape_10.rotationPointX * f5, this.shape_10.rotationPointY * f5, this.shape_10.rotationPointZ * f5);
      GlStateManager.scale(1.1, 0.6, 0.7);
      GlStateManager.translate(-this.shape_10.offsetX, -this.shape_10.offsetY, -this.shape_10.offsetZ);
      GlStateManager.translate(-this.shape_10.rotationPointX * f5, -this.shape_10.rotationPointY * f5, -this.shape_10.rotationPointZ * f5);
      this.shape_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape.offsetX, this.shape.offsetY, this.shape.offsetZ);
      GlStateManager.translate(this.shape.rotationPointX * f5, this.shape.rotationPointY * f5, this.shape.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.0, 1.1);
      GlStateManager.translate(-this.shape.offsetX, -this.shape.offsetY, -this.shape.offsetZ);
      GlStateManager.translate(-this.shape.rotationPointX * f5, -this.shape.rotationPointY * f5, -this.shape.rotationPointZ * f5);
      this.shape.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_7.offsetX, this.shape_7.offsetY, this.shape_7.offsetZ);
      GlStateManager.translate(this.shape_7.rotationPointX * f5, this.shape_7.rotationPointY * f5, this.shape_7.rotationPointZ * f5);
      GlStateManager.scale(1.1, 0.6, 0.85);
      GlStateManager.translate(-this.shape_7.offsetX, -this.shape_7.offsetY, -this.shape_7.offsetZ);
      GlStateManager.translate(-this.shape_7.rotationPointX * f5, -this.shape_7.rotationPointY * f5, -this.shape_7.rotationPointZ * f5);
      this.shape_7.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_3.offsetX, this.shape_3.offsetY, this.shape_3.offsetZ);
      GlStateManager.translate(this.shape_3.rotationPointX * f5, this.shape_3.rotationPointY * f5, this.shape_3.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.8);
      GlStateManager.translate(-this.shape_3.offsetX, -this.shape_3.offsetY, -this.shape_3.offsetZ);
      GlStateManager.translate(-this.shape_3.rotationPointX * f5, -this.shape_3.rotationPointY * f5, -this.shape_3.rotationPointZ * f5);
      this.shape_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1.offsetX, this.shapess1.offsetY, this.shapess1.offsetZ);
      GlStateManager.translate(this.shapess1.rotationPointX * f5, this.shapess1.rotationPointY * f5, this.shapess1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 1.2);
      GlStateManager.translate(-this.shapess1.offsetX, -this.shapess1.offsetY, -this.shapess1.offsetZ);
      GlStateManager.translate(-this.shapess1.rotationPointX * f5, -this.shapess1.rotationPointY * f5, -this.shapess1.rotationPointZ * f5);
      this.shapess1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_4.offsetX, this.shape_4.offsetY, this.shape_4.offsetZ);
      GlStateManager.translate(this.shape_4.rotationPointX * f5, this.shape_4.rotationPointY * f5, this.shape_4.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.8);
      GlStateManager.translate(-this.shape_4.offsetX, -this.shape_4.offsetY, -this.shape_4.offsetZ);
      GlStateManager.translate(-this.shape_4.rotationPointX * f5, -this.shape_4.rotationPointY * f5, -this.shape_4.rotationPointZ * f5);
      this.shape_4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_11.offsetX, this.shape_11.offsetY, this.shape_11.offsetZ);
      GlStateManager.translate(this.shape_11.rotationPointX * f5, this.shape_11.rotationPointY * f5, this.shape_11.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.5, 0.6);
      GlStateManager.translate(-this.shape_11.offsetX, -this.shape_11.offsetY, -this.shape_11.offsetZ);
      GlStateManager.translate(-this.shape_11.rotationPointX * f5, -this.shape_11.rotationPointY * f5, -this.shape_11.rotationPointZ * f5);
      this.shape_11.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_9.offsetX, this.shape_9.offsetY, this.shape_9.offsetZ);
      GlStateManager.translate(this.shape_9.rotationPointX * f5, this.shape_9.rotationPointY * f5, this.shape_9.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.6, 0.7);
      GlStateManager.translate(-this.shape_9.offsetX, -this.shape_9.offsetY, -this.shape_9.offsetZ);
      GlStateManager.translate(-this.shape_9.rotationPointX * f5, -this.shape_9.rotationPointY * f5, -this.shape_9.rotationPointZ * f5);
      this.shape_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_8.offsetX, this.shape_8.offsetY, this.shape_8.offsetZ);
      GlStateManager.translate(this.shape_8.rotationPointX * f5, this.shape_8.rotationPointY * f5, this.shape_8.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 1.0);
      GlStateManager.translate(-this.shape_8.offsetX, -this.shape_8.offsetY, -this.shape_8.offsetZ);
      GlStateManager.translate(-this.shape_8.rotationPointX * f5, -this.shape_8.rotationPointY * f5, -this.shape_8.rotationPointZ * f5);
      this.shape_8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_5.offsetX, this.shape_5.offsetY, this.shape_5.offsetZ);
      GlStateManager.translate(this.shape_5.rotationPointX * f5, this.shape_5.rotationPointY * f5, this.shape_5.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.8);
      GlStateManager.translate(-this.shape_5.offsetX, -this.shape_5.offsetY, -this.shape_5.offsetZ);
      GlStateManager.translate(-this.shape_5.rotationPointX * f5, -this.shape_5.rotationPointY * f5, -this.shape_5.rotationPointZ * f5);
      this.shape_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_2.offsetX, this.shape_2.offsetY, this.shape_2.offsetZ);
      GlStateManager.translate(this.shape_2.rotationPointX * f5, this.shape_2.rotationPointY * f5, this.shape_2.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 1.0);
      GlStateManager.translate(-this.shape_2.offsetX, -this.shape_2.offsetY, -this.shape_2.offsetZ);
      GlStateManager.translate(-this.shape_2.rotationPointX * f5, -this.shape_2.rotationPointY * f5, -this.shape_2.rotationPointZ * f5);
      this.shape_2.render(f5);
      GlStateManager.popMatrix();
      float lbX = OpenGlHelper.lastBrightnessX;
      float lbY = OpenGlHelper.lastBrightnessY;
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, Math.min(240.0F, 150.0F + lbX), Math.min(240.0F, 150.0F + lbY));
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_1.offsetX, this.shape_1.offsetY, this.shape_1.offsetZ);
      GlStateManager.translate(this.shape_1.rotationPointX * f5, this.shape_1.rotationPointY * f5, this.shape_1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape_1.offsetX, -this.shape_1.offsetY, -this.shape_1.offsetZ);
      GlStateManager.translate(-this.shape_1.rotationPointX * f5, -this.shape_1.rotationPointY * f5, -this.shape_1.rotationPointZ * f5);
      this.shape_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_6.offsetX, this.shape_6.offsetY, this.shape_6.offsetZ);
      GlStateManager.translate(this.shape_6.rotationPointX * f5, this.shape_6.rotationPointY * f5, this.shape_6.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.1, 1.1);
      GlStateManager.translate(-this.shape_6.offsetX, -this.shape_6.offsetY, -this.shape_6.offsetZ);
      GlStateManager.translate(-this.shape_6.rotationPointX * f5, -this.shape_6.rotationPointY * f5, -this.shape_6.rotationPointZ * f5);
      this.shape_6.render(f5);
      GlStateManager.popMatrix();
      GL11.glEnable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, lbX, lbY);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
