package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.GetMOP;
import com.Vivern.Arpg.renders.ModelRendererGlow;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class PlasmaMinigunModel extends ModelBase {
   public ModelRenderer shapess1;
   public ModelRenderer shapess3;
   public ModelRenderer shape1;
   public ModelRenderer shapess4;
   public ModelRenderer shape2;
   public ModelRenderer shapess5;
   public ModelRenderer shape32;
   public ModelRenderer shape33;
   public ModelRenderer ammo;
   public ModelRenderer shape3_a;
   public ModelRenderer shape3_b;
   public ModelRenderer shape_s_1;
   public ModelRenderer shape_s_3;
   public ModelRenderer shape_r_1;
   public ModelRenderer barrel_1_a;
   public ModelRenderer barrel_1_b;
   public ModelRenderer barrel_1_c;
   public ModelRenderer shape_r_3;
   public ModelRenderer barrel_3_a;
   public ModelRenderer barrel_3_b;
   public ModelRenderer barrel_3_c;
   public ModelRenderer shape_s_2;
   public ModelRenderer shape_s_4;
   public ModelRenderer shape_r_2;
   public ModelRenderer barrel_2_a;
   public ModelRenderer barrel_2_b;
   public ModelRenderer barrel_2_c;
   public ModelRenderer shape_r_4;
   public ModelRenderer barrel_4_a;
   public ModelRenderer barrel_4_b;
   public ModelRenderer barrel_4_c;
   public ModelRenderer shapess6;
   public ModelRenderer bullet1;
   public ModelRenderer bullet2;
   public ModelRenderer bullet3;

   public PlasmaMinigunModel() {
      int lowlight = 40;
      int biglight = 125;
      int bulletlight = 80;
      this.textureWidth = 36;
      this.textureHeight = 24;
      this.bullet2 = new ModelRendererGlow(this, 0, 3, bulletlight, true);
      this.bullet2.setRotationPoint(-0.9F, -0.8F, 0.7F);
      this.bullet2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.bullet2, 0.0F, 0.0F, -1.0016445F);
      this.barrel_3_a = new ModelRenderer(this, 10, 0);
      this.barrel_3_a.setRotationPoint(-0.5F, -0.5F, -1.0F);
      this.barrel_3_a.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_3_a, 0.0F, 0.0F, 0.045553092F);
      this.shapess5 = new ModelRenderer(this, 30, 13);
      this.shapess5.setRotationPoint(5.0F, 0.5F, 4.0F);
      this.shapess5.addBox(0.0F, 0.0F, -1.0F, 1, 5, 2, 0.0F);
      this.shape2 = new ModelRenderer(this, 10, 13);
      this.shape2.setRotationPoint(2.5F, 2.5F, 0.0F);
      this.shape2.addBox(-1.5F, -1.5F, -1.0F, 3, 3, 1, 0.0F);
      this.shape_s_3 = new ModelRendererGlow(this, 0, 11, lowlight, true);
      this.shape_s_3.setRotationPoint(0.6F, 1.1F, -2.0F);
      this.shape_s_3.addBox(-3.0F, -0.8F, -2.0F, 2, 2, 3, 0.0F);
      this.bullet1 = new ModelRendererGlow(this, 0, 3, bulletlight, true);
      this.bullet1.setRotationPoint(-0.2F, -0.5F, 0.6F);
      this.bullet1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.bullet1, 0.0F, 0.0F, -0.5462881F);
      this.shape_r_4 = new ModelRenderer(this, 0, 0);
      this.shape_r_4.setRotationPoint(2.0F, 0.0F, -2.0F);
      this.shape_r_4.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 1, 0.0F);
      this.setRotateAngle(this.shape_r_4, 0.0F, 0.0F, (float) (Math.PI * 2.0 / 3.0));
      this.barrel_3_c = new ModelRenderer(this, 10, 0);
      this.barrel_3_c.setRotationPoint(-0.1F, 1.0F, -1.0F);
      this.barrel_3_c.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_3_c, 0.0F, 0.0F, -0.5462881F);
      this.shape1 = new ModelRenderer(this, 0, 0);
      this.shape1.setRotationPoint(-2.5F, 7.5F, 3.0F);
      this.shape1.addBox(0.0F, 0.0F, 0.0F, 5, 5, 6, 0.0F);
      this.shape32 = new ModelRendererGlow(this, 24, 7, biglight, true);
      this.shape32.setRotationPoint(1.0F, 1.0F, 7.0F);
      this.shape32.addBox(0.0F, 0.0F, 0.0F, 3, 4, 1, 0.0F);
      this.shape_s_4 = new ModelRendererGlow(this, 0, 11, lowlight, true);
      this.shape_s_4.setRotationPoint(-0.6F, 1.1F, -2.0F);
      this.shape_s_4.addBox(1.0F, -0.8F, -2.0F, 2, 2, 3, 0.0F);
      this.shape_r_1 = new ModelRenderer(this, 0, 0);
      this.shape_r_1.setRotationPoint(-1.0F, -2.3F, -2.0F);
      this.shape_r_1.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 1, 0.0F);
      this.setRotateAngle(this.shape_r_1, 0.0F, 0.0F, (float) (-Math.PI / 3));
      this.shapess6 = new ModelRenderer(this, 24, 16);
      this.shapess6.setRotationPoint(-0.5F, 5.0F, 0.0F);
      this.shapess6.addBox(0.0F, 0.0F, -2.0F, 1, 1, 4, 0.0F);
      this.barrel_2_b = new ModelRenderer(this, 10, 0);
      this.barrel_2_b.setRotationPoint(1.0F, -0.1F, -1.0F);
      this.barrel_2_b.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_2_b, 0.0F, 0.0F, 0.5462881F);
      this.bullet3 = new ModelRendererGlow(this, 0, 3, bulletlight, true);
      this.bullet3.setRotationPoint(-1.7F, -0.7F, 0.8F);
      this.bullet3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 2, 0.0F);
      this.setRotateAngle(this.bullet3, 0.0F, 0.0F, -1.5025539F);
      this.shape_r_2 = new ModelRenderer(this, 0, 0);
      this.shape_r_2.setRotationPoint(1.0F, -2.3F, -2.0F);
      this.shape_r_2.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 1, 0.0F);
      this.setRotateAngle(this.shape_r_2, 0.0F, 0.0F, (float) (Math.PI * 5.0 / 6.0));
      this.shape33 = new ModelRendererGlow(this, 30, 0, biglight, true);
      this.shape33.setRotationPoint(1.5F, 2.0F, 8.5F);
      this.shape33.addBox(0.0F, 0.0F, 0.0F, 2, 3, 1, 0.0F);
      this.shapess1 = new ModelRenderer(this, 24, 0);
      this.shapess1.setRotationPoint(0.0F, 2.0F, 4.5F);
      this.shapess1.addBox(-0.5F, 1.3F, 1.0F, 1, 5, 2, 0.0F);
      this.setRotateAngle(this.shapess1, 0.18203785F, 0.0F, 0.0F);
      this.barrel_3_b = new ModelRenderer(this, 10, 0);
      this.barrel_3_b.setRotationPoint(1.0F, -0.1F, -1.0F);
      this.barrel_3_b.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_3_b, 0.0F, 0.0F, 0.5462881F);
      this.shape3_a = new ModelRenderer(this, 0, 16);
      this.shape3_a.setRotationPoint(0.0F, 0.0F, -1.0F);
      this.shape3_a.addBox(-2.0F, -2.0F, -2.0F, 2, 4, 2, 0.0F);
      this.barrel_2_c = new ModelRenderer(this, 10, 0);
      this.barrel_2_c.setRotationPoint(-0.1F, 1.0F, -1.0F);
      this.barrel_2_c.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_2_c, 0.0F, 0.0F, -0.5462881F);
      this.shapess4 = new ModelRenderer(this, 18, 21);
      this.shapess4.setRotationPoint(0.0F, 7.0F, 7.0F);
      this.shapess4.addBox(-0.5F, 0.0F, -1.0F, 4, 1, 2, 0.0F);
      this.barrel_2_a = new ModelRenderer(this, 10, 0);
      this.barrel_2_a.setRotationPoint(-0.5F, -0.5F, -1.0F);
      this.barrel_2_a.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_2_a, 0.0F, 0.0F, 0.045553092F);
      this.shape3_b = new ModelRenderer(this, 0, 16);
      this.shape3_b.setRotationPoint(0.0F, 0.0F, -1.0F);
      this.shape3_b.addBox(0.0F, -2.0F, -2.0F, 2, 4, 2, 0.0F);
      this.barrel_1_a = new ModelRenderer(this, 10, 0);
      this.barrel_1_a.setRotationPoint(-0.5F, -0.5F, -1.0F);
      this.barrel_1_a.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_1_a, 0.0F, 0.0F, 0.045553092F);
      this.barrel_1_c = new ModelRenderer(this, 10, 0);
      this.barrel_1_c.setRotationPoint(-0.1F, 1.0F, -1.0F);
      this.barrel_1_c.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_1_c, 0.0F, 0.0F, -0.5462881F);
      this.shapess3 = new ModelRenderer(this, 15, 13);
      this.shapess3.setRotationPoint(0.0F, 2.5F, 7.25F);
      this.shapess3.addBox(-0.5F, 0.0F, -2.0F, 1, 1, 5, 0.0F);
      this.barrel_1_b = new ModelRenderer(this, 10, 0);
      this.barrel_1_b.setRotationPoint(1.0F, -0.1F, -1.0F);
      this.barrel_1_b.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_1_b, 0.0F, 0.0F, 0.5462881F);
      this.shape_s_1 = new ModelRendererGlow(this, 0, 11, lowlight, true);
      this.shape_s_1.setRotationPoint(-0.4F, 1.1F, -2.0F);
      this.shape_s_1.addBox(-2.0F, -3.5F, -2.0F, 2, 2, 3, 0.0F);
      this.barrel_4_c = new ModelRenderer(this, 10, 0);
      this.barrel_4_c.setRotationPoint(-0.1F, 1.0F, -1.0F);
      this.barrel_4_c.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_4_c, 0.0F, 0.0F, -0.5462881F);
      this.barrel_4_a = new ModelRenderer(this, 10, 0);
      this.barrel_4_a.setRotationPoint(-0.5F, -0.5F, -1.0F);
      this.barrel_4_a.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_4_a, 0.0F, 0.0F, 0.045553092F);
      this.shape_r_3 = new ModelRenderer(this, 0, 0);
      this.shape_r_3.setRotationPoint(-2.0F, 0.0F, -2.0F);
      this.shape_r_3.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 1, 0.0F);
      this.setRotateAngle(this.shape_r_3, 0.0F, 0.0F, (float) (-Math.PI / 6));
      this.ammo = new ModelRendererGlow(this, 8, 17, lowlight, true);
      this.ammo.setRotationPoint(6.0F, 1.4F, -0.5F);
      this.ammo.addBox(0.0F, 0.0F, 0.0F, 2, 3, 3, 0.0F);
      this.shape_s_2 = new ModelRendererGlow(this, 0, 11, lowlight, true);
      this.shape_s_2.setRotationPoint(0.4F, 1.1F, -2.0F);
      this.shape_s_2.addBox(0.0F, -3.5F, -2.0F, 2, 2, 3, 0.0F);
      this.barrel_4_b = new ModelRenderer(this, 10, 0);
      this.barrel_4_b.setRotationPoint(1.0F, -0.1F, -1.0F);
      this.barrel_4_b.addBox(-0.5F, -0.5F, -12.0F, 1, 1, 12, 0.0F);
      this.setRotateAngle(this.barrel_4_b, 0.0F, 0.0F, 0.5462881F);
      this.ammo.addChild(this.bullet2);
      this.shape_r_3.addChild(this.barrel_3_a);
      this.shape1.addChild(this.shapess5);
      this.shape1.addChild(this.shape2);
      this.shape3_a.addChild(this.shape_s_3);
      this.ammo.addChild(this.bullet1);
      this.shape_s_4.addChild(this.shape_r_4);
      this.shape_r_3.addChild(this.barrel_3_c);
      this.shape1.addChild(this.shape32);
      this.shape3_b.addChild(this.shape_s_4);
      this.shape_s_1.addChild(this.shape_r_1);
      this.shapess5.addChild(this.shapess6);
      this.shape_r_2.addChild(this.barrel_2_b);
      this.ammo.addChild(this.bullet3);
      this.shape_s_2.addChild(this.shape_r_2);
      this.shape1.addChild(this.shape33);
      this.shape_r_3.addChild(this.barrel_3_b);
      this.shape2.addChild(this.shape3_a);
      this.shape_r_2.addChild(this.barrel_2_c);
      this.shape_r_2.addChild(this.barrel_2_a);
      this.shape2.addChild(this.shape3_b);
      this.shape_r_1.addChild(this.barrel_1_a);
      this.shape_r_1.addChild(this.barrel_1_c);
      this.shape_r_1.addChild(this.barrel_1_b);
      this.shape3_a.addChild(this.shape_s_1);
      this.shape_r_4.addChild(this.barrel_4_c);
      this.shape_r_4.addChild(this.barrel_4_a);
      this.shape_s_3.addChild(this.shape_r_3);
      this.shape1.addChild(this.ammo);
      this.shape3_b.addChild(this.shape_s_2);
      this.shape_r_4.addChild(this.barrel_4_b);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.shape1.offsetX = 6.0F * GetMOP.getfromto(f1, 0.0F, 0.3F);
      this.shape3_a.offsetX = -1.5F * GetMOP.getfromto(f1, 0.3F, 0.5F);
      this.shape3_b.offsetX = 1.5F * GetMOP.getfromto(f1, 0.3F, 0.5F);
      this.shape_s_1.rotateAngleZ = -0.5F * GetMOP.getfromto(f1, 0.5F, 0.65F);
      this.shape_s_2.rotateAngleZ = 0.5F * GetMOP.getfromto(f1, 0.5F, 0.65F);
      this.shape_s_3.rotateAngleZ = -0.91F * GetMOP.getfromto(f1, 0.65F, 0.8F);
      this.shape_s_4.rotateAngleZ = 0.91F * GetMOP.getfromto(f1, 0.65F, 0.8F);
      this.shapess5.rotateAngleZ = -2.0F * GetMOP.getfromto(f1, 0.5F, 1.0F);
      float wdf2 = MathHelper.wrapDegrees(f2);
      float ft1 = GetMOP.getfromto(f1, 0.8F, 1.0F);
      float mult = 0.027453F + 0.03F * f1;
      this.shape2.rotateAngleZ = wdf2 * mult * (1.0F - GetMOP.getfromto(f1, 0.0F, 0.3F));
      this.shape_r_1.rotateAngleZ = wdf2 * mult * ft1 - (float) (Math.PI / 3);
      this.shape_r_2.rotateAngleZ = -wdf2 * mult * ft1 + (float) (Math.PI * 5.0 / 6.0);
      this.shape_r_3.rotateAngleZ = -wdf2 * mult * ft1 - (float) (Math.PI / 6);
      this.shape_r_4.rotateAngleZ = wdf2 * mult * ft1 + (float) (Math.PI * 2.0 / 3.0);
      boolean hidden = f3 == 0.0F;
      this.shapess1.isHidden = hidden;
      this.shapess3.isHidden = hidden;
      this.shapess4.isHidden = hidden;
      this.shapess5.isHidden = hidden;
      this.shapess6.isHidden = hidden;
      this.shape32.isHidden = hidden;
      this.shape33.isHidden = hidden;
      this.ammo.isHidden = hidden;
      this.bullet1.isHidden = hidden;
      this.bullet2.isHidden = hidden;
      this.bullet3.isHidden = hidden;
      this.shape1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1.offsetX, this.shapess1.offsetY, this.shapess1.offsetZ);
      GlStateManager.translate(this.shapess1.rotationPointX * f5, this.shapess1.rotationPointY * f5, this.shapess1.rotationPointZ * f5);
      GlStateManager.scale(1.1, 1.0, 1.0);
      GlStateManager.translate(-this.shapess1.offsetX, -this.shapess1.offsetY, -this.shapess1.offsetZ);
      GlStateManager.translate(-this.shapess1.rotationPointX * f5, -this.shapess1.rotationPointY * f5, -this.shapess1.rotationPointZ * f5);
      this.shapess1.render(f5);
      GlStateManager.popMatrix();
      this.shapess4.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess3.offsetX, this.shapess3.offsetY, this.shapess3.offsetZ);
      GlStateManager.translate(this.shapess3.rotationPointX * f5, this.shapess3.rotationPointY * f5, this.shapess3.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.0, 1.0);
      GlStateManager.translate(-this.shapess3.offsetX, -this.shapess3.offsetY, -this.shapess3.offsetZ);
      GlStateManager.translate(-this.shapess3.rotationPointX * f5, -this.shapess3.rotationPointY * f5, -this.shapess3.rotationPointZ * f5);
      this.shapess3.render(f5);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
