package com.vivern.arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class PlasmaAcceleratorModel extends ModelBase {
   public ModelRenderer shapessh;
   public ModelRenderer shape;
   public ModelRenderer shape7;
   public ModelRenderer shape8;
   public ModelRenderer glass;
   public ModelRenderer core;
   public ModelRenderer shape_1;
   public ModelRenderer manip1;
   public ModelRenderer shape4;
   public ModelRenderer shape3;
   public ModelRenderer shape6;
   public ModelRenderer shape5;
   public ModelRenderer shape2;
   public ModelRenderer shapelev1;
   public ModelRenderer shapelev2;
   public ModelRenderer shapelev3;
   public ModelRenderer shapeprav1;
   public ModelRenderer shapeprav2;
   public ModelRenderer shapeprav3;
   public ModelRenderer manip2;
   public ModelRenderer manip3;
   public ModelRenderer display;
   public ModelRenderer lamp1;
   public ModelRenderer lamp2;
   public ModelRenderer lamp3;
   public ModelRenderer manipbig1;
   public ModelRenderer manipbig2;
   public ModelRenderer manipbig3;

   public PlasmaAcceleratorModel() {
      this.textureWidth = 30;
      this.textureHeight = 32;
      this.lamp1 = new ModelRenderer(this, 8, 0);
      this.lamp1.setRotationPoint(0.0F, -4.1F, 4.11F);
      this.lamp1.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.manipbig2 = new ModelRenderer(this, 5, 11);
      this.manipbig2.setRotationPoint(0.0F, 3.7F, 0.0F);
      this.manipbig2.addBox(-1.5F, 0.0F, -0.5F, 3, 6, 1, 0.0F);
      this.setRotateAngle(this.manipbig2, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.shape8 = new ModelRenderer(this, 0, 26);
      this.shape8.setRotationPoint(0.0F, -1.0F, 0.5F);
      this.shape8.addBox(-2.0F, -1.5F, 0.0F, 4, 5, 1, 0.0F);
      this.setRotateAngle(this.shape8, 0.0F, (float) Math.PI, 0.0F);
      this.lamp2 = new ModelRenderer(this, 8, 0);
      this.lamp2.setRotationPoint(0.92F, -2.7F, 4.11F);
      this.lamp2.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.shapeprav1 = new ModelRenderer(this, 0, 6);
      this.shapeprav1.mirror = true;
      this.shapeprav1.setRotationPoint(0.0F, -1.0F, 9.0F);
      this.shapeprav1.addBox(-3.1F, -1.0F, 0.0F, 1, 3, 2, 0.0F);
      this.core = new ModelRenderer(this, 0, 16);
      this.core.setRotationPoint(0.0F, 0.0F, -5.7F);
      this.core.addBox(-0.5F, 0.0F, -0.5F, 1, 6, 1, 0.0F);
      this.setRotateAngle(this.core, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape5 = new ModelRenderer(this, 13, 0);
      this.shape5.setRotationPoint(-0.9F, 3.0F, -1.9F);
      this.shape5.addBox(-0.5F, 0.0F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape5, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shapessh = new ModelRenderer(this, 11, 16);
      this.shapessh.setRotationPoint(0.0F, 2.0F, 4.5F);
      this.shapessh.addBox(-0.5F, -0.5F, 0.0F, 1, 5, 2, 0.0F);
      this.setRotateAngle(this.shapessh, 0.27314404F, 0.0F, 0.0F);
      this.manip1 = new ModelRenderer(this, 13, 11);
      this.manip1.setRotationPoint(0.0F, 0.0F, -2.7F);
      this.manip1.addBox(-0.5F, 0.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.manip1, -2.3675392F, 0.0F, 0.0F);
      this.manip3 = new ModelRenderer(this, 13, 11);
      this.manip3.setRotationPoint(0.0F, 0.0F, -2.7F);
      this.manip3.addBox(-0.5F, 0.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.manip3, -2.3675392F, 0.0F, (float) (-Math.PI * 2.0 / 3.0));
      this.shape4 = new ModelRenderer(this, 13, 0);
      this.shape4.setRotationPoint(0.9F, 1.0F, -3.5F);
      this.shape4.addBox(-0.52F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape4, 0.7740535F, 0.0F, 0.0F);
      this.manipbig1 = new ModelRenderer(this, 5, 11);
      this.manipbig1.setRotationPoint(0.0F, 3.7F, 0.0F);
      this.manipbig1.addBox(-1.5F, 0.0F, -0.5F, 3, 6, 1, 0.0F);
      this.setRotateAngle(this.manipbig1, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.shape6 = new ModelRenderer(this, 13, 0);
      this.shape6.setRotationPoint(-0.9F, 1.0F, -3.5F);
      this.shape6.addBox(-0.48F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape6, 0.7740535F, 0.0F, 0.0F);
      this.shapelev3 = new ModelRenderer(this, 9, 7);
      this.shapelev3.setRotationPoint(0.0F, -1.0F, 15.0F);
      this.shapelev3.addBox(1.9F, -1.0F, 0.0F, 1, 1, 2, 0.0F);
      this.display = new ModelRenderer(this, 0, 0);
      this.display.setRotationPoint(0.0F, -4.2F, 4.1F);
      this.display.addBox(-1.5F, 0.0F, -0.5F, 3, 3, 1, 0.0F);
      this.shapelev2 = new ModelRenderer(this, 9, 7);
      this.shapelev2.setRotationPoint(0.0F, -1.0F, 12.0F);
      this.shapelev2.addBox(2.0F, -1.0F, 0.0F, 1, 2, 2, 0.0F);
      this.lamp3 = new ModelRenderer(this, 8, 0);
      this.lamp3.setRotationPoint(-0.92F, -2.7F, 4.11F);
      this.lamp3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.manipbig3 = new ModelRenderer(this, 5, 11);
      this.manipbig3.setRotationPoint(0.0F, 3.7F, 0.0F);
      this.manipbig3.addBox(-1.5F, 0.0F, -0.5F, 3, 6, 1, 0.0F);
      this.setRotateAngle(this.manipbig3, (float) (Math.PI / 4), 0.0F, 0.0F);
      this.shape3 = new ModelRenderer(this, 13, 0);
      this.shape3.setRotationPoint(0.9F, 3.0F, -1.9F);
      this.shape3.addBox(-0.5F, 0.0F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape3, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shapeprav2 = new ModelRenderer(this, 9, 7);
      this.shapeprav2.mirror = true;
      this.shapeprav2.setRotationPoint(0.0F, -1.0F, 12.0F);
      this.shapeprav2.addBox(-3.0F, -1.0F, 0.0F, 1, 2, 2, 0.0F);
      this.shapeprav3 = new ModelRenderer(this, 9, 7);
      this.shapeprav3.mirror = true;
      this.shapeprav3.setRotationPoint(0.0F, -1.0F, 15.0F);
      this.shapeprav3.addBox(-2.9F, -1.0F, 0.0F, 1, 1, 2, 0.0F);
      this.manip2 = new ModelRenderer(this, 13, 11);
      this.manip2.setRotationPoint(0.0F, 0.0F, -2.7F);
      this.manip2.addBox(-0.5F, 0.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.manip2, -2.3675392F, 0.0F, (float) (Math.PI * 2.0 / 3.0));
      this.shape = new ModelRenderer(this, 10, 24);
      this.shape.setRotationPoint(0.0F, -1.0F, 3.5F);
      this.shape.addBox(-1.5F, -0.5F, 0.0F, 3, 3, 5, 0.0F);
      this.shapelev1 = new ModelRenderer(this, 0, 6);
      this.shapelev1.setRotationPoint(0.0F, -1.0F, 9.0F);
      this.shapelev1.addBox(2.1F, -1.0F, 0.0F, 1, 3, 2, 0.0F);
      this.shape2 = new ModelRenderer(this, 17, 0);
      this.shape2.setRotationPoint(0.0F, 0.3F, 3.4F);
      this.shape2.addBox(-1.5F, 0.0F, 0.0F, 3, 20, 3, 0.0F);
      this.setRotateAngle(this.shape2, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape7 = new ModelRenderer(this, 0, 26);
      this.shape7.setRotationPoint(0.0F, -1.0F, 2.5F);
      this.shape7.addBox(-2.0F, -1.5F, 0.0F, 4, 5, 1, 0.0F);
      this.glass = new ModelRenderer(this, 0, 19);
      this.glass.setRotationPoint(0.0F, 0.0F, -4.0F);
      this.glass.addBox(-1.5F, -1.5F, 0.0F, 3, 3, 4, 0.0F);
      this.shape_1 = new ModelRenderer(this, 21, 23);
      this.shape_1.mirror = true;
      this.shape_1.setRotationPoint(0.0F, 0.0F, -9.2F);
      this.shape_1.addBox(-1.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.shape_1, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.manip2.addChild(this.manipbig2);
      this.manip1.addChild(this.manipbig1);
      this.manip3.addChild(this.manipbig3);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      float lbX = OpenGlHelper.lastBrightnessX;
      float lbY = OpenGlHelper.lastBrightnessY;
      this.manip1.rotateAngleZ = f;
      this.manip2.rotateAngleZ = f + (float) (Math.PI * 2.0 / 3.0);
      this.manip3.rotateAngleZ = f - (float) (Math.PI * 2.0 / 3.0);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape5.offsetX, this.shape5.offsetY, this.shape5.offsetZ);
      GlStateManager.translate(this.shape5.rotationPointX * f5, this.shape5.rotationPointY * f5, this.shape5.rotationPointZ * f5);
      GlStateManager.scale(0.91, 0.91, 0.91);
      GlStateManager.translate(-this.shape5.offsetX, -this.shape5.offsetY, -this.shape5.offsetZ);
      GlStateManager.translate(-this.shape5.rotationPointX * f5, -this.shape5.rotationPointY * f5, -this.shape5.rotationPointZ * f5);
      this.shape5.render(f5);
      GlStateManager.popMatrix();
      this.shapessh.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape4.offsetX, this.shape4.offsetY, this.shape4.offsetZ);
      GlStateManager.translate(this.shape4.rotationPointX * f5, this.shape4.rotationPointY * f5, this.shape4.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape4.offsetX, -this.shape4.offsetY, -this.shape4.offsetZ);
      GlStateManager.translate(-this.shape4.rotationPointX * f5, -this.shape4.rotationPointY * f5, -this.shape4.rotationPointZ * f5);
      this.shape4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape6.offsetX, this.shape6.offsetY, this.shape6.offsetZ);
      GlStateManager.translate(this.shape6.rotationPointX * f5, this.shape6.rotationPointY * f5, this.shape6.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape6.offsetX, -this.shape6.offsetY, -this.shape6.offsetZ);
      GlStateManager.translate(-this.shape6.rotationPointX * f5, -this.shape6.rotationPointY * f5, -this.shape6.rotationPointZ * f5);
      this.shape6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape3.offsetX, this.shape3.offsetY, this.shape3.offsetZ);
      GlStateManager.translate(this.shape3.rotationPointX * f5, this.shape3.rotationPointY * f5, this.shape3.rotationPointZ * f5);
      GlStateManager.scale(0.91, 0.91, 0.91);
      GlStateManager.translate(-this.shape3.offsetX, -this.shape3.offsetY, -this.shape3.offsetZ);
      GlStateManager.translate(-this.shape3.rotationPointX * f5, -this.shape3.rotationPointY * f5, -this.shape3.rotationPointZ * f5);
      this.shape3.render(f5);
      GlStateManager.popMatrix();
      this.shape.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape2.offsetX, this.shape2.offsetY, this.shape2.offsetZ);
      GlStateManager.translate(this.shape2.rotationPointX * f5, this.shape2.rotationPointY * f5, this.shape2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shape2.offsetX, -this.shape2.offsetY, -this.shape2.offsetZ);
      GlStateManager.translate(-this.shape2.rotationPointX * f5, -this.shape2.rotationPointY * f5, -this.shape2.rotationPointZ * f5);
      this.shape2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      if (f4 > 0.0F) {
         GlStateManager.color(0.7F, 0.2F, 0.6F);
      }

      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, f1, f1);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.lamp1.offsetX, this.lamp1.offsetY, this.lamp1.offsetZ);
      GlStateManager.translate(this.lamp1.rotationPointX * f5, this.lamp1.rotationPointY * f5, this.lamp1.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.6);
      GlStateManager.translate(-this.lamp1.offsetX, -this.lamp1.offsetY, -this.lamp1.offsetZ);
      GlStateManager.translate(-this.lamp1.rotationPointX * f5, -this.lamp1.rotationPointY * f5, -this.lamp1.rotationPointZ * f5);
      this.lamp1.render(f5);
      GlStateManager.popMatrix();
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, f2, f2);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.lamp2.offsetX, this.lamp2.offsetY, this.lamp2.offsetZ);
      GlStateManager.translate(this.lamp2.rotationPointX * f5, this.lamp2.rotationPointY * f5, this.lamp2.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.6);
      GlStateManager.translate(-this.lamp2.offsetX, -this.lamp2.offsetY, -this.lamp2.offsetZ);
      GlStateManager.translate(-this.lamp2.rotationPointX * f5, -this.lamp2.rotationPointY * f5, -this.lamp2.rotationPointZ * f5);
      this.lamp2.render(f5);
      GlStateManager.popMatrix();
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, f3, f3);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.lamp3.offsetX, this.lamp3.offsetY, this.lamp3.offsetZ);
      GlStateManager.translate(this.lamp3.rotationPointX * f5, this.lamp3.rotationPointY * f5, this.lamp3.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.6);
      GlStateManager.translate(-this.lamp3.offsetX, -this.lamp3.offsetY, -this.lamp3.offsetZ);
      GlStateManager.translate(-this.lamp3.rotationPointX * f5, -this.lamp3.rotationPointY * f5, -this.lamp3.rotationPointZ * f5);
      this.lamp3.render(f5);
      GlStateManager.popMatrix();
      if (f4 > 0.0F) {
         GlStateManager.color(1.0F, 1.0F, 1.0F);
      }

      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 150.0F, 150.0F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeprav1.offsetX, this.shapeprav1.offsetY, this.shapeprav1.offsetZ);
      GlStateManager.translate(this.shapeprav1.rotationPointX * f5, this.shapeprav1.rotationPointY * f5, this.shapeprav1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapeprav1.offsetX, -this.shapeprav1.offsetY, -this.shapeprav1.offsetZ);
      GlStateManager.translate(-this.shapeprav1.rotationPointX * f5, -this.shapeprav1.rotationPointY * f5, -this.shapeprav1.rotationPointZ * f5);
      this.shapeprav1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapelev3.offsetX, this.shapelev3.offsetY, this.shapelev3.offsetZ);
      GlStateManager.translate(this.shapelev3.rotationPointX * f5, this.shapelev3.rotationPointY * f5, this.shapelev3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapelev3.offsetX, -this.shapelev3.offsetY, -this.shapelev3.offsetZ);
      GlStateManager.translate(-this.shapelev3.rotationPointX * f5, -this.shapelev3.rotationPointY * f5, -this.shapelev3.rotationPointZ * f5);
      this.shapelev3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.display.offsetX, this.display.offsetY, this.display.offsetZ);
      GlStateManager.translate(this.display.rotationPointX * f5, this.display.rotationPointY * f5, this.display.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 0.1);
      GlStateManager.translate(-this.display.offsetX, -this.display.offsetY, -this.display.offsetZ);
      GlStateManager.translate(-this.display.rotationPointX * f5, -this.display.rotationPointY * f5, -this.display.rotationPointZ * f5);
      this.display.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeprav2.offsetX, this.shapeprav2.offsetY, this.shapeprav2.offsetZ);
      GlStateManager.translate(this.shapeprav2.rotationPointX * f5, this.shapeprav2.rotationPointY * f5, this.shapeprav2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapeprav2.offsetX, -this.shapeprav2.offsetY, -this.shapeprav2.offsetZ);
      GlStateManager.translate(-this.shapeprav2.rotationPointX * f5, -this.shapeprav2.rotationPointY * f5, -this.shapeprav2.rotationPointZ * f5);
      this.shapeprav2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeprav3.offsetX, this.shapeprav3.offsetY, this.shapeprav3.offsetZ);
      GlStateManager.translate(this.shapeprav3.rotationPointX * f5, this.shapeprav3.rotationPointY * f5, this.shapeprav3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapeprav3.offsetX, -this.shapeprav3.offsetY, -this.shapeprav3.offsetZ);
      GlStateManager.translate(-this.shapeprav3.rotationPointX * f5, -this.shapeprav3.rotationPointY * f5, -this.shapeprav3.rotationPointZ * f5);
      this.shapeprav3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapelev2.offsetX, this.shapelev2.offsetY, this.shapelev2.offsetZ);
      GlStateManager.translate(this.shapelev2.rotationPointX * f5, this.shapelev2.rotationPointY * f5, this.shapelev2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapelev2.offsetX, -this.shapelev2.offsetY, -this.shapelev2.offsetZ);
      GlStateManager.translate(-this.shapelev2.rotationPointX * f5, -this.shapelev2.rotationPointY * f5, -this.shapelev2.rotationPointZ * f5);
      this.shapelev2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapelev1.offsetX, this.shapelev1.offsetY, this.shapelev1.offsetZ);
      GlStateManager.translate(this.shapelev1.rotationPointX * f5, this.shapelev1.rotationPointY * f5, this.shapelev1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.shapelev1.offsetX, -this.shapelev1.offsetY, -this.shapelev1.offsetZ);
      GlStateManager.translate(-this.shapelev1.rotationPointX * f5, -this.shapelev1.rotationPointY * f5, -this.shapelev1.rotationPointZ * f5);
      this.shapelev1.render(f5);
      GlStateManager.popMatrix();
      this.shape8.render(f5);
      this.shape7.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.manip2.offsetX, this.manip2.offsetY, this.manip2.offsetZ);
      GlStateManager.translate(this.manip2.rotationPointX * f5, this.manip2.rotationPointY * f5, this.manip2.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.manip2.offsetX, -this.manip2.offsetY, -this.manip2.offsetZ);
      GlStateManager.translate(-this.manip2.rotationPointX * f5, -this.manip2.rotationPointY * f5, -this.manip2.rotationPointZ * f5);
      this.manip2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.manip1.offsetX, this.manip1.offsetY, this.manip1.offsetZ);
      GlStateManager.translate(this.manip1.rotationPointX * f5, this.manip1.rotationPointY * f5, this.manip1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.manip1.offsetX, -this.manip1.offsetY, -this.manip1.offsetZ);
      GlStateManager.translate(-this.manip1.rotationPointX * f5, -this.manip1.rotationPointY * f5, -this.manip1.rotationPointZ * f5);
      this.manip1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.manip3.offsetX, this.manip3.offsetY, this.manip3.offsetZ);
      GlStateManager.translate(this.manip3.rotationPointX * f5, this.manip3.rotationPointY * f5, this.manip3.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.manip3.offsetX, -this.manip3.offsetY, -this.manip3.offsetZ);
      GlStateManager.translate(-this.manip3.rotationPointX * f5, -this.manip3.rotationPointY * f5, -this.manip3.rotationPointZ * f5);
      this.manip3.render(f5);
      GlStateManager.popMatrix();
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0F, 240.0F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.core.offsetX, this.core.offsetY, this.core.offsetZ);
      GlStateManager.translate(this.core.rotationPointX * f5, this.core.rotationPointY * f5, this.core.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.core.offsetX, -this.core.offsetY, -this.core.offsetZ);
      GlStateManager.translate(-this.core.rotationPointX * f5, -this.core.rotationPointY * f5, -this.core.rotationPointZ * f5);
      this.core.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_1.offsetX, this.shape_1.offsetY, this.shape_1.offsetZ);
      GlStateManager.translate(this.shape_1.rotationPointX * f5, this.shape_1.rotationPointY * f5, this.shape_1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape_1.offsetX, -this.shape_1.offsetY, -this.shape_1.offsetZ);
      GlStateManager.translate(-this.shape_1.rotationPointX * f5, -this.shape_1.rotationPointY * f5, -this.shape_1.rotationPointZ * f5);
      this.shape_1.render(f5);
      GlStateManager.popMatrix();
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, lbX, lbY);
      GL11.glEnable(2896);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.glass.offsetX, this.glass.offsetY, this.glass.offsetZ);
      GlStateManager.translate(this.glass.rotationPointX * f5, this.glass.rotationPointY * f5, this.glass.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.glass.offsetX, -this.glass.offsetY, -this.glass.offsetZ);
      GlStateManager.translate(-this.glass.rotationPointX * f5, -this.glass.rotationPointY * f5, -this.glass.rotationPointZ * f5);
      this.glass.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
