package com.vivern.arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class QuadroBeltModel2 extends ModelBase {
   public ModelRenderer shape15;
   public ModelRenderer shape15_1;
   public ModelRenderer shape15_2;
   public ModelRenderer shape15_3;
   public ModelRenderer shape15_4;
   public ModelRenderer shape15_5;
   public ModelRenderer shape15_6;
   public ModelRenderer shape15_7;
   public ModelRenderer back;
   public ModelRenderer turbine1;
   public ModelRenderer turbine2;
   public ModelRenderer turbine3;
   public ModelRenderer turbine5;
   public ModelRenderer turbine4;
   public ModelRenderer Bturbine3;
   public ModelRenderer Bturbine1;
   public ModelRenderer Bturbine2;
   public ModelRenderer Bturbine5;
   public ModelRenderer Bturbine4;
   public ModelRenderer propeller1;
   public ModelRenderer Bpropeller1;
   public ModelRenderer Aforward1;
   public ModelRenderer Aturbine1;
   public ModelRenderer Aturbine3;
   public ModelRenderer Aturbine5;
   public ModelRenderer Aturbine4;
   public ModelRenderer Aturbine2;
   public ModelRenderer Apropeller1;
   public ModelRenderer AAforward2;
   public ModelRenderer AAturbine4;
   public ModelRenderer AAturbine5;
   public ModelRenderer AAturbine3;
   public ModelRenderer AAturbine2;
   public ModelRenderer AAturbine1;
   public ModelRenderer AApropeller1;
   public ModelRenderer batteryL1;
   public ModelRenderer batteryL2;
   public ModelRenderer batteryL3;
   public ModelRenderer batteryR1;
   public ModelRenderer batteryR2;
   public ModelRenderer batteryR3;

   public QuadroBeltModel2() {
      this.textureWidth = 32;
      this.textureHeight = 16;
      this.Apropeller1 = new ModelRenderer(this, 10, 11);
      this.Apropeller1.setRotationPoint(10.5F, 2.5F, -1.5F);
      this.Apropeller1.addBox(-2.5F, 0.0F, -0.5F, 5, 1, 1, 0.0F);
      this.shape15_3 = new ModelRenderer(this, 0, 0);
      this.shape15_3.setRotationPoint(0.0F, 10.0F, -3.0F);
      this.shape15_3.addBox(-4.0F, 0.0F, -1.0F, 1, 3, 1, 0.0F);
      this.AAturbine2 = new ModelRenderer(this, 10, 13);
      this.AAturbine2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.AAturbine2.addBox(-13.0F, 2.5F, -5.0F, 5, 1, 1, 0.0F);
      this.setRotateAngle(this.AAturbine2, -0.5462881F, 0.0F, 0.0F);
      this.batteryL3 = new ModelRenderer(this, 24, 0);
      this.batteryL3.setRotationPoint(5.0F, 13.0F, 1.8F);
      this.batteryL3.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.shape15_6 = new ModelRenderer(this, 0, 0);
      this.shape15_6.setRotationPoint(0.0F, 10.0F, -3.0F);
      this.shape15_6.addBox(4.0F, 2.0F, -1.0F, 1, 1, 8, 0.0F);
      this.Bturbine4 = new ModelRenderer(this, 9, 13);
      this.Bturbine4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Bturbine4.addBox(-9.0F, 4.0F, 8.0F, 6, 1, 1, 0.0F);
      this.setRotateAngle(this.Bturbine4, 0.5462881F, 0.0F, 0.0F);
      this.shape15_4 = new ModelRenderer(this, 0, 0);
      this.shape15_4.setRotationPoint(0.0F, 10.0F, -3.0F);
      this.shape15_4.addBox(3.0F, 0.0F, -1.0F, 1, 3, 1, 0.0F);
      this.Aturbine3 = new ModelRenderer(this, 16, 8);
      this.Aturbine3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Aturbine3.addBox(13.0F, 2.5F, -5.0F, 1, 1, 7, 0.0F);
      this.setRotateAngle(this.Aturbine3, -0.5462881F, 0.0F, 0.0F);
      this.batteryR3 = new ModelRenderer(this, 24, 0);
      this.batteryR3.setRotationPoint(-5.0F, 13.0F, 1.8F);
      this.batteryR3.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.Bpropeller1 = new ModelRenderer(this, 9, 11);
      this.Bpropeller1.setRotationPoint(-6.0F, 4.0F, 5.0F);
      this.Bpropeller1.addBox(-3.0F, 0.0F, -0.5F, 6, 1, 1, 0.0F);
      this.shape15_7 = new ModelRenderer(this, 0, 0);
      this.shape15_7.setRotationPoint(0.0F, 11.0F, 2.0F);
      this.shape15_7.addBox(-5.0F, 0.0F, 0.0F, 10, 1, 1, 0.0F);
      this.propeller1 = new ModelRenderer(this, 9, 11);
      this.propeller1.setRotationPoint(6.0F, 4.0F, 5.0F);
      this.propeller1.addBox(-3.0F, 0.0F, -0.5F, 6, 1, 1, 0.0F);
      this.shape15 = new ModelRenderer(this, 0, 13);
      this.shape15.setRotationPoint(0.0F, 9.0F, -3.0F);
      this.shape15.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
      this.AAturbine1 = new ModelRenderer(this, 16, 8);
      this.AAturbine1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.AAturbine1.addBox(-14.0F, 2.5F, -5.0F, 1, 1, 7, 0.0F);
      this.setRotateAngle(this.AAturbine1, -0.5462881F, 0.0F, 0.0F);
      this.Aturbine4 = new ModelRenderer(this, 10, 13);
      this.Aturbine4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Aturbine4.addBox(8.0F, 2.5F, 1.0F, 5, 1, 1, 0.0F);
      this.setRotateAngle(this.Aturbine4, -0.5462881F, 0.0F, 0.0F);
      this.turbine4 = new ModelRenderer(this, 9, 13);
      this.turbine4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.turbine4.addBox(3.0F, 4.0F, 8.0F, 6, 1, 1, 0.0F);
      this.setRotateAngle(this.turbine4, 0.5462881F, 0.0F, 0.0F);
      this.Bturbine1 = new ModelRenderer(this, 0, 0);
      this.Bturbine1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Bturbine1.addBox(-10.0F, 4.0F, 1.0F, 1, 1, 8, 0.0F);
      this.setRotateAngle(this.Bturbine1, 0.5462881F, 0.0F, 0.0F);
      this.shape15_5 = new ModelRenderer(this, 0, 0);
      this.shape15_5.setRotationPoint(0.0F, 10.0F, -3.0F);
      this.shape15_5.addBox(-5.0F, 2.0F, -1.0F, 1, 1, 8, 0.0F);
      this.Bturbine3 = new ModelRenderer(this, 0, 0);
      this.Bturbine3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Bturbine3.addBox(-3.0F, 4.0F, 1.0F, 1, 1, 8, 0.0F);
      this.setRotateAngle(this.Bturbine3, 0.5462881F, 0.0F, 0.0F);
      this.batteryL1 = new ModelRenderer(this, 24, 0);
      this.batteryL1.setRotationPoint(5.0F, 13.0F, -2.0F);
      this.batteryL1.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.batteryR2 = new ModelRenderer(this, 24, 0);
      this.batteryR2.setRotationPoint(-5.0F, 13.0F, -0.1F);
      this.batteryR2.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.Aforward1 = new ModelRenderer(this, 0, 9);
      this.Aforward1.setRotationPoint(0.0F, 12.5F, -3.0F);
      this.Aforward1.addBox(5.0F, 0.0F, -5.0F, 2, 1, 6, 0.0F);
      this.setRotateAngle(this.Aforward1, 0.5462881F, 0.0F, 0.0F);
      this.Aturbine2 = new ModelRenderer(this, 10, 13);
      this.Aturbine2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Aturbine2.addBox(8.0F, 2.5F, -5.0F, 5, 1, 1, 0.0F);
      this.setRotateAngle(this.Aturbine2, -0.5462881F, 0.0F, 0.0F);
      this.turbine5 = new ModelRenderer(this, 0, 0);
      this.turbine5.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.turbine5.addBox(5.5F, 5.0F, 1.0F, 1, 1, 8, 0.0F);
      this.setRotateAngle(this.turbine5, 0.5462881F, 0.0F, 0.0F);
      this.Aturbine5 = new ModelRenderer(this, 0, 0);
      this.Aturbine5.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Aturbine5.addBox(10.0F, 3.5F, -5.0F, 1, 1, 7, 0.0F);
      this.setRotateAngle(this.Aturbine5, -0.5462881F, 0.0F, 0.0F);
      this.shape15_2 = new ModelRenderer(this, 0, 0);
      this.shape15_2.setRotationPoint(0.0F, 10.0F, -3.0F);
      this.shape15_2.addBox(-4.0F, 0.0F, 0.0F, 3, 1, 1, 0.0F);
      this.Aturbine1 = new ModelRenderer(this, 16, 8);
      this.Aturbine1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Aturbine1.addBox(7.0F, 2.5F, -5.0F, 1, 1, 7, 0.0F);
      this.setRotateAngle(this.Aturbine1, -0.5462881F, 0.0F, 0.0F);
      this.shape15_1 = new ModelRenderer(this, 0, 0);
      this.shape15_1.setRotationPoint(0.0F, 10.0F, -3.0F);
      this.shape15_1.addBox(1.0F, 0.0F, 0.0F, 3, 1, 1, 0.0F);
      this.batteryR1 = new ModelRenderer(this, 24, 0);
      this.batteryR1.setRotationPoint(-5.0F, 13.0F, -2.0F);
      this.batteryR1.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.Bturbine2 = new ModelRenderer(this, 9, 13);
      this.Bturbine2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Bturbine2.addBox(-9.0F, 4.0F, 1.0F, 6, 1, 1, 0.0F);
      this.setRotateAngle(this.Bturbine2, 0.5462881F, 0.0F, 0.0F);
      this.AAforward2 = new ModelRenderer(this, 0, 9);
      this.AAforward2.setRotationPoint(0.0F, 12.5F, -3.0F);
      this.AAforward2.addBox(-7.0F, 0.0F, -5.0F, 2, 1, 6, 0.0F);
      this.setRotateAngle(this.AAforward2, 0.5462881F, 0.0F, 0.0F);
      this.AAturbine4 = new ModelRenderer(this, 10, 13);
      this.AAturbine4.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.AAturbine4.addBox(-13.0F, 2.5F, 1.0F, 5, 1, 1, 0.0F);
      this.setRotateAngle(this.AAturbine4, -0.5462881F, 0.0F, 0.0F);
      this.batteryL2 = new ModelRenderer(this, 24, 0);
      this.batteryL2.setRotationPoint(5.0F, 13.0F, -0.1F);
      this.batteryL2.addBox(-1.0F, 0.0F, -1.0F, 2, 5, 2, 0.0F);
      this.back = new ModelRenderer(this, 8, 0);
      this.back.setRotationPoint(0.0F, 11.0F, 3.0F);
      this.back.addBox(-2.0F, 0.0F, 0.0F, 4, 1, 8, 0.0F);
      this.setRotateAngle(this.back, -0.5462881F, 0.0F, 0.0F);
      this.AAturbine3 = new ModelRenderer(this, 16, 8);
      this.AAturbine3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.AAturbine3.addBox(-8.0F, 2.5F, -5.0F, 1, 1, 7, 0.0F);
      this.setRotateAngle(this.AAturbine3, -0.5462881F, 0.0F, 0.0F);
      this.turbine1 = new ModelRenderer(this, 0, 0);
      this.turbine1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.turbine1.addBox(2.0F, 4.0F, 1.0F, 1, 1, 8, 0.0F);
      this.setRotateAngle(this.turbine1, 0.5462881F, 0.0F, 0.0F);
      this.Bturbine5 = new ModelRenderer(this, 0, 0);
      this.Bturbine5.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.Bturbine5.addBox(-6.5F, 5.0F, 1.0F, 1, 1, 8, 0.0F);
      this.setRotateAngle(this.Bturbine5, 0.5462881F, 0.0F, 0.0F);
      this.AApropeller1 = new ModelRenderer(this, 10, 11);
      this.AApropeller1.setRotationPoint(-10.5F, 2.5F, -1.5F);
      this.AApropeller1.addBox(-2.5F, 0.0F, -0.5F, 5, 1, 1, 0.0F);
      this.turbine3 = new ModelRenderer(this, 0, 0);
      this.turbine3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.turbine3.addBox(9.0F, 4.0F, 1.0F, 1, 1, 8, 0.0F);
      this.setRotateAngle(this.turbine3, 0.5462881F, 0.0F, 0.0F);
      this.AAturbine5 = new ModelRenderer(this, 0, 0);
      this.AAturbine5.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.AAturbine5.addBox(-11.0F, 3.5F, -5.0F, 1, 1, 7, 0.0F);
      this.setRotateAngle(this.AAturbine5, -0.5462881F, 0.0F, 0.0F);
      this.turbine2 = new ModelRenderer(this, 9, 13);
      this.turbine2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.turbine2.addBox(3.0F, 4.0F, 1.0F, 6, 1, 1, 0.0F);
      this.setRotateAngle(this.turbine2, 0.5462881F, 0.0F, 0.0F);
      this.Aturbine5.addChild(this.Apropeller1);
      this.AAforward2.addChild(this.AAturbine2);
      this.back.addChild(this.Bturbine4);
      this.Aforward1.addChild(this.Aturbine3);
      this.Bturbine5.addChild(this.Bpropeller1);
      this.turbine5.addChild(this.propeller1);
      this.AAforward2.addChild(this.AAturbine1);
      this.Aforward1.addChild(this.Aturbine4);
      this.back.addChild(this.turbine4);
      this.back.addChild(this.Bturbine1);
      this.back.addChild(this.Bturbine3);
      this.Aforward1.addChild(this.Aturbine2);
      this.back.addChild(this.turbine5);
      this.Aforward1.addChild(this.Aturbine5);
      this.Aforward1.addChild(this.Aturbine1);
      this.back.addChild(this.Bturbine2);
      this.AAforward2.addChild(this.AAturbine4);
      this.AAforward2.addChild(this.AAturbine3);
      this.back.addChild(this.turbine1);
      this.back.addChild(this.Bturbine5);
      this.AAturbine5.addChild(this.AApropeller1);
      this.back.addChild(this.turbine3);
      this.AAforward2.addChild(this.AAturbine5);
      this.back.addChild(this.turbine2);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.shape15_3.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.batteryL3.offsetX, this.batteryL3.offsetY, this.batteryL3.offsetZ);
      GlStateManager.translate(this.batteryL3.rotationPointX * f5, this.batteryL3.rotationPointY * f5, this.batteryL3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.batteryL3.offsetX, -this.batteryL3.offsetY, -this.batteryL3.offsetZ);
      GlStateManager.translate(-this.batteryL3.rotationPointX * f5, -this.batteryL3.rotationPointY * f5, -this.batteryL3.rotationPointZ * f5);
      this.batteryL3.render(f5);
      GlStateManager.popMatrix();
      this.shape15_6.render(f5);
      this.shape15_4.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.batteryR3.offsetX, this.batteryR3.offsetY, this.batteryR3.offsetZ);
      GlStateManager.translate(this.batteryR3.rotationPointX * f5, this.batteryR3.rotationPointY * f5, this.batteryR3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.batteryR3.offsetX, -this.batteryR3.offsetY, -this.batteryR3.offsetZ);
      GlStateManager.translate(-this.batteryR3.rotationPointX * f5, -this.batteryR3.rotationPointY * f5, -this.batteryR3.rotationPointZ * f5);
      this.batteryR3.render(f5);
      GlStateManager.popMatrix();
      this.shape15_7.render(f5);
      this.shape15.render(f5);
      this.shape15_5.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.batteryL1.offsetX, this.batteryL1.offsetY, this.batteryL1.offsetZ);
      GlStateManager.translate(this.batteryL1.rotationPointX * f5, this.batteryL1.rotationPointY * f5, this.batteryL1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.batteryL1.offsetX, -this.batteryL1.offsetY, -this.batteryL1.offsetZ);
      GlStateManager.translate(-this.batteryL1.rotationPointX * f5, -this.batteryL1.rotationPointY * f5, -this.batteryL1.rotationPointZ * f5);
      this.batteryL1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.batteryR2.offsetX, this.batteryR2.offsetY, this.batteryR2.offsetZ);
      GlStateManager.translate(this.batteryR2.rotationPointX * f5, this.batteryR2.rotationPointY * f5, this.batteryR2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.batteryR2.offsetX, -this.batteryR2.offsetY, -this.batteryR2.offsetZ);
      GlStateManager.translate(-this.batteryR2.rotationPointX * f5, -this.batteryR2.rotationPointY * f5, -this.batteryR2.rotationPointZ * f5);
      this.batteryR2.render(f5);
      GlStateManager.popMatrix();
      this.Aforward1.render(f5);
      this.shape15_2.render(f5);
      this.shape15_1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.batteryR1.offsetX, this.batteryR1.offsetY, this.batteryR1.offsetZ);
      GlStateManager.translate(this.batteryR1.rotationPointX * f5, this.batteryR1.rotationPointY * f5, this.batteryR1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.batteryR1.offsetX, -this.batteryR1.offsetY, -this.batteryR1.offsetZ);
      GlStateManager.translate(-this.batteryR1.rotationPointX * f5, -this.batteryR1.rotationPointY * f5, -this.batteryR1.rotationPointZ * f5);
      this.batteryR1.render(f5);
      GlStateManager.popMatrix();
      this.AAforward2.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.batteryL2.offsetX, this.batteryL2.offsetY, this.batteryL2.offsetZ);
      GlStateManager.translate(this.batteryL2.rotationPointX * f5, this.batteryL2.rotationPointY * f5, this.batteryL2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 0.8);
      GlStateManager.translate(-this.batteryL2.offsetX, -this.batteryL2.offsetY, -this.batteryL2.offsetZ);
      GlStateManager.translate(-this.batteryL2.rotationPointX * f5, -this.batteryL2.rotationPointY * f5, -this.batteryL2.rotationPointZ * f5);
      this.batteryL2.render(f5);
      GlStateManager.popMatrix();
      this.back.render(f5);
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
