package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class SandScepterModel extends ModelBase {
   public ModelRenderer shape1;
   public ModelRenderer shape1_1;
   public ModelRenderer shape1_2;
   public ModelRenderer shape1_3;
   public ModelRenderer shape8;
   public ModelRenderer shape1_4;
   public ModelRenderer shape1_5;
   public ModelRenderer shape1_6;
   public ModelRenderer shape1_7;
   public ModelRenderer shape1_8;
   public ModelRenderer shape1_9;
   public ModelRenderer shape1_10;
   public ModelRenderer shape1_11;
   public ModelRenderer shape1_12;
   public ModelRenderer shape1_13;
   public ModelRenderer shape1_14;
   public ModelRenderer shape1_15;
   public ModelRenderer shape1_16;
   public ModelRenderer shape1_17;
   public ModelRenderer shape1_18;

   public SandScepterModel() {
      this.textureWidth = 20;
      this.textureHeight = 32;
      this.shape1_5 = new ModelRenderer(this, 8, 9);
      this.shape1_5.setRotationPoint(0.0F, -5.4F, 5.0F);
      this.shape1_5.addBox(-0.5F, -4.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape1_5, 0.59184116F, 0.59184116F, 0.0F);
      this.shape1_6 = new ModelRenderer(this, 12, 12);
      this.shape1_6.setRotationPoint(0.0F, -5.4F, 5.0F);
      this.shape1_6.addBox(-0.5F, -4.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape1_6, -0.59184116F, 0.59184116F, -0.59184116F);
      this.shape1_13 = new ModelRenderer(this, 11, 19);
      this.shape1_13.setRotationPoint(0.0F, 11.0F, 5.0F);
      this.shape1_13.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shape1_13, 0.0F, (float) Math.PI, 0.0F);
      this.shape8 = new ModelRenderer(this, 5, 24);
      this.shape8.setRotationPoint(0.0F, -8.0F, 5.0F);
      this.shape8.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.shape8, (float) (Math.PI / 4), 0.0F, (float) (Math.PI / 4));
      this.shape1_14 = new ModelRenderer(this, 8, 20);
      this.shape1_14.setRotationPoint(0.0F, 15.0F, 5.0F);
      this.shape1_14.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shape1_14, 0.0F, (float) Math.PI, 0.0F);
      this.shape1_4 = new ModelRenderer(this, 15, 8);
      this.shape1_4.setRotationPoint(0.0F, -5.4F, 5.0F);
      this.shape1_4.addBox(-0.5F, -4.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape1_4, 0.0F, 0.0F, 0.59184116F);
      this.shape1_15 = new ModelRenderer(this, 0, 26);
      this.shape1_15.setRotationPoint(0.0F, 11.16F, 5.0F);
      this.shape1_15.addBox(2.5F, -0.5F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape1_15, 0.0F, (float) Math.PI, 0.0F);
      this.shape1_11 = new ModelRenderer(this, 15, 5);
      this.shape1_11.setRotationPoint(0.0F, 15.0F, 5.0F);
      this.shape1_11.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shape1_11, 0.0F, (float) (Math.PI / 2), 0.0F);
      this.shape1 = new ModelRenderer(this, 0, 0);
      this.shape1.setRotationPoint(0.0F, 2.0F, 5.0F);
      this.shape1.addBox(-1.0F, -8.0F, -1.0F, 2, 25, 2, 0.0F);
      this.shape1_1 = new ModelRenderer(this, 8, 0);
      this.shape1_1.setRotationPoint(0.0F, 0.0F, 5.0F);
      this.shape1_1.addBox(-1.0F, -0.5F, -1.0F, 2, 1, 2, 0.0F);
      this.shape1_3 = new ModelRenderer(this, 8, 6);
      this.shape1_3.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.shape1_3.addBox(-1.0F, -0.5F, -1.0F, 2, 1, 2, 0.0F);
      this.shape1_10 = new ModelRenderer(this, 15, 2);
      this.shape1_10.setRotationPoint(0.0F, 11.0F, 5.0F);
      this.shape1_10.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shape1_10, 0.0F, (float) (Math.PI / 2), 0.0F);
      this.shape1_12 = new ModelRenderer(this, 15, 16);
      this.shape1_12.setRotationPoint(0.0F, 11.16F, 5.0F);
      this.shape1_12.addBox(2.5F, -0.5F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape1_12, 0.0F, (float) (Math.PI / 2), 0.0F);
      this.shape1_17 = new ModelRenderer(this, 8, 22);
      this.shape1_17.setRotationPoint(0.0F, 15.0F, 5.0F);
      this.shape1_17.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shape1_17, 0.0F, (float) (Math.PI * 3.0 / 2.0), 0.0F);
      this.shape1_7 = new ModelRenderer(this, 6, 0);
      this.shape1_7.setRotationPoint(0.0F, 11.0F, 5.0F);
      this.shape1_7.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.shape1_2 = new ModelRenderer(this, 8, 3);
      this.shape1_2.setRotationPoint(0.0F, -2.0F, 5.0F);
      this.shape1_2.addBox(-1.0F, -0.5F, -1.0F, 2, 1, 2, 0.0F);
      this.shape1_18 = new ModelRenderer(this, 0, 26);
      this.shape1_18.setRotationPoint(0.0F, 11.16F, 5.0F);
      this.shape1_18.addBox(2.5F, -0.5F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape1_18, 0.0F, (float) (Math.PI * 3.0 / 2.0), 0.0F);
      this.shape1_9 = new ModelRenderer(this, 8, 14);
      this.shape1_9.setRotationPoint(0.0F, 11.16F, 5.0F);
      this.shape1_9.addBox(2.5F, -0.5F, -0.5F, 1, 5, 1, 0.0F);
      this.shape1_16 = new ModelRenderer(this, 11, 21);
      this.shape1_16.setRotationPoint(0.0F, 11.0F, 5.0F);
      this.shape1_16.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.shape1_16, 0.0F, (float) (Math.PI * 3.0 / 2.0), 0.0F);
      this.shape1_8 = new ModelRenderer(this, 14, 0);
      this.shape1_8.setRotationPoint(0.0F, 15.0F, 5.0F);
      this.shape1_8.addBox(0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.shape1_5.render(f5);
      this.shape1_6.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_13.offsetX, this.shape1_13.offsetY, this.shape1_13.offsetZ);
      GlStateManager.translate(this.shape1_13.rotationPointX * f5, this.shape1_13.rotationPointY * f5, this.shape1_13.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.6, 0.6);
      GlStateManager.translate(-this.shape1_13.offsetX, -this.shape1_13.offsetY, -this.shape1_13.offsetZ);
      GlStateManager.translate(-this.shape1_13.rotationPointX * f5, -this.shape1_13.rotationPointY * f5, -this.shape1_13.rotationPointZ * f5);
      this.shape1_13.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_14.offsetX, this.shape1_14.offsetY, this.shape1_14.offsetZ);
      GlStateManager.translate(this.shape1_14.rotationPointX * f5, this.shape1_14.rotationPointY * f5, this.shape1_14.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.6, 0.6);
      GlStateManager.translate(-this.shape1_14.offsetX, -this.shape1_14.offsetY, -this.shape1_14.offsetZ);
      GlStateManager.translate(-this.shape1_14.rotationPointX * f5, -this.shape1_14.rotationPointY * f5, -this.shape1_14.rotationPointZ * f5);
      this.shape1_14.render(f5);
      GlStateManager.popMatrix();
      this.shape1_4.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_15.offsetX, this.shape1_15.offsetY, this.shape1_15.offsetZ);
      GlStateManager.translate(this.shape1_15.rotationPointX * f5, this.shape1_15.rotationPointY * f5, this.shape1_15.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.92, 0.6);
      GlStateManager.translate(-this.shape1_15.offsetX, -this.shape1_15.offsetY, -this.shape1_15.offsetZ);
      GlStateManager.translate(-this.shape1_15.rotationPointX * f5, -this.shape1_15.rotationPointY * f5, -this.shape1_15.rotationPointZ * f5);
      this.shape1_15.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_11.offsetX, this.shape1_11.offsetY, this.shape1_11.offsetZ);
      GlStateManager.translate(this.shape1_11.rotationPointX * f5, this.shape1_11.rotationPointY * f5, this.shape1_11.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 1.0);
      GlStateManager.translate(-this.shape1_11.offsetX, -this.shape1_11.offsetY, -this.shape1_11.offsetZ);
      GlStateManager.translate(-this.shape1_11.rotationPointX * f5, -this.shape1_11.rotationPointY * f5, -this.shape1_11.rotationPointZ * f5);
      this.shape1_11.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1.offsetX, this.shape1.offsetY, this.shape1.offsetZ);
      GlStateManager.translate(this.shape1.rotationPointX * f5, this.shape1.rotationPointY * f5, this.shape1.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.0, 0.6);
      GlStateManager.translate(-this.shape1.offsetX, -this.shape1.offsetY, -this.shape1.offsetZ);
      GlStateManager.translate(-this.shape1.rotationPointX * f5, -this.shape1.rotationPointY * f5, -this.shape1.rotationPointZ * f5);
      this.shape1.render(f5);
      GlStateManager.popMatrix();
      this.shape1_1.render(f5);
      this.shape1_3.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_10.offsetX, this.shape1_10.offsetY, this.shape1_10.offsetZ);
      GlStateManager.translate(this.shape1_10.rotationPointX * f5, this.shape1_10.rotationPointY * f5, this.shape1_10.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 1.0);
      GlStateManager.translate(-this.shape1_10.offsetX, -this.shape1_10.offsetY, -this.shape1_10.offsetZ);
      GlStateManager.translate(-this.shape1_10.rotationPointX * f5, -this.shape1_10.rotationPointY * f5, -this.shape1_10.rotationPointZ * f5);
      this.shape1_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_12.offsetX, this.shape1_12.offsetY, this.shape1_12.offsetZ);
      GlStateManager.translate(this.shape1_12.rotationPointX * f5, this.shape1_12.rotationPointY * f5, this.shape1_12.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.92, 0.6);
      GlStateManager.translate(-this.shape1_12.offsetX, -this.shape1_12.offsetY, -this.shape1_12.offsetZ);
      GlStateManager.translate(-this.shape1_12.rotationPointX * f5, -this.shape1_12.rotationPointY * f5, -this.shape1_12.rotationPointZ * f5);
      this.shape1_12.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_17.offsetX, this.shape1_17.offsetY, this.shape1_17.offsetZ);
      GlStateManager.translate(this.shape1_17.rotationPointX * f5, this.shape1_17.rotationPointY * f5, this.shape1_17.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 1.0);
      GlStateManager.translate(-this.shape1_17.offsetX, -this.shape1_17.offsetY, -this.shape1_17.offsetZ);
      GlStateManager.translate(-this.shape1_17.rotationPointX * f5, -this.shape1_17.rotationPointY * f5, -this.shape1_17.rotationPointZ * f5);
      this.shape1_17.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_7.offsetX, this.shape1_7.offsetY, this.shape1_7.offsetZ);
      GlStateManager.translate(this.shape1_7.rotationPointX * f5, this.shape1_7.rotationPointY * f5, this.shape1_7.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.6, 0.6);
      GlStateManager.translate(-this.shape1_7.offsetX, -this.shape1_7.offsetY, -this.shape1_7.offsetZ);
      GlStateManager.translate(-this.shape1_7.rotationPointX * f5, -this.shape1_7.rotationPointY * f5, -this.shape1_7.rotationPointZ * f5);
      this.shape1_7.render(f5);
      GlStateManager.popMatrix();
      this.shape1_2.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_18.offsetX, this.shape1_18.offsetY, this.shape1_18.offsetZ);
      GlStateManager.translate(this.shape1_18.rotationPointX * f5, this.shape1_18.rotationPointY * f5, this.shape1_18.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.92, 0.6);
      GlStateManager.translate(-this.shape1_18.offsetX, -this.shape1_18.offsetY, -this.shape1_18.offsetZ);
      GlStateManager.translate(-this.shape1_18.rotationPointX * f5, -this.shape1_18.rotationPointY * f5, -this.shape1_18.rotationPointZ * f5);
      this.shape1_18.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_9.offsetX, this.shape1_9.offsetY, this.shape1_9.offsetZ);
      GlStateManager.translate(this.shape1_9.rotationPointX * f5, this.shape1_9.rotationPointY * f5, this.shape1_9.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.92, 0.6);
      GlStateManager.translate(-this.shape1_9.offsetX, -this.shape1_9.offsetY, -this.shape1_9.offsetZ);
      GlStateManager.translate(-this.shape1_9.rotationPointX * f5, -this.shape1_9.rotationPointY * f5, -this.shape1_9.rotationPointZ * f5);
      this.shape1_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_16.offsetX, this.shape1_16.offsetY, this.shape1_16.offsetZ);
      GlStateManager.translate(this.shape1_16.rotationPointX * f5, this.shape1_16.rotationPointY * f5, this.shape1_16.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.6, 1.0);
      GlStateManager.translate(-this.shape1_16.offsetX, -this.shape1_16.offsetY, -this.shape1_16.offsetZ);
      GlStateManager.translate(-this.shape1_16.rotationPointX * f5, -this.shape1_16.rotationPointY * f5, -this.shape1_16.rotationPointZ * f5);
      this.shape1_16.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape1_8.offsetX, this.shape1_8.offsetY, this.shape1_8.offsetZ);
      GlStateManager.translate(this.shape1_8.rotationPointX * f5, this.shape1_8.rotationPointY * f5, this.shape1_8.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.6, 0.6);
      GlStateManager.translate(-this.shape1_8.offsetX, -this.shape1_8.offsetY, -this.shape1_8.offsetZ);
      GlStateManager.translate(-this.shape1_8.rotationPointX * f5, -this.shape1_8.rotationPointY * f5, -this.shape1_8.rotationPointZ * f5);
      this.shape1_8.render(f5);
      GlStateManager.popMatrix();
      if (f1 == 0.0F) {
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.shape8.offsetX, this.shape8.offsetY, this.shape8.offsetZ);
         GlStateManager.translate(this.shape8.rotationPointX * f5, this.shape8.rotationPointY * f5, this.shape8.rotationPointZ * f5);
         GlStateManager.scale(0.9, 0.7, 0.9);
         GlStateManager.translate(-this.shape8.offsetX, -this.shape8.offsetY, -this.shape8.offsetZ);
         GlStateManager.translate(-this.shape8.rotationPointX * f5, -this.shape8.rotationPointY * f5, -this.shape8.rotationPointZ * f5);
         AbstractMobModel.light((int)(f * 180.0F), true);
         GlStateManager.color(1.0F, 1.0F - f, 1.0F - f, 1.0F);
         this.shape8.render(f5);
         GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);
         AbstractMobModel.returnlight();
         GlStateManager.popMatrix();
      }
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
