package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class SeaEffloresceModel extends ModelBase {
   public ModelRenderer shapedecor;
   public ModelRenderer shapessh;
   public ModelRenderer shape2;
   public ModelRenderer pearl;
   public ModelRenderer shape3;
   public ModelRenderer weed;
   public ModelRenderer weed_1;
   public ModelRenderer weed_2;
   public ModelRenderer decor;
   public ModelRenderer decor2;
   public ModelRenderer decor3;
   public ModelRenderer decor4;
   public ModelRenderer weeda;
   public ModelRenderer weedb;
   public ModelRenderer weedc;
   public ModelRenderer weeda_1;
   public ModelRenderer weedb_1;
   public ModelRenderer weedc_1;
   public ModelRenderer weeda_2;
   public ModelRenderer weedb_2;

   public SeaEffloresceModel() {
      this.textureWidth = 42;
      this.textureHeight = 32;
      this.shapessh = new ModelRenderer(this, 0, 27);
      this.shapessh.setRotationPoint(0.0F, 2.0F, 4.5F);
      this.shapessh.addBox(-0.5F, -0.5F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shapessh, 0.13665928F, 0.0F, 0.0F);
      this.shape3 = new ModelRenderer(this, 12, 27);
      this.shape3.setRotationPoint(0.0F, 3.0F, 1.5F);
      this.shape3.addBox(-0.5F, -0.5F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shape3, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.weedb = new ModelRenderer(this, 18, 27);
      this.weedb.setRotationPoint(0.0F, -5.0F, 0.0F);
      this.weedb.addBox(-0.5F, -2.8F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.weedb, 0.27314404F, -0.22759093F, 0.7740535F);
      this.weeda_2 = new ModelRenderer(this, 18, 17);
      this.weeda_2.setRotationPoint(0.0F, -5.0F, 0.0F);
      this.weeda_2.addBox(-0.5F, -4.8F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.weeda_2, -0.22759093F, 0.0F, 1.0927507F);
      this.weedb_2 = new ModelRenderer(this, 18, 27);
      this.weedb_2.setRotationPoint(0.0F, -5.0F, 0.0F);
      this.weedb_2.addBox(-0.5F, -3.8F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.weedb_2, -0.18203785F, -0.31869712F, -0.63739425F);
      this.decor4 = new ModelRenderer(this, 0, 14);
      this.decor4.setRotationPoint(0.2F, -2.4F, -2.9F);
      this.decor4.addBox(-4.0F, 0.0F, 0.0F, 1, 3, 10, 0.0F);
      this.setRotateAngle(this.decor4, 0.0F, 0.0F, -0.27314404F);
      this.shapedecor = new ModelRenderer(this, 0, 0);
      this.shapedecor.setRotationPoint(-2.0F, 1.5F, 3.5F);
      this.shapedecor.addBox(0.0F, 0.0F, 0.0F, 4, 4, 10, 0.0F);
      this.weed = new ModelRenderer(this, 18, 17);
      this.weed.setRotationPoint(0.0F, 1.2F, -3.4F);
      this.weed.addBox(-0.5F, -5.0F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.weed, 1.1383038F, 0.8196066F, 0.13665928F);
      this.decor = new ModelRenderer(this, 22, 19);
      this.decor.setRotationPoint(0.0F, -2.9F, -2.9F);
      this.decor.addBox(-0.5F, 0.0F, 0.0F, 1, 4, 9, 0.0F);
      this.weedc_1 = new ModelRenderer(this, 18, 27);
      this.weedc_1.setRotationPoint(0.0F, -5.0F, 0.0F);
      this.weedc_1.addBox(-0.5F, -2.6F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.weedc_1, 0.045553092F, 0.0F, 0.5462881F);
      this.weeda_1 = new ModelRenderer(this, 18, 27);
      this.weeda_1.setRotationPoint(0.0F, -5.0F, 0.0F);
      this.weeda_1.addBox(-0.5F, -2.8F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.weeda_1, 0.13665928F, -0.045553092F, -0.95609134F);
      this.shape2 = new ModelRenderer(this, 35, 17);
      this.shape2.setRotationPoint(0.0F, 2.0F, -4.5F);
      this.shape2.addBox(-0.5F, -0.5F, 0.0F, 1, 10, 1, 0.0F);
      this.setRotateAngle(this.shape2, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.pearl = new ModelRenderer(this, 4, 28);
      this.pearl.setRotationPoint(-1.0F, 0.5F, -6.9F);
      this.pearl.addBox(0.0F, 0.0F, 0.0F, 2, 2, 2, 0.0F);
      this.weed_1 = new ModelRenderer(this, 22, 17);
      this.weed_1.setRotationPoint(0.0F, 1.2F, -3.4F);
      this.weed_1.addBox(-0.5F, -5.0F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.weed_1, 1.775698F, -1.4570009F, 0.13665928F);
      this.decor2 = new ModelRenderer(this, 20, 6);
      this.decor2.setRotationPoint(-1.5F, 0.3F, -4.5F);
      this.decor2.addBox(0.0F, 0.0F, 0.0F, 3, 3, 8, 0.0F);
      this.weedc = new ModelRenderer(this, 18, 27);
      this.weedc.setRotationPoint(0.0F, -3.0F, 0.0F);
      this.weedc.addBox(-0.5F, -3.8F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.weedc, -0.4553564F, 0.0F, -0.63739425F);
      this.weeda = new ModelRenderer(this, 22, 17);
      this.weeda.setRotationPoint(0.0F, -5.0F, 0.0F);
      this.weeda.addBox(-0.5F, -4.8F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.weeda, 0.5009095F, -0.13665928F, 0.31869712F);
      this.weed_2 = new ModelRenderer(this, 18, 17);
      this.weed_2.setRotationPoint(0.0F, 1.2F, -3.4F);
      this.weed_2.addBox(-0.5F, -5.0F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.weed_2, 2.2310543F, 1.1383038F, 0.13665928F);
      this.decor3 = new ModelRenderer(this, 0, 14);
      this.decor3.setRotationPoint(-0.2F, -2.4F, -2.9F);
      this.decor3.addBox(3.0F, 0.0F, 0.0F, 1, 3, 10, 0.0F);
      this.setRotateAngle(this.decor3, 0.0F, 0.0F, 0.27314404F);
      this.weedb_1 = new ModelRenderer(this, 18, 17);
      this.weedb_1.setRotationPoint(0.0F, -3.0F, 0.0F);
      this.weedb_1.addBox(-0.5F, -4.6F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.weedb_1, -0.22759093F, -0.045553092F, -0.68294734F);
      this.weeda.addChild(this.weedb);
      this.weed_2.addChild(this.weeda_2);
      this.weeda_2.addChild(this.weedb_2);
      this.weedb_1.addChild(this.weedc_1);
      this.weed_1.addChild(this.weeda_1);
      this.weedb.addChild(this.weedc);
      this.weed.addChild(this.weeda);
      this.weeda_1.addChild(this.weedb_1);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      if (f1 == 0.0F) {
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.decor4.offsetX, this.decor4.offsetY, this.decor4.offsetZ);
         GlStateManager.translate(this.decor4.rotationPointX * f5, this.decor4.rotationPointY * f5, this.decor4.rotationPointZ * f5);
         GlStateManager.scale(0.4, 1.0, 1.0);
         GlStateManager.translate(-this.decor4.offsetX, -this.decor4.offsetY, -this.decor4.offsetZ);
         GlStateManager.translate(-this.decor4.rotationPointX * f5, -this.decor4.rotationPointY * f5, -this.decor4.rotationPointZ * f5);
         this.decor4.render(f5);
         GlStateManager.popMatrix();
         this.shapedecor.render(f5);
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.decor.offsetX, this.decor.offsetY, this.decor.offsetZ);
         GlStateManager.translate(this.decor.rotationPointX * f5, this.decor.rotationPointY * f5, this.decor.rotationPointZ * f5);
         GlStateManager.scale(0.4, 1.0, 1.0);
         GlStateManager.translate(-this.decor.offsetX, -this.decor.offsetY, -this.decor.offsetZ);
         GlStateManager.translate(-this.decor.rotationPointX * f5, -this.decor.rotationPointY * f5, -this.decor.rotationPointZ * f5);
         this.decor.render(f5);
         GlStateManager.popMatrix();
         this.decor2.render(f5);
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.decor3.offsetX, this.decor3.offsetY, this.decor3.offsetZ);
         GlStateManager.translate(this.decor3.rotationPointX * f5, this.decor3.rotationPointY * f5, this.decor3.rotationPointZ * f5);
         GlStateManager.scale(0.4, 1.0, 1.0);
         GlStateManager.translate(-this.decor3.offsetX, -this.decor3.offsetY, -this.decor3.offsetZ);
         GlStateManager.translate(-this.decor3.rotationPointX * f5, -this.decor3.rotationPointY * f5, -this.decor3.rotationPointZ * f5);
         this.decor3.render(f5);
         GlStateManager.popMatrix();
      }

      this.shapessh.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape3.offsetX, this.shape3.offsetY, this.shape3.offsetZ);
      GlStateManager.translate(this.shape3.rotationPointX * f5, this.shape3.rotationPointY * f5, this.shape3.rotationPointZ * f5);
      GlStateManager.scale(1.35, 1.0, 1.0);
      GlStateManager.translate(-this.shape3.offsetX, -this.shape3.offsetY, -this.shape3.offsetZ);
      GlStateManager.translate(-this.shape3.rotationPointX * f5, -this.shape3.rotationPointY * f5, -this.shape3.rotationPointZ * f5);
      this.shape3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.weed.offsetX, this.weed.offsetY, this.weed.offsetZ);
      GlStateManager.translate(this.weed.rotationPointX * f5, this.weed.rotationPointY * f5, this.weed.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.8, 0.8);
      GlStateManager.translate(-this.weed.offsetX, -this.weed.offsetY, -this.weed.offsetZ);
      GlStateManager.translate(-this.weed.rotationPointX * f5, -this.weed.rotationPointY * f5, -this.weed.rotationPointZ * f5);
      this.weed.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape2.offsetX, this.shape2.offsetY, this.shape2.offsetZ);
      GlStateManager.translate(this.shape2.rotationPointX * f5, this.shape2.rotationPointY * f5, this.shape2.rotationPointZ * f5);
      GlStateManager.scale(1.05, 1.0, 1.0);
      GlStateManager.translate(-this.shape2.offsetX, -this.shape2.offsetY, -this.shape2.offsetZ);
      GlStateManager.translate(-this.shape2.rotationPointX * f5, -this.shape2.rotationPointY * f5, -this.shape2.rotationPointZ * f5);
      this.shape2.render(f5);
      GlStateManager.popMatrix();
      this.pearl.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.weed_1.offsetX, this.weed_1.offsetY, this.weed_1.offsetZ);
      GlStateManager.translate(this.weed_1.rotationPointX * f5, this.weed_1.rotationPointY * f5, this.weed_1.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.8, 0.8);
      GlStateManager.translate(-this.weed_1.offsetX, -this.weed_1.offsetY, -this.weed_1.offsetZ);
      GlStateManager.translate(-this.weed_1.rotationPointX * f5, -this.weed_1.rotationPointY * f5, -this.weed_1.rotationPointZ * f5);
      this.weed_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.weed_2.offsetX, this.weed_2.offsetY, this.weed_2.offsetZ);
      GlStateManager.translate(this.weed_2.rotationPointX * f5, this.weed_2.rotationPointY * f5, this.weed_2.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.8, 0.8);
      GlStateManager.translate(-this.weed_2.offsetX, -this.weed_2.offsetY, -this.weed_2.offsetZ);
      GlStateManager.translate(-this.weed_2.rotationPointX * f5, -this.weed_2.rotationPointY * f5, -this.weed_2.rotationPointZ * f5);
      this.weed_2.render(f5);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
