//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.GetMOP;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class SnapballModel extends ModelBase {
   public ModelRenderer shape1;
   public ModelRenderer shapess1;
   public ModelRenderer shape2;
   public ModelRenderer shape3;
   public ModelRenderer shape4;
   public ModelRenderer shape5;
   public ModelRenderer shape6;
   public ModelRenderer shape7;
   public ModelRenderer shapea1;
   public ModelRenderer circlea;
   public ModelRenderer circle1;
   public ModelRenderer shape8;
   public ModelRenderer shapess2;
   public ModelRenderer shapess3;
   public ModelRenderer circle2;
   public ModelRenderer circle3;
   public ModelRenderer circle4;
   public ModelRenderer shapeb1;
   public ModelRenderer shapea2;
   public ModelRenderer shapea3;
   public ModelRenderer shapea4;
   public ModelRenderer focus1;
   public ModelRenderer focus2;
   public ModelRenderer focus3;
   public ModelRenderer shapeb2;
   public ModelRenderer shapeb3;
   public ModelRenderer shapeb4;

   public SnapballModel() {
      this.textureWidth = 32;
      this.textureHeight = 20;
      this.circle4 = new ModelRenderer(this, 0, 14);
      this.circle4.setRotationPoint(0.0F, -1.0F, -3.5F);
      this.circle4.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 0, 0.0F);
      this.focus1 = new ModelRenderer(this, 3, 0);
      this.focus1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.focus1.addBox(-0.5F, -2.5F, -0.5F, 1, 1, 1, 0.0F);
      this.shapeb2 = new ModelRenderer(this, 24, 5);
      this.shapeb2.mirror = true;
      this.shapeb2.setRotationPoint(-0.6F, 0.5F, 4.0F);
      this.shapeb2.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shapeb2, 0.0F, 0.0F, 0.5462881F);
      this.focus2 = new ModelRenderer(this, 3, 0);
      this.focus2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.focus2.addBox(-0.5F, -2.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.focus2, 0.0F, 0.0F, (float) (Math.PI * 2.0 / 3.0));
      this.shape8 = new ModelRenderer(this, 15, 6);
      this.shape8.setRotationPoint(0.0F, -0.5F, 7.5F);
      this.shape8.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shapea3 = new ModelRenderer(this, 24, 5);
      this.shapea3.setRotationPoint(2.2F, 3.2F, 4.0F);
      this.shapea3.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shapea3, 0.0F, 0.0F, 0.59184116F);
      this.shapess1 = new ModelRenderer(this, 0, 9);
      this.shapess1.setRotationPoint(0.0F, 2.4F, 4.6F);
      this.shapess1.addBox(-0.5F, -0.5F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shapess1, 0.27314404F, 0.0F, 0.0F);
      this.shape4 = new ModelRenderer(this, 12, 10);
      this.shape4.setRotationPoint(2.0F, -1.0F, -2.5F);
      this.shape4.addBox(0.0F, 0.0F, 0.0F, 2, 1, 7, 0.0F);
      this.shapea4 = new ModelRenderer(this, 16, 3);
      this.shapea4.setRotationPoint(0.0F, 5.0F, 0.0F);
      this.shapea4.addBox(0.0F, -1.0F, 0.0F, 1, 1, 6, 0.0F);
      this.setRotateAngle(this.shapea4, 0.0F, 0.0F, (float) (Math.PI / 2));
      this.shapea1 = new ModelRenderer(this, 16, 3);
      this.shapea1.setRotationPoint(1.0F, -3.5F, -2.0F);
      this.shapea1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 6, 0.0F);
      this.circle2 = new ModelRenderer(this, 0, 14);
      this.circle2.setRotationPoint(0.0F, -1.0F, -7.5F);
      this.circle2.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 0, 0.0F);
      this.focus3 = new ModelRenderer(this, 3, 0);
      this.focus3.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.focus3.addBox(-0.5F, -2.5F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.focus3, 0.0F, 0.0F, (float) (-Math.PI * 2.0 / 3.0));
      this.shapeb3 = new ModelRenderer(this, 24, 5);
      this.shapeb3.mirror = true;
      this.shapeb3.setRotationPoint(-2.2F, 3.2F, 4.0F);
      this.shapeb3.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shapeb3, 0.0F, 0.0F, -0.59184116F);
      this.shape3 = new ModelRenderer(this, 12, 0);
      this.shape3.mirror = true;
      this.shape3.setRotationPoint(-3.0F, -1.5F, 3.5F);
      this.shape3.addBox(0.0F, 0.0F, 0.0F, 2, 2, 3, 0.0F);
      this.circle1 = new ModelRenderer(this, 0, 14);
      this.circle1.setRotationPoint(0.0F, -1.0F, -9.5F);
      this.circle1.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 0, 0.0F);
      this.shapea2 = new ModelRenderer(this, 24, 5);
      this.shapea2.setRotationPoint(0.6F, 0.5F, 4.0F);
      this.shapea2.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shapea2, 0.0F, 0.0F, -0.5462881F);
      this.shapess3 = new ModelRenderer(this, 23, 13);
      this.shapess3.setRotationPoint(0.0F, 1.5F, -6.0F);
      this.shapess3.addBox(-0.5F, -1.0F, 0.0F, 1, 1, 3, 0.0F);
      this.shapeb4 = new ModelRenderer(this, 16, 3);
      this.shapeb4.mirror = true;
      this.shapeb4.setRotationPoint(0.0F, 5.0F, 0.0F);
      this.shapeb4.addBox(-1.0F, -1.0F, 0.0F, 1, 1, 6, 0.0F);
      this.setRotateAngle(this.shapeb4, 0.0F, 0.0F, (float) (-Math.PI / 2));
      this.shape6 = new ModelRenderer(this, 0, 10);
      this.shape6.setRotationPoint(1.0F, -1.0F, -10.5F);
      this.shape6.addBox(0.0F, 0.0F, 0.0F, 2, 1, 8, 0.0F);
      this.shape1 = new ModelRenderer(this, 0, 2);
      this.shape1.setRotationPoint(-2.0F, -1.0F, 4.5F);
      this.shape1.addBox(0.0F, 0.0F, 0.0F, 4, 3, 3, 0.0F);
      this.shape5 = new ModelRenderer(this, 12, 10);
      this.shape5.mirror = true;
      this.shape5.setRotationPoint(-4.0F, -1.0F, -2.5F);
      this.shape5.addBox(0.0F, 0.0F, 0.0F, 2, 1, 7, 0.0F);
      this.circle3 = new ModelRenderer(this, 0, 14);
      this.circle3.setRotationPoint(0.0F, -1.0F, -5.5F);
      this.circle3.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 0, 0.0F);
      this.shapess2 = new ModelRenderer(this, 4, 10);
      this.shapess2.setRotationPoint(0.0F, 2.0F, -5.0F);
      this.shapess2.addBox(-0.5F, -0.5F, 0.0F, 1, 3, 1, 0.0F);
      this.shapeb1 = new ModelRenderer(this, 16, 3);
      this.shapeb1.mirror = true;
      this.shapeb1.setRotationPoint(-1.0F, -3.5F, -2.0F);
      this.shapeb1.addBox(-1.0F, 0.0F, 0.0F, 1, 1, 6, 0.0F);
      this.shape2 = new ModelRenderer(this, 12, 0);
      this.shape2.setRotationPoint(1.0F, -1.5F, 3.5F);
      this.shape2.addBox(0.0F, 0.0F, 0.0F, 2, 2, 3, 0.0F);
      this.circlea = new ModelRenderer(this, 0, 14);
      this.circlea.setRotationPoint(0.0F, -1.0F, -1.5F);
      this.circlea.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 0, 0.0F);
      this.setRotateAngle(this.circlea, 0.0F, 0.0F, (float) Math.PI);
      this.shape7 = new ModelRenderer(this, 0, 10);
      this.shape7.mirror = true;
      this.shape7.setRotationPoint(-3.0F, -1.0F, -10.5F);
      this.shape7.addBox(0.0F, 0.0F, 0.0F, 2, 1, 8, 0.0F);
      this.circlea.addChild(this.focus1);
      this.shapeb1.addChild(this.shapeb2);
      this.circlea.addChild(this.focus2);
      this.shapea1.addChild(this.shapea3);
      this.shapea1.addChild(this.shapea4);
      this.circlea.addChild(this.focus3);
      this.shapeb1.addChild(this.shapeb3);
      this.shapea1.addChild(this.shapea2);
      this.shapeb1.addChild(this.shapeb4);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.shapea1.offsetZ = -4.0F * GetMOP.getfromto(f, 0.0F, 0.2F) + 4.0F * GetMOP.getfromto(f, 0.8F, 1.0F);
      this.circlea.offsetZ = 2.5F * GetMOP.getfromto(f, 0.1F, 0.3F) - 2.5F * GetMOP.getfromto(f, 0.7F, 0.9F);
      this.circlea.rotateAngleZ = (float)(Math.PI - (Math.PI * 2) * GetMOP.getfromto(f, 0.3F, 0.8F));
      this.shapeb1.offsetZ = this.shapea1.offsetZ;
      this.shape8.render(f5);
      this.shapess1.render(f5);
      this.shape4.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapea1.offsetX, this.shapea1.offsetY, this.shapea1.offsetZ);
      GlStateManager.translate(this.shapea1.rotationPointX * f5, this.shapea1.rotationPointY * f5, this.shapea1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shapea1.offsetX, -this.shapea1.offsetY, -this.shapea1.offsetZ);
      GlStateManager.translate(-this.shapea1.rotationPointX * f5, -this.shapea1.rotationPointY * f5, -this.shapea1.rotationPointZ * f5);
      this.shapea1.render(f5);
      GlStateManager.popMatrix();
      this.shape3.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess3.offsetX, this.shapess3.offsetY, this.shapess3.offsetZ);
      GlStateManager.translate(this.shapess3.rotationPointX * f5, this.shapess3.rotationPointY * f5, this.shapess3.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.5, 1.0);
      GlStateManager.translate(-this.shapess3.offsetX, -this.shapess3.offsetY, -this.shapess3.offsetZ);
      GlStateManager.translate(-this.shapess3.rotationPointX * f5, -this.shapess3.rotationPointY * f5, -this.shapess3.rotationPointZ * f5);
      this.shapess3.render(f5);
      GlStateManager.popMatrix();
      this.shape6.render(f5);
      this.shape1.render(f5);
      this.shape5.render(f5);
      this.shapess2.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeb1.offsetX, this.shapeb1.offsetY, this.shapeb1.offsetZ);
      GlStateManager.translate(this.shapeb1.rotationPointX * f5, this.shapeb1.rotationPointY * f5, this.shapeb1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shapeb1.offsetX, -this.shapeb1.offsetY, -this.shapeb1.offsetZ);
      GlStateManager.translate(-this.shapeb1.rotationPointX * f5, -this.shapeb1.rotationPointY * f5, -this.shapeb1.rotationPointZ * f5);
      this.shapeb1.render(f5);
      GlStateManager.popMatrix();
      this.shape2.render(f5);
      this.shape7.render(f5);
      if (f4 == 0.0F) {
         this.circlea.render(f5);
         this.circle3.render(f5);
         this.circle1.render(f5);
         this.circle2.render(f5);
         this.circle4.render(f5);
      }
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
