//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class SnowballCannonModel extends ModelBase {
   public ModelRenderer shapess1;
   public ModelRenderer shapess2;
   public ModelRenderer shape1;
   public ModelRenderer shape2;
   public ModelRenderer shape3;
   public ModelRenderer shape4;
   public ModelRenderer shape5;
   public ModelRenderer shape6;
   public ModelRenderer shapeaaa1;
   public ModelRenderer shapeaaa2;
   public ModelRenderer shapeaaa3;
   public ModelRenderer shapeaaa4;
   public ModelRenderer shapeaaa5;

   public SnowballCannonModel() {
      this.textureWidth = 32;
      this.textureHeight = 16;
      this.shapess2 = new ModelRenderer(this, 26, 5);
      this.shapess2.setRotationPoint(0.0F, 5.2F, 6.3F);
      this.shapess2.addBox(-1.0F, -0.5F, 0.0F, 2, 3, 1, 0.0F);
      this.setRotateAngle(this.shapess2, (float) (-Math.PI / 2), 0.0F, 0.0F);
      this.shapeaaa4 = new ModelRenderer(this, 16, 8);
      this.shapeaaa4.setRotationPoint(0.0F, 0.2F, 5.0F);
      this.shapeaaa4.addBox(-3.5F, -0.8F, -1.5F, 1, 1, 7, 0.0F);
      this.shape3 = new ModelRenderer(this, 0, 11);
      this.shape3.setRotationPoint(0.0F, -0.8F, 0.0F);
      this.shape3.addBox(-1.5F, -0.5F, 0.0F, 3, 3, 1, 0.0F);
      this.shape5 = new ModelRenderer(this, 15, 8);
      this.shape5.setRotationPoint(0.0F, -1.4F, 3.0F);
      this.shape5.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 2, 0.0F);
      this.shapeaaa2 = new ModelRenderer(this, 16, 0);
      this.shapeaaa2.setRotationPoint(0.0F, 0.2F, 5.0F);
      this.shapeaaa2.addBox(-1.5F, -1.5F, 10.0F, 3, 3, 1, 0.0F);
      this.shape2 = new ModelRenderer(this, 0, 6);
      this.shape2.setRotationPoint(0.0F, -0.8F, 1.0F);
      this.shape2.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 3, 0.0F);
      this.shapeaaa1 = new ModelRenderer(this, 9, 3);
      this.shapeaaa1.setRotationPoint(0.0F, 0.2F, 5.0F);
      this.shapeaaa1.addBox(-1.0F, -1.0F, 2.0F, 2, 2, 3, 0.0F);
      this.shape6 = new ModelRenderer(this, 24, 2);
      this.shape6.setRotationPoint(0.0F, -2.4F, 4.0F);
      this.shape6.addBox(-1.0F, -0.5F, -1.0F, 2, 1, 2, 0.0F);
      this.shape4 = new ModelRenderer(this, 19, 5);
      this.shape4.setRotationPoint(0.0F, 0.2F, -1.0F);
      this.shape4.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shapeaaa5 = new ModelRenderer(this, 24, 0);
      this.shapeaaa5.setRotationPoint(0.0F, 0.2F, 5.0F);
      this.shapeaaa5.addBox(-1.5F, -0.8F, -3.0F, 3, 1, 1, 0.0F);
      this.shapeaaa3 = new ModelRenderer(this, 16, 8);
      this.shapeaaa3.setRotationPoint(0.0F, 0.2F, 5.0F);
      this.shapeaaa3.addBox(2.5F, -0.8F, -1.5F, 1, 1, 7, 0.0F);
      this.shapess1 = new ModelRenderer(this, 11, 8);
      this.shapess1.setRotationPoint(0.0F, 2.0F, 4.5F);
      this.shapess1.addBox(-0.5F, -0.5F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.shapess1, 0.18203785F, 0.0F, 0.0F);
      this.shape1 = new ModelRenderer(this, 0, 0);
      this.shape1.setRotationPoint(0.0F, -0.8F, 4.0F);
      this.shape1.addBox(-1.5F, -0.5F, 0.0F, 3, 3, 3, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess2.offsetX, this.shapess2.offsetY, this.shapess2.offsetZ);
      GlStateManager.translate(this.shapess2.rotationPointX * f5, this.shapess2.rotationPointY * f5, this.shapess2.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.0, 1.2);
      GlStateManager.translate(-this.shapess2.offsetX, -this.shapess2.offsetY, -this.shapess2.offsetZ);
      GlStateManager.translate(-this.shapess2.rotationPointX * f5, -this.shapess2.rotationPointY * f5, -this.shapess2.rotationPointZ * f5);
      this.shapess2.render(f5);
      GlStateManager.popMatrix();
      this.shape3.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape5.offsetX, this.shape5.offsetY, this.shape5.offsetZ);
      GlStateManager.translate(this.shape5.rotationPointX * f5, this.shape5.rotationPointY * f5, this.shape5.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.8, 1.0);
      GlStateManager.translate(-this.shape5.offsetX, -this.shape5.offsetY, -this.shape5.offsetZ);
      GlStateManager.translate(-this.shape5.rotationPointX * f5, -this.shape5.rotationPointY * f5, -this.shape5.rotationPointZ * f5);
      this.shape5.render(f5);
      GlStateManager.popMatrix();
      this.shape2.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape6.offsetX, this.shape6.offsetY, this.shape6.offsetZ);
      GlStateManager.translate(this.shape6.rotationPointX * f5, this.shape6.rotationPointY * f5, this.shape6.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.5, 1.3);
      GlStateManager.translate(-this.shape6.offsetX, -this.shape6.offsetY, -this.shape6.offsetZ);
      GlStateManager.translate(-this.shape6.rotationPointX * f5, -this.shape6.rotationPointY * f5, -this.shape6.rotationPointZ * f5);
      this.shape6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape4.offsetX, this.shape4.offsetY, this.shape4.offsetZ);
      GlStateManager.translate(this.shape4.rotationPointX * f5, this.shape4.rotationPointY * f5, this.shape4.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 1.0);
      GlStateManager.translate(-this.shape4.offsetX, -this.shape4.offsetY, -this.shape4.offsetZ);
      GlStateManager.translate(-this.shape4.rotationPointX * f5, -this.shape4.rotationPointY * f5, -this.shape4.rotationPointZ * f5);
      this.shape4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(0.0F, 0.0F, -f1 * 2.5F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeaaa2.offsetX, this.shapeaaa2.offsetY, this.shapeaaa2.offsetZ);
      GlStateManager.translate(this.shapeaaa2.rotationPointX * f5, this.shapeaaa2.rotationPointY * f5, this.shapeaaa2.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.5);
      GlStateManager.translate(-this.shapeaaa2.offsetX, -this.shapeaaa2.offsetY, -this.shapeaaa2.offsetZ);
      GlStateManager.translate(-this.shapeaaa2.rotationPointX * f5, -this.shapeaaa2.rotationPointY * f5, -this.shapeaaa2.rotationPointZ * f5);
      this.shapeaaa2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeaaa4.offsetX, this.shapeaaa4.offsetY, this.shapeaaa4.offsetZ);
      GlStateManager.translate(this.shapeaaa4.rotationPointX * f5, this.shapeaaa4.rotationPointY * f5, this.shapeaaa4.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 1.0);
      GlStateManager.translate(-this.shapeaaa4.offsetX, -this.shapeaaa4.offsetY, -this.shapeaaa4.offsetZ);
      GlStateManager.translate(-this.shapeaaa4.rotationPointX * f5, -this.shapeaaa4.rotationPointY * f5, -this.shapeaaa4.rotationPointZ * f5);
      this.shapeaaa4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeaaa1.offsetX, this.shapeaaa1.offsetY, this.shapeaaa1.offsetZ);
      GlStateManager.translate(this.shapeaaa1.rotationPointX * f5, this.shapeaaa1.rotationPointY * f5, this.shapeaaa1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 1.0);
      GlStateManager.translate(-this.shapeaaa1.offsetX, -this.shapeaaa1.offsetY, -this.shapeaaa1.offsetZ);
      GlStateManager.translate(-this.shapeaaa1.rotationPointX * f5, -this.shapeaaa1.rotationPointY * f5, -this.shapeaaa1.rotationPointZ * f5);
      this.shapeaaa1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeaaa5.offsetX, this.shapeaaa5.offsetY, this.shapeaaa5.offsetZ);
      GlStateManager.translate(this.shapeaaa5.rotationPointX * f5, this.shapeaaa5.rotationPointY * f5, this.shapeaaa5.rotationPointZ * f5);
      GlStateManager.scale(1.0, 0.48, 0.49);
      GlStateManager.translate(-this.shapeaaa5.offsetX, -this.shapeaaa5.offsetY, -this.shapeaaa5.offsetZ);
      GlStateManager.translate(-this.shapeaaa5.rotationPointX * f5, -this.shapeaaa5.rotationPointY * f5, -this.shapeaaa5.rotationPointZ * f5);
      this.shapeaaa5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeaaa3.offsetX, this.shapeaaa3.offsetY, this.shapeaaa3.offsetZ);
      GlStateManager.translate(this.shapeaaa3.rotationPointX * f5, this.shapeaaa3.rotationPointY * f5, this.shapeaaa3.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.5, 1.0);
      GlStateManager.translate(-this.shapeaaa3.offsetX, -this.shapeaaa3.offsetY, -this.shapeaaa3.offsetZ);
      GlStateManager.translate(-this.shapeaaa3.rotationPointX * f5, -this.shapeaaa3.rotationPointY * f5, -this.shapeaaa3.rotationPointZ * f5);
      this.shapeaaa3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1.offsetX, this.shapess1.offsetY, this.shapess1.offsetZ);
      GlStateManager.translate(this.shapess1.rotationPointX * f5, this.shapess1.rotationPointY * f5, this.shapess1.rotationPointZ * f5);
      GlStateManager.scale(1.2, 1.0, 1.2);
      GlStateManager.translate(-this.shapess1.offsetX, -this.shapess1.offsetY, -this.shapess1.offsetZ);
      GlStateManager.translate(-this.shapess1.rotationPointX * f5, -this.shapess1.rotationPointY * f5, -this.shapess1.rotationPointZ * f5);
      this.shapess1.render(f5);
      GlStateManager.popMatrix();
      this.shape1.render(f5);
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
