//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class StaffOfCorpseModel extends ModelBase {
   public ModelRenderer staf1;
   public ModelRenderer staf2;
   public ModelRenderer skull1;
   public ModelRenderer skull2;
   public ModelRenderer skull3;
   public ModelRenderer shape1;
   public ModelRenderer shape2;
   public ModelRenderer shape3;
   public ModelRenderer shape4;
   public ModelRenderer shape5;
   public ModelRenderer shape1_1;
   public ModelRenderer shape2_1;
   public ModelRenderer shape3_1;
   public ModelRenderer shape4_1;
   public ModelRenderer shape5_1;
   public ModelRenderer staf1_1;
   public ModelRenderer staf2_1;

   public StaffOfCorpseModel() {
      this.textureWidth = 16;
      this.textureHeight = 32;
      this.skull1 = new ModelRenderer(this, 8, 10);
      this.skull1.setRotationPoint(0.0F, -9.7F, 5.0F);
      this.skull1.addBox(-1.0F, -1.0F, -0.6F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.skull1, -0.5009095F, 0.0F, 0.0F);
      this.skull2 = new ModelRenderer(this, 9, 8);
      this.skull2.setRotationPoint(0.0F, -9.1F, 5.0F);
      this.skull2.addBox(-1.0F, 0.1F, -1.1F, 2, 1, 1, 0.0F);
      this.setRotateAngle(this.skull2, -0.8196066F, 0.0F, 0.0F);
      this.shape3 = new ModelRenderer(this, 8, 0);
      this.shape3.setRotationPoint(0.0F, -3.5F, 5.0F);
      this.shape3.addBox(-0.8F, -0.2F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape3, -1.9123572F, -2.3675392F, 0.0F);
      this.shape2_1 = new ModelRenderer(this, 8, 0);
      this.shape2_1.setRotationPoint(0.0F, -2.2F, 5.0F);
      this.shape2_1.addBox(-0.2F, -0.2F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape2_1, -1.7301449F, 2.3675392F, 0.0F);
      this.shape5_1 = new ModelRenderer(this, 8, 0);
      this.shape5_1.setRotationPoint(-0.2F, -6.5F, 5.0F);
      this.shape5_1.addBox(-0.2F, -0.2F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape5_1, -2.321986F, 2.3675392F, 0.0F);
      this.shape1 = new ModelRenderer(this, 8, 0);
      this.shape1.setRotationPoint(0.0F, -1.0F, 5.0F);
      this.shape1.addBox(-0.8F, -0.2F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shape1, -1.5025539F, -2.4130921F, 0.0F);
      this.shape2 = new ModelRenderer(this, 8, 0);
      this.shape2.setRotationPoint(0.0F, -2.2F, 5.0F);
      this.shape2.addBox(-0.8F, -0.2F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape2, -1.7301449F, -2.3675392F, 0.0F);
      this.shape3_1 = new ModelRenderer(this, 8, 0);
      this.shape3_1.setRotationPoint(0.0F, -3.5F, 5.0F);
      this.shape3_1.addBox(-0.2F, -0.2F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape3_1, -1.9123572F, 2.3675392F, 0.0F);
      this.skull3 = new ModelRenderer(this, 8, 14);
      this.skull3.setRotationPoint(0.0F, -9.1F, 5.0F);
      this.skull3.addBox(-1.0F, 0.3F, -1.4F, 2, 1, 2, 0.0F);
      this.setRotateAngle(this.skull3, 0.5009095F, 0.0F, 0.0F);
      this.shape4 = new ModelRenderer(this, 8, 0);
      this.shape4.setRotationPoint(0.1F, -4.9F, 5.0F);
      this.shape4.addBox(-0.8F, -0.2F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape4, (float) (-Math.PI * 2.0 / 3.0), -2.3675392F, 0.0F);
      this.shape1_1 = new ModelRenderer(this, 8, 0);
      this.shape1_1.setRotationPoint(0.0F, -1.0F, 5.0F);
      this.shape1_1.addBox(-0.2F, -0.2F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shape1_1, -1.5025539F, 2.4130921F, 0.0F);
      this.shape5 = new ModelRenderer(this, 8, 0);
      this.shape5.setRotationPoint(0.2F, -6.5F, 5.0F);
      this.shape5.addBox(-0.8F, -0.2F, -0.5F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shape5, -2.321986F, -2.3675392F, 0.0F);
      this.shape4_1 = new ModelRenderer(this, 8, 0);
      this.shape4_1.setRotationPoint(-0.1F, -4.9F, 5.0F);
      this.shape4_1.addBox(-0.2F, -0.2F, -0.5F, 1, 5, 1, 0.0F);
      this.setRotateAngle(this.shape4_1, (float) (-Math.PI * 2.0 / 3.0), 2.3675392F, 0.0F);
      this.staf2_1 = new ModelRenderer(this, 0, 24);
      this.staf2_1.setRotationPoint(0.0F, 13.6F, 5.0F);
      this.staf2_1.addBox(-1.0F, -8.0F, -1.0F, 2, 6, 2, 0.0F);
      this.staf1_1 = new ModelRenderer(this, 0, 0);
      this.staf1_1.setRotationPoint(0.0F, 6.0F, 5.0F);
      this.staf1_1.addBox(-1.0F, -8.0F, -1.0F, 2, 10, 2, 0.0F);
      this.staf1 = new ModelRenderer(this, 0, 12);
      this.staf1.setRotationPoint(0.0F, 18.0F, 5.0F);
      this.staf1.addBox(-1.0F, -8.0F, -1.0F, 2, 10, 2, 0.0F);
      this.staf2 = new ModelRenderer(this, 8, 17);
      this.staf2.setRotationPoint(0.0F, -3.3F, 5.0F);
      this.staf2.addBox(-1.0F, -8.0F, -1.0F, 2, 12, 2, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      this.skull1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.skull2.offsetX, this.skull2.offsetY, this.skull2.offsetZ);
      GlStateManager.translate(this.skull2.rotationPointX * f5, this.skull2.rotationPointY * f5, this.skull2.rotationPointZ * f5);
      GlStateManager.scale(0.6, 0.8, 0.8);
      GlStateManager.translate(-this.skull2.offsetX, -this.skull2.offsetY, -this.skull2.offsetZ);
      GlStateManager.translate(-this.skull2.rotationPointX * f5, -this.skull2.rotationPointY * f5, -this.skull2.rotationPointZ * f5);
      this.skull2.render(f5);
      GlStateManager.popMatrix();
      this.shape3.render(f5);
      this.shape2_1.render(f5);
      this.shape5_1.render(f5);
      this.shape1.render(f5);
      this.shape2.render(f5);
      this.shape3_1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.skull3.offsetX, this.skull3.offsetY, this.skull3.offsetZ);
      GlStateManager.translate(this.skull3.rotationPointX * f5, this.skull3.rotationPointY * f5, this.skull3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.0);
      GlStateManager.translate(-this.skull3.offsetX, -this.skull3.offsetY, -this.skull3.offsetZ);
      GlStateManager.translate(-this.skull3.rotationPointX * f5, -this.skull3.rotationPointY * f5, -this.skull3.rotationPointZ * f5);
      this.skull3.render(f5);
      GlStateManager.popMatrix();
      this.shape4.render(f5);
      this.shape1_1.render(f5);
      this.shape5.render(f5);
      this.shape4_1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf1_1.offsetX, this.staf1_1.offsetY, this.staf1_1.offsetZ);
      GlStateManager.translate(this.staf1_1.rotationPointX * f5, this.staf1_1.rotationPointY * f5, this.staf1_1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.8, 0.7);
      GlStateManager.translate(-this.staf1_1.offsetX, -this.staf1_1.offsetY, -this.staf1_1.offsetZ);
      GlStateManager.translate(-this.staf1_1.rotationPointX * f5, -this.staf1_1.rotationPointY * f5, -this.staf1_1.rotationPointZ * f5);
      this.staf1_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf1.offsetX, this.staf1.offsetY, this.staf1.offsetZ);
      GlStateManager.translate(this.staf1.rotationPointX * f5, this.staf1.rotationPointY * f5, this.staf1.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.8, 0.65);
      GlStateManager.translate(-this.staf1.offsetX, -this.staf1.offsetY, -this.staf1.offsetZ);
      GlStateManager.translate(-this.staf1.rotationPointX * f5, -this.staf1.rotationPointY * f5, -this.staf1.rotationPointZ * f5);
      this.staf1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 180.0F, 180.0F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf2_1.offsetX, this.staf2_1.offsetY, this.staf2_1.offsetZ);
      GlStateManager.translate(this.staf2_1.rotationPointX * f5, this.staf2_1.rotationPointY * f5, this.staf2_1.rotationPointZ * f5);
      GlStateManager.scale(0.45, 0.8, 0.45);
      GlStateManager.translate(-this.staf2_1.offsetX, -this.staf2_1.offsetY, -this.staf2_1.offsetZ);
      GlStateManager.translate(-this.staf2_1.rotationPointX * f5, -this.staf2_1.rotationPointY * f5, -this.staf2_1.rotationPointZ * f5);
      this.staf2_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf2.offsetX, this.staf2.offsetY, this.staf2.offsetZ);
      GlStateManager.translate(this.staf2.rotationPointX * f5, this.staf2.rotationPointY * f5, this.staf2.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.8, 0.5);
      GlStateManager.translate(-this.staf2.offsetX, -this.staf2.offsetY, -this.staf2.offsetZ);
      GlStateManager.translate(-this.staf2.rotationPointX * f5, -this.staf2.rotationPointY * f5, -this.staf2.rotationPointZ * f5);
      this.staf2.render(f5);
      GlStateManager.popMatrix();
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
