package com.vivern.arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class StaticLanceModel extends ModelBase {
   public ModelRenderer staf;
   public ModelRenderer stonee;
   public ModelRenderer stone;
   public ModelRenderer shape;
   public ModelRenderer shape_1;
   public ModelRenderer shape_2;
   public ModelRenderer shape_3;
   public ModelRenderer shape_4;
   public ModelRenderer shape_5;
   public ModelRenderer shape_6;
   public ModelRenderer shape_7;
   public ModelRenderer blade;
   public ModelRenderer staf1;
   public ModelRenderer staf2;
   public ModelRenderer staf3;

   public StaticLanceModel() {
      this.textureWidth = 16;
      this.textureHeight = 32;
      this.shape_6 = new ModelRenderer(this, 9, 15);
      this.shape_6.setRotationPoint(0.0F, -6.9F, 5.0F);
      this.shape_6.addBox(-1.0F, -9.5F, -0.5F, 2, 4, 1, 0.0F);
      this.setRotateAngle(this.shape_6, 0.27314404F, 0.0F, 0.0F);
      this.shape_5 = new ModelRenderer(this, 8, 7);
      this.shape_5.setRotationPoint(0.0F, -7.5F, 5.0F);
      this.shape_5.addBox(-1.0F, -8.5F, -1.7F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.shape_5, -2.5041983F, 0.0F, 0.0F);
      this.shape_2 = new ModelRenderer(this, 8, 0);
      this.shape_2.setRotationPoint(0.0F, -7.3F, 5.0F);
      this.shape_2.addBox(-1.0F, -9.0F, -0.3F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.shape_2, 0.91053826F, 0.0F, 0.0F);
      this.shape = new ModelRenderer(this, 8, 7);
      this.shape.setRotationPoint(0.0F, -7.3F, 5.0F);
      this.shape.addBox(-1.0F, -8.5F, 0.0F, 2, 6, 2, 0.0F);
      this.setRotateAngle(this.shape, 2.2310543F, 0.0F, 0.0F);
      this.stonee = new ModelRenderer(this, 8, 20);
      this.stonee.setRotationPoint(0.0F, -7.0F, 5.0F);
      this.stonee.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.stonee, 1.5934856F, 0.7740535F, -0.8196066F);
      this.stone = new ModelRenderer(this, 8, 20);
      this.stone.setRotationPoint(0.0F, -7.0F, 5.0F);
      this.stone.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.stone, 0.0F, 0.7983136F, 0.0F);
      this.shape_4 = new ModelRenderer(this, 8, 7);
      this.shape_4.setRotationPoint(0.0F, -7.5F, 5.0F);
      this.shape_4.addBox(-1.0F, -8.5F, -0.3F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.shape_4, 2.5041983F, 0.0F, 0.0F);
      this.staf = new ModelRenderer(this, 0, 0);
      this.staf.setRotationPoint(0.0F, 4.0F, 5.0F);
      this.staf.addBox(-1.0F, -8.0F, -1.0F, 2, 30, 2, 0.0F);
      this.staf1 = new ModelRenderer(this, 8, 28);
      this.staf1.setRotationPoint(0.0F, 27.1F, 5.0F);
      this.staf1.addBox(-1.0F, 0.0F, -1.0F, 2, 1, 2, 0.0F);
      this.setRotateAngle(this.staf1, -0.13665928F, 0.0F, 0.0F);
      this.shape_7 = new ModelRenderer(this, 9, 15);
      this.shape_7.setRotationPoint(0.0F, -6.9F, 5.0F);
      this.shape_7.addBox(-1.0F, -9.5F, -0.5F, 2, 4, 1, 0.0F);
      this.setRotateAngle(this.shape_7, -0.27314404F, 0.0F, 0.0F);
      this.staf2 = new ModelRenderer(this, 8, 28);
      this.staf2.setRotationPoint(0.0F, 28.7F, 5.0F);
      this.staf2.addBox(-1.0F, 0.0F, -1.0F, 2, 1, 2, 0.0F);
      this.setRotateAngle(this.staf2, 0.27314404F, 0.0F, 0.0F);
      this.staf3 = new ModelRenderer(this, 10, 30);
      this.staf3.setRotationPoint(0.0F, 30.1F, 5.0F);
      this.staf3.addBox(-0.5F, 0.0F, -0.5F, 1, 1, 1, 0.0F);
      this.setRotateAngle(this.staf3, -0.045553092F, 0.0F, 0.0F);
      this.shape_1 = new ModelRenderer(this, 8, 7);
      this.shape_1.setRotationPoint(0.0F, -7.3F, 5.0F);
      this.shape_1.addBox(-1.0F, -8.5F, -2.0F, 2, 6, 2, 0.0F);
      this.setRotateAngle(this.shape_1, -2.2310543F, 0.0F, 0.0F);
      this.shape_3 = new ModelRenderer(this, 8, 0);
      this.shape_3.setRotationPoint(0.0F, -7.3F, 5.0F);
      this.shape_3.addBox(-1.0F, -9.0F, -1.7F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.shape_3, -0.91053826F, 0.0F, 0.0F);
      this.blade = new ModelRenderer(this, 8, 24);
      this.blade.setRotationPoint(0.0F, -15.0F, 5.0F);
      this.blade.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.blade, (float) (Math.PI / 4), 0.0F, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_6.offsetX, this.shape_6.offsetY, this.shape_6.offsetZ);
      GlStateManager.translate(this.shape_6.rotationPointX * f5, this.shape_6.rotationPointY * f5, this.shape_6.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.75, 0.95);
      GlStateManager.translate(-this.shape_6.offsetX, -this.shape_6.offsetY, -this.shape_6.offsetZ);
      GlStateManager.translate(-this.shape_6.rotationPointX * f5, -this.shape_6.rotationPointY * f5, -this.shape_6.rotationPointZ * f5);
      this.shape_6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_5.offsetX, this.shape_5.offsetY, this.shape_5.offsetZ);
      GlStateManager.translate(this.shape_5.rotationPointX * f5, this.shape_5.rotationPointY * f5, this.shape_5.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.75, 0.65);
      GlStateManager.translate(-this.shape_5.offsetX, -this.shape_5.offsetY, -this.shape_5.offsetZ);
      GlStateManager.translate(-this.shape_5.rotationPointX * f5, -this.shape_5.rotationPointY * f5, -this.shape_5.rotationPointZ * f5);
      this.shape_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_2.offsetX, this.shape_2.offsetY, this.shape_2.offsetZ);
      GlStateManager.translate(this.shape_2.rotationPointX * f5, this.shape_2.rotationPointY * f5, this.shape_2.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.45, 0.85);
      GlStateManager.translate(-this.shape_2.offsetX, -this.shape_2.offsetY, -this.shape_2.offsetZ);
      GlStateManager.translate(-this.shape_2.rotationPointX * f5, -this.shape_2.rotationPointY * f5, -this.shape_2.rotationPointZ * f5);
      this.shape_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape.offsetX, this.shape.offsetY, this.shape.offsetZ);
      GlStateManager.translate(this.shape.rotationPointX * f5, this.shape.rotationPointY * f5, this.shape.rotationPointZ * f5);
      GlStateManager.scale(0.55, 0.45, 0.95);
      GlStateManager.translate(-this.shape.offsetX, -this.shape.offsetY, -this.shape.offsetZ);
      GlStateManager.translate(-this.shape.rotationPointX * f5, -this.shape.rotationPointY * f5, -this.shape.rotationPointZ * f5);
      this.shape.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_4.offsetX, this.shape_4.offsetY, this.shape_4.offsetZ);
      GlStateManager.translate(this.shape_4.rotationPointX * f5, this.shape_4.rotationPointY * f5, this.shape_4.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.75, 0.65);
      GlStateManager.translate(-this.shape_4.offsetX, -this.shape_4.offsetY, -this.shape_4.offsetZ);
      GlStateManager.translate(-this.shape_4.rotationPointX * f5, -this.shape_4.rotationPointY * f5, -this.shape_4.rotationPointZ * f5);
      this.shape_4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf.offsetX, this.staf.offsetY, this.staf.offsetZ);
      GlStateManager.translate(this.staf.rotationPointX * f5, this.staf.rotationPointY * f5, this.staf.rotationPointZ * f5);
      GlStateManager.scale(0.65, 1.0, 0.65);
      GlStateManager.translate(-this.staf.offsetX, -this.staf.offsetY, -this.staf.offsetZ);
      GlStateManager.translate(-this.staf.rotationPointX * f5, -this.staf.rotationPointY * f5, -this.staf.rotationPointZ * f5);
      this.staf.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf1.offsetX, this.staf1.offsetY, this.staf1.offsetZ);
      GlStateManager.translate(this.staf1.rotationPointX * f5, this.staf1.rotationPointY * f5, this.staf1.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.9, 0.85);
      GlStateManager.translate(-this.staf1.offsetX, -this.staf1.offsetY, -this.staf1.offsetZ);
      GlStateManager.translate(-this.staf1.rotationPointX * f5, -this.staf1.rotationPointY * f5, -this.staf1.rotationPointZ * f5);
      this.staf1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_7.offsetX, this.shape_7.offsetY, this.shape_7.offsetZ);
      GlStateManager.translate(this.shape_7.rotationPointX * f5, this.shape_7.rotationPointY * f5, this.shape_7.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.75, 0.95);
      GlStateManager.translate(-this.shape_7.offsetX, -this.shape_7.offsetY, -this.shape_7.offsetZ);
      GlStateManager.translate(-this.shape_7.rotationPointX * f5, -this.shape_7.rotationPointY * f5, -this.shape_7.rotationPointZ * f5);
      this.shape_7.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf2.offsetX, this.staf2.offsetY, this.staf2.offsetZ);
      GlStateManager.translate(this.staf2.rotationPointX * f5, this.staf2.rotationPointY * f5, this.staf2.rotationPointZ * f5);
      GlStateManager.scale(0.55, 0.8, 0.65);
      GlStateManager.translate(-this.staf2.offsetX, -this.staf2.offsetY, -this.staf2.offsetZ);
      GlStateManager.translate(-this.staf2.rotationPointX * f5, -this.staf2.rotationPointY * f5, -this.staf2.rotationPointZ * f5);
      this.staf2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf3.offsetX, this.staf3.offsetY, this.staf3.offsetZ);
      GlStateManager.translate(this.staf3.rotationPointX * f5, this.staf3.rotationPointY * f5, this.staf3.rotationPointZ * f5);
      GlStateManager.scale(0.95, 0.7, 0.95);
      GlStateManager.translate(-this.staf3.offsetX, -this.staf3.offsetY, -this.staf3.offsetZ);
      GlStateManager.translate(-this.staf3.rotationPointX * f5, -this.staf3.rotationPointY * f5, -this.staf3.rotationPointZ * f5);
      this.staf3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_1.offsetX, this.shape_1.offsetY, this.shape_1.offsetZ);
      GlStateManager.translate(this.shape_1.rotationPointX * f5, this.shape_1.rotationPointY * f5, this.shape_1.rotationPointZ * f5);
      GlStateManager.scale(0.55, 0.45, 0.95);
      GlStateManager.translate(-this.shape_1.offsetX, -this.shape_1.offsetY, -this.shape_1.offsetZ);
      GlStateManager.translate(-this.shape_1.rotationPointX * f5, -this.shape_1.rotationPointY * f5, -this.shape_1.rotationPointZ * f5);
      this.shape_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_3.offsetX, this.shape_3.offsetY, this.shape_3.offsetZ);
      GlStateManager.translate(this.shape_3.rotationPointX * f5, this.shape_3.rotationPointY * f5, this.shape_3.rotationPointZ * f5);
      GlStateManager.scale(0.5, 0.45, 0.85);
      GlStateManager.translate(-this.shape_3.offsetX, -this.shape_3.offsetY, -this.shape_3.offsetZ);
      GlStateManager.translate(-this.shape_3.rotationPointX * f5, -this.shape_3.rotationPointY * f5, -this.shape_3.rotationPointZ * f5);
      this.shape_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 180.0F, 180.0F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.stonee.offsetX, this.stonee.offsetY, this.stonee.offsetZ);
      GlStateManager.translate(this.stonee.rotationPointX * f5, this.stonee.rotationPointY * f5, this.stonee.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.4, 0.8);
      GlStateManager.translate(-this.stonee.offsetX, -this.stonee.offsetY, -this.stonee.offsetZ);
      GlStateManager.translate(-this.stonee.rotationPointX * f5, -this.stonee.rotationPointY * f5, -this.stonee.rotationPointZ * f5);
      this.stonee.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.stone.offsetX, this.stone.offsetY, this.stone.offsetZ);
      GlStateManager.translate(this.stone.rotationPointX * f5, this.stone.rotationPointY * f5, this.stone.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.2, 0.8);
      GlStateManager.translate(-this.stone.offsetX, -this.stone.offsetY, -this.stone.offsetZ);
      GlStateManager.translate(-this.stone.rotationPointX * f5, -this.stone.rotationPointY * f5, -this.stone.rotationPointZ * f5);
      this.stone.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.blade.offsetX, this.blade.offsetY, this.blade.offsetZ);
      GlStateManager.translate(this.blade.rotationPointX * f5, this.blade.rotationPointY * f5, this.blade.rotationPointZ * f5);
      GlStateManager.scale(0.5, 3.35, 0.55);
      GlStateManager.translate(-this.blade.offsetX, -this.blade.offsetY, -this.blade.offsetZ);
      GlStateManager.translate(-this.blade.rotationPointX * f5, -this.blade.rotationPointY * f5, -this.blade.rotationPointZ * f5);
      this.blade.render(f5);
      GlStateManager.popMatrix();
      GL11.glEnable(2896);
      GlStateManager.popMatrix();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
