package com.vivern.arpg.elements.models;

import com.vivern.arpg.main.AnimationTimer;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.client.renderer.GlStateManager.DestFactor;
import net.minecraft.client.renderer.GlStateManager.SourceFactor;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ThistleThornModel extends ModelBase {
   public ModelRenderer staf1;
   public ModelRenderer staf2;
   public ModelRenderer staf3;
   public ModelRenderer flower1;
   public ModelRenderer flower2;
   public ModelRenderer flower3;
   public ModelRenderer flow1;
   public ModelRenderer flow2;
   public ModelRenderer flow3;
   public ModelRenderer flow4;
   public ModelRenderer flow5;
   public ModelRenderer flow6;
   public ModelRenderer flower4;
   public ModelRenderer stem1;
   public ModelRenderer stem2;
   public ModelRenderer stem3;
   public ModelRenderer stem4;
   public ModelRenderer overflower1;
   public ModelRenderer overflower2;
   public ModelRenderer overflower3;
   public ModelRenderer overflower3_1;
   public ModelRenderer leaf1;
   public ModelRenderer leaf2;
   public ModelRenderer leaf3;
   public ModelRenderer leafsmall1;
   public ModelRenderer leafsmall2;
   public ModelRenderer leafsmall3;
   public ModelRenderer thorns1;
   public ModelRenderer thorns2;
   public ModelRenderer thorns3;
   public ModelRenderer thorns4;
   public ModelRenderer magic1;
   public ModelRenderer magic2;

   public ThistleThornModel() {
      this.textureWidth = 64;
      this.textureHeight = 48;
      this.leafsmall1 = new ModelRenderer(this, 20, 22);
      this.leafsmall1.setRotationPoint(0.0F, -2.0F, 3.7F);
      this.leafsmall1.addBox(-2.0F, -10.0F, 0.0F, 4, 10, 0, 0.0F);
      this.setRotateAngle(this.leafsmall1, 0.91053826F, 0.59184116F, 0.0F);
      this.magic1 = new ModelRenderer(this, -12, 32);
      this.magic1.setRotationPoint(0.0F, 4.0F, 4.5F);
      this.magic1.addBox(-6.0F, 0.0F, -6.0F, 12, 0, 12, 0.0F);
      this.overflower2 = new ModelRenderer(this, 33, 7);
      this.overflower2.setRotationPoint(-7.0F, -12.6F, 2.7F);
      this.overflower2.addBox(-1.5F, 0.0F, -1.5F, 3, 4, 3, 0.0F);
      this.leaf3 = new ModelRenderer(this, 12, 22);
      this.leaf3.setRotationPoint(0.0F, 10.0F, 5.0F);
      this.leaf3.addBox(-2.0F, -10.0F, 0.0F, 4, 10, 0, 0.0F);
      this.setRotateAngle(this.leaf3, 0.59184116F, -2.1399481F, 0.0F);
      this.leaf2 = new ModelRenderer(this, 12, 22);
      this.leaf2.setRotationPoint(0.0F, 4.0F, 3.7F);
      this.leaf2.addBox(-2.0F, -10.0F, 0.0F, 4, 10, 0, 0.0F);
      this.setRotateAngle(this.leaf2, 0.7285004F, -0.045553092F, 0.0F);
      this.flower3 = new ModelRenderer(this, 8, 0);
      this.flower3.setRotationPoint(0.0F, -8.8F, 3.9F);
      this.flower3.addBox(-1.5F, 0.0F, -1.5F, 3, 3, 3, 0.0F);
      this.thorns2 = new ModelRenderer(this, 55, 17);
      this.thorns2.setRotationPoint(0.0F, -4.0F, 3.7F);
      this.thorns2.addBox(-2.0F, -3.0F, 0.0F, 4, 19, 0, 0.0F);
      this.setRotateAngle(this.thorns2, 0.091106184F, 0.0F, 0.0F);
      this.flow4 = new ModelRenderer(this, 0, 18);
      this.flow4.setRotationPoint(0.0F, -5.5F, 3.9F);
      this.flow4.addBox(0.5F, 0.0F, -1.5F, 1, 11, 3, 0.0F);
      this.setRotateAngle(this.flow4, 3.0049334F, -0.18203785F, -1.2747885F);
      this.flow2 = new ModelRenderer(this, 0, 18);
      this.flow2.setRotationPoint(0.0F, -5.4F, 3.9F);
      this.flow2.addBox(0.5F, 0.0F, -1.5F, 1, 11, 3, 0.0F);
      this.setRotateAngle(this.flow2, (float) (-Math.PI / 3), -0.18203785F, -1.775698F);
      this.staf2 = new ModelRenderer(this, 0, 0);
      this.staf2.setRotationPoint(0.0F, -4.0F, 3.7F);
      this.staf2.addBox(-1.0F, 0.0F, -1.0F, 2, 16, 2, 0.0F);
      this.setRotateAngle(this.staf2, 0.091106184F, 0.0F, 0.0F);
      this.flower4 = new ModelRenderer(this, 12, 9);
      this.flower4.setRotationPoint(0.0F, -13.0F, 3.9F);
      this.flower4.addBox(-3.0F, 0.0F, -3.0F, 6, 7, 6, 0.0F);
      this.stem3 = new ModelRenderer(this, 8, 20);
      this.stem3.setRotationPoint(-6.0F, -6.0F, 3.0F);
      this.stem3.addBox(-1.0F, 0.0F, -1.0F, 1, 11, 1, 0.0F);
      this.setRotateAngle(this.stem3, 0.18203785F, 0.0F, -0.8651597F);
      this.flower1 = new ModelRenderer(this, 20, 0);
      this.flower1.setRotationPoint(0.0F, -13.4F, 3.9F);
      this.flower1.addBox(-2.0F, 0.0F, -2.0F, 4, 5, 4, 0.0F);
      this.flower2 = new ModelRenderer(this, 52, 7);
      this.flower2.setRotationPoint(0.0F, -14.1F, 3.9F);
      this.flower2.addBox(-1.5F, 0.0F, -1.5F, 3, 7, 3, 0.0F);
      this.overflower1 = new ModelRenderer(this, 33, 7);
      this.overflower1.setRotationPoint(6.5F, -11.7F, 2.7F);
      this.overflower1.addBox(-1.5F, 0.0F, -1.5F, 3, 4, 3, 0.0F);
      this.flow3 = new ModelRenderer(this, 0, 18);
      this.flow3.setRotationPoint(0.0F, -5.8F, 3.9F);
      this.flow3.addBox(0.5F, 0.0F, -1.5F, 1, 11, 3, 0.0F);
      this.setRotateAngle(this.flow3, -2.276433F, -0.13665928F, -1.3658947F);
      this.thorns3 = new ModelRenderer(this, 47, 34);
      this.thorns3.setRotationPoint(6.0F, -4.0F, 3.0F);
      this.thorns3.addBox(-2.0F, -2.0F, -0.5F, 3, 13, 0, 0.0F);
      this.setRotateAngle(this.thorns3, 0.18203785F, 0.0F, 0.7740535F);
      this.leaf1 = new ModelRenderer(this, 12, 22);
      this.leaf1.setRotationPoint(0.0F, 7.0F, 5.0F);
      this.leaf1.addBox(-2.0F, -10.0F, 0.0F, 4, 10, 0, 0.0F);
      this.setRotateAngle(this.leaf1, 1.0016445F, (float) (Math.PI / 3), 0.0F);
      this.magic2 = new ModelRenderer(this, 14, 32);
      this.magic2.setRotationPoint(0.0F, -5.0F, 3.9F);
      this.magic2.addBox(-5.0F, 0.0F, -5.0F, 10, 0, 10, 0.0F);
      this.flow1 = new ModelRenderer(this, 0, 18);
      this.flow1.setRotationPoint(0.0F, -5.8F, 3.9F);
      this.flow1.addBox(0.5F, 0.0F, -1.5F, 1, 11, 3, 0.0F);
      this.setRotateAngle(this.flow1, 0.0F, 0.0F, -1.775698F);
      this.overflower3_1 = new ModelRenderer(this, 40, 0);
      this.overflower3_1.setRotationPoint(-7.0F, -9.9F, 2.7F);
      this.overflower3_1.addBox(-3.0F, 0.0F, -3.0F, 6, 1, 6, 0.0F);
      this.thorns1 = new ModelRenderer(this, 47, 17);
      this.thorns1.setRotationPoint(0.0F, 7.0F, 4.7F);
      this.thorns1.addBox(-2.0F, 0.0F, 0.0F, 4, 16, 0, 0.0F);
      this.setRotateAngle(this.thorns1, -0.091106184F, 0.0F, 0.0F);
      this.stem1 = new ModelRenderer(this, 8, 20);
      this.stem1.setRotationPoint(6.0F, -4.0F, 3.0F);
      this.stem1.addBox(-1.0F, 0.0F, -1.0F, 1, 11, 1, 0.0F);
      this.setRotateAngle(this.stem1, 0.18203785F, 0.0F, 0.7740535F);
      this.overflower3 = new ModelRenderer(this, 40, 0);
      this.overflower3.setRotationPoint(6.5F, -8.9F, 2.7F);
      this.overflower3.addBox(-3.0F, 0.0F, -3.0F, 6, 1, 6, 0.0F);
      this.leafsmall2 = new ModelRenderer(this, 20, 22);
      this.leafsmall2.setRotationPoint(-4.0F, -4.0F, 3.7F);
      this.leafsmall2.addBox(-2.0F, -10.0F, 0.0F, 4, 10, 0, 0.0F);
      this.setRotateAngle(this.leafsmall2, 1.1838568F, 2.1855013F, -0.59184116F);
      this.stem4 = new ModelRenderer(this, 8, 20);
      this.stem4.setRotationPoint(-7.0F, -11.8F, 3.0F);
      this.stem4.addBox(-1.0F, 0.0F, -1.0F, 1, 9, 1, 0.0F);
      this.setRotateAngle(this.stem4, 0.0F, 0.0F, -0.18203785F);
      this.flow5 = new ModelRenderer(this, 0, 18);
      this.flow5.setRotationPoint(0.0F, -5.9F, 3.9F);
      this.flow5.addBox(0.5F, 0.0F, -1.5F, 1, 11, 3, 0.0F);
      this.setRotateAngle(this.flow5, 2.276433F, -0.3642502F, -1.2747885F);
      this.thorns4 = new ModelRenderer(this, 37, 14);
      this.thorns4.setRotationPoint(-6.0F, -6.0F, 3.0F);
      this.thorns4.addBox(-2.0F, -2.0F, -0.6F, 3, 13, 0, 0.0F);
      this.setRotateAngle(this.thorns4, 0.18203785F, 0.0F, -0.8651597F);
      this.staf3 = new ModelRenderer(this, 0, 0);
      this.staf3.setRotationPoint(0.0F, -9.5F, 3.9F);
      this.staf3.addBox(-1.0F, 0.0F, -1.0F, 2, 8, 2, 0.0F);
      this.setRotateAngle(this.staf3, -0.045553092F, 0.0F, 0.0F);
      this.flow6 = new ModelRenderer(this, 0, 18);
      this.flow6.setRotationPoint(0.0F, -5.8F, 3.9F);
      this.flow6.addBox(0.5F, 0.0F, -1.5F, 1, 11, 3, 0.0F);
      this.setRotateAngle(this.flow6, 0.7285004F, -0.22759093F, -1.6845918F);
      this.staf1 = new ModelRenderer(this, 0, 0);
      this.staf1.setRotationPoint(0.0F, 7.0F, 4.7F);
      this.staf1.addBox(-1.0F, 0.0F, -1.0F, 2, 16, 2, 0.0F);
      this.setRotateAngle(this.staf1, -0.091106184F, 0.0F, 0.0F);
      this.leafsmall3 = new ModelRenderer(this, 20, 22);
      this.leafsmall3.setRotationPoint(3.2F, -1.3F, 3.2F);
      this.leafsmall3.addBox(-2.0F, -10.0F, 0.0F, 4, 10, 0, 0.0F);
      this.setRotateAngle(this.leafsmall3, 0.4553564F, -0.59184116F, 0.7285004F);
      this.stem2 = new ModelRenderer(this, 8, 20);
      this.stem2.setRotationPoint(7.0F, -10.8F, 3.0F);
      this.stem2.addBox(-1.0F, 0.0F, -1.0F, 1, 10, 1, 0.0F);
      this.setRotateAngle(this.stem2, 0.0F, 0.0F, 0.13665928F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      float lbX = OpenGlHelper.lastBrightnessX;
      float lbY = OpenGlHelper.lastBrightnessY;
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf2.offsetX, this.staf2.offsetY, this.staf2.offsetZ);
      GlStateManager.translate(this.staf2.rotationPointX * f5, this.staf2.rotationPointY * f5, this.staf2.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.staf2.offsetX, -this.staf2.offsetY, -this.staf2.offsetZ);
      GlStateManager.translate(-this.staf2.rotationPointX * f5, -this.staf2.rotationPointY * f5, -this.staf2.rotationPointZ * f5);
      this.staf2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.stem3.offsetX, this.stem3.offsetY, this.stem3.offsetZ);
      GlStateManager.translate(this.stem3.rotationPointX * f5, this.stem3.rotationPointY * f5, this.stem3.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.stem3.offsetX, -this.stem3.offsetY, -this.stem3.offsetZ);
      GlStateManager.translate(-this.stem3.rotationPointX * f5, -this.stem3.rotationPointY * f5, -this.stem3.rotationPointZ * f5);
      this.stem3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.stem1.offsetX, this.stem1.offsetY, this.stem1.offsetZ);
      GlStateManager.translate(this.stem1.rotationPointX * f5, this.stem1.rotationPointY * f5, this.stem1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.stem1.offsetX, -this.stem1.offsetY, -this.stem1.offsetZ);
      GlStateManager.translate(-this.stem1.rotationPointX * f5, -this.stem1.rotationPointY * f5, -this.stem1.rotationPointZ * f5);
      this.stem1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.stem4.offsetX, this.stem4.offsetY, this.stem4.offsetZ);
      GlStateManager.translate(this.stem4.rotationPointX * f5, this.stem4.rotationPointY * f5, this.stem4.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.stem4.offsetX, -this.stem4.offsetY, -this.stem4.offsetZ);
      GlStateManager.translate(-this.stem4.rotationPointX * f5, -this.stem4.rotationPointY * f5, -this.stem4.rotationPointZ * f5);
      this.stem4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf3.offsetX, this.staf3.offsetY, this.staf3.offsetZ);
      GlStateManager.translate(this.staf3.rotationPointX * f5, this.staf3.rotationPointY * f5, this.staf3.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.staf3.offsetX, -this.staf3.offsetY, -this.staf3.offsetZ);
      GlStateManager.translate(-this.staf3.rotationPointX * f5, -this.staf3.rotationPointY * f5, -this.staf3.rotationPointZ * f5);
      this.staf3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf1.offsetX, this.staf1.offsetY, this.staf1.offsetZ);
      GlStateManager.translate(this.staf1.rotationPointX * f5, this.staf1.rotationPointY * f5, this.staf1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.staf1.offsetX, -this.staf1.offsetY, -this.staf1.offsetZ);
      GlStateManager.translate(-this.staf1.rotationPointX * f5, -this.staf1.rotationPointY * f5, -this.staf1.rotationPointZ * f5);
      this.staf1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.stem2.offsetX, this.stem2.offsetY, this.stem2.offsetZ);
      GlStateManager.translate(this.stem2.rotationPointX * f5, this.stem2.rotationPointY * f5, this.stem2.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.stem2.offsetX, -this.stem2.offsetY, -this.stem2.offsetZ);
      GlStateManager.translate(-this.stem2.rotationPointX * f5, -this.stem2.rotationPointY * f5, -this.stem2.rotationPointZ * f5);
      this.stem2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.disableCull();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.overflower2.offsetX, this.overflower2.offsetY, this.overflower2.offsetZ);
      GlStateManager.translate(this.overflower2.rotationPointX * f5, this.overflower2.rotationPointY * f5, this.overflower2.rotationPointZ * f5);
      GlStateManager.scale(0.65, 0.65, 0.65);
      GlStateManager.translate(-this.overflower2.offsetX, -this.overflower2.offsetY, -this.overflower2.offsetZ);
      GlStateManager.translate(-this.overflower2.rotationPointX * f5, -this.overflower2.rotationPointY * f5, -this.overflower2.rotationPointZ * f5);
      this.overflower2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.overflower1.offsetX, this.overflower1.offsetY, this.overflower1.offsetZ);
      GlStateManager.translate(this.overflower1.rotationPointX * f5, this.overflower1.rotationPointY * f5, this.overflower1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.overflower1.offsetX, -this.overflower1.offsetY, -this.overflower1.offsetZ);
      GlStateManager.translate(-this.overflower1.rotationPointX * f5, -this.overflower1.rotationPointY * f5, -this.overflower1.rotationPointZ * f5);
      this.overflower1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.flower3.offsetX, this.flower3.offsetY, this.flower3.offsetZ);
      GlStateManager.translate(this.flower3.rotationPointX * f5, this.flower3.rotationPointY * f5, this.flower3.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.7, 0.8);
      GlStateManager.translate(-this.flower3.offsetX, -this.flower3.offsetY, -this.flower3.offsetZ);
      GlStateManager.translate(-this.flower3.rotationPointX * f5, -this.flower3.rotationPointY * f5, -this.flower3.rotationPointZ * f5);
      this.flower3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.flower1.offsetX, this.flower1.offsetY, this.flower1.offsetZ);
      GlStateManager.translate(this.flower1.rotationPointX * f5, this.flower1.rotationPointY * f5, this.flower1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.flower1.offsetX, -this.flower1.offsetY, -this.flower1.offsetZ);
      GlStateManager.translate(-this.flower1.rotationPointX * f5, -this.flower1.rotationPointY * f5, -this.flower1.rotationPointZ * f5);
      this.flower1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.flower2.offsetX, this.flower2.offsetY, this.flower2.offsetZ);
      GlStateManager.translate(this.flower2.rotationPointX * f5, this.flower2.rotationPointY * f5, this.flower2.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.flower2.offsetX, -this.flower2.offsetY, -this.flower2.offsetZ);
      GlStateManager.translate(-this.flower2.rotationPointX * f5, -this.flower2.rotationPointY * f5, -this.flower2.rotationPointZ * f5);
      this.flower2.render(f5);
      GlStateManager.popMatrix();
      if (f1 == 0.0F) {
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.overflower3.offsetX, this.overflower3.offsetY, this.overflower3.offsetZ);
         GlStateManager.translate(this.overflower3.rotationPointX * f5, this.overflower3.rotationPointY * f5, this.overflower3.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.overflower3.offsetX, -this.overflower3.offsetY, -this.overflower3.offsetZ);
         GlStateManager.translate(-this.overflower3.rotationPointX * f5, -this.overflower3.rotationPointY * f5, -this.overflower3.rotationPointZ * f5);
         this.overflower3.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.leafsmall1.offsetX, this.leafsmall1.offsetY, this.leafsmall1.offsetZ);
         GlStateManager.translate(this.leafsmall1.rotationPointX * f5, this.leafsmall1.rotationPointY * f5, this.leafsmall1.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.leafsmall1.offsetX, -this.leafsmall1.offsetY, -this.leafsmall1.offsetZ);
         GlStateManager.translate(-this.leafsmall1.rotationPointX * f5, -this.leafsmall1.rotationPointY * f5, -this.leafsmall1.rotationPointZ * f5);
         this.leafsmall1.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.leaf3.offsetX, this.leaf3.offsetY, this.leaf3.offsetZ);
         GlStateManager.translate(this.leaf3.rotationPointX * f5, this.leaf3.rotationPointY * f5, this.leaf3.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.leaf3.offsetX, -this.leaf3.offsetY, -this.leaf3.offsetZ);
         GlStateManager.translate(-this.leaf3.rotationPointX * f5, -this.leaf3.rotationPointY * f5, -this.leaf3.rotationPointZ * f5);
         this.leaf3.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.leaf2.offsetX, this.leaf2.offsetY, this.leaf2.offsetZ);
         GlStateManager.translate(this.leaf2.rotationPointX * f5, this.leaf2.rotationPointY * f5, this.leaf2.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.leaf2.offsetX, -this.leaf2.offsetY, -this.leaf2.offsetZ);
         GlStateManager.translate(-this.leaf2.rotationPointX * f5, -this.leaf2.rotationPointY * f5, -this.leaf2.rotationPointZ * f5);
         this.leaf2.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.thorns2.offsetX, this.thorns2.offsetY, this.thorns2.offsetZ);
         GlStateManager.translate(this.thorns2.rotationPointX * f5, this.thorns2.rotationPointY * f5, this.thorns2.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.thorns2.offsetX, -this.thorns2.offsetY, -this.thorns2.offsetZ);
         GlStateManager.translate(-this.thorns2.rotationPointX * f5, -this.thorns2.rotationPointY * f5, -this.thorns2.rotationPointZ * f5);
         this.thorns2.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.flow4.offsetX, this.flow4.offsetY, this.flow4.offsetZ);
         GlStateManager.translate(this.flow4.rotationPointX * f5, this.flow4.rotationPointY * f5, this.flow4.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.flow4.offsetX, -this.flow4.offsetY, -this.flow4.offsetZ);
         GlStateManager.translate(-this.flow4.rotationPointX * f5, -this.flow4.rotationPointY * f5, -this.flow4.rotationPointZ * f5);
         this.flow4.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.flow2.offsetX, this.flow2.offsetY, this.flow2.offsetZ);
         GlStateManager.translate(this.flow2.rotationPointX * f5, this.flow2.rotationPointY * f5, this.flow2.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.flow2.offsetX, -this.flow2.offsetY, -this.flow2.offsetZ);
         GlStateManager.translate(-this.flow2.rotationPointX * f5, -this.flow2.rotationPointY * f5, -this.flow2.rotationPointZ * f5);
         this.flow2.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.flower4.offsetX, this.flower4.offsetY, this.flower4.offsetZ);
         GlStateManager.translate(this.flower4.rotationPointX * f5, this.flower4.rotationPointY * f5, this.flower4.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.flower4.offsetX, -this.flower4.offsetY, -this.flower4.offsetZ);
         GlStateManager.translate(-this.flower4.rotationPointX * f5, -this.flower4.rotationPointY * f5, -this.flower4.rotationPointZ * f5);
         this.flower4.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.flow3.offsetX, this.flow3.offsetY, this.flow3.offsetZ);
         GlStateManager.translate(this.flow3.rotationPointX * f5, this.flow3.rotationPointY * f5, this.flow3.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.flow3.offsetX, -this.flow3.offsetY, -this.flow3.offsetZ);
         GlStateManager.translate(-this.flow3.rotationPointX * f5, -this.flow3.rotationPointY * f5, -this.flow3.rotationPointZ * f5);
         this.flow3.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.thorns3.offsetX, this.thorns3.offsetY, this.thorns3.offsetZ);
         GlStateManager.translate(this.thorns3.rotationPointX * f5, this.thorns3.rotationPointY * f5, this.thorns3.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.thorns3.offsetX, -this.thorns3.offsetY, -this.thorns3.offsetZ);
         GlStateManager.translate(-this.thorns3.rotationPointX * f5, -this.thorns3.rotationPointY * f5, -this.thorns3.rotationPointZ * f5);
         this.thorns3.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.leaf1.offsetX, this.leaf1.offsetY, this.leaf1.offsetZ);
         GlStateManager.translate(this.leaf1.rotationPointX * f5, this.leaf1.rotationPointY * f5, this.leaf1.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.leaf1.offsetX, -this.leaf1.offsetY, -this.leaf1.offsetZ);
         GlStateManager.translate(-this.leaf1.rotationPointX * f5, -this.leaf1.rotationPointY * f5, -this.leaf1.rotationPointZ * f5);
         this.leaf1.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.flow1.offsetX, this.flow1.offsetY, this.flow1.offsetZ);
         GlStateManager.translate(this.flow1.rotationPointX * f5, this.flow1.rotationPointY * f5, this.flow1.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.flow1.offsetX, -this.flow1.offsetY, -this.flow1.offsetZ);
         GlStateManager.translate(-this.flow1.rotationPointX * f5, -this.flow1.rotationPointY * f5, -this.flow1.rotationPointZ * f5);
         this.flow1.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.overflower3_1.offsetX, this.overflower3_1.offsetY, this.overflower3_1.offsetZ);
         GlStateManager.translate(this.overflower3_1.rotationPointX * f5, this.overflower3_1.rotationPointY * f5, this.overflower3_1.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.overflower3_1.offsetX, -this.overflower3_1.offsetY, -this.overflower3_1.offsetZ);
         GlStateManager.translate(-this.overflower3_1.rotationPointX * f5, -this.overflower3_1.rotationPointY * f5, -this.overflower3_1.rotationPointZ * f5);
         this.overflower3_1.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.thorns1.offsetX, this.thorns1.offsetY, this.thorns1.offsetZ);
         GlStateManager.translate(this.thorns1.rotationPointX * f5, this.thorns1.rotationPointY * f5, this.thorns1.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.thorns1.offsetX, -this.thorns1.offsetY, -this.thorns1.offsetZ);
         GlStateManager.translate(-this.thorns1.rotationPointX * f5, -this.thorns1.rotationPointY * f5, -this.thorns1.rotationPointZ * f5);
         this.thorns1.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.leafsmall2.offsetX, this.leafsmall2.offsetY, this.leafsmall2.offsetZ);
         GlStateManager.translate(this.leafsmall2.rotationPointX * f5, this.leafsmall2.rotationPointY * f5, this.leafsmall2.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.leafsmall2.offsetX, -this.leafsmall2.offsetY, -this.leafsmall2.offsetZ);
         GlStateManager.translate(-this.leafsmall2.rotationPointX * f5, -this.leafsmall2.rotationPointY * f5, -this.leafsmall2.rotationPointZ * f5);
         this.leafsmall2.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.flow5.offsetX, this.flow5.offsetY, this.flow5.offsetZ);
         GlStateManager.translate(this.flow5.rotationPointX * f5, this.flow5.rotationPointY * f5, this.flow5.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.flow5.offsetX, -this.flow5.offsetY, -this.flow5.offsetZ);
         GlStateManager.translate(-this.flow5.rotationPointX * f5, -this.flow5.rotationPointY * f5, -this.flow5.rotationPointZ * f5);
         this.flow5.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.thorns4.offsetX, this.thorns4.offsetY, this.thorns4.offsetZ);
         GlStateManager.translate(this.thorns4.rotationPointX * f5, this.thorns4.rotationPointY * f5, this.thorns4.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.thorns4.offsetX, -this.thorns4.offsetY, -this.thorns4.offsetZ);
         GlStateManager.translate(-this.thorns4.rotationPointX * f5, -this.thorns4.rotationPointY * f5, -this.thorns4.rotationPointZ * f5);
         this.thorns4.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.flow6.offsetX, this.flow6.offsetY, this.flow6.offsetZ);
         GlStateManager.translate(this.flow6.rotationPointX * f5, this.flow6.rotationPointY * f5, this.flow6.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.flow6.offsetX, -this.flow6.offsetY, -this.flow6.offsetZ);
         GlStateManager.translate(-this.flow6.rotationPointX * f5, -this.flow6.rotationPointY * f5, -this.flow6.rotationPointZ * f5);
         this.flow6.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.leafsmall3.offsetX, this.leafsmall3.offsetY, this.leafsmall3.offsetZ);
         GlStateManager.translate(this.leafsmall3.rotationPointX * f5, this.leafsmall3.rotationPointY * f5, this.leafsmall3.rotationPointZ * f5);
         GlStateManager.scale(0.7, 0.7, 0.7);
         GlStateManager.translate(-this.leafsmall3.offsetX, -this.leafsmall3.offsetY, -this.leafsmall3.offsetZ);
         GlStateManager.translate(-this.leafsmall3.rotationPointX * f5, -this.leafsmall3.rotationPointY * f5, -this.leafsmall3.rotationPointZ * f5);
         this.leafsmall3.render(f5);
         GlStateManager.popMatrix();
         GL11.glDisable(2896);
         OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 240.0F, 240.0F);
         this.magic1.rotateAngleY = AnimationTimer.tick / 57.0F;
         this.magic2.rotateAngleY = -AnimationTimer.tick / 57.0F;
         if (f2 == 1.0F) {
            GlStateManager.color(0.95F, 1.0F, 0.25F);
         }

         if (f2 == 2.0F) {
            GlStateManager.color(0.8F, 0.27F, 0.95F);
         }

         GlStateManager.blendFunc(SourceFactor.ONE, DestFactor.ONE);
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.magic1.offsetX, this.magic1.offsetY, this.magic1.offsetZ);
         GlStateManager.translate(this.magic1.rotationPointX * f5, this.magic1.rotationPointY * f5, this.magic1.rotationPointZ * f5);
         GlStateManager.scale(0.8, 0.7, 0.8);
         GlStateManager.translate(-this.magic1.offsetX, -this.magic1.offsetY, -this.magic1.offsetZ);
         GlStateManager.translate(-this.magic1.rotationPointX * f5, -this.magic1.rotationPointY * f5, -this.magic1.rotationPointZ * f5);
         this.magic1.render(f5);
         GlStateManager.popMatrix();
         GlStateManager.pushMatrix();
         GlStateManager.translate(this.magic2.offsetX, this.magic2.offsetY, this.magic2.offsetZ);
         GlStateManager.translate(this.magic2.rotationPointX * f5, this.magic2.rotationPointY * f5, this.magic2.rotationPointZ * f5);
         GlStateManager.scale(0.8, 0.7, 0.8);
         GlStateManager.translate(-this.magic2.offsetX, -this.magic2.offsetY, -this.magic2.offsetZ);
         GlStateManager.translate(-this.magic2.rotationPointX * f5, -this.magic2.rotationPointY * f5, -this.magic2.rotationPointZ * f5);
         this.magic2.render(f5);
         GlStateManager.popMatrix();
         GL11.glEnable(2896);
         OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, lbX, lbY);
         GlStateManager.blendFunc(SourceFactor.SRC_ALPHA, DestFactor.ONE_MINUS_SRC_ALPHA);
         GlStateManager.color(1.0F, 1.0F, 1.0F);
      }

      GlStateManager.enableCull();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
