package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.AnimationTimer;
import com.Vivern.Arpg.renders.ModelRendererGlow;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class ToxiniumArmorModel extends ModelBiped {
   public int lightt = 180;
   public ModelRenderer helm;
   public ModelRenderer chest;
   public ModelRenderer rightarm;
   public ModelRenderer leftarm;
   public ModelRenderer rightleg;
   public ModelRenderer leftleg;
   public ModelRenderer rightboot;
   public ModelRenderer leftboot;
   public ModelRenderer rarmGLOW;
   public ModelRenderer larmGLOW;
   public ModelRenderer chestGLOW;
   public ModelRenderer helm_1;
   public ModelRenderer chest_1;
   public ModelRenderer venta;
   public ModelRenderer venta_1;
   public ModelRenderer chest_2;
   public ModelRenderer chest_3;
   public ModelRenderer venta_2;
   public ModelRenderer ventb;
   public ModelRenderer ventb_1;
   public ModelRenderer ventb_2;
   public ModelRenderer rightarm_1;
   public ModelRenderer rightarm_2;
   public ModelRenderer leftarm_1;
   public ModelRenderer leftarm_2;
   public ModelRenderer rightleg_1;
   public ModelRenderer rightleg_2;
   public ModelRenderer leftleg_1;
   public ModelRenderer leftleg_2;
   public ModelRenderer helm_2;
   public ModelRenderer helm_3;
   public ModelRenderer helm_4;

   public ToxiniumArmorModel() {
      this.textureWidth = 64;
      this.textureHeight = 64;
      this.chest = new ModelRenderer(this, 16, 16);
      this.chest.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.chest.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 0.5F);
      this.leftleg = new ModelRenderer(this, 0, 16);
      this.leftleg.mirror = true;
      this.leftleg.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.venta_2 = new ModelRenderer(this, 0, 35);
      this.venta_2.setRotationPoint(1.0F, 8.5F, 2.9F);
      this.venta_2.addBox(-2.0F, -2.0F, -0.5F, 4, 4, 1, 0.0F);
      this.rightleg_1 = new ModelRenderer(this, 53, 23);
      this.rightleg_1.mirror = true;
      this.rightleg_1.setRotationPoint(-1.9F, -0.5F, 0.5F);
      this.rightleg_1.addBox(-2.0F, 0.0F, 0.0F, 2, 3, 3, 0.0F);
      this.setRotateAngle(this.rightleg_1, 0.0F, 0.5009095F, 0.0F);
      this.rightleg_2 = new ModelRenderer(this, 53, 23);
      this.rightleg_2.mirror = true;
      this.rightleg_2.setRotationPoint(-1.9F, -0.5F, 0.5F);
      this.rightleg_2.addBox(-2.0F, 0.0F, -4.0F, 2, 3, 3, 0.0F);
      this.setRotateAngle(this.rightleg_2, 0.0F, -0.3642502F, 0.0F);
      this.rightarm_2 = new ModelRenderer(this, 32, 5);
      this.rightarm_2.mirror = true;
      this.rightarm_2.setRotationPoint(-3.6F, 8.5F, -1.0F);
      this.rightarm_2.addBox(0.0F, -7.0F, 0.0F, 0, 7, 3, 0.0F);
      this.setRotateAngle(this.rightarm_2, 0.0F, -0.31869712F, 0.0F);
      this.helm_3 = new ModelRenderer(this, 24, 0);
      this.helm_3.mirror = true;
      this.helm_3.setRotationPoint(3.0F, -1.0F, -5.6F);
      this.helm_3.addBox(-2.5F, -1.5F, -0.5F, 5, 3, 3, 0.0F);
      this.setRotateAngle(this.helm_3, 0.0F, -0.4098033F, -0.18203785F);
      this.leftboot = new ModelRenderer(this, 40, 24);
      this.leftboot.setRotationPoint(1.9F, 12.0F, 0.0F);
      this.leftboot.addBox(-1.8F, 9.0F, -2.5F, 4, 3, 5, 0.4F);
      this.chest_3 = new ModelRenderer(this, 27, 53);
      this.chest_3.setRotationPoint(0.0F, -0.7F, 0.0F);
      this.chest_3.addBox(-5.0F, 7.5F, 1.0F, 3, 5, 2, 0.0F);
      this.venta = new ModelRenderer(this, 0, 35);
      this.venta.setRotationPoint(1.5F, 3.4F, -3.9F);
      this.venta.addBox(-2.0F, -2.0F, -0.5F, 4, 4, 1, 0.0F);
      this.chest_2 = new ModelRenderer(this, 16, 53);
      this.chest_2.setRotationPoint(0.0F, -0.7F, 0.0F);
      this.chest_2.addBox(2.0F, 7.5F, -3.0F, 3, 5, 2, 0.0F);
      this.ventb_2 = new ModelRenderer(this, 55, 35);
      this.ventb_2.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.ventb_2.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 0, 0.0F);
      this.rightarm = new ModelRenderer(this, 40, 11);
      this.rightarm.setRotationPoint(-5.0F, 2.0F, 0.0F);
      this.rightarm.addBox(-3.2F, 2.0F, -2.0F, 4, 8, 4, 0.4F);
      this.ventb = new ModelRenderer(this, 55, 35);
      this.ventb.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.ventb.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 0, 0.0F);
      this.helm_4 = new ModelRenderer(this, 40, 0);
      this.helm_4.setRotationPoint(0.0F, 1.9F, 0.0F);
      this.helm_4.addBox(-2.0F, -4.8F, -6.8F, 4, 4, 3, 0.0F);
      this.chestGLOW = new ModelRendererGlow(this, 33, 56, this.lightt, false);
      this.chestGLOW.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.chestGLOW.addBox(-4.0F, 0.0F, -2.0F, 8, 4, 4, 0.5F);
      this.leftleg_1 = new ModelRenderer(this, 53, 23);
      this.leftleg_1.mirror = true;
      this.leftleg_1.setRotationPoint(1.1F, -0.5F, 0.5F);
      this.leftleg_1.addBox(1.0F, 0.0F, -4.0F, 2, 3, 3, 0.0F);
      this.setRotateAngle(this.leftleg_1, 0.0F, 0.3642502F, 0.0F);
      this.ventb_1 = new ModelRenderer(this, 55, 32);
      this.ventb_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.ventb_1.addBox(-1.5F, -1.5F, 0.0F, 3, 3, 0, 0.0F);
      this.chest_1 = new ModelRenderer(this, 28, 32);
      this.chest_1.setRotationPoint(0.0F, -0.7F, 0.0F);
      this.chest_1.addBox(-5.0F, 0.0F, -3.5F, 10, 6, 7, 0.0F);
      this.rarmGLOW = new ModelRendererGlow(this, 48, 52, this.lightt, false);
      this.rarmGLOW.setRotationPoint(-5.0F, 2.0F, 0.0F);
      this.rarmGLOW.addBox(-3.5F, -2.0F, -2.0F, 4, 3, 4, 0.4F);
      this.leftleg_2 = new ModelRenderer(this, 0, 54);
      this.leftleg_2.mirror = true;
      this.leftleg_2.setRotationPoint(1.1F, -0.5F, 0.5F);
      this.leftleg_2.addBox(-2.0F, 0.0F, 0.0F, 4, 3, 3, 0.0F);
      this.setRotateAngle(this.leftleg_2, 0.0F, 0.22759093F, 0.0F);
      this.leftarm = new ModelRenderer(this, 40, 11);
      this.leftarm.mirror = true;
      this.leftarm.setRotationPoint(5.0F, 2.0F, 0.0F);
      this.leftarm.addBox(-0.8F, 2.0F, -2.0F, 4, 8, 4, 0.4F);
      this.helm = new ModelRendererGlow(this, 0, 0, this.lightt, false);
      this.helm.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm.addBox(-4.0F, -8.0F, -4.0F, 8, 8, 8, 0.2F);
      this.larmGLOW = new ModelRendererGlow(this, 48, 52, this.lightt, false);
      this.larmGLOW.mirror = true;
      this.larmGLOW.setRotationPoint(5.0F, 2.0F, 0.0F);
      this.larmGLOW.addBox(-0.5F, -2.0F, -2.0F, 4, 3, 4, 0.4F);
      this.leftarm_2 = new ModelRenderer(this, 32, 5);
      this.leftarm_2.mirror = true;
      this.leftarm_2.setRotationPoint(3.6F, 8.5F, -1.0F);
      this.leftarm_2.addBox(0.0F, -7.0F, 0.0F, 0, 7, 3, 0.0F);
      this.setRotateAngle(this.leftarm_2, 0.0F, 0.31869712F, 0.0F);
      this.rightleg = new ModelRenderer(this, 0, 16);
      this.rightleg.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightleg.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 0.2F);
      this.rightboot = new ModelRenderer(this, 40, 24);
      this.rightboot.mirror = true;
      this.rightboot.setRotationPoint(-1.9F, 12.0F, 0.0F);
      this.rightboot.addBox(-2.2F, 9.0F, -2.5F, 4, 3, 5, 0.4F);
      this.leftarm_1 = new ModelRenderer(this, 40, 45);
      this.leftarm_1.mirror = true;
      this.leftarm_1.setRotationPoint(5.0F, 2.0F, 0.0F);
      this.leftarm_1.addBox(-6.5F, -5.0F, -3.0F, 6, 5, 6, 0.0F);
      this.venta_1 = new ModelRenderer(this, 0, 41);
      this.venta_1.setRotationPoint(-1.8F, 9.8F, -2.9F);
      this.venta_1.addBox(-1.4F, -1.5F, -0.5F, 3, 3, 1, 0.0F);
      this.helm_2 = new ModelRenderer(this, 24, 0);
      this.helm_2.setRotationPoint(-3.0F, -1.0F, -5.6F);
      this.helm_2.addBox(-2.5F, -1.5F, -0.5F, 5, 3, 3, 0.0F);
      this.setRotateAngle(this.helm_2, 0.0F, 0.4098033F, 0.18203785F);
      this.helm_1 = new ModelRenderer(this, 0, 35);
      this.helm_1.setRotationPoint(0.0F, 0.0F, 0.0F);
      this.helm_1.addBox(-4.5F, -8.5F, -5.3F, 9, 8, 10, 0.0F);
      this.rightarm_1 = new ModelRenderer(this, 40, 45);
      this.rightarm_1.mirror = true;
      this.rightarm_1.setRotationPoint(-4.5F, 2.0F, 0.0F);
      this.rightarm_1.addBox(0.0F, -5.0F, -3.0F, 6, 5, 6, 0.0F);
      this.chest.addChild(this.venta_2);
      this.rightleg.addChild(this.rightleg_1);
      this.rightleg.addChild(this.rightleg_2);
      this.rightarm.addChild(this.rightarm_2);
      this.helm_1.addChild(this.helm_3);
      this.chest.addChild(this.chest_3);
      this.chest.addChild(this.venta);
      this.chest.addChild(this.chest_2);
      this.venta_2.addChild(this.ventb_2);
      this.venta.addChild(this.ventb);
      this.helm_1.addChild(this.helm_4);
      this.leftleg.addChild(this.leftleg_1);
      this.venta_1.addChild(this.ventb_1);
      this.chest.addChild(this.chest_1);
      this.leftleg.addChild(this.leftleg_2);
      this.leftarm.addChild(this.leftarm_2);
      this.leftarm.addChild(this.leftarm_1);
      this.chest.addChild(this.venta_1);
      this.helm_1.addChild(this.helm_2);
      this.rightarm.addChild(this.rightarm_1);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      if (entity.isSneaking()) {
         GlStateManager.translate(0.0F, 0.2F, 0.0F);
      }

      AbstractMobModel.copyModel(this.rightarm, this.rarmGLOW);
      AbstractMobModel.copyModel(this.leftarm, this.larmGLOW);
      AbstractMobModel.copyModel(this.chest, this.chestGLOW);
      AbstractMobModel.copyModel(this.helm, this.helm_1);
      this.ventb.rotateAngleZ = AnimationTimer.tick * 0.1F;
      this.ventb_1.rotateAngleZ = AnimationTimer.tick * -0.1F;
      this.ventb_2.rotateAngleZ = AnimationTimer.tick * -0.05F;
      this.rarmGLOW.render(f5);
      this.larmGLOW.render(f5);
      this.chestGLOW.render(f5);
      this.helm.render(f5);
      this.leftboot.render(f5);
      this.rightboot.render(f5);
      this.chest.render(f5);
      this.helm_1.render(f5);
      this.leftarm.render(f5);
      this.rightarm.render(f5);
      this.rightleg.render(f5);
      this.leftleg.render(f5);
      GlStateManager.popMatrix();
   }

   public void setModelAttributes(ModelBase model) {
      super.setModelAttributes(model);
      if (model instanceof ModelBiped) {
         ModelBiped modelbiped = (ModelBiped)model;
         this.rightarm.rotateAngleX = modelbiped.bipedRightArm.rotateAngleX;
         this.rightarm.rotateAngleY = modelbiped.bipedRightArm.rotateAngleY;
         this.rightarm.rotateAngleZ = modelbiped.bipedRightArm.rotateAngleZ;
         this.leftarm.rotateAngleX = modelbiped.bipedLeftArm.rotateAngleX;
         this.leftarm.rotateAngleY = modelbiped.bipedLeftArm.rotateAngleY;
         this.leftarm.rotateAngleZ = modelbiped.bipedLeftArm.rotateAngleZ;
         this.helm.rotateAngleX = modelbiped.bipedHead.rotateAngleX;
         this.helm.rotateAngleY = modelbiped.bipedHead.rotateAngleY;
         this.helm.rotateAngleZ = modelbiped.bipedHead.rotateAngleZ;
         this.chest.rotateAngleX = modelbiped.bipedBody.rotateAngleX;
         this.chest.rotateAngleY = modelbiped.bipedBody.rotateAngleY;
         this.chest.rotateAngleZ = modelbiped.bipedBody.rotateAngleZ;
         this.rightleg.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightleg.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightleg.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftleg.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftleg.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftleg.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightboot.rotateAngleX = modelbiped.bipedRightLeg.rotateAngleX;
         this.rightboot.rotateAngleY = modelbiped.bipedRightLeg.rotateAngleY;
         this.rightboot.rotateAngleZ = modelbiped.bipedRightLeg.rotateAngleZ;
         this.leftboot.rotateAngleX = modelbiped.bipedLeftLeg.rotateAngleX;
         this.leftboot.rotateAngleY = modelbiped.bipedLeftLeg.rotateAngleY;
         this.leftboot.rotateAngleZ = modelbiped.bipedLeftLeg.rotateAngleZ;
         this.rightarm.rotationPointX = modelbiped.bipedRightArm.rotationPointX;
         this.rightarm.rotationPointY = modelbiped.bipedRightArm.rotationPointY;
         this.rightarm.rotationPointZ = modelbiped.bipedRightArm.rotationPointZ;
         this.leftarm.rotationPointX = modelbiped.bipedLeftArm.rotationPointX;
         this.leftarm.rotationPointY = modelbiped.bipedLeftArm.rotationPointY;
         this.leftarm.rotationPointZ = modelbiped.bipedLeftArm.rotationPointZ;
         this.helm.rotationPointX = modelbiped.bipedHead.rotationPointX;
         this.helm.rotationPointY = modelbiped.bipedHead.rotationPointY;
         this.helm.rotationPointZ = modelbiped.bipedHead.rotationPointZ;
         this.chest.rotationPointX = modelbiped.bipedBody.rotationPointX;
         this.chest.rotationPointY = modelbiped.bipedBody.rotationPointY;
         this.chest.rotationPointZ = modelbiped.bipedBody.rotationPointZ;
         this.rightleg.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightleg.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightleg.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftleg.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftleg.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftleg.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
         this.rightboot.rotationPointX = modelbiped.bipedRightLeg.rotationPointX;
         this.rightboot.rotationPointY = modelbiped.bipedRightLeg.rotationPointY;
         this.rightboot.rotationPointZ = modelbiped.bipedRightLeg.rotationPointZ;
         this.leftboot.rotationPointX = modelbiped.bipedLeftLeg.rotationPointX;
         this.leftboot.rotationPointY = modelbiped.bipedLeftLeg.rotationPointY;
         this.leftboot.rotationPointZ = modelbiped.bipedLeftLeg.rotationPointZ;
      }
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
