package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class VacuumGunModel extends ModelBase {
   public ModelRenderer shapess1;
   public ModelRenderer shape;
   public ModelRenderer core;
   public ModelRenderer shape_1;
   public ModelRenderer shape_2;
   public ModelRenderer shape_3;
   public ModelRenderer shape_4;
   public ModelRenderer shape_5;
   public ModelRenderer shape_6;
   public ModelRenderer shape_7;
   public ModelRenderer shape_8;
   public ModelRenderer shape_9;
   public ModelRenderer shape_10;
   public ModelRenderer crystal;
   public ModelRenderer crystal_1;
   public ModelRenderer crystal_2;
   public ModelRenderer crystal_3;
   public ModelRenderer crystal_4;
   public ModelRenderer crystal_5;
   public ModelRenderer crystal_6;
   public ModelRenderer crystal_7;
   public ModelRenderer crystal_8;
   public ModelRenderer crystal_9;
   public ModelRenderer crystal_10;
   public ModelRenderer colb;

   public VacuumGunModel() {
      this.textureWidth = 22;
      this.textureHeight = 24;
      this.crystal_6 = new ModelRenderer(this, 0, 0);
      this.crystal_6.setRotationPoint(0.0F, 0.1F, 1.8F);
      this.crystal_6.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.crystal_6, (float) (-Math.PI / 3), -1.6845918F, 1.9577358F);
      this.shape_1 = new ModelRenderer(this, 0, 0);
      this.shape_1.setRotationPoint(0.0F, -1.0F, 3.4F);
      this.shape_1.addBox(-1.5F, -0.5F, 0.0F, 3, 3, 5, 0.0F);
      this.crystal_5 = new ModelRenderer(this, 0, 0);
      this.crystal_5.setRotationPoint(0.0F, -0.2F, 1.1F);
      this.crystal_5.addBox(-0.5F, 0.0F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.crystal_5, -1.3203416F, -1.0927507F, 1.4570009F);
      this.shape_9 = new ModelRenderer(this, 0, 18);
      this.shape_9.setRotationPoint(0.0F, -0.7F, 13.0F);
      this.shape_9.addBox(-0.5F, 0.0F, 0.0F, 1, 2, 3, 0.0F);
      this.setRotateAngle(this.shape_9, -0.4098033F, 0.0F, 0.0F);
      this.shape_5 = new ModelRenderer(this, 6, 18);
      this.shape_5.setRotationPoint(0.0F, -2.8F, -6.5F);
      this.shape_5.addBox(-0.5F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shape_5, -0.3642502F, 0.0F, 0.0F);
      this.shape = new ModelRenderer(this, 8, 18);
      this.shape.setRotationPoint(0.0F, -1.0F, -3.5F);
      this.shape.addBox(-1.5F, -0.5F, 0.0F, 3, 3, 3, 0.0F);
      this.shape_8 = new ModelRenderer(this, 0, 18);
      this.shape_8.setRotationPoint(0.0F, -1.2F, 10.6F);
      this.shape_8.addBox(-0.5F, 0.0F, 0.0F, 1, 2, 3, 0.0F);
      this.setRotateAngle(this.shape_8, -0.091106184F, 0.0F, 0.0F);
      this.shape_2 = new ModelRenderer(this, 15, 0);
      this.shape_2.setRotationPoint(0.0F, -1.0F, -4.5F);
      this.shape_2.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shape_4 = new ModelRenderer(this, 11, 0);
      this.shape_4.setRotationPoint(0.0F, 1.0F, -3.3F);
      this.shape_4.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape_4, -2.276433F, 0.0F, (float) Math.PI);
      this.shapess1 = new ModelRenderer(this, 15, 6);
      this.shapess1.setRotationPoint(0.0F, 1.9F, 4.4F);
      this.shapess1.addBox(-0.5F, -0.5F, 0.0F, 1, 5, 2, 0.0F);
      this.setRotateAngle(this.shapess1, 0.5009095F, 0.0F, 0.0F);
      this.shape_7 = new ModelRenderer(this, 0, 18);
      this.shape_7.setRotationPoint(0.0F, -1.1F, 8.1F);
      this.shape_7.addBox(-0.5F, 0.0F, 0.0F, 1, 2, 3, 0.0F);
      this.setRotateAngle(this.shape_7, 0.18203785F, 0.0F, 0.0F);
      this.shape_3 = new ModelRenderer(this, 11, 0);
      this.shape_3.setRotationPoint(0.0F, -1.0F, -3.3F);
      this.shape_3.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape_3, -2.276433F, 0.0F, 0.0F);
      this.crystal_1 = new ModelRenderer(this, 0, 0);
      this.crystal_1.setRotationPoint(0.0F, 0.1F, 1.5F);
      this.crystal_1.addBox(-0.5F, 0.0F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.crystal_1, (float) -Math.PI, 0.68294734F, 0.95609134F);
      this.crystal_8 = new ModelRenderer(this, 0, 0);
      this.crystal_8.setRotationPoint(0.0F, 0.1F, 1.3F);
      this.crystal_8.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.crystal_8, -1.3658947F, -1.9577358F, 0.7740535F);
      this.crystal_4 = new ModelRenderer(this, 0, 0);
      this.crystal_4.setRotationPoint(0.0F, 0.1F, 1.1F);
      this.crystal_4.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.crystal_4, -0.22759093F, -1.3203416F, 2.2310543F);
      this.shape_6 = new ModelRenderer(this, 6, 18);
      this.shape_6.setRotationPoint(0.0F, 2.8F, -6.5F);
      this.shape_6.addBox(-0.5F, 0.0F, -1.0F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.shape_6, -2.7773426F, 0.0F, 0.0F);
      this.crystal_3 = new ModelRenderer(this, 0, 0);
      this.crystal_3.setRotationPoint(0.0F, 0.1F, 2.0F);
      this.crystal_3.addBox(-0.5F, 0.0F, 0.0F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.crystal_3, 0.22759093F, -0.68294734F, 1.9123572F);
      this.crystal_9 = new ModelRenderer(this, 0, 0);
      this.crystal_9.setRotationPoint(0.0F, 0.1F, 2.5F);
      this.crystal_9.addBox(-0.5F, 0.0F, -0.5F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.crystal_9, -1.3658947F, -1.821251F, 1.1838568F);
      this.crystal = new ModelRenderer(this, 0, 0);
      this.crystal.setRotationPoint(0.0F, -0.4F, 0.9F);
      this.crystal.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.crystal, -2.8684487F, 0.31869712F, -0.13665928F);
      this.crystal_7 = new ModelRenderer(this, 0, 0);
      this.crystal_7.setRotationPoint(0.0F, 0.1F, 0.3F);
      this.crystal_7.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.crystal_7, 3.0504866F, -2.1855013F, 2.003289F);
      this.shape_10 = new ModelRenderer(this, 0, 9);
      this.shape_10.setRotationPoint(0.0F, 0.1F, 15.2F);
      this.shape_10.addBox(-0.5F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.shape_10, -0.4098033F, 0.0F, 0.0F);
      this.colb = new ModelRenderer(this, 0, 8);
      this.colb.setRotationPoint(0.0F, -2.0F, -1.0F);
      this.colb.addBox(-2.5F, -0.5F, 0.0F, 5, 5, 5, 0.0F);
      this.core = new ModelRenderer(this, 0, 0);
      this.core.setRotationPoint(0.0F, 0.0F, -0.5F);
      this.core.addBox(-0.5F, 0.0F, -0.5F, 1, 4, 1, 0.0F);
      this.setRotateAngle(this.core, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.crystal_10 = new ModelRenderer(this, 0, 0);
      this.crystal_10.setRotationPoint(0.0F, 0.1F, 0.9F);
      this.crystal_10.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.setRotateAngle(this.crystal_10, -2.6406832F, 0.31869712F, -1.5025539F);
      this.crystal_2 = new ModelRenderer(this, 0, 0);
      this.crystal_2.setRotationPoint(0.0F, 0.1F, 2.5F);
      this.crystal_2.addBox(-0.5F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
      this.setRotateAngle(this.crystal_2, 2.7317894F, 1.0016445F, 0.95609134F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      float lbX = OpenGlHelper.lastBrightnessX;
      float lbY = OpenGlHelper.lastBrightnessY;
      this.shape_1.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_9.offsetX, this.shape_9.offsetY, this.shape_9.offsetZ);
      GlStateManager.translate(this.shape_9.rotationPointX * f5, this.shape_9.rotationPointY * f5, this.shape_9.rotationPointZ * f5);
      GlStateManager.scale(0.8, 0.9, 0.9);
      GlStateManager.translate(-this.shape_9.offsetX, -this.shape_9.offsetY, -this.shape_9.offsetZ);
      GlStateManager.translate(-this.shape_9.rotationPointX * f5, -this.shape_9.rotationPointY * f5, -this.shape_9.rotationPointZ * f5);
      this.shape_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_5.offsetX, this.shape_5.offsetY, this.shape_5.offsetZ);
      GlStateManager.translate(this.shape_5.rotationPointX * f5, this.shape_5.rotationPointY * f5, this.shape_5.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shape_5.offsetX, -this.shape_5.offsetY, -this.shape_5.offsetZ);
      GlStateManager.translate(-this.shape_5.rotationPointX * f5, -this.shape_5.rotationPointY * f5, -this.shape_5.rotationPointZ * f5);
      this.shape_5.render(f5);
      GlStateManager.popMatrix();
      this.shape.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_8.offsetX, this.shape_8.offsetY, this.shape_8.offsetZ);
      GlStateManager.translate(this.shape_8.rotationPointX * f5, this.shape_8.rotationPointY * f5, this.shape_8.rotationPointZ * f5);
      GlStateManager.scale(0.9, 0.9, 0.9);
      GlStateManager.translate(-this.shape_8.offsetX, -this.shape_8.offsetY, -this.shape_8.offsetZ);
      GlStateManager.translate(-this.shape_8.rotationPointX * f5, -this.shape_8.rotationPointY * f5, -this.shape_8.rotationPointZ * f5);
      this.shape_8.render(f5);
      GlStateManager.popMatrix();
      this.shape_2.render(f5);
      this.shape_4.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1.offsetX, this.shapess1.offsetY, this.shapess1.offsetZ);
      GlStateManager.translate(this.shapess1.rotationPointX * f5, this.shapess1.rotationPointY * f5, this.shapess1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.0, 0.9);
      GlStateManager.translate(-this.shapess1.offsetX, -this.shapess1.offsetY, -this.shapess1.offsetZ);
      GlStateManager.translate(-this.shapess1.rotationPointX * f5, -this.shapess1.rotationPointY * f5, -this.shapess1.rotationPointZ * f5);
      this.shapess1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_7.offsetX, this.shape_7.offsetY, this.shape_7.offsetZ);
      GlStateManager.translate(this.shape_7.rotationPointX * f5, this.shape_7.rotationPointY * f5, this.shape_7.rotationPointZ * f5);
      GlStateManager.scale(1.1, 0.9, 0.9);
      GlStateManager.translate(-this.shape_7.offsetX, -this.shape_7.offsetY, -this.shape_7.offsetZ);
      GlStateManager.translate(-this.shape_7.rotationPointX * f5, -this.shape_7.rotationPointY * f5, -this.shape_7.rotationPointZ * f5);
      this.shape_7.render(f5);
      GlStateManager.popMatrix();
      this.shape_3.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_6.offsetX, this.shape_6.offsetY, this.shape_6.offsetZ);
      GlStateManager.translate(this.shape_6.rotationPointX * f5, this.shape_6.rotationPointY * f5, this.shape_6.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.shape_6.offsetX, -this.shape_6.offsetY, -this.shape_6.offsetZ);
      GlStateManager.translate(-this.shape_6.rotationPointX * f5, -this.shape_6.rotationPointY * f5, -this.shape_6.rotationPointZ * f5);
      this.shape_6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shape_10.offsetX, this.shape_10.offsetY, this.shape_10.offsetZ);
      GlStateManager.translate(this.shape_10.rotationPointX * f5, this.shape_10.rotationPointY * f5, this.shape_10.rotationPointZ * f5);
      GlStateManager.scale(1.1, 0.9, 0.9);
      GlStateManager.translate(-this.shape_10.offsetX, -this.shape_10.offsetY, -this.shape_10.offsetZ);
      GlStateManager.translate(-this.shape_10.rotationPointX * f5, -this.shape_10.rotationPointY * f5, -this.shape_10.rotationPointZ * f5);
      this.shape_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GL11.glDisable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, 200.0F, 200.0F);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_6.offsetX, this.crystal_6.offsetY, this.crystal_6.offsetZ);
      GlStateManager.translate(this.crystal_6.rotationPointX * f5, this.crystal_6.rotationPointY * f5, this.crystal_6.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_6.offsetX, -this.crystal_6.offsetY, -this.crystal_6.offsetZ);
      GlStateManager.translate(-this.crystal_6.rotationPointX * f5, -this.crystal_6.rotationPointY * f5, -this.crystal_6.rotationPointZ * f5);
      this.crystal_6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_5.offsetX, this.crystal_5.offsetY, this.crystal_5.offsetZ);
      GlStateManager.translate(this.crystal_5.rotationPointX * f5, this.crystal_5.rotationPointY * f5, this.crystal_5.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_5.offsetX, -this.crystal_5.offsetY, -this.crystal_5.offsetZ);
      GlStateManager.translate(-this.crystal_5.rotationPointX * f5, -this.crystal_5.rotationPointY * f5, -this.crystal_5.rotationPointZ * f5);
      this.crystal_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_1.offsetX, this.crystal_1.offsetY, this.crystal_1.offsetZ);
      GlStateManager.translate(this.crystal_1.rotationPointX * f5, this.crystal_1.rotationPointY * f5, this.crystal_1.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_1.offsetX, -this.crystal_1.offsetY, -this.crystal_1.offsetZ);
      GlStateManager.translate(-this.crystal_1.rotationPointX * f5, -this.crystal_1.rotationPointY * f5, -this.crystal_1.rotationPointZ * f5);
      this.crystal_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_8.offsetX, this.crystal_8.offsetY, this.crystal_8.offsetZ);
      GlStateManager.translate(this.crystal_8.rotationPointX * f5, this.crystal_8.rotationPointY * f5, this.crystal_8.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_8.offsetX, -this.crystal_8.offsetY, -this.crystal_8.offsetZ);
      GlStateManager.translate(-this.crystal_8.rotationPointX * f5, -this.crystal_8.rotationPointY * f5, -this.crystal_8.rotationPointZ * f5);
      this.crystal_8.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_4.offsetX, this.crystal_4.offsetY, this.crystal_4.offsetZ);
      GlStateManager.translate(this.crystal_4.rotationPointX * f5, this.crystal_4.rotationPointY * f5, this.crystal_4.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_4.offsetX, -this.crystal_4.offsetY, -this.crystal_4.offsetZ);
      GlStateManager.translate(-this.crystal_4.rotationPointX * f5, -this.crystal_4.rotationPointY * f5, -this.crystal_4.rotationPointZ * f5);
      this.crystal_4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_3.offsetX, this.crystal_3.offsetY, this.crystal_3.offsetZ);
      GlStateManager.translate(this.crystal_3.rotationPointX * f5, this.crystal_3.rotationPointY * f5, this.crystal_3.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_3.offsetX, -this.crystal_3.offsetY, -this.crystal_3.offsetZ);
      GlStateManager.translate(-this.crystal_3.rotationPointX * f5, -this.crystal_3.rotationPointY * f5, -this.crystal_3.rotationPointZ * f5);
      this.crystal_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_9.offsetX, this.crystal_9.offsetY, this.crystal_9.offsetZ);
      GlStateManager.translate(this.crystal_9.rotationPointX * f5, this.crystal_9.rotationPointY * f5, this.crystal_9.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_9.offsetX, -this.crystal_9.offsetY, -this.crystal_9.offsetZ);
      GlStateManager.translate(-this.crystal_9.rotationPointX * f5, -this.crystal_9.rotationPointY * f5, -this.crystal_9.rotationPointZ * f5);
      this.crystal_9.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal.offsetX, this.crystal.offsetY, this.crystal.offsetZ);
      GlStateManager.translate(this.crystal.rotationPointX * f5, this.crystal.rotationPointY * f5, this.crystal.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal.offsetX, -this.crystal.offsetY, -this.crystal.offsetZ);
      GlStateManager.translate(-this.crystal.rotationPointX * f5, -this.crystal.rotationPointY * f5, -this.crystal.rotationPointZ * f5);
      this.crystal.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_7.offsetX, this.crystal_7.offsetY, this.crystal_7.offsetZ);
      GlStateManager.translate(this.crystal_7.rotationPointX * f5, this.crystal_7.rotationPointY * f5, this.crystal_7.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_7.offsetX, -this.crystal_7.offsetY, -this.crystal_7.offsetZ);
      GlStateManager.translate(-this.crystal_7.rotationPointX * f5, -this.crystal_7.rotationPointY * f5, -this.crystal_7.rotationPointZ * f5);
      this.crystal_7.render(f5);
      GlStateManager.popMatrix();
      this.core.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_10.offsetX, this.crystal_10.offsetY, this.crystal_10.offsetZ);
      GlStateManager.translate(this.crystal_10.rotationPointX * f5, this.crystal_10.rotationPointY * f5, this.crystal_10.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_10.offsetX, -this.crystal_10.offsetY, -this.crystal_10.offsetZ);
      GlStateManager.translate(-this.crystal_10.rotationPointX * f5, -this.crystal_10.rotationPointY * f5, -this.crystal_10.rotationPointZ * f5);
      this.crystal_10.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_2.offsetX, this.crystal_2.offsetY, this.crystal_2.offsetZ);
      GlStateManager.translate(this.crystal_2.rotationPointX * f5, this.crystal_2.rotationPointY * f5, this.crystal_2.rotationPointZ * f5);
      GlStateManager.scale(0.7, 0.7, 0.7);
      GlStateManager.translate(-this.crystal_2.offsetX, -this.crystal_2.offsetY, -this.crystal_2.offsetZ);
      GlStateManager.translate(-this.crystal_2.rotationPointX * f5, -this.crystal_2.rotationPointY * f5, -this.crystal_2.rotationPointZ * f5);
      this.crystal_2.render(f5);
      GlStateManager.popMatrix();
      GL11.glEnable(2896);
      OpenGlHelper.setLightmapTextureCoords(OpenGlHelper.lightmapTexUnit, lbX, lbY);
      GlStateManager.popMatrix();
      this.colb.render(f5);
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
