//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class ViolenceModel extends ModelBase {
   public ModelRenderer staf;
   public ModelRenderer gem1;
   public ModelRenderer gem2;
   public ModelRenderer crystalM;
   public ModelRenderer crystalM_1;
   public ModelRenderer crystalM_2;
   public ModelRenderer crystalM_3;
   public ModelRenderer crystalM_4;
   public ModelRenderer crystalM_5;
   public ModelRenderer crystalM_6;
   public ModelRenderer crystalM_7;
   public ModelRenderer crystal;
   public ModelRenderer crystal_1;
   public ModelRenderer crystal_2;
   public ModelRenderer crystal_3;
   public ModelRenderer crystal_4;
   public ModelRenderer crystal_5;
   public ModelRenderer gemdown;

   public ViolenceModel() {
      this.textureWidth = 32;
      this.textureHeight = 32;
      this.crystalM = new ModelRenderer(this, 0, 0);
      this.crystalM.setRotationPoint(0.0F, -8.0F, 5.0F);
      this.crystalM.addBox(-1.0F, -5.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.crystalM, -0.091106184F, 0.63739425F, 0.8651597F);
      this.crystal_3 = new ModelRenderer(this, 0, 23);
      this.crystal_3.setRotationPoint(0.0F, 3.5F, 5.0F);
      this.crystal_3.addBox(-1.0F, -3.7F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.crystal_3, -0.7740535F, -2.7773426F, -0.91053826F);
      this.crystal_2 = new ModelRenderer(this, 0, 23);
      this.crystal_2.setRotationPoint(0.0F, 1.0F, 5.0F);
      this.crystal_2.addBox(-1.0F, -3.2F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.crystal_2, -2.003289F, 2.5953045F, -0.7740535F);
      this.crystal = new ModelRenderer(this, 0, 19);
      this.crystal.setRotationPoint(0.0F, -3.0F, 5.0F);
      this.crystal.addBox(-1.0F, -2.9F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.crystal, -1.2747885F, -0.27314404F, 0.8651597F);
      this.gemdown = new ModelRenderer(this, 16, 6);
      this.gemdown.setRotationPoint(0.0F, 28.3F, 5.0F);
      this.gemdown.addBox(-1.0F, -1.0F, -0.5F, 2, 2, 1, 0.0F);
      this.setRotateAngle(this.gemdown, -0.18203785F, 0.13665928F, -0.6195919F);
      this.gem1 = new ModelRenderer(this, 16, 0);
      this.gem1.mirror = true;
      this.gem1.setRotationPoint(0.0F, -16.0F, 5.0F);
      this.gem1.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.gem1, 0.68294734F, 0.0F, -0.6195919F);
      this.gem2 = new ModelRenderer(this, 16, 0);
      this.gem2.setRotationPoint(0.0F, -16.0F, 5.0F);
      this.gem2.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3, 0.0F);
      this.setRotateAngle(this.gem2, 0.68294734F, 0.0F, 0.6195919F);
      this.crystalM_1 = new ModelRenderer(this, 0, 6);
      this.crystalM_1.setRotationPoint(0.0F, -8.0F, 5.0F);
      this.crystalM_1.addBox(-1.0F, -4.0F, -1.0F, 2, 3, 2, 0.0F);
      this.setRotateAngle(this.crystalM_1, 1.2747885F, 0.59184116F, 0.8651597F);
      this.crystalM_5 = new ModelRenderer(this, 0, 27);
      this.crystalM_5.setRotationPoint(0.0F, -4.0F, 5.0F);
      this.crystalM_5.addBox(-1.0F, -4.6F, -1.0F, 2, 3, 2, 0.0F);
      this.setRotateAngle(this.crystalM_5, 2.003289F, 1.2292354F, (float) (Math.PI / 3));
      this.crystalM_2 = new ModelRenderer(this, 0, 0);
      this.crystalM_2.setRotationPoint(0.0F, -7.3F, 5.0F);
      this.crystalM_2.addBox(-1.0F, -5.0F, -1.0F, 2, 4, 2, 0.0F);
      this.setRotateAngle(this.crystalM_2, -0.13665928F, 0.63739425F, -0.91053826F);
      this.crystalM_7 = new ModelRenderer(this, 0, 14);
      this.crystalM_7.setRotationPoint(0.0F, -5.0F, 5.0F);
      this.crystalM_7.addBox(-1.0F, -4.6F, -1.0F, 2, 3, 2, 0.0F);
      this.setRotateAngle(this.crystalM_7, 0.5462881F, -0.18203785F, 0.63739425F);
      this.crystalM_4 = new ModelRenderer(this, 0, 27);
      this.crystalM_4.setRotationPoint(0.0F, -5.0F, 5.0F);
      this.crystalM_4.addBox(-1.0F, -4.6F, -1.0F, 2, 3, 2, 0.0F);
      this.setRotateAngle(this.crystalM_4, -0.4553564F, 0.4553564F, 0.8651597F);
      this.crystal_4 = new ModelRenderer(this, 0, 23);
      this.crystal_4.setRotationPoint(0.0F, 5.5F, 5.0F);
      this.crystal_4.addBox(-1.0F, -3.7F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.crystal_4, -0.4553564F, -0.95609134F, -0.95609134F);
      this.staf = new ModelRenderer(this, 8, -2);
      this.staf.setRotationPoint(0.0F, -9.0F, 5.0F);
      this.staf.addBox(-1.0F, 0.0F, -1.0F, 2, 32, 2, 0.0F);
      this.crystalM_6 = new ModelRenderer(this, 0, 14);
      this.crystalM_6.setRotationPoint(0.0F, -6.0F, 5.0F);
      this.crystalM_6.addBox(-1.0F, -4.6F, -1.0F, 2, 3, 2, 0.0F);
      this.setRotateAngle(this.crystalM_6, -0.68294734F, -0.27314404F, -0.7285004F);
      this.crystal_1 = new ModelRenderer(this, 0, 19);
      this.crystal_1.setRotationPoint(0.0F, -1.0F, 5.0F);
      this.crystal_1.addBox(-1.0F, -2.9F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.crystal_1, -1.9123572F, 1.0927507F, -0.7740535F);
      this.crystalM_3 = new ModelRenderer(this, 0, 6);
      this.crystalM_3.setRotationPoint(0.0F, -7.6F, 5.0F);
      this.crystalM_3.addBox(-1.0F, -5.9F, -1.0F, 2, 5, 2, 0.0F);
      this.setRotateAngle(this.crystalM_3, (float) (-Math.PI / 3), -0.5009095F, 0.91053826F);
      this.crystal_5 = new ModelRenderer(this, 0, 23);
      this.crystal_5.setRotationPoint(0.0F, 7.5F, 5.0F);
      this.crystal_5.addBox(-1.0F, -3.7F, -1.0F, 2, 2, 2, 0.0F);
      this.setRotateAngle(this.crystal_5, -1.3658947F, -0.4098033F, -0.31869712F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.staf.offsetX, this.staf.offsetY, this.staf.offsetZ);
      GlStateManager.translate(this.staf.rotationPointX * f5, this.staf.rotationPointY * f5, this.staf.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.1, 0.9);
      GlStateManager.translate(-this.staf.offsetX, -this.staf.offsetY, -this.staf.offsetZ);
      GlStateManager.translate(-this.staf.rotationPointX * f5, -this.staf.rotationPointY * f5, -this.staf.rotationPointZ * f5);
      this.staf.render(f5);
      GlStateManager.popMatrix();
      AbstractMobModel.light(110, true);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_2.offsetX, this.crystal_2.offsetY, this.crystal_2.offsetZ);
      GlStateManager.translate(this.crystal_2.rotationPointX * f5, this.crystal_2.rotationPointY * f5, this.crystal_2.rotationPointZ * f5);
      GlStateManager.scale(0.5, 1.05, 0.5);
      GlStateManager.translate(-this.crystal_2.offsetX, -this.crystal_2.offsetY, -this.crystal_2.offsetZ);
      GlStateManager.translate(-this.crystal_2.rotationPointX * f5, -this.crystal_2.rotationPointY * f5, -this.crystal_2.rotationPointZ * f5);
      this.crystal_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_4.offsetX, this.crystal_4.offsetY, this.crystal_4.offsetZ);
      GlStateManager.translate(this.crystal_4.rotationPointX * f5, this.crystal_4.rotationPointY * f5, this.crystal_4.rotationPointZ * f5);
      GlStateManager.scale(0.4, 0.9, 0.4);
      GlStateManager.translate(-this.crystal_4.offsetX, -this.crystal_4.offsetY, -this.crystal_4.offsetZ);
      GlStateManager.translate(-this.crystal_4.rotationPointX * f5, -this.crystal_4.rotationPointY * f5, -this.crystal_4.rotationPointZ * f5);
      this.crystal_4.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.gemdown.offsetX, this.gemdown.offsetY, this.gemdown.offsetZ);
      GlStateManager.translate(this.gemdown.rotationPointX * f5, this.gemdown.rotationPointY * f5, this.gemdown.rotationPointZ * f5);
      GlStateManager.scale(1.0, 2.9, 1.0);
      GlStateManager.translate(-this.gemdown.offsetX, -this.gemdown.offsetY, -this.gemdown.offsetZ);
      GlStateManager.translate(-this.gemdown.rotationPointX * f5, -this.gemdown.rotationPointY * f5, -this.gemdown.rotationPointZ * f5);
      this.gemdown.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM.offsetX, this.crystalM.offsetY, this.crystalM.offsetZ);
      GlStateManager.translate(this.crystalM.rotationPointX * f5, this.crystalM.rotationPointY * f5, this.crystalM.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.9, 0.9);
      GlStateManager.translate(-this.crystalM.offsetX, -this.crystalM.offsetY, -this.crystalM.offsetZ);
      GlStateManager.translate(-this.crystalM.rotationPointX * f5, -this.crystalM.rotationPointY * f5, -this.crystalM.rotationPointZ * f5);
      this.crystalM.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_3.offsetX, this.crystal_3.offsetY, this.crystal_3.offsetZ);
      GlStateManager.translate(this.crystal_3.rotationPointX * f5, this.crystal_3.rotationPointY * f5, this.crystal_3.rotationPointZ * f5);
      GlStateManager.scale(0.45, 1.0, 0.45);
      GlStateManager.translate(-this.crystal_3.offsetX, -this.crystal_3.offsetY, -this.crystal_3.offsetZ);
      GlStateManager.translate(-this.crystal_3.rotationPointX * f5, -this.crystal_3.rotationPointY * f5, -this.crystal_3.rotationPointZ * f5);
      this.crystal_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_1.offsetX, this.crystal_1.offsetY, this.crystal_1.offsetZ);
      GlStateManager.translate(this.crystal_1.rotationPointX * f5, this.crystal_1.rotationPointY * f5, this.crystal_1.rotationPointZ * f5);
      GlStateManager.scale(0.55, 1.1, 0.65);
      GlStateManager.translate(-this.crystal_1.offsetX, -this.crystal_1.offsetY, -this.crystal_1.offsetZ);
      GlStateManager.translate(-this.crystal_1.rotationPointX * f5, -this.crystal_1.rotationPointY * f5, -this.crystal_1.rotationPointZ * f5);
      this.crystal_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal_5.offsetX, this.crystal_5.offsetY, this.crystal_5.offsetZ);
      GlStateManager.translate(this.crystal_5.rotationPointX * f5, this.crystal_5.rotationPointY * f5, this.crystal_5.rotationPointZ * f5);
      GlStateManager.scale(0.35, 0.85, 0.35);
      GlStateManager.translate(-this.crystal_5.offsetX, -this.crystal_5.offsetY, -this.crystal_5.offsetZ);
      GlStateManager.translate(-this.crystal_5.rotationPointX * f5, -this.crystal_5.rotationPointY * f5, -this.crystal_5.rotationPointZ * f5);
      this.crystal_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM_2.offsetX, this.crystalM_2.offsetY, this.crystalM_2.offsetZ);
      GlStateManager.translate(this.crystalM_2.rotationPointX * f5, this.crystalM_2.rotationPointY * f5, this.crystalM_2.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.9, 0.9);
      GlStateManager.translate(-this.crystalM_2.offsetX, -this.crystalM_2.offsetY, -this.crystalM_2.offsetZ);
      GlStateManager.translate(-this.crystalM_2.rotationPointX * f5, -this.crystalM_2.rotationPointY * f5, -this.crystalM_2.rotationPointZ * f5);
      this.crystalM_2.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystal.offsetX, this.crystal.offsetY, this.crystal.offsetZ);
      GlStateManager.translate(this.crystal.rotationPointX * f5, this.crystal.rotationPointY * f5, this.crystal.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.2, 0.7);
      GlStateManager.translate(-this.crystal.offsetX, -this.crystal.offsetY, -this.crystal.offsetZ);
      GlStateManager.translate(-this.crystal.rotationPointX * f5, -this.crystal.rotationPointY * f5, -this.crystal.rotationPointZ * f5);
      this.crystal.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM_6.offsetX, this.crystalM_6.offsetY, this.crystalM_6.offsetZ);
      GlStateManager.translate(this.crystalM_6.rotationPointX * f5, this.crystalM_6.rotationPointY * f5, this.crystalM_6.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.4, 0.7);
      GlStateManager.translate(-this.crystalM_6.offsetX, -this.crystalM_6.offsetY, -this.crystalM_6.offsetZ);
      GlStateManager.translate(-this.crystalM_6.rotationPointX * f5, -this.crystalM_6.rotationPointY * f5, -this.crystalM_6.rotationPointZ * f5);
      this.crystalM_6.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM_3.offsetX, this.crystalM_3.offsetY, this.crystalM_3.offsetZ);
      GlStateManager.translate(this.crystalM_3.rotationPointX * f5, this.crystalM_3.rotationPointY * f5, this.crystalM_3.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.9, 0.6);
      GlStateManager.translate(-this.crystalM_3.offsetX, -this.crystalM_3.offsetY, -this.crystalM_3.offsetZ);
      GlStateManager.translate(-this.crystalM_3.rotationPointX * f5, -this.crystalM_3.rotationPointY * f5, -this.crystalM_3.rotationPointZ * f5);
      this.crystalM_3.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM_5.offsetX, this.crystalM_5.offsetY, this.crystalM_5.offsetZ);
      GlStateManager.translate(this.crystalM_5.rotationPointX * f5, this.crystalM_5.rotationPointY * f5, this.crystalM_5.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.4, 0.7);
      GlStateManager.translate(-this.crystalM_5.offsetX, -this.crystalM_5.offsetY, -this.crystalM_5.offsetZ);
      GlStateManager.translate(-this.crystalM_5.rotationPointX * f5, -this.crystalM_5.rotationPointY * f5, -this.crystalM_5.rotationPointZ * f5);
      this.crystalM_5.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM_7.offsetX, this.crystalM_7.offsetY, this.crystalM_7.offsetZ);
      GlStateManager.translate(this.crystalM_7.rotationPointX * f5, this.crystalM_7.rotationPointY * f5, this.crystalM_7.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.4, 0.7);
      GlStateManager.translate(-this.crystalM_7.offsetX, -this.crystalM_7.offsetY, -this.crystalM_7.offsetZ);
      GlStateManager.translate(-this.crystalM_7.rotationPointX * f5, -this.crystalM_7.rotationPointY * f5, -this.crystalM_7.rotationPointZ * f5);
      this.crystalM_7.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM_1.offsetX, this.crystalM_1.offsetY, this.crystalM_1.offsetZ);
      GlStateManager.translate(this.crystalM_1.rotationPointX * f5, this.crystalM_1.rotationPointY * f5, this.crystalM_1.rotationPointZ * f5);
      GlStateManager.scale(0.9, 1.9, 0.6);
      GlStateManager.translate(-this.crystalM_1.offsetX, -this.crystalM_1.offsetY, -this.crystalM_1.offsetZ);
      GlStateManager.translate(-this.crystalM_1.rotationPointX * f5, -this.crystalM_1.rotationPointY * f5, -this.crystalM_1.rotationPointZ * f5);
      this.crystalM_1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.crystalM_4.offsetX, this.crystalM_4.offsetY, this.crystalM_4.offsetZ);
      GlStateManager.translate(this.crystalM_4.rotationPointX * f5, this.crystalM_4.rotationPointY * f5, this.crystalM_4.rotationPointZ * f5);
      GlStateManager.scale(0.6, 1.4, 0.7);
      GlStateManager.translate(-this.crystalM_4.offsetX, -this.crystalM_4.offsetY, -this.crystalM_4.offsetZ);
      GlStateManager.translate(-this.crystalM_4.rotationPointX * f5, -this.crystalM_4.rotationPointY * f5, -this.crystalM_4.rotationPointZ * f5);
      this.crystalM_4.render(f5);
      GlStateManager.popMatrix();
      AbstractMobModel.returnlight();
      AbstractMobModel.light(160, true);
      this.gem1.render(f5);
      this.gem2.render(f5);
      AbstractMobModel.returnlight();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
