//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\Admin\Desktop\stuff\asbtractrpg\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

package com.Vivern.Arpg.elements.models;

import com.Vivern.Arpg.main.GetMOP;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;

public class XmassLauncherModel extends ModelBase {
   public ModelRenderer shapess1;
   public ModelRenderer shape1;
   public ModelRenderer shape2;
   public ModelRenderer shape3;
   public ModelRenderer shape4;
   public ModelRenderer shape5;
   public ModelRenderer shapeF1;
   public ModelRenderer shapeF2;
   public ModelRenderer shapess2;
   public ModelRenderer shapeA1;
   public ModelRenderer shapeA2;
   public ModelRenderer shapeA3;
   public ModelRenderer shape6;
   public ModelRenderer shape7;
   public ModelRenderer shape8;
   public ModelRenderer shapeA4;
   public ModelRenderer shapeA5;
   public ModelRenderer shapeA6;
   public ModelRenderer shapeA7;
   public ModelRenderer shapeA8;
   public ModelRenderer shapeA9;
   public ModelRenderer shapeA10;
   public ModelRenderer shapeA11;
   public ModelRenderer shapeA12;
   public ModelRenderer shapeR1;
   public ModelRenderer shapeR2;
   public ModelRenderer shapeR3;
   public ModelRenderer shapeA13;
   public ModelRenderer shapeA14;
   public ModelRenderer shapeA15;
   public ModelRenderer ammoBase;
   public ModelRenderer shape5A;
   public ModelRenderer shape6A;
   public ModelRenderer shapeAmmo;
   public ModelRenderer shapeAmmo_1;
   public ModelRenderer shapeAmmo_2;
   public ModelRenderer shapeAmmo_3;

   public XmassLauncherModel() {
      this.textureWidth = 64;
      this.textureHeight = 32;
      this.shapess2 = new ModelRenderer(this, 0, 19);
      this.shapess2.setRotationPoint(0.0F, 0.3F, -5.2F);
      this.shapess2.addBox(-1.0F, 0.5F, -1.0F, 2, 6, 2, 0.0F);
      this.setRotateAngle(this.shapess2, 0.18203785F, 0.0F, 0.0F);
      this.shapeAmmo = new ModelRenderer(this, 56, 25);
      this.shapeAmmo.mirror = true;
      this.shapeAmmo.setRotationPoint(0.0F, 1.0F, 0.0F);
      this.shapeAmmo.addBox(-1.5F, 0.0F, 0.0F, 3, 6, 1, 0.0F);
      this.setRotateAngle(this.shapeAmmo, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shapess1 = new ModelRenderer(this, 0, 19);
      this.shapess1.setRotationPoint(0.0F, 0.9F, 4.0F);
      this.shapess1.addBox(-1.0F, 0.5F, -1.0F, 2, 6, 2, 0.0F);
      this.setRotateAngle(this.shapess1, 0.18203785F, 0.0F, 0.0F);
      this.shapeA10 = new ModelRenderer(this, 0, 7);
      this.shapeA10.setRotationPoint(-2.0F, -1.0F, -5.0F);
      this.shapeA10.addBox(-1.0F, 0.0F, 0.0F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shapeA10, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape8 = new ModelRenderer(this, 20, 2);
      this.shape8.setRotationPoint(0.0F, -4.5F, -14.0F);
      this.shape8.addBox(-3.0F, 0.0F, 0.0F, 2, 6, 4, 0.0F);
      this.shape7 = new ModelRenderer(this, 20, 2);
      this.shape7.setRotationPoint(0.0F, -4.5F, -14.0F);
      this.shape7.addBox(1.0F, 0.0F, 0.0F, 2, 6, 4, 0.0F);
      this.shapeA13 = new ModelRenderer(this, 16, 0);
      this.shapeA13.setRotationPoint(0.0F, 5.5F, -13.0F);
      this.shapeA13.addBox(-3.0F, 0.0F, 0.0F, 6, 1, 1, 0.0F);
      this.shapeA3 = new ModelRenderer(this, 10, 7);
      this.shapeA3.setRotationPoint(0.0F, 2.0F, 2.5F);
      this.shapeA3.addBox(-1.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
      this.shape6 = new ModelRenderer(this, 0, 0);
      this.shape6.setRotationPoint(0.0F, 2.0F, -12.0F);
      this.shape6.addBox(-1.0F, -1.0F, -3.0F, 2, 1, 5, 0.0F);
      this.setRotateAngle(this.shape6, 0.0F, 0.0F, (float) Math.PI);
      this.shapeR1 = new ModelRenderer(this, 54, 0);
      this.shapeR1.setRotationPoint(0.0F, -4.5F, 13.0F);
      this.shapeR1.addBox(-0.5F, 0.0F, 0.0F, 1, 1, 2, 0.0F);
      this.shapeA9 = new ModelRenderer(this, 60, 0);
      this.shapeA9.setRotationPoint(0.0F, -5.0F, -4.0F);
      this.shapeA9.addBox(-0.5F, 0.0F, 0.0F, 1, 15, 1, 0.0F);
      this.setRotateAngle(this.shapeA9, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shapeA6 = new ModelRenderer(this, 0, 7);
      this.shapeA6.setRotationPoint(2.0F, -1.0F, -5.0F);
      this.shapeA6.addBox(0.0F, 0.0F, 0.0F, 1, 7, 1, 0.0F);
      this.setRotateAngle(this.shapeA6, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape5A = new ModelRenderer(this, 50, 4);
      this.shape5A.setRotationPoint(0.0F, 0.0F, -3.0F);
      this.shape5A.addBox(-1.0F, 0.0F, 0.0F, 2, 3, 2, 0.0F);
      this.shapeA12 = new ModelRenderer(this, 30, 0);
      this.shapeA12.setRotationPoint(-2.0F, -5.0F, -5.0F);
      this.shapeA12.addBox(-1.0F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.shapeA1 = new ModelRenderer(this, 7, 3);
      this.shapeA1.setRotationPoint(0.0F, 6.0F, -12.0F);
      this.shapeA1.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 9, 0.0F);
      this.shapeA8 = new ModelRenderer(this, 16, 0);
      this.shapeA8.setRotationPoint(0.0F, -6.0F, -5.0F);
      this.shapeA8.addBox(-3.0F, 0.0F, 0.0F, 6, 1, 1, 0.0F);
      this.shapeR2 = new ModelRenderer(this, 54, 0);
      this.shapeR2.setRotationPoint(0.0F, -0.5F, 13.0F);
      this.shapeR2.addBox(-0.5F, 0.0F, 0.0F, 1, 1, 2, 0.0F);
      this.shapeA5 = new ModelRenderer(this, 30, 0);
      this.shapeA5.setRotationPoint(2.0F, -1.0F, -1.0F);
      this.shapeA5.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
      this.shapeR3 = new ModelRenderer(this, 49, 0);
      this.shapeR3.setRotationPoint(0.0F, -3.5F, 14.5F);
      this.shapeR3.addBox(-0.5F, 0.0F, -0.5F, 1, 3, 1, 0.0F);
      this.shapeAmmo_2 = new ModelRenderer(this, 56, 25);
      this.shapeAmmo_2.mirror = true;
      this.shapeAmmo_2.setRotationPoint(0.0F, 3.8F, 0.0F);
      this.shapeAmmo_2.addBox(-1.5F, 0.0F, 0.0F, 3, 6, 1, 0.0F);
      this.setRotateAngle(this.shapeAmmo_2, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape3 = new ModelRenderer(this, 32, 0);
      this.shape3.setRotationPoint(0.0F, -5.0F, 4.0F);
      this.shape3.addBox(-2.0F, 0.0F, 0.0F, 4, 6, 9, 0.0F);
      this.shapeAmmo_3 = new ModelRenderer(this, 56, 25);
      this.shapeAmmo_3.setRotationPoint(0.0F, 5.2F, 0.0F);
      this.shapeAmmo_3.addBox(-1.5F, 0.0F, 0.0F, 3, 6, 1, 0.0F);
      this.setRotateAngle(this.shapeAmmo_3, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shapeA14 = new ModelRenderer(this, 36, 0);
      this.shapeA14.setRotationPoint(2.0F, 1.5F, -13.0F);
      this.shapeA14.addBox(0.0F, 0.0F, 0.0F, 1, 4, 1, 0.0F);
      this.shapeA15 = new ModelRenderer(this, 36, 0);
      this.shapeA15.setRotationPoint(-2.0F, 1.5F, -13.0F);
      this.shapeA15.addBox(-1.0F, 0.0F, 0.0F, 1, 4, 1, 0.0F);
      this.ammoBase = new ModelRenderer(this, 0, 0);
      this.ammoBase.setRotationPoint(6.0F, 1.4F, 4.0F);
      this.ammoBase.addBox(-1.5F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
      this.shape2 = new ModelRenderer(this, 28, 16);
      this.shape2.setRotationPoint(0.0F, -5.5F, 3.0F);
      this.shape2.addBox(-2.5F, 0.0F, 0.0F, 5, 7, 9, 0.0F);
      this.shapeAmmo_1 = new ModelRenderer(this, 56, 25);
      this.shapeAmmo_1.setRotationPoint(0.0F, 2.4F, 0.0F);
      this.shapeAmmo_1.addBox(-1.5F, 0.0F, 0.0F, 3, 6, 1, 0.0F);
      this.setRotateAngle(this.shapeAmmo_1, (float) (Math.PI / 2), 0.0F, 0.0F);
      this.shape4 = new ModelRenderer(this, 17, 13);
      this.shape4.setRotationPoint(0.0F, -5.0F, -12.0F);
      this.shape4.addBox(-2.5F, 0.0F, 0.0F, 5, 7, 5, 0.0F);
      this.shape6A = new ModelRenderer(this, 50, 4);
      this.shape6A.setRotationPoint(0.0F, 0.0F, -3.0F);
      this.shape6A.addBox(-1.0F, 0.0F, 0.0F, 2, 3, 2, 0.0F);
      this.shapeF1 = new ModelRenderer(this, 47, 16);
      this.shapeF1.setRotationPoint(0.0F, -5.5F, -9.0F);
      this.shapeF1.addBox(-3.0F, 0.0F, 0.0F, 6, 8, 1, 0.0F);
      this.shape5 = new ModelRenderer(this, 0, 0);
      this.shape5.setRotationPoint(0.0F, -5.0F, -12.0F);
      this.shape5.addBox(-1.0F, -1.0F, -3.0F, 2, 1, 5, 0.0F);
      this.shapeA4 = new ModelRenderer(this, 16, 0);
      this.shapeA4.setRotationPoint(0.0F, 1.0F, -1.0F);
      this.shapeA4.addBox(-3.0F, 0.0F, 0.0F, 6, 1, 1, 0.0F);
      this.shapeF2 = new ModelRenderer(this, 47, 16);
      this.shapeF2.setRotationPoint(0.0F, -5.5F, -7.0F);
      this.shapeF2.addBox(-3.0F, 0.0F, 0.0F, 6, 8, 1, 0.0F);
      this.shape1 = new ModelRenderer(this, 0, 18);
      this.shape1.setRotationPoint(0.0F, -4.0F, -6.0F);
      this.shape1.addBox(-2.0F, 0.0F, 0.0F, 4, 5, 9, 0.0F);
      this.shapeA2 = new ModelRenderer(this, 8, 13);
      this.shapeA2.setRotationPoint(0.0F, 1.0F, 0.0F);
      this.shapeA2.addBox(-1.5F, 0.0F, 0.0F, 3, 1, 4, 0.0F);
      this.shapeA7 = new ModelRenderer(this, 30, 0);
      this.shapeA7.setRotationPoint(2.0F, -5.0F, -5.0F);
      this.shapeA7.addBox(0.0F, 0.0F, 0.0F, 1, 3, 1, 0.0F);
      this.shapeA11 = new ModelRenderer(this, 30, 0);
      this.shapeA11.setRotationPoint(-2.0F, -1.0F, -1.0F);
      this.shapeA11.addBox(-1.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
      this.ammoBase.addChild(this.shapeAmmo);
      this.shape5.addChild(this.shape5A);
      this.ammoBase.addChild(this.shapeAmmo_2);
      this.ammoBase.addChild(this.shapeAmmo_3);
      this.ammoBase.addChild(this.shapeAmmo_1);
      this.shape6.addChild(this.shape6A);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      GlStateManager.disableCull();
      float ft0 = GetMOP.getfromto(f, 0.0F, 0.1F);
      float ft1 = ft0 - GetMOP.getfromto(f, 0.5F, 1.0F);
      float ft2 = ft0 - GetMOP.getfromto(f, 0.6F, 0.8F);
      float ft3 = GetMOP.getfromto(f, 0.1F, 0.2F) - GetMOP.getfromto(f, 0.8F, 1.0F);
      this.shape5.rotateAngleX = -0.35F * ft1;
      this.shape6.rotateAngleX = -0.35F * ft1;
      this.shape7.offsetZ = 1.0F * ft2;
      this.shape7.offsetX = 1.0F * ft3;
      this.shape8.offsetZ = 1.0F * ft2;
      this.shape8.offsetX = -1.0F * ft3;
      if (f2 > 0.0F && f2 < 1.0F) {
         ft0 = GetMOP.getfromto(f2, 0.0F, 0.2F);
         ft1 = GetMOP.getfromto(f2, 0.2F, 0.35F);
         ft2 = GetMOP.getfromto(f2, 0.3F, 0.45F);
         ft3 = GetMOP.getfromto(f2, 0.45F, 0.52F) - GetMOP.getfromto(f2, 0.52F, 0.59F);
         float ft7 = GetMOP.getfromto(f2, 0.45F, 0.55F);
         float ft8 = GetMOP.getfromto(f2, 0.65F, 0.9F);
         float moffset = 8.0F * ft0 - 8.0F * ft8;
         this.shape3.offsetZ = moffset;
         this.shapeR1.offsetZ = moffset;
         this.shapeR2.offsetZ = moffset;
         this.shapeR3.offsetZ = moffset;
         this.ammoBase.offsetX = -6.0F * ft2;
         this.ammoBase.offsetY = -14.0F * ft1 + 8.0F * ft7;
         this.ammoBase.offsetZ = 8.0F * ft2 + 1.0F * ft3 - 8.0F * ft8;
         this.ammoBase.rotateAngleX = 0.4F * ft3;
         this.ammoBase.render(f5);
      } else {
         this.shape3.offsetZ = 0.0F;
         this.shapeR1.offsetZ = 0.0F;
         this.shapeR2.offsetZ = 0.0F;
         this.shapeR3.offsetZ = 0.0F;
      }

      this.shapeA8.render(f5);
      this.shapeR2.render(f5);
      this.shapeA9.render(f5);
      this.shape3.render(f5);
      this.shapeA5.render(f5);
      this.shape6.render(f5);
      this.shapeA12.render(f5);
      this.shapeR1.render(f5);
      this.shapeA6.render(f5);
      this.shapeA1.render(f5);
      this.shapeA11.render(f5);
      this.shapeA13.render(f5);
      this.shape2.render(f5);
      this.shape8.render(f5);
      this.shape5.render(f5);
      this.shapeA10.render(f5);
      this.shapeF2.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess1.offsetX, this.shapess1.offsetY, this.shapess1.offsetZ);
      GlStateManager.translate(this.shapess1.rotationPointX * f5, this.shapess1.rotationPointY * f5, this.shapess1.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.1);
      GlStateManager.translate(-this.shapess1.offsetX, -this.shapess1.offsetY, -this.shapess1.offsetZ);
      GlStateManager.translate(-this.shapess1.rotationPointX * f5, -this.shapess1.rotationPointY * f5, -this.shapess1.rotationPointZ * f5);
      this.shapess1.render(f5);
      GlStateManager.popMatrix();
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapeR3.offsetX, this.shapeR3.offsetY, this.shapeR3.offsetZ);
      GlStateManager.translate(this.shapeR3.rotationPointX * f5, this.shapeR3.rotationPointY * f5, this.shapeR3.rotationPointZ * f5);
      GlStateManager.scale(1.3, 1.0, 1.3);
      GlStateManager.translate(-this.shapeR3.offsetX, -this.shapeR3.offsetY, -this.shapeR3.offsetZ);
      GlStateManager.translate(-this.shapeR3.rotationPointX * f5, -this.shapeR3.rotationPointY * f5, -this.shapeR3.rotationPointZ * f5);
      this.shapeR3.render(f5);
      GlStateManager.popMatrix();
      this.shapeF1.render(f5);
      this.shapeA14.render(f5);
      this.shape1.render(f5);
      this.shapeA3.render(f5);
      this.shapeA7.render(f5);
      GlStateManager.pushMatrix();
      GlStateManager.translate(this.shapess2.offsetX, this.shapess2.offsetY, this.shapess2.offsetZ);
      GlStateManager.translate(this.shapess2.rotationPointX * f5, this.shapess2.rotationPointY * f5, this.shapess2.rotationPointZ * f5);
      GlStateManager.scale(0.8, 1.0, 1.1);
      GlStateManager.translate(-this.shapess2.offsetX, -this.shapess2.offsetY, -this.shapess2.offsetZ);
      GlStateManager.translate(-this.shapess2.rotationPointX * f5, -this.shapess2.rotationPointY * f5, -this.shapess2.rotationPointZ * f5);
      this.shapess2.render(f5);
      GlStateManager.popMatrix();
      this.shape7.render(f5);
      this.shape4.render(f5);
      this.shapeA15.render(f5);
      this.shapeA2.render(f5);
      this.shapeA4.render(f5);
      GlStateManager.enableCull();
   }

   public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
      modelRenderer.rotateAngleX = x;
      modelRenderer.rotateAngleY = y;
      modelRenderer.rotateAngleZ = z;
   }
}
