package com.vivern.arpg.recipes;

import com.vivern.arpg.main.BlocksRegister;
import com.vivern.arpg.main.ItemsRegister;
import com.vivern.arpg.main.OreDicHelper;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.crafting.CraftingHelper;
import net.minecraftforge.common.crafting.IRecipeFactory;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class CraftingRegister {
   public static void register() {
      registerRecipe("absorption_totem");
      registerRecipe("advanced_block_detector1");
      registerRecipe("advanced_block_detector2");
      registerRecipe("advanced_circuit");
      registerRecipe("aluminium_ingot");
      registerRecipe("aluminium_nugget");
      registerRecipe("amethyst_axe");
      registerRecipe("amethyst_lamp");
      registerRecipe("amethyst_lantern");
      registerRecipe("amethyst_pickaxe");
      registerRecipe("amethyst_shovel");
      registerRecipe("anti_rad_pills");
      registerRecipe("anti_rad_plating");
      registerRecipe("arsenic_ingot");
      registerRecipe("arsenic_nugget");
      registerRecipe("assembly_table");
      registerRecipe("bauxite_block");
      registerRecipe("bearing_alloy_dust");
      registerRecipe("beryllium_dust");
      registerRecipe("beryllium_grains");
      registerRecipe("block_detector");
      registerRecipe("block_placer");
      registerRecipe("bomb");
      registerRecipe("brass_dust");
      registerRecipe("brass_ingot");
      registerRecipe("brass_nugget");
      registerRecipe("brown_pudding");
      registerRecipe("brown_pudding2");
      registerRecipe("burning_frost_igniter");
      registerRecipe("calibration_crystal_attract_medium");
      registerRecipe("calibration_crystal_attract_small");
      registerRecipe("calibration_crystal_detract_medium");
      registerRecipe("calibration_crystal_detract_small");
      registerRecipe("calibration_crystal_focus_medium");
      registerRecipe("calibration_crystal_focus_small");
      registerRecipe("calibration_crystal_range_medium");
      registerRecipe("calibration_crystal_range_small");
      registerRecipe("calibration_crystal_slow_medium");
      registerRecipe("calibration_crystal_slow_small");
      registerRecipe("calibration_crystal_speed_medium");
      registerRecipe("calibration_crystal_speed_small");
      registerRecipe("chain_mace");
      registerRecipe("chest_coral");
      registerRecipe("chest_crystal");
      registerRecipe("chest_frozen");
      registerRecipe("chest_rusted");
      registerRecipe("chest_storm");
      registerRecipe("chest_sunken");
      registerRecipe("chest_toxic");
      registerRecipe("chocolate");
      registerRecipe("christmas_balls1");
      registerRecipe("christmas_balls2");
      registerRecipe("christmas_balls3");
      registerRecipe("christmas_balls4");
      registerRecipe("circuit");
      registerRecipe("citrine_axe");
      registerRecipe("citrine_lamp");
      registerRecipe("citrine_lantern");
      registerRecipe("citrine_pickaxe");
      registerRecipe("citrine_shovel");
      registerRecipe("cobblestone");
      registerRecipe("conifer_chair");
      registerRecipe("conifer_crafting_table");
      registerRecipe("conifer_ornament1");
      registerRecipe("conifer_ornament2");
      registerRecipe("conifer_pilaster");
      registerRecipe("conifer_planks");
      registerRecipe("conifer_stairs");
      registerRecipe("conifer_stick");
      registerRecipe("conifer_table");
      registerRecipe("copper_wire");
      registerRecipe("coral_bricks");
      registerRecipe("coral_chair");
      registerRecipe("coral_chandelier");
      registerRecipe("coral_table");
      registerRecipe("coral_torch");
      registerRecipe("coral_vase");
      registerRecipe("crackable_frozen_bricks");
      registerRecipe("crystal_chair");
      registerRecipe("crystal_chandelier");
      registerRecipe("crystal_table");
      registerRecipe("crystal_torch");
      registerRecipe("crystal_vase");
      registerRecipe("dash_belt_black");
      registerRecipe("decorative_chain");
      registerRecipe("demonic_igniter");
      registerRecipe("demonite_shard");
      registerRecipe("diamond_chain_mace");
      registerRecipe("diamond_lamp");
      registerRecipe("diamond_lantern");
      registerRecipe("disenchantment_table");
      registerRecipe("dolerite_bricks");
      registerRecipe("dolerite_column");
      registerRecipe("dolerite_pilaster");
      registerRecipe("dolerite_stairs");
      registerRecipe("dough");
      registerRecipe("electric_motor");
      registerRecipe("electric_sieve");
      registerRecipe("emerald_lamp");
      registerRecipe("emerald_lantern");
      registerRecipe("empty_syringe1");
      registerRecipe("empty_syringe2");
      registerRecipe("erebris_fragment");
      registerRecipe("fiber_bandage");
      registerRecipe("fiber_cloth");
      registerRecipe("fiery_bean_planks");
      registerRecipe("frozen_bricks");
      registerRecipe("frozen_chair");
      registerRecipe("frozen_chandelier");
      registerRecipe("frozen_pilaster");
      registerRecipe("frozen_roof_stairs");
      registerRecipe("frozen_stairs");
      registerRecipe("frozen_table");
      registerRecipe("frozen_tile_roof");
      registerRecipe("frozen_torch");
      registerRecipe("conifer_rosin");
      registerRecipe("frozen_vase");
      registerRecipe("garland");
      registerRecipe("green_pudding");
      registerRecipe("green_pudding2");
      registerRecipe("gunpowder1");
      registerRecipe("gunpowder2");
      registerRecipe("health_fruit");
      registerRecipe("ice_pane");
      registerRecipe("industrial_mixer");
      registerRecipe("infernum_ingot");
      registerRecipe("infernum_nugget");
      registerRecipe("ink_bottle");
      registerRecipe("linear_motor");
      registerRecipe("lithium_ingot");
      registerRecipe("lithium_nugget");
      registerRecipe("machinery_casing");
      registerRecipe("magic_bricks");
      registerRecipe("magic_candle_black");
      registerRecipe("magic_candle_blue");
      registerRecipe("magic_candle_brown");
      registerRecipe("magic_candle_cyan");
      registerRecipe("magic_candle_gray");
      registerRecipe("magic_candle_green");
      registerRecipe("magic_candle_lightblue");
      registerRecipe("magic_candle_lightgray");
      registerRecipe("magic_candle_lime");
      registerRecipe("magic_candle_magenta");
      registerRecipe("magic_candle_orange");
      registerRecipe("magic_candle_pink");
      registerRecipe("magic_candle_purple");
      registerRecipe("magic_candle_red");
      registerRecipe("magic_candle_white");
      registerRecipe("magic_candle_yellow");
      registerRecipe("magic_exploring_kit");
      registerRecipe("magic_ornament");
      registerRecipe("magic_research_kit");
      registerRecipe("magic_wood");
      registerRecipe("magic_writing_kit");
      registerRecipe("metallic_rock_pilaster");
      registerRecipe("mithril_ingot");
      registerRecipe("mithril_nugget");
      registerRecipe("molten_nugget");
      registerRecipe("money_box");
      registerRecipe("niveous_bricks1");
      registerRecipe("niveous_bricks2");
      registerRecipe("niveous_bricks3");
      registerRecipe("niveous_column");
      registerRecipe("niveous_pilaster");
      registerRecipe("niveous_stairs");
      registerRecipe("oil_bottle");
      registerRecipe("orange_pudding");
      registerRecipe("orange_pudding2");
      registerRecipe("palm_chair");
      registerRecipe("palm_planks");
      registerRecipe("palm_table");
      registerRecipe("palm_torch");
      registerRecipe("pearlescent_bricks");
      registerRecipe("pearlescent_pilaster");
      registerRecipe("pearlescent_stairs");
      registerRecipe("photoresisted_plate");
      registerRecipe("plant_fiber");
      registerRecipe("polished_niveous_block1");
      registerRecipe("polished_niveous_block2");
      registerRecipe("polished_niveous_pilaster");
      registerRecipe("present_box");
      registerRecipe("research_table");
      registerRecipe("rhinestone");
      registerRecipe("rhinestone_axe");
      registerRecipe("rhinestone_block");
      registerRecipe("rhinestone_lamp");
      registerRecipe("rhinestone_lantern");
      registerRecipe("rhinestone_pickaxe");
      registerRecipe("rhinestone_shovel");
      registerRecipe("rope_hook");
      registerRecipe("ruby_axe");
      registerRecipe("ruby_lamp");
      registerRecipe("ruby_lantern");
      registerRecipe("ruby_pickaxe");
      registerRecipe("ruby_shovel");
      registerRecipe("rust_armature");
      registerRecipe("rust_lamp");
      registerRecipe("salt_dust");
      registerRecipe("salt_grains");
      registerRecipe("sapphire_axe");
      registerRecipe("sapphire_lamp");
      registerRecipe("sapphire_lantern");
      registerRecipe("sapphire_pickaxe");
      registerRecipe("sapphire_shovel");
      registerRecipe("scrap_bomb1");
      registerRecipe("scrap_bomb2");
      registerRecipe("scrap_bomb3");
      registerRecipe("shell_arrow1");
      registerRecipe("shell_arrow2");
      registerRecipe("sieve");
      registerRecipe("silver_block");
      registerRecipe("silver_ingot");
      registerRecipe("silver_ingot2");
      registerRecipe("silver_nugget");
      registerRecipe("siren_key");
      registerRecipe("sky_crystal");
      registerRecipe("sky_crystal_piece");
      registerRecipe("slime_boots");
      registerRecipe("slime_chestplate");
      registerRecipe("slime_grapling_hook");
      registerRecipe("slime_helmet");
      registerRecipe("slime_leggins");
      registerRecipe("slime_locator");
      registerRecipe("snow_sewing");
      registerRecipe("spell_forge");
      registerRecipe("spell_hammer");
      registerRecipe("spell_pliers");
      registerRecipe("spell_rod");
      registerRecipe("stained_glass_aurora");
      registerRecipe("stained_glass_marigold");
      registerRecipe("stained_glass_rose");
      registerRecipe("stained_glass_sky");
      registerRecipe("stained_glass_starlight");
      registerRecipe("stained_glass_sunset");
      registerRecipe("stamp_mold1");
      registerRecipe("stamp_mold2");
      registerRecipe("star_lantern");
      registerRecipe("stone_axe");
      registerRecipe("stone_dust");
      registerRecipe("stone_hoe");
      registerRecipe("stone_pickaxe");
      registerRecipe("stone_rubble");
      registerRecipe("stone_shovel");
      registerRecipe("stone_sword");
      registerRecipe("stormbrass_ingot");
      registerRecipe("stormbrass_nugget");
      registerRecipe("stormsteel_ingot");
      registerRecipe("stormsteel_nugget");
      registerRecipe("storm_pilaster");
      registerRecipe("sweet_dough1");
      registerRecipe("sweet_dough2");
      registerRecipe("titanium_ingot");
      registerRecipe("titanium_nugget");
      registerRecipe("tomato_stem");
      registerRecipe("topaz_axe");
      registerRecipe("topaz_lamp");
      registerRecipe("topaz_lantern");
      registerRecipe("topaz_pickaxe");
      registerRecipe("topaz_shovel");
      registerRecipe("toxedge_dough");
      registerRecipe("toxiberry_stick");
      registerRecipe("toxic_chandelier");
      registerRecipe("toxic_planks");
      registerRecipe("toxic_planks_chair");
      registerRecipe("toxic_planks_pilaster");
      registerRecipe("toxic_planks_stairs");
      registerRecipe("toxic_table");
      registerRecipe("toxic_torch");
      registerRecipe("toxinium_ingot");
      registerRecipe("toxinium_nugget");
      registerRecipe("uranium_ingot");
      registerRecipe("uranium_nugget");
      registerRecipe("vicious_arrow");
      registerRecipe("violet_pudding");
      registerRecipe("violet_pudding2");
      registerRecipe("void_arrow");
      registerRecipe("wasteburger");
      registerRecipe("whip");
      registerRecipe("winter_sacrifice");
      registerRecipe("wolfram_ingot");
      registerRecipe("wolfram_nugget");
      registerRecipe("wooden_bookcase");
      registerRecipe("zinc_ingot");
      registerRecipe("zinc_nugget");
      registerRecipe("swarmeter");
      registerRecipe("team_banner");
      registerRecipe("aquatic_nugget");
   }

   public static void addSmeltingRecipes() {
      GameRegistry.addSmelting(BlocksRegister.OREINFERNUM, new ItemStack(ItemsRegister.INGOTINFERNUM), 2.0F);
      GameRegistry.addSmelting(BlocksRegister.OREDEMONITE, new ItemStack(ItemsRegister.DEMONITE), 4.0F);
      GameRegistry.addSmelting(BlocksRegister.FIERYBEANSAPLING, new ItemStack(ItemsRegister.FIERYOIL), 0.5F);
      GameRegistry.addSmelting(BlocksRegister.OREARSENIC, new ItemStack(ItemsRegister.INGOTARSENIC), 2.0F);
      GameRegistry.addSmelting(BlocksRegister.OREZINC, new ItemStack(ItemsRegister.INGOTZINC), 1.0F);
      GameRegistry.addSmelting(BlocksRegister.ORESILVER, new ItemStack(ItemsRegister.INGOTSILVER), 1.0F);
      GameRegistry.addSmelting(ItemsRegister.PLANTFIBER, new ItemStack(ItemsRegister.DRIEDPLANTFIBER), 0.2F);
      GameRegistry.addSmelting(ItemsRegister.DUSTZINC, new ItemStack(ItemsRegister.INGOTZINC), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTBERYLLIUM, new ItemStack(ItemsRegister.INGOTBERYLLIUM), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTCHROMIUM, new ItemStack(ItemsRegister.INGOTCHROMIUM), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTMANGANESE, new ItemStack(ItemsRegister.INGOTMANGANESE), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTBRASS, new ItemStack(ItemsRegister.INGOTBRASS), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTSTORMBRASS, new ItemStack(ItemsRegister.INGOTSTORMBRASS), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTARSENIC, new ItemStack(ItemsRegister.INGOTARSENIC), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTSILVER, new ItemStack(ItemsRegister.INGOTSILVER), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTALUMINIUM, new ItemStack(ItemsRegister.INGOTALUMINIUM), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTLITHIUM, new ItemStack(ItemsRegister.INGOTLITHIUM), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTURANIUM, new ItemStack(ItemsRegister.INGOTURANIUM), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.DUSTMITHRIL, new ItemStack(ItemsRegister.INGOTMITHRIL), 0.0F);
      GameRegistry.addSmelting(ItemsRegister.STAMPMOLD, new ItemStack(ItemsRegister.STEELSTAMP), 10.0F);
      GameRegistry.addSmelting(BlocksRegister.MANAOILSPELEOTHEM, new ItemStack(ItemsRegister.ALCHEMICALWAX), 0.4F);
      GameRegistry.addSmelting(ItemsRegister.DOUGH, new ItemStack(Items.BREAD), 0.35F);
      GameRegistry.addSmelting(ItemsRegister.TOXEDGEDOUGH, new ItemStack(ItemsRegister.TOXEDGEBREAD), 0.35F);
      GameRegistry.addSmelting(Items.SUGAR, new ItemStack(ItemsRegister.CARAMEL), 0.35F);
      GameRegistry.addSmelting(ItemsRegister.SWEETDOUGH, new ItemStack(ItemsRegister.BISCUIT, 2), 0.5F);
      if (OreDicHelper.doesOreNameExist("dustWood")) {
         GameRegistry.addSmelting(OreDicHelper.get("dustWood", 1), new ItemStack(ItemsRegister.ASH, 1), 0.5F);
      }

      GameRegistry.addSmelting(ItemsRegister.FISHSTEAKRAW, new ItemStack(ItemsRegister.FISHSTEAKROASTED), 0.35F);
      GameRegistry.addSmelting(ItemsRegister.PALEMEATRAW, new ItemStack(ItemsRegister.PALEMEATSMOKED), 0.35F);
      GameRegistry.addSmelting(BlocksRegister.OREMITHRIL, new ItemStack(ItemsRegister.INGOTMITHRIL), 2.0F);
   }

   public static void registerRecipe(String name) {
      // FIX: cast 2nd argument to `IRecipeFactory`
      CraftingHelper.register(new ResourceLocation("arpg", name), (IRecipeFactory) (context, json) -> CraftingHelper.getRecipe(json, context));
   }
}
