package com.Vivern.Arpg.main;

import com.Vivern.Arpg.biomes.AquaticaBeach;
import com.Vivern.Arpg.biomes.ArthroheliaIslands;
import com.Vivern.Arpg.biomes.CalciteClefts;
import com.Vivern.Arpg.biomes.Corals;
import com.Vivern.Arpg.biomes.CrystalCaves;
import com.Vivern.Arpg.biomes.CrystallizedSkyIslands;
import com.Vivern.Arpg.biomes.DeadLands;
import com.Vivern.Arpg.biomes.DirtyBeach;
import com.Vivern.Arpg.biomes.ElectrofernGrove;
import com.Vivern.Arpg.biomes.ElectrofernWastelands;
import com.Vivern.Arpg.biomes.EverfrostRiver;
import com.Vivern.Arpg.biomes.FrozenBeach;
import com.Vivern.Arpg.biomes.FrozenForest;
import com.Vivern.Arpg.biomes.FrozenLake;
import com.Vivern.Arpg.biomes.FrozenMeadow;
import com.Vivern.Arpg.biomes.FrozenMountain;
import com.Vivern.Arpg.biomes.FrozenWarmForest;
import com.Vivern.Arpg.biomes.GlowingTunnels;
import com.Vivern.Arpg.biomes.IceHills;
import com.Vivern.Arpg.biomes.IslandHills;
import com.Vivern.Arpg.biomes.IslandRiver;
import com.Vivern.Arpg.biomes.Islands;
import com.Vivern.Arpg.biomes.MagicCrystalCaves;
import com.Vivern.Arpg.biomes.OnyxCaves;
import com.Vivern.Arpg.biomes.PoisonOcean;
import com.Vivern.Arpg.biomes.PoisonRiver;
import com.Vivern.Arpg.biomes.Reef;
import com.Vivern.Arpg.biomes.SeaBottom;
import com.Vivern.Arpg.biomes.SeaweedBay;
import com.Vivern.Arpg.biomes.Shallow;
import com.Vivern.Arpg.biomes.SkyIslands;
import com.Vivern.Arpg.biomes.SlimeRiver;
import com.Vivern.Arpg.biomes.ToxicFlowerIslands;
import com.Vivern.Arpg.biomes.ToxicHighRocks;
import com.Vivern.Arpg.biomes.ToxicJungle;
import com.Vivern.Arpg.biomes.ToxicMountains;
import com.Vivern.Arpg.biomes.ToxicPlains;
import com.Vivern.Arpg.biomes.ToxicSlimeland;
import com.Vivern.Arpg.biomes.ToxicSwamp;
import com.Vivern.Arpg.biomes.Tunnels;
import com.Vivern.Arpg.biomes.UndergroundLake;
import com.Vivern.Arpg.biomes.WaterCaves;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.common.BiomeDictionary;
import net.minecraftforge.common.BiomeManager;
import net.minecraftforge.common.BiomeDictionary.Type;
import net.minecraftforge.common.BiomeManager.BiomeType;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public class BiomesRegister {
   public static final Biome FROZEN_FOREST = new FrozenForest();
   public static final Biome FROZEN_WARM_FOREST = new FrozenWarmForest();
   public static final Biome FROZEN_LAKE = new FrozenLake();
   public static final Biome ICE_HILLS = new IceHills();
   public static final Biome TUNNELS = new Tunnels();
   public static final Biome ONYX_CAVES = new OnyxCaves();
   public static final Biome CRYSTAL_CAVES = new CrystalCaves();
   public static final Biome MAGIC_CRYSTAL_CAVES = new MagicCrystalCaves();
   public static final Biome GLOWING_TUNNELS = new GlowingTunnels();
   public static final Biome CALCITE_CLEFTS = new CalciteClefts();
   public static final Biome WATER_CAVES = new WaterCaves();
   public static final Biome UNDERGROUND_LAKE = new UndergroundLake();
   public static final Biome TOXIC_PLAINS = new ToxicPlains();
   public static final Biome TOXIC_SWAMP = new ToxicSwamp();
   public static final Biome TOXIC_MOUNTAINS = new ToxicMountains();
   public static final Biome TOXIC_HIGH_ROCKS = new ToxicHighRocks();
   public static final Biome TOXIC_JUNGLE = new ToxicJungle();
   public static final Biome TOXIC_FLOWER_ISLAND = new ToxicFlowerIslands();
   public static final Biome TOXIC_SLIME_LAND = new ToxicSlimeland();
   public static final Biome FROZEN_MEADOW = new FrozenMeadow();
   public static final Biome ISLANDS = new Islands();
   public static final Biome SEA_BOTTOM = new SeaBottom();
   public static final Biome ISLANDHILLS = new IslandHills();
   public static final Biome AQUATICABEACH = new AquaticaBeach();
   public static final Biome SHALLOW = new Shallow();
   public static final Biome REEF = new Reef();
   public static final Biome ISLAND_RIVER = new IslandRiver();
   public static final Biome CORALS = new Corals();
   public static final Biome SEAWEED_BAY = new SeaweedBay();
   public static final Biome SKY_ISLANDS = new SkyIslands();
   public static final Biome DEAD_LANDS = new DeadLands();
   public static final Biome DIRTY_BEACH = new DirtyBeach();
   public static final Biome SLIME_RIVER = new SlimeRiver();
   public static final Biome POISON_RIVER = new PoisonRiver();
   public static final Biome POISON_OCEAN = new PoisonOcean();
   public static final Biome EVERFROST_RIVER = new EverfrostRiver();
   public static final Biome FROZEN_BEACH = new FrozenBeach();
   public static int frozen_mountains_amount = 7;
   public static final Biome[] FROZEN_MOUNTAINS = new Biome[frozen_mountains_amount];
   public static final Biome ARTHROHELIA_ISLANDS = new ArthroheliaIslands();
   public static final Biome CRYSTALLIZED_SKY_ISLANDS = new CrystallizedSkyIslands();
   public static final Biome ELECTROFERN_GROVE = new ElectrofernGrove();
   public static final Biome ELECTROFERN_WASTELANDS = new ElectrofernWastelands();

   public static void registerBiomes() {
      init(FROZEN_FOREST, "Frozen Forest", BiomeType.ICY, Type.CONIFEROUS, Type.COLD, Type.SNOWY, Type.FOREST);
      init(FROZEN_WARM_FOREST, "Frozen Warm Forest", BiomeType.COOL, Type.CONIFEROUS, Type.COLD, Type.SNOWY, Type.FOREST);
      init(FROZEN_LAKE, "Frozen Lake", BiomeType.ICY, Type.OCEAN, Type.COLD, Type.WATER);
      init(ICE_HILLS, "Ice Hills", BiomeType.ICY, Type.HILLS, Type.COLD, Type.MOUNTAIN, Type.SNOWY);
      init(TUNNELS, "Tunnels", BiomeType.COOL, Type.WET, Type.COLD);
      init(ONYX_CAVES, "Onyx Caves", BiomeType.COOL, Type.WET, Type.COLD, Type.RARE);
      init(CRYSTAL_CAVES, "Crystal Caves", BiomeType.COOL, Type.WET, Type.COLD);
      init(MAGIC_CRYSTAL_CAVES, "Magic Crystal Caves", BiomeType.COOL, Type.WET, Type.COLD, Type.RARE, Type.MAGICAL);
      init(GLOWING_TUNNELS, "Glowing Tunnels", BiomeType.COOL, Type.WET, Type.COLD, Type.MAGICAL);
      init(CALCITE_CLEFTS, "Calcite Clefts", BiomeType.COOL, Type.DRY, Type.COLD);
      init(WATER_CAVES, "Water Caves", BiomeType.COOL, Type.WATER, Type.RIVER, Type.WET);
      init(UNDERGROUND_LAKE, "Underground Lake", BiomeType.COOL, Type.WATER, Type.WET);
      init(TOXIC_PLAINS, "Toxic Plains", BiomeType.WARM, Type.PLAINS);
      init(TOXIC_SWAMP, "Toxic Swamp", BiomeType.WARM, Type.SWAMP, Type.WET);
      init(TOXIC_MOUNTAINS, "Toxic Mountains", BiomeType.COOL, Type.HILLS, Type.MOUNTAIN);
      init(TOXIC_HIGH_ROCKS, "Toxic High Rocks", BiomeType.WARM, Type.MESA, Type.MOUNTAIN);
      init(TOXIC_JUNGLE, "Toxic Jungle", BiomeType.WARM, Type.DENSE, Type.HILLS, Type.HOT, Type.JUNGLE, Type.LUSH, Type.WET);
      init(TOXIC_FLOWER_ISLAND, "Toxic Flower Island", BiomeType.WARM, Type.PLAINS, Type.RARE, Type.HOT, Type.LUSH, Type.WET);
      init(TOXIC_SLIME_LAND, "Toxic Slime Lands", BiomeType.WARM, Type.HOT, Type.RARE, Type.WET);
      init(FROZEN_MEADOW, "Frozen Meadow", BiomeType.COOL, Type.CONIFEROUS, Type.COLD, Type.SNOWY, Type.FOREST, Type.PLAINS);
      init(ISLANDS, "Islands", BiomeType.WARM, Type.BEACH, Type.HOT, Type.JUNGLE, Type.SANDY);
      init(SEA_BOTTOM, "Sea Bottom", BiomeType.WARM, Type.OCEAN, Type.SANDY, Type.WATER);
      init(ISLANDHILLS, "Island Hills", BiomeType.WARM, Type.HILLS, Type.SANDY, Type.HOT, Type.JUNGLE);
      init(AQUATICABEACH, "Aquatica Beach", BiomeType.WARM, Type.OCEAN, Type.SANDY, Type.WATER, Type.BEACH, Type.HOT);
      init(SHALLOW, "Shallow", BiomeType.WARM, Type.OCEAN, Type.SANDY, Type.WATER, Type.BEACH);
      init(REEF, "Reef", BiomeType.WARM, Type.OCEAN, Type.WATER);
      init(ISLAND_RIVER, "Island River", BiomeType.WARM, Type.RIVER, Type.WATER, Type.SANDY);
      init(CORALS, "Corals", BiomeType.WARM, Type.OCEAN, Type.WATER, Type.MAGICAL, Type.DENSE);
      init(SEAWEED_BAY, "Seaweed Bay", BiomeType.WARM, Type.OCEAN, Type.WATER, Type.SANDY, Type.DENSE);
      init(SKY_ISLANDS, "Sky Islands", BiomeType.COOL, Type.VOID, Type.HILLS, Type.PLAINS);
      init(DEAD_LANDS, "Dead Lands", BiomeType.COOL, Type.DEAD, Type.DRY, Type.HILLS);
      init(DIRTY_BEACH, "Dirty Beach", BiomeType.WARM, Type.BEACH, Type.SANDY, Type.WET);
      init(SLIME_RIVER, "Slime River", BiomeType.WARM, Type.RIVER, Type.WET, Type.HOT);
      init(POISON_RIVER, "Poison River", BiomeType.WARM, Type.RIVER, Type.WET);
      init(POISON_OCEAN, "Poison Ocean", BiomeType.WARM, Type.OCEAN);
      init(EVERFROST_RIVER, "Everfrost River", BiomeType.ICY, Type.RIVER, Type.COLD, Type.WATER);
      init(FROZEN_BEACH, "Frozen Beach", BiomeType.ICY, Type.BEACH, Type.OCEAN, Type.COLD, Type.WATER, Type.SNOWY);
      init(ARTHROHELIA_ISLANDS, "Arthrohelia Islands", BiomeType.COOL, Type.VOID, Type.HILLS, Type.MAGICAL);
      init(CRYSTALLIZED_SKY_ISLANDS, "Crystallized Sky Islands", BiomeType.COOL, Type.VOID, Type.HILLS, Type.MAGICAL);
      init(ELECTROFERN_GROVE, "Electrofern Grove", BiomeType.COOL, Type.VOID, Type.HILLS, Type.MAGICAL, Type.JUNGLE);
      init(ELECTROFERN_WASTELANDS, "Electrofern Wastelands", BiomeType.COOL, Type.VOID, Type.MAGICAL, Type.WASTELAND);

      for (int i = 1; i <= frozen_mountains_amount; i++) {
         Biome biome = new FrozenMountain(i * 1.25F);
         FROZEN_MOUNTAINS[i - 1] = biome;
         init(biome, "Frozen Mountain " + i, BiomeType.ICY, Type.COLD, Type.CONIFEROUS, Type.MOUNTAIN, Type.SNOWY);
      }
   }

   public static void init(Biome biome, String name, BiomeType biomeType, Type... types) {
      biome.setRegistryName(name);
      ForgeRegistries.BIOMES.register(biome);
      BiomeDictionary.addTypes(biome, types);
      BiomeManager.addSpawnBiome(biome);
   }
}
